# Import Libraries

In [1]:
# Data manipulation
import pandas as pd
import numpy as np

# Data visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Statistical analysis
from scipy import stats

# Machine learning preprocessing
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split

# Ignore warnings
import warnings
warnings.filterwarnings("ignore")

# Display settings
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.float_format", "{:.2f}".format)

# Plot settings
plt.style.use("ggplot")
sns.set_theme(style="whitegrid")

print("Libraries imported successfully!")

Libraries imported successfully!

# Loading Dataset

In [2]:
home_team = pd.read_csv("train_home_team_statistics_df.csv")
home_team.head()

,ID,LEAGUE,TEAM_NAME,TEAM_SHOTS_TOTAL_season_sum,TEAM_SHOTS_INSIDEBOX_season_sum,TEAM_SHOTS_OFF_TARGET_season_sum,TEAM_SHOTS_ON_TARGET_season_sum,TEAM_SHOTS_OUTSIDEBOX_season_sum,TEAM_PASSES_season_sum,TEAM_SUCCESSFUL_PASSES_season_sum,TEAM_SAVES_season_sum,TEAM_CORNERS_season_sum,TEAM_FOULS_season_sum,TEAM_YELLOWCARDS_season_sum,TEAM_REDCARDS_season_sum,TEAM_OFFSIDES_season_sum,TEAM_ATTACKS_season_sum,TEAM_PENALTIES_season_sum,TEAM_SUBSTITUTIONS_season_sum,TEAM_BALL_SAFE_season_sum,TEAM_DANGEROUS_ATTACKS_season_sum,TEAM_INJURIES_season_sum,TEAM_GOALS_season_sum,TEAM_GAME_WON_season_sum,TEAM_GAME_DRAW_season_sum,TEAM_GAME_LOST_season_sum,TEAM_SHOTS_TOTAL_season_average,TEAM_SHOTS_INSIDEBOX_season_average,TEAM_SHOTS_OFF_TARGET_season_average,TEAM_SHOTS_ON_TARGET_season_average,TEAM_SHOTS_OUTSIDEBOX_season_average,TEAM_PASSES_season_average,TEAM_SUCCESSFUL_PASSES_season_average,TEAM_SUCCESSFUL_PASSES_PERCENTAGE_season_average,TEAM_SAVES_season_average,TEAM_CORNERS_season_average,TEAM_BALL_POSSESSION_season_average,TEAM_FOULS_season_average,TEAM_YELLOWCARDS_season_average,TEAM_REDCARDS_season_average,TEAM_OFFSIDES_season_average,TEAM_ATTACKS_season_average,TEAM_PENALTIES_season_average,TEAM_SUBSTITUTIONS_season_average,TEAM_BALL_SAFE_season_average,TEAM_DANGEROUS_ATTACKS_season_average,TEAM_INJURIES_season_average,TEAM_GOALS_season_average,TEAM_GAME_WON_season_average,TEAM_GAME_DRAW_season_average,TEAM_GAME_LOST_season_average,TEAM_SHOTS_TOTAL_season_std,TEAM_SHOTS_INSIDEBOX_season_std,TEAM_SHOTS_OFF_TARGET_season_std,TEAM_SHOTS_ON_TARGET_season_std,TEAM_SHOTS_OUTSIDEBOX_season_std,TEAM_PASSES_season_std,TEAM_SUCCESSFUL_PASSES_season_std,TEAM_SUCCESSFUL_PASSES_PERCENTAGE_season_std,TEAM_SAVES_season_std,TEAM_CORNERS_season_std,TEAM_BALL_POSSESSION_season_std,TEAM_FOULS_season_std,TEAM_YELLOWCARDS_season_std,TEAM_REDCARDS_season_std,TEAM_OFFSIDES_season_std,TEAM_ATTACKS_season_std,TEAM_PENALTIES_season_std,TEAM_SUBSTITUTIONS_season_std,TEAM_BALL_SAFE_season_std,TEAM_DANGEROUS_ATTACKS_season_std,TEAM_INJURIES_season_std,TEAM_GOALS_season_std,TEAM_SHOTS_TOTAL_5_last_match_sum,TEAM_SHOTS_INSIDEBOX_5_last_match_sum,TEAM_SHOTS_OFF_TARGET_5_last_match_sum,TEAM_SHOTS_ON_TARGET_5_last_match_sum,TEAM_SHOTS_OUTSIDEBOX_5_last_match_sum,TEAM_PASSES_5_last_match_sum,TEAM_SUCCESSFUL_PASSES_5_last_match_sum,TEAM_SAVES_5_last_match_sum,TEAM_CORNERS_5_last_match_sum,TEAM_FOULS_5_last_match_sum,TEAM_YELLOWCARDS_5_last_match_sum,TEAM_REDCARDS_5_last_match_sum,TEAM_OFFSIDES_5_last_match_sum,TEAM_ATTACKS_5_last_match_sum,TEAM_PENALTIES_5_last_match_sum,TEAM_SUBSTITUTIONS_5_last_match_sum,TEAM_BALL_SAFE_5_last_match_sum,TEAM_DANGEROUS_ATTACKS_5_last_match_sum,TEAM_INJURIES_5_last_match_sum,TEAM_GOALS_5_last_match_sum,TEAM_GAME_WON_5_last_match_sum,TEAM_GAME_DRAW_5_last_match_sum,TEAM_GAME_LOST_5_last_match_sum,TEAM_SHOTS_TOTAL_5_last_match_average,TEAM_SHOTS_INSIDEBOX_5_last_match_average,TEAM_SHOTS_OFF_TARGET_5_last_match_average,TEAM_SHOTS_ON_TARGET_5_last_match_average,TEAM_SHOTS_OUTSIDEBOX_5_last_match_average,TEAM_PASSES_5_last_match_average,TEAM_SUCCESSFUL_PASSES_5_last_match_average,TEAM_SUCCESSFUL_PASSES_PERCENTAGE_5_last_match_average,TEAM_SAVES_5_last_match_average,TEAM_CORNERS_5_last_match_average,TEAM_BALL_POSSESSION_5_last_match_average,TEAM_FOULS_5_last_match_average,TEAM_YELLOWCARDS_5_last_match_average,TEAM_REDCARDS_5_last_match_average,TEAM_OFFSIDES_5_last_match_average,TEAM_ATTACKS_5_last_match_average,TEAM_PENALTIES_5_last_match_average,TEAM_SUBSTITUTIONS_5_last_match_average,TEAM_BALL_SAFE_5_last_match_average,TEAM_DANGEROUS_ATTACKS_5_last_match_average,TEAM_INJURIES_5_last_match_average,TEAM_GOALS_5_last_match_average,TEAM_GAME_WON_5_last_match_average,TEAM_GAME_DRAW_5_last_match_average,TEAM_GAME_LOST_5_last_match_average,TEAM_SHOTS_TOTAL_5_last_match_std,TEAM_SHOTS_INSIDEBOX_5_last_match_std,TEAM_SHOTS_OFF_TARGET_5_last_match_std,TEAM_SHOTS_ON_TARGET_5_last_match_std,TEAM_SHOTS_OUTSIDEBOX_5_last_match_std,TEAM_PASSES_5_last_match_std,TEAM_SUCCESSFUL_PASSES_5_last_match_std,TEAM_SUCCESSFUL_PASSES_PERCENTAGE_5_last_match_std,TEAM_SAVES_5_last_match_std,TEAM_CORNERS_5_last_match_std,TEAM_BALL_POSSESSION_5_last_match_std,TEAM_FOULS_5_last_match_std,TEAM_YELLOWCARDS_5_last_match_std,TEAM_REDCARDS_5_last_match_std,TEAM_OFFSIDES_5_last_match_std,TEAM_ATTACKS_5_last_match_std,TEAM_PENALTIES_5_last_match_std,TEAM_SUBSTITUTIONS_5_last_match_std,TEAM_BALL_SAFE_5_last_match_std,TEAM_DANGEROUS_ATTACKS_5_last_match_std,TEAM_INJURIES_5_last_match_std,TEAM_GOALS_5_last_match_std
0,0,Ligue 1,Toulouse,3.00,2.00,5.00,2.00,1.00,2.00,2.00,5.00,3.00,6.00,2.00,2.00,1.00,2.00,6.00,8.00,4.00,4.00,0.00,3.00,1.00,6.00,10.00,3.00,2.00,4.00,2.00,1.00,2.00,1.00,2.00,5.00,3.00,1.00,6.00,2.00,2.00,1.00,1.00,6.00,8.00,2.00,4.00,0.00,3.00,1.00,5.00,10.00,5.00,4.00,3.00,5.00,3.00,10.00,9.00,7.00,8.00,1.00,10.00,3.00,7.00,4.00,4.00,2.00,10.00,4.00,4.00,4.00,0.00,1.00,4.00,3.00,6.00,3.00,6.00,0.00,0.00,0.00,2.00,8.00,8.00,0.00,2.00,2.00,10.00,5.00,5.00,6.00,1.00,4.00,2.00,0.00,10.00,4.00,3.00,6.00,3.00,6.00,0.00,0.00,1.00,0.00,2.00,0.00,8.00,8.00,0.00,2.00,2.00,10.00,4.00,5.00,6.00,2.00,4.00,2.00,0.00,10.00,4.00,4.00,7.00,1.00,5.00,4.00,2.00,2.00,4.00,0.00,6.00,6.00,3.00,0.00,6.00,0.00,10.00,8.00,7.00,2.00,4.00,3.00
1,1,Ligue 2,Brest,6.00,8.00,3.00,6.00,5.00,8.00,7.00,10.00,6.00,8.00,3.00,0.00,7.00,7.00,6.00,10.00,9.00,6.00,2.00,10.00,8.00,4.00,1.00,5.00,7.00,2.00,5.00,2.00,5.00,5.00,6.00,9.00,5.00,6.00,5.00,3.00,0.00,5.00,4.00,6.00,7.00,5.00,4.00,2.00,9.00,7.00,3.00,1.00,4.00,3.00,1.00,5.00,6.00,1.00,1.00,0.00,10.00,6.00,3.00,4.00,4.00,0.00,3.00,6.00,8.00,4.00,2.00,4.00,3.00,10.00,5.00,6.00,1.00,7.00,3.00,4.00,4.00,5.00,1.00,2.00,4.00,0.00,7.00,8.00,10.00,10.00,5.00,3.00,3.00,10.00,8.00,3.00,0.00,5.00,6.00,1.00,7.00,3.00,4.00,4.00,5.00,5.00,1.00,5.00,1.00,4.00,0.00,7.00,8.00,10.00,10.00,5.00,3.00,3.00,10.00,8.00,3.00,0.00,5.00,2.00,1.00,3.00,7.00,5.00,5.00,3.00,7.00,2.00,6.00,3.00,4.00,0.00,4.00,3.00,10.00,0.00,1.00,2.00,8.00,4.00
2,2,Serie A,Sampdoria,4.00,2.00,5.00,2.00,8.00,1.00,1.00,2.00,2.00,7.00,7.00,6.00,3.00,4.00,5.00,10.00,5.00,3.00,8.00,1.00,1.00,2.00,8.00,4.00,2.00,4.00,2.00,7.00,1.00,1.00,1.00,2.00,2.00,1.00,7.00,7.00,6.00,3.00,4.00,5.00,10.00,3.00,3.00,7.00,1.00,1.00,2.00,7.00,6.00,6.00,7.00,5.00,5.00,4.00,4.00,9.00,2.00,0.00,6.00,6.00,3.00,5.00,4.00,7.00,6.00,4.00,3.00,5.00,7.00,3.00,5.00,4.00,2.00,4.00,4.00,1.00,1.00,3.00,2.00,7.00,7.00,3.00,4.00,3.00,5.00,10.00,1.00,4.00,2.00,3.00,4.00,0.00,7.00,5.00,4.00,2.00,4.00,4.00,1.00,1.00,2.00,3.00,2.00,2.00,7.00,7.00,3.00,4.00,3.00,5.00,10.00,1.00,4.00,2.00,3.00,4.00,0.00,7.00,3.00,4.00,1.00,4.00,1.00,5.00,4.00,6.00,7.00,4.00,5.00,3.00,4.00,5.00,6.00,3.00,6.00,7.00,2.00,3.00,2.00,4.00
3,3,League One,Coventry City,7.00,5.00,5.00,6.00,6.00,9.00,9.00,2.00,2.00,0.00,0.00,6.00,8.00,6.00,5.00,3.00,3.00,3.00,0.00,5.00,6.00,10.00,0.00,7.00,5.00,6.00,7.00,6.00,9.00,9.00,9.00,2.00,3.00,9.00,1.00,0.00,6.00,8.00,8.00,5.00,4.00,7.00,3.00,0.00,5.00,7.00,10.00,0.00,5.00,8.00,7.00,4.00,4.00,5.00,5.00,0.00,4.00,2.00,4.00,3.00,0.00,9.00,7.00,9.00,6.00,5.00,9.00,6.00,NaN,5.00,3.00,2.00,1.00,4.00,3.00,7.00,7.00,5.00,5.00,3.00,3.00,0.00,5.00,2.00,5.00,10.00,3.00,0.00,NaN,7.00,7.00,5.00,0.00,3.00,1.00,1.00,4.00,3.00,7.00,7.00,6.00,5.00,5.00,7.00,3.00,3.00,0.00,5.00,2.00,5.00,10.00,7.00,0.00,NaN,7.00,7.00,5.00,0.00,5.00,7.00,6.00,2.00,5.00,5.00,6.00,1.00,2.00,10.00,4.00,8.00,4.00,0.00,1.00,8.00,8.00,5.00,5.00,5.00,NaN,6.00
4,4,Premier League,Wolverhampton Wanderers,3.00,3.00,2.00,3.00,4.00,4.00,3.00,4.00,4.00,7.00,4.00,6.00,2.00,4.00,3.00,3.00,5.00,4.00,4.00,3.00,2.00,9.00,4.00,2.00,3.00,1.00,2.00,3.00,3.00,3.00,5.00,4.00,4.00,4.00,6.00,4.00,6.00,2.00,3.00,3.00,2.00,2.00,3.00,4.00,2.00,1.00,8.00,3.00,5.00,1.00,1.00,2.00,7.00,3.00,4.00,8.00,2.00,2.00,8.00,7.00,6.00,8.00,1.00,5.00,5.00,10.00,2.00,2.00,3.00,0.00,3.00,4.00,2.00,3.00,3.00,3.00,3.00,4.00,2.00,3.00,0.00,0.00,0.00,1.00,5.00,3.00,4.00,3.00,7.00,3.00,2.00,6.00,6.00,3.00,4.00,2.00,3.00,3.00,3.00,3.00,5.00,4.00,2.00,4.00,3.00,0.00,0.00,0.00,1.00,5.00,3.00,4.00,3.00,5.00,3.00,2.00,6.00,6.00,4.00,3.00,2.00,0.00,5.00,5.00,5.00,8.00,7.00,2.00,8.00,4.00,1.00,0.00,2.00,5.00,8.00,7.00,2.00,6.00,4.00,4.00

In [3]:
away_team = pd.read_csv("train_away_team_statistics_df.csv")
away_team.head()

,ID,LEAGUE,TEAM_NAME,TEAM_SHOTS_TOTAL_season_sum,TEAM_SHOTS_INSIDEBOX_season_sum,TEAM_SHOTS_OFF_TARGET_season_sum,TEAM_SHOTS_ON_TARGET_season_sum,TEAM_SHOTS_OUTSIDEBOX_season_sum,TEAM_PASSES_season_sum,TEAM_SUCCESSFUL_PASSES_season_sum,TEAM_SAVES_season_sum,TEAM_CORNERS_season_sum,TEAM_FOULS_season_sum,TEAM_YELLOWCARDS_season_sum,TEAM_REDCARDS_season_sum,TEAM_OFFSIDES_season_sum,TEAM_ATTACKS_season_sum,TEAM_PENALTIES_season_sum,TEAM_SUBSTITUTIONS_season_sum,TEAM_BALL_SAFE_season_sum,TEAM_DANGEROUS_ATTACKS_season_sum,TEAM_INJURIES_season_sum,TEAM_GOALS_season_sum,TEAM_GAME_WON_season_sum,TEAM_GAME_DRAW_season_sum,TEAM_GAME_LOST_season_sum,TEAM_SHOTS_TOTAL_season_average,TEAM_SHOTS_INSIDEBOX_season_average,TEAM_SHOTS_OFF_TARGET_season_average,TEAM_SHOTS_ON_TARGET_season_average,TEAM_SHOTS_OUTSIDEBOX_season_average,TEAM_PASSES_season_average,TEAM_SUCCESSFUL_PASSES_season_average,TEAM_SUCCESSFUL_PASSES_PERCENTAGE_season_average,TEAM_SAVES_season_average,TEAM_CORNERS_season_average,TEAM_BALL_POSSESSION_season_average,TEAM_FOULS_season_average,TEAM_YELLOWCARDS_season_average,TEAM_REDCARDS_season_average,TEAM_OFFSIDES_season_average,TEAM_ATTACKS_season_average,TEAM_PENALTIES_season_average,TEAM_SUBSTITUTIONS_season_average,TEAM_BALL_SAFE_season_average,TEAM_DANGEROUS_ATTACKS_season_average,TEAM_INJURIES_season_average,TEAM_GOALS_season_average,TEAM_GAME_WON_season_average,TEAM_GAME_DRAW_season_average,TEAM_GAME_LOST_season_average,TEAM_SHOTS_TOTAL_season_std,TEAM_SHOTS_INSIDEBOX_season_std,TEAM_SHOTS_OFF_TARGET_season_std,TEAM_SHOTS_ON_TARGET_season_std,TEAM_SHOTS_OUTSIDEBOX_season_std,TEAM_PASSES_season_std,TEAM_SUCCESSFUL_PASSES_season_std,TEAM_SUCCESSFUL_PASSES_PERCENTAGE_season_std,TEAM_SAVES_season_std,TEAM_CORNERS_season_std,TEAM_BALL_POSSESSION_season_std,TEAM_FOULS_season_std,TEAM_YELLOWCARDS_season_std,TEAM_REDCARDS_season_std,TEAM_OFFSIDES_season_std,TEAM_ATTACKS_season_std,TEAM_PENALTIES_season_std,TEAM_SUBSTITUTIONS_season_std,TEAM_BALL_SAFE_season_std,TEAM_DANGEROUS_ATTACKS_season_std,TEAM_INJURIES_season_std,TEAM_GOALS_season_std,TEAM_SHOTS_TOTAL_5_last_match_sum,TEAM_SHOTS_INSIDEBOX_5_last_match_sum,TEAM_SHOTS_OFF_TARGET_5_last_match_sum,TEAM_SHOTS_ON_TARGET_5_last_match_sum,TEAM_SHOTS_OUTSIDEBOX_5_last_match_sum,TEAM_PASSES_5_last_match_sum,TEAM_SUCCESSFUL_PASSES_5_last_match_sum,TEAM_SAVES_5_last_match_sum,TEAM_CORNERS_5_last_match_sum,TEAM_FOULS_5_last_match_sum,TEAM_YELLOWCARDS_5_last_match_sum,TEAM_REDCARDS_5_last_match_sum,TEAM_OFFSIDES_5_last_match_sum,TEAM_ATTACKS_5_last_match_sum,TEAM_PENALTIES_5_last_match_sum,TEAM_SUBSTITUTIONS_5_last_match_sum,TEAM_BALL_SAFE_5_last_match_sum,TEAM_DANGEROUS_ATTACKS_5_last_match_sum,TEAM_INJURIES_5_last_match_sum,TEAM_GOALS_5_last_match_sum,TEAM_GAME_WON_5_last_match_sum,TEAM_GAME_DRAW_5_last_match_sum,TEAM_GAME_LOST_5_last_match_sum,TEAM_SHOTS_TOTAL_5_last_match_average,TEAM_SHOTS_INSIDEBOX_5_last_match_average,TEAM_SHOTS_OFF_TARGET_5_last_match_average,TEAM_SHOTS_ON_TARGET_5_last_match_average,TEAM_SHOTS_OUTSIDEBOX_5_last_match_average,TEAM_PASSES_5_last_match_average,TEAM_SUCCESSFUL_PASSES_5_last_match_average,TEAM_SUCCESSFUL_PASSES_PERCENTAGE_5_last_match_average,TEAM_SAVES_5_last_match_average,TEAM_CORNERS_5_last_match_average,TEAM_BALL_POSSESSION_5_last_match_average,TEAM_FOULS_5_last_match_average,TEAM_YELLOWCARDS_5_last_match_average,TEAM_REDCARDS_5_last_match_average,TEAM_OFFSIDES_5_last_match_average,TEAM_ATTACKS_5_last_match_average,TEAM_PENALTIES_5_last_match_average,TEAM_SUBSTITUTIONS_5_last_match_average,TEAM_BALL_SAFE_5_last_match_average,TEAM_DANGEROUS_ATTACKS_5_last_match_average,TEAM_INJURIES_5_last_match_average,TEAM_GOALS_5_last_match_average,TEAM_GAME_WON_5_last_match_average,TEAM_GAME_DRAW_5_last_match_average,TEAM_GAME_LOST_5_last_match_average,TEAM_SHOTS_TOTAL_5_last_match_std,TEAM_SHOTS_INSIDEBOX_5_last_match_std,TEAM_SHOTS_OFF_TARGET_5_last_match_std,TEAM_SHOTS_ON_TARGET_5_last_match_std,TEAM_SHOTS_OUTSIDEBOX_5_last_match_std,TEAM_PASSES_5_last_match_std,TEAM_SUCCESSFUL_PASSES_5_last_match_std,TEAM_SUCCESSFUL_PASSES_PERCENTAGE_5_last_match_std,TEAM_SAVES_5_last_match_std,TEAM_CORNERS_5_last_match_std,TEAM_BALL_POSSESSION_5_last_match_std,TEAM_FOULS_5_last_match_std,TEAM_YELLOWCARDS_5_last_match_std,TEAM_REDCARDS_5_last_match_std,TEAM_OFFSIDES_5_last_match_std,TEAM_ATTACKS_5_last_match_std,TEAM_PENALTIES_5_last_match_std,TEAM_SUBSTITUTIONS_5_last_match_std,TEAM_BALL_SAFE_5_last_match_std,TEAM_DANGEROUS_ATTACKS_5_last_match_std,TEAM_INJURIES_5_last_match_std,TEAM_GOALS_5_last_match_std
0,0,Ligue 1,Olympique Marseille,4.00,1.00,4.00,1.00,5.00,4.00,3.00,6.00,4.00,6.00,10.00,6.00,1.00,4.00,10.00,8.00,2.00,4.00,1.00,4.00,5.00,8.00,0.00,4.00,1.00,4.00,1.00,5.00,3.00,3.00,5.00,6.00,4.00,3.00,6.00,10.00,6.00,1.00,4.00,10.00,8.00,0.00,4.00,0.00,4.00,4.00,7.00,0.00,4.00,1.00,0.00,3.00,10.00,7.00,7.00,5.00,4.00,6.00,7.00,2.00,7.00,9.00,1.00,1.00,6.00,4.00,3.00,10.00,1.00,4.00,2.00,2.00,2.00,1.00,4.00,2.00,3.00,2.00,4.00,4.00,6.00,3.00,5.00,4.00,10.00,5.00,0.00,6.00,0.00,4.00,7.00,0.00,5.00,2.00,2.00,2.00,1.00,4.00,2.00,3.00,5.00,2.00,4.00,3.00,4.00,6.00,3.00,4.00,4.00,10.00,4.00,0.00,6.00,0.00,4.00,7.00,0.00,5.00,0.00,3.00,2.00,3.00,7.00,6.00,6.00,6.00,0.00,1.00,8.00,2.00,5.00,5.00,4.00,0.00,6.00,8.00,4.00,3.00,2.00,3.00
1,1,Ligue 2,Red Star,4.00,3.00,4.00,3.00,8.00,8.00,7.00,8.00,5.00,8.00,3.00,2.00,5.00,5.00,3.00,10.00,4.00,7.00,5.00,2.00,1.00,4.00,8.00,3.00,2.00,2.00,2.00,6.00,4.00,4.00,5.00,8.00,4.00,4.00,5.00,3.00,1.00,3.00,2.00,3.00,7.00,0.00,5.00,6.00,2.00,1.00,3.00,7.00,5.00,0.00,4.00,2.00,8.00,6.00,5.00,3.00,7.00,1.00,5.00,9.00,2.00,4.00,3.00,7.00,6.00,4.00,10.00,6.00,4.00,2.00,3.00,2.00,0.00,3.00,5.00,5.00,5.00,7.00,3.00,5.00,3.00,0.00,5.00,3.00,5.00,5.00,0.00,4.00,3.00,2.00,2.00,3.00,7.00,3.00,2.00,0.00,3.00,5.00,5.00,5.00,6.00,7.00,3.00,5.00,5.00,3.00,0.00,4.00,3.00,5.00,4.00,0.00,4.00,3.00,2.00,2.00,3.00,7.00,4.00,0.00,3.00,3.00,4.00,9.00,8.00,5.00,5.00,1.00,6.00,10.00,0.00,0.00,3.00,1.00,8.00,4.00,10.00,0.00,5.00,3.00
2,2,Serie A,Bologna,4.00,3.00,4.00,2.00,6.00,4.00,4.00,1.00,6.00,8.00,10.00,7.00,7.00,5.00,3.00,7.00,4.00,7.00,2.00,3.00,2.00,5.00,5.00,4.00,3.00,4.00,2.00,5.00,4.00,4.00,5.00,1.00,6.00,6.00,8.00,10.00,7.00,6.00,5.00,3.00,7.00,3.00,6.00,2.00,3.00,2.00,5.00,5.00,2.00,7.00,2.00,6.00,5.00,4.00,4.00,5.00,3.00,7.00,10.00,0.00,6.00,7.00,6.00,7.00,5.00,5.00,9.00,7.00,4.00,2.00,7.00,5.00,6.00,0.00,7.00,3.00,3.00,2.00,5.00,6.00,3.00,6.00,4.00,8.00,0.00,6.00,4.00,8.00,6.00,1.00,2.00,2.00,7.00,7.00,5.00,6.00,0.00,7.00,3.00,3.00,5.00,2.00,5.00,6.00,6.00,3.00,6.00,4.00,8.00,0.00,6.00,4.00,8.00,6.00,1.00,2.00,2.00,7.00,1.00,5.00,2.00,0.00,10.00,3.00,4.00,3.00,8.00,1.00,4.00,2.00,6.00,10.00,4.00,4.00,0.00,8.00,3.00,0.00,9.00,6.00
3,3,League One,Bolton Wanderers,0.00,0.00,0.00,0.00,1.00,3.00,3.00,8.00,1.00,3.00,0.00,5.00,2.00,2.00,0.00,0.00,10.00,0.00,NaN,0.00,1.00,5.00,6.00,0.00,0.00,2.00,0.00,2.00,4.00,4.00,5.00,8.00,2.00,4.00,5.00,0.00,5.00,2.00,5.00,0.00,1.00,8.00,0.00,NaN,0.00,1.00,5.00,7.00,4.00,5.00,3.00,2.00,3.00,7.00,4.00,6.00,8.00,5.00,6.00,7.00,1.00,6.00,3.00,4.00,0.00,5.00,4.00,3.00,NaN,1.00,7.00,3.00,5.00,1.00,10.00,5.00,4.00,3.00,5.00,3.00,2.00,0.00,0.00,7.00,0.00,5.00,2.00,5.00,NaN,3.00,2.00,2.00,7.00,7.00,3.00,5.00,1.00,10.00,5.00,4.00,5.00,3.00,5.00,5.00,3.00,2.00,0.00,0.00,7.00,0.00,4.00,2.00,5.00,NaN,3.00,2.00,2.00,7.00,6.00,4.00,6.00,0.00,7.00,2.00,3.00,0.00,4.00,0.00,3.00,5.00,0.00,0.00,1.00,2.00,0.00,5.00,6.00,3.00,NaN,2.00
4,4,Premier League,Leicester City,5.00,4.00,5.00,6.00,5.00,6.00,6.00,4.00,5.00,5.00,0.00,0.00,6.00,6.00,6.00,7.00,6.00,5.00,2.00,7.00,5.00,2.00,4.00,4.00,4.00,5.00,6.00,5.00,6.00,5.00,6.00,3.00,5.00,7.00,4.00,0.00,0.00,6.00,5.00,6.00,5.00,3.00,4.00,2.00,7.00,5.00,2.00,3.00,8.00,10.00,4.00,10.00,8.00,5.00,5.00,3.00,6.00,2.00,6.00,9.00,2.00,0.00,4.00,7.00,7.00,4.00,4.00,1.00,5.00,10.00,6.00,6.00,1.00,10.00,6.00,5.00,5.00,4.00,2.00,4.00,0.00,0.00,3.00,5.00,10.00,7.00,1.00,4.00,4.00,8.00,4.00,3.00,6.00,6.00,6.00,1.00,10.00,6.00,5.00,5.00,6.00,4.00,2.00,7.00,4.00,0.00,0.00,3.00,5.00,10.00,7.00,1.00,4.00,3.00,8.00,4.00,3.00,6.00,8.00,4.00,3.00,7.00,4.00,8.00,8.00,6.00,10.00,2.00,7.00,2.00,1.00,0.00,4.00,4.00,9.00,4.00,1.00,4.00,6.00,5.00

In [4]:
home_player = pd.read_csv("train_home_player_statistics_df.csv")
home_player.head()

,ID,LEAGUE,TEAM_NAME,POSITION,PLAYER_NAME,PLAYER_ACCURATE_CROSSES_season_sum,PLAYER_ACCURATE_PASSES_season_sum,PLAYER_AERIALS_WON_season_sum,PLAYER_ASSISTS_season_sum,PLAYER_BIG_CHANCES_CREATED_season_sum,PLAYER_BIG_CHANCES_MISSED_season_sum,PLAYER_BLOCKED_SHOTS_season_sum,PLAYER_CAPTAIN_season_sum,PLAYER_CLEARANCES_season_sum,PLAYER_CLEARANCE_OFFLINE_season_sum,PLAYER_DISPOSSESSED_season_sum,PLAYER_DRIBBLED_ATTEMPTS_season_sum,PLAYER_DRIBBLED_PAST_season_sum,PLAYER_DUELS_LOST_season_sum,PLAYER_DUELS_WON_season_sum,PLAYER_ERROR_LEAD_TO_GOAL_season_sum,PLAYER_FOULS_season_sum,PLAYER_FOULS_DRAWN_season_sum,PLAYER_GOALKEEPER_GOALS_CONCEDED_season_sum,PLAYER_GOALS_season_sum,PLAYER_GOALS_CONCEDED_season_sum,PLAYER_HIT_WOODWORK_season_sum,PLAYER_INTERCEPTIONS_season_sum,PLAYER_KEY_PASSES_season_sum,PLAYER_MINUTES_PLAYED_season_sum,PLAYER_OFFSIDES_season_sum,PLAYER_OWN_GOALS_season_sum,PLAYER_PASSES_season_sum,PLAYER_PENALTIES_COMMITTED_season_sum,PLAYER_PENALTIES_MISSES_season_sum,PLAYER_PENALTIES_SAVED_season_sum,PLAYER_PENALTIES_SCORED_season_sum,PLAYER_PENALTIES_WON_season_sum,PLAYER_REDCARDS_season_sum,PLAYER_SAVES_season_sum,PLAYER_SAVES_INSIDE_BOX_season_sum,PLAYER_SHOTS_BLOCKED_season_sum,PLAYER_SHOTS_ON_TARGET_season_sum,PLAYER_SHOTS_TOTAL_season_sum,PLAYER_STARTING_LINEUP_season_sum,PLAYER_SUCCESSFUL_DRIBBLES_season_sum,PLAYER_TACKLES_season_sum,PLAYER_TOTAL_CROSSES_season_sum,PLAYER_TOTAL_DUELS_season_sum,PLAYER_YELLOWCARDS_season_sum,PLAYER_PUNCHES_season_sum,PLAYER_LONG_BALLS_season_sum,PLAYER_LONG_BALLS_WON_season_sum,PLAYER_SHOTS_OFF_TARGET_season_sum,PLAYER_ACCURATE_CROSSES_season_average,PLAYER_ACCURATE_PASSES_season_average,PLAYER_ACCURATE_PASSES_PERCENTAGE_season_average,PLAYER_AERIALS_WON_season_average,PLAYER_ASSISTS_season_average,PLAYER_BIG_CHANCES_CREATED_season_average,PLAYER_BIG_CHANCES_MISSED_season_average,PLAYER_BLOCKED_SHOTS_season_average,PLAYER_CAPTAIN_season_average,PLAYER_CLEARANCES_season_average,PLAYER_CLEARANCE_OFFLINE_season_average,PLAYER_DISPOSSESSED_season_average,PLAYER_DRIBBLED_ATTEMPTS_season_average,PLAYER_DRIBBLED_PAST_season_average,PLAYER_DUELS_LOST_season_average,PLAYER_DUELS_WON_season_average,PLAYER_ERROR_LEAD_TO_GOAL_season_average,PLAYER_FOULS_season_average,PLAYER_FOULS_DRAWN_season_average,PLAYER_GOALKEEPER_GOALS_CONCEDED_season_average,PLAYER_GOALS_season_average,PLAYER_GOALS_CONCEDED_season_average,PLAYER_HIT_WOODWORK_season_average,PLAYER_INTERCEPTIONS_season_average,PLAYER_KEY_PASSES_season_average,PLAYER_MINUTES_PLAYED_season_average,PLAYER_OFFSIDES_season_average,PLAYER_OWN_GOALS_season_average,PLAYER_PASSES_season_average,PLAYER_PENALTIES_COMMITTED_season_average,PLAYER_PENALTIES_MISSES_season_average,PLAYER_PENALTIES_SAVED_season_average,PLAYER_PENALTIES_SCORED_season_average,PLAYER_PENALTIES_WON_season_average,PLAYER_RATING_season_average,PLAYER_REDCARDS_season_average,PLAYER_SAVES_season_average,PLAYER_SAVES_INSIDE_BOX_season_average,PLAYER_SHOTS_BLOCKED_season_average,PLAYER_SHOTS_ON_TARGET_season_average,PLAYER_SHOTS_TOTAL_season_average,PLAYER_STARTING_LINEUP_season_average,PLAYER_SUCCESSFUL_DRIBBLES_season_average,PLAYER_TACKLES_season_average,PLAYER_TOTAL_CROSSES_season_average,PLAYER_TOTAL_DUELS_season_average,PLAYER_YELLOWCARDS_season_average,PLAYER_PUNCHES_season_average,PLAYER_LONG_BALLS_season_average,PLAYER_LONG_BALLS_WON_season_average,PLAYER_SHOTS_OFF_TARGET_season_average,PLAYER_ACCURATE_CROSSES_season_std,PLAYER_ACCURATE_PASSES_season_std,PLAYER_ACCURATE_PASSES_PERCENTAGE_season_std,PLAYER_AERIALS_WON_season_std,PLAYER_ASSISTS_season_std,PLAYER_BIG_CHANCES_CREATED_season_std,PLAYER_BIG_CHANCES_MISSED_season_std,PLAYER_BLOCKED_SHOTS_season_std,PLAYER_CAPTAIN_season_std,PLAYER_CLEARANCES_season_std,PLAYER_CLEARANCE_OFFLINE_season_std,PLAYER_DISPOSSESSED_season_std,PLAYER_DRIBBLED_ATTEMPTS_season_std,PLAYER_DRIBBLED_PAST_season_std,PLAYER_DUELS_LOST_season_std,PLAYER_DUELS_WON_season_std,PLAYER_ERROR_LEAD_TO_GOAL_season_std,PLAYER_FOULS_season_std,PLAYER_FOULS_DRAWN_season_std,PLAYER_GOALKEEPER_GOALS_CONCEDED_season_std,PLAYER_GOALS_season_std,PLAYER_GOALS_CONCEDED_season_std,PLAYER_HIT_WOODWORK_season_std,PLAYER_INTERCEPTIONS_season_std,PLAYER_KEY_PASSES_season_std,PLAYER_MINUTES_PLAYED_season_std,PLAYER_OFFSIDES_season_std,PLAYER_OWN_GOALS_season_std,PLAYER_PASSES_season_std,PLAYER_PENALTIES_COMMITTED_season_std,PLAYER_PENALTIES_MISSES_season_std,PLAYER_PENALTIES_SAVED_season_std,PLAYER_PENALTIES_SCORED_season_std,PLAYER_PENALTIES_WON_season_std,PLAYER_RATING_season_std,PLAYER_REDCARDS_season_std,PLAYER_SAVES_season_std,PLAYER_SAVES_INSIDE_BOX_season_std,PLAYER_SHOTS_BLOCKED_season_std,PLAYER_SHOTS_ON_TARGET_season_std,PLAYER_SHOTS_TOTAL_season_std,PLAYER_STARTING_LINEUP_season_std,PLAYER_SUCCESSFUL_DRIBBLES_season_std,PLAYER_TACKLES_season_std,PLAYER_TOTAL_CROSSES_season_std,PLAYER_TOTAL_DUELS_season_std,PLAYER_YELLOWCARDS_season_std,PLAYER_PUNCHES_season_std,PLAYER_LONG_BALLS_season_std,PLAYER_LONG_BALLS_WON_season_std,PLAYER_SHOTS_OFF_TARGET_season_std,PLAYER_ACCURATE_CROSSES_5_last_match_sum,PLAYER_ACCURATE_PASSES_5_last_match_sum,PLAYER_AERIALS_WON_5_last_match_sum,PLAYER_ASSISTS_5_last_match_sum,PLAYER_BIG_CHANCES_CREATED_5_last_match_sum,PLAYER_BIG_CHANCES_MISSED_5_last_match_sum,PLAYER_BLOCKED_SHOTS_5_last_match_sum,PLAYER_CAPTAIN_5_last_match_sum,PLAYER_CLEARANCES_5_last_match_sum,PLAYER_CLEARANCE_OFFLINE_5_last_match_sum,PLAYER_DISPOSSESSED_5_last_match_sum,PLAYER_DRIBBLED_ATTEMPTS_5_last_match_sum,PLAYER_DRIBBLED_PAST_5_last_match_sum,PLAYER_DUELS_LOST_5_last_match_sum,PLAYER_DUELS_WON_5_last_match_sum,PLAYER_ERROR_LEAD_TO_GOAL_5_last_match_sum,PLAYER_FOULS_5_last_match_sum,PLAYER_FOULS_DRAWN_5_last_match_sum,PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_sum,PLAYER_GOALS_5_last_match_sum,PLAYER_GOALS_CONCEDED_5_last_match_sum,PLAYER_HIT_WOODWORK_5_last_match_sum,PLAYER_INTERCEPTIONS_5_last_match_sum,PLAYER_KEY_PASSES_5_last_match_sum,PLAYER_MINUTES_PLAYED_5_last_match_sum,PLAYER_OFFSIDES_5_last_match_sum,PLAYER_OWN_GOALS_5_last_match_sum,PLAYER_PASSES_5_last_match_sum,PLAYER_PENALTIES_COMMITTED_5_last_match_sum,PLAYER_PENALTIES_MISSES_5_last_match_sum,PLAYER_PENALTIES_SAVED_5_last_match_sum,PLAYER_PENALTIES_SCORED_5_last_match_sum,PLAYER_PENALTIES_WON_5_last_match_sum,PLAYER_REDCARDS_5_last_match_sum,PLAYER_SAVES_5_last_match_sum,PLAYER_SAVES_INSIDE_BOX_5_last_match_sum,PLAYER_SHOTS_BLOCKED_5_last_match_sum,PLAYER_SHOTS_ON_TARGET_5_last_match_sum,PLAYER_SHOTS_TOTAL_5_last_match_sum,PLAYER_STARTING_LINEUP_5_last_match_sum,PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_sum,PLAYER_TACKLES_5_last_match_sum,PLAYER_TOTAL_CROSSES_5_last_match_sum,PLAYER_TOTAL_DUELS_5_last_match_sum,PLAYER_YELLOWCARDS_5_last_match_sum,PLAYER_PUNCHES_5_last_match_sum,PLAYER_LONG_BALLS_5_last_match_sum,PLAYER_LONG_BALLS_WON_5_last_match_sum,PLAYER_SHOTS_OFF_TARGET_5_last_match_sum,PLAYER_ACCURATE_CROSSES_5_last_match_average,PLAYER_ACCURATE_PASSES_5_last_match_average,PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_average,PLAYER_AERIALS_WON_5_last_match_average,PLAYER_ASSISTS_5_last_match_average,PLAYER_BIG_CHANCES_CREATED_5_last_match_average,PLAYER_BIG_CHANCES_MISSED_5_last_match_average,PLAYER_BLOCKED_SHOTS_5_last_match_average,PLAYER_CAPTAIN_5_last_match_average,PLAYER_CLEARANCES_5_last_match_average,PLAYER_CLEARANCE_OFFLINE_5_last_match_average,PLAYER_DISPOSSESSED_5_last_match_average,PLAYER_DRIBBLED_ATTEMPTS_5_last_match_average,PLAYER_DRIBBLED_PAST_5_last_match_average,PLAYER_DUELS_LOST_5_last_match_average,PLAYER_DUELS_WON_5_last_match_average,PLAYER_ERROR_LEAD_TO_GOAL_5_last_match_average,PLAYER_FOULS_5_last_match_average,PLAYER_FOULS_DRAWN_5_last_match_average,PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_average,PLAYER_GOALS_5_last_match_average,PLAYER_GOALS_CONCEDED_5_last_match_average,PLAYER_HIT_WOODWORK_5_last_match_average,PLAYER_INTERCEPTIONS_5_last_match_average,PLAYER_KEY_PASSES_5_last_match_average,PLAYER_MINUTES_PLAYED_5_last_match_average,PLAYER_OFFSIDES_5_last_match_average,PLAYER_OWN_GOALS_5_last_match_average,PLAYER_PASSES_5_last_match_average,PLAYER_PENALTIES_COMMITTED_5_last_match_average,PLAYER_PENALTIES_MISSES_5_last_match_average,PLAYER_PENALTIES_SAVED_5_last_match_average,PLAYER_PENALTIES_SCORED_5_last_match_average,PLAYER_PENALTIES_WON_5_last_match_average,PLAYER_RATING_5_last_match_average,PLAYER_REDCARDS_5_last_match_average,PLAYER_SAVES_5_last_match_average,PLAYER_SAVES_INSIDE_BOX_5_last_match_average,PLAYER_SHOTS_BLOCKED_5_last_match_average,PLAYER_SHOTS_ON_TARGET_5_last_match_average,PLAYER_SHOTS_TOTAL_5_last_match_average,PLAYER_STARTING_LINEUP_5_last_match_average,PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_average,PLAYER_TACKLES_5_last_match_average,PLAYER_TOTAL_CROSSES_5_last_match_average,PLAYER_TOTAL_DUELS_5_last_match_average,PLAYER_YELLOWCARDS_5_last_match_average,PLAYER_PUNCHES_5_last_match_average,PLAYER_LONG_BALLS_5_last_match_average,PLAYER_LONG_BALLS_WON_5_last_match_average,PLAYER_SHOTS_OFF_TARGET_5_last_match_average,PLAYER_ACCURATE_CROSSES_5_last_match_std,PLAYER_ACCURATE_PASSES_5_last_match_std,PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_std,PLAYER_AERIALS_WON_5_last_match_std,PLAYER_ASSISTS_5_last_match_std,PLAYER_BIG_CHANCES_CREATED_5_last_match_std,PLAYER_BIG_CHANCES_MISSED_5_last_match_std,PLAYER_BLOCKED_SHOTS_5_last_match_std,PLAYER_CAPTAIN_5_last_match_std,PLAYER_CLEARANCES_5_last_match_std,PLAYER_CLEARANCE_OFFLINE_5_last_match_std,PLAYER_DISPOSSESSED_5_last_match_std,PLAYER_DRIBBLED_ATTEMPTS_5_last_match_std,PLAYER_DRIBBLED_PAST_5_last_match_std,PLAYER_DUELS_LOST_5_last_match_std,PLAYER_DUELS_WON_5_last_match_std,PLAYER_ERROR_LEAD_TO_GOAL_5_last_match_std,PLAYER_FOULS_5_last_match_std,PLAYER_FOULS_DRAWN_5_last_match_std,PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_std,PLAYER_GOALS_5_last_match_std,PLAYER_GOALS_CONCEDED_5_last_match_std,PLAYER_HIT_WOODWORK_5_last_match_std,PLAYER_INTERCEPTIONS_5_last_match_std,PLAYER_KEY_PASSES_5_last_match_std,PLAYER_MINUTES_PLAYED_5_last_match_std,PLAYER_OFFSIDES_5_last_match_std,PLAYER_OWN_GOALS_5_last_match_std,PLAYER_PASSES_5_last_match_std,PLAYER_PENALTIES_COMMITTED_5_last_match_std,PLAYER_PENALTIES_MISSES_5_last_match_std,PLAYER_PENALTIES_SAVED_5_last_match_std,PLAYER_PENALTIES_SCORED_5_last_match_std,PLAYER_PENALTIES_WON_5_last_match_std,PLAYER_RATING_5_last_match_std,PLAYER_REDCARDS_5_last_match_std,PLAYER_SAVES_5_last_match_std,PLAYER_SAVES_INSIDE_BOX_5_last_match_std,PLAYER_SHOTS_BLOCKED_5_last_match_std,PLAYER_SHOTS_ON_TARGET_5_last_match_std,PLAYER_SHOTS_TOTAL_5_last_match_std,PLAYER_STARTING_LINEUP_5_last_match_std,PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_std,PLAYER_TACKLES_5_last_match_std,PLAYER_TOTAL_CROSSES_5_last_match_std,PLAYER_TOTAL_DUELS_5_last_match_std,PLAYER_YELLOWCARDS_5_last_match_std,PLAYER_PUNCHES_5_last_match_std,PLAYER_LONG_BALLS_5_last_match_std,PLAYER_LONG_BALLS_WON_5_last_match_std,PLAYER_SHOTS_OFF_TARGET_5_last_match_std
0,0,Ligue 1,Toulouse,defender,Agustín Rogel,0.00,8.00,5.00,0.00,0.00,0.00,0.00,NaN,4.00,0.00,0.00,0.00,0.00,0.00,3.00,0.00,0.00,0.00,0.00,0.00,4.00,0.00,0.00,0.00,6.00,0.00,0.00,7.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2.00,7.00,0.00,0.00,0.00,1.00,0.00,NaN,NaN,NaN,NaN,0.00,89.00,NaN,61.00,0.00,0.00,0.00,0.00,NaN,44.00,0.00,0.00,0.00,0.00,0.00,35.00,0.00,0.00,0.00,0.00,0.00,25.00,0.00,0.00,0.00,86.00,0.00,0.00,88.00,0.00,0.00,0.00,0.00,0.00,86.00,0.00,0.00,0.00,0.00,0.00,18.00,100.00,0.00,0.00,0.00,20.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,16.00,10.00,0.00,0.00,0.00,0.00,NaN,8.00,0.00,0.00,0.00,0.00,0.00,6.00,0.00,0.00,0.00,0.00,0.00,7.00,0.00,0.00,0.00,17.00,0.00,0.00,16.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,3.00,20.00,0.00,0.00,0.00,3.00,0.00,NaN,NaN,NaN,NaN,0.00,81.00,NaN,54.00,0.00,0.00,0.00,0.00,NaN,44.00,0.00,0.00,0.00,0.00,0.00,31.00,0.00,0.00,0.00,0.00,0.00,25.00,0.00,0.00,0.00,86.00,0.00,0.00,82.00,0.00,0.00,0.00,0.00,0.00,82.00,0.00,0.00,0.00,0.00,0.00,18.00,100.00,0.00,0.00,0.00,19.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,Ligue 1,Toulouse,defender,Mathieu Goncalves,0.00,7.00,4.00,0.00,0.00,0.00,6.00,NaN,12.00,0.00,4.00,1.00,19.00,8.00,7.00,0.00,9.00,2.00,0.00,0.00,64.00,0.00,3.00,0.00,20.00,0.00,100.00,8.00,50.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,6.00,0.00,0.00,15.00,4.00,5.00,0.00,8.00,20.00,NaN,NaN,NaN,NaN,0.00,11.00,75.00,6.00,0.00,0.00,0.00,9.00,NaN,17.00,0.00,8.00,1.00,25.00,14.00,11.00,0.00,10.00,3.00,0.00,0.00,57.00,0.00,3.00,0.00,38.00,0.00,42.00,14.00,71.00,0.00,0.00,0.00,0.00,32.00,0.00,0.00,0.00,11.00,0.00,0.00,28.00,3.00,10.00,0.00,14.00,14.00,NaN,NaN,NaN,NaN,0.00,26.00,31.00,16.00,0.00,0.00,0.00,23.00,NaN,33.00,0.00,32.00,7.00,45.00,30.00,21.00,0.00,17.00,13.00,0.00,0.00,48.00,0.00,10.00,0.00,69.00,0.00,65.00,35.00,59.00,0.00,0.00,0.00,0.00,59.00,0.00,0.00,0.00,23.00,0.00,0.00,69.00,13.00,14.00,0.00,32.00,65.00,NaN,NaN,NaN,NaN,0.00,10.00,8.00,0.00,0.00,0.00,12.00,NaN,14.00,0.00,0.00,2.00,28.00,14.00,9.00,0.00,11.00,0.00,0.00,0.00,92.00,0.00,0.00,0.00,34.00,0.00,0.00,12.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,12.00,0.00,0.00,20.00,4.00,8.00,0.00,14.00,25.00,NaN,NaN,NaN,NaN,0.00,10.00,75.00,8.00,0.00,0.00,0.00,12.00,NaN,14.00,0.00,0.00,2.00,28.00,14.00,9.00,0.00,10.00,0.00,0.00,0.00,60.00,0.00,0.00,0.00,34.00,0.00,0.00,12.00,0.00,0.00,0.00,0.00,0.00,29.00,0.00,0.00,0.00,12.00,0.00,0.00,20.00,4.00,8.00,0.00,14.00,20.00,NaN,NaN,NaN,NaN,0.00,26.00,25.00,16.00,0.00,0.00,0.00,25.00,NaN,24.00,0.00,0.00,9.00,48.00,47.00,22.00,0.00,17.00,0.00,0.00,0.00,31.00,0.00,0.00,0.00,67.00,0.00,0.00,31.00,0.00,0.00,0.00,0.00,0.00,62.00,0.00,0.00,0.00,21.00,0.00,0.00,63.00,14.00,13.00,0.00,36.00,77.00,NaN,NaN,NaN,NaN
2,0,Ligue 1,Toulouse,goalkeeper,Baptiste Reynet,0.00,33.00,2.00,0.00,0.00,0.00,0.00,NaN,16.00,0.00,0.00,0.00,0.00,1.00,2.00,0.00,0.00,0.00,100.00,0.00,100.00,0.00,0.00,2.00,100.00,0.00,0.00,48.00,0.00,0.00,100.00,0.00,0.00,0.00,78.00,84.00,0.00,0.00,0.00,100.00,0.00,1.00,0.00,2.00,20.00,NaN,NaN,NaN,NaN,0.00,27.00,53.00,2.00,0.00,0.00,0.00,0.00,NaN,12.00,0.00,0.00,0.00,0.00,1.00,2.00,0.00,0.00,0.00,100.00,0.00,48.00,0.00,0.00,2.00,100.00,0.00,0.00,41.00,0.00,0.00,100.00,0.00,0.00,86.00,0.00,66.00,76.00,0.00,0.00,0.00,100.00,0.00,1.00,0.00,2.00,7.00,NaN,NaN,NaN,NaN,0.00,18.00,42.00,8.00,0.00,0.00,0.00,0.00,NaN,18.00,0.00,0.00,0.00,0.00,5.00,8.00,0.00,0.00,0.00,62.00,0.00,43.00,0.00,0.00,9.00,0.00,0.00,0.00,12.00,0.00,0.00,100.00,0.00,0.00,13.00,0.00,77.00,84.00,0.00,0.00,0.00,0.00,0.00,7.00,0.00,6.00,48.00,NaN,NaN,NaN,NaN,0.00,19.00,0.00,0.00,0.00,0.00,0.00,NaN,11.00,0.00,0.00,0.00,0.00,1.00,0.00,0.00,0.00,0.00,100.00,0.00,100.00,0.00,0.00,0.00,100.00,0.00,0.00,34.00,0.00,0.00,0.00,0.00,0.00,0.00,34.00,27.00,0.00,0.00,0.00,100.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,0.00,19.00,43.00,0.00,0.00,0.00,0.00,0.00,NaN,11.00,0.00,0.00,0.00,0.00,1.00,0.00,0.00,0.00,0.00,100.00,0.00,65.00,0.00,0.00,0.00,100.00,0.00,0.00,34.00,0.00,0.00,0.00,0.00,0.00,74.00,0.00,34.00,27.00,0.00,0.00,0.00,100.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,0.00,11.00,31.00,0.00,0.00,0.00,0.00,0.00,NaN,6.00,0.00,0.00,0.00,0.00,7.00,0.00,0.00,0.00,0.00,51.00,0.00,31.00,0.00,0.00,0.00,0.00,0.00,0.00,7.00,0.00,0.00,0.00,0.00,0.00,9.00,0.00,61.00,38.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,3.00,0.00,NaN,NaN,NaN,NaN
3,0,Ligue 1,Toulouse,midfielder,Jean-Victor Makengo,8.00,27.00,2.00,0.00,8.00,0.00,6.00,NaN,1.00,0.00,28.00,6.00,4.00,32.00,23.00,0.00,37.00,32.00,0.00,22.00,80.00,0.00,3.00,24.00,53.00,6.00,0.00,29.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,20.00,11.00,16.00,61.00,8.00,13.00,3.00,30.00,0.00,NaN,NaN,NaN,NaN,6.00,23.00,68.00,2.00,0.00,7.00,0.00,5.00,NaN,1.00,0.00,26.00,3.00,3.00,30.00,17.00,0.00,23.00,22.00,0.00,18.00,38.00,0.00,1.00,20.00,53.00,6.00,0.00,25.00,0.00,0.00,0.00,0.00,0.00,63.00,0.00,0.00,0.00,19.00,5.00,9.00,61.00,3.00,13.00,2.00,27.00,0.00,NaN,NaN,NaN,NaN,18.00,38.00,46.00,8.00,0.00,24.00,0.00,16.00,NaN,5.00,0.00,51.00,17.00,11.00,39.00,26.00,0.00,36.00,41.00,0.00,41.00,39.00,0.00,7.00,30.00,59.00,22.00,0.00,42.00,0.00,0.00,0.00,0.00,0.00,53.00,0.00,0.00,0.00,26.00,19.00,40.00,71.00,19.00,23.00,9.00,36.00,0.00,NaN,NaN,NaN,NaN,6.00,3.00,0.00,0.00,0.00,0.00,12.00,NaN,2.00,0.00,9.00,0.00,7.00,9.00,6.00,0.00,11.00,10.00,0.00,0.00,61.00,0.00,0.00,4.00,15.00,0.00,0.00,5.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,12.00,0.00,3.00,20.00,0.00,8.00,2.00,9.00,0.00,NaN,NaN,NaN,NaN,5.00,3.00,55.00,0.00,0.00,0.00,0.00,12.00,NaN,2.00,0.00,9.00,0.00,7.00,9.00,6.00,0.00,10.00,10.00,0.00,0.00,40.00,0.00,0.00,4.00,15.00,0.00,0.00,5.00,0.00,0.00,0.00,0.00,0.00,46.00,0.00,0.00,0.00,12.00,0.00,3.00,20.00,0.00,8.00,1.00,9.00,0.00,NaN,NaN,NaN,NaN,12.00,7.00,30.00,0.00,0.00,0.00,0.00,25.00,NaN,6.00,0.00,19.00,0.00,16.00,29.00,11.00,0.00,17.00,18.00,0.00,0.00,31.00,0.00,0.00,15.00,29.00,0.00,0.00,9.00,0.00,0.00,0.00,0.00,0.00,64.00,0.00,0.00,0.00,21.00,0.00,14.00,63.00,0.00,13.00,6.00,17.00,0.00,NaN,NaN,NaN,NaN
4,0,Ligue 1,Toulouse,NaN,Efthymios Koulouris,2.00,23.00,27.00,14.00,8.00,37.00,12.00,NaN,7.00,0.00,33.00,11.00,9.00,53.00,29.00,0.00,28.00,16.00,0.00,44.00,84.00,100.00,6.00,24.00,77.00,20.00,0.00,28.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,26.00,58.00,59.00,76.00,16.00,5.00,4.00,44.00,0.00,NaN,NaN,NaN,NaN,2.00,19.00,72.00,23.00,7.00,7.00,23.00,10.00,NaN,5.00,0.00,30.00,6.00,6.00,49.00,22.00,0.00,17.00,11.00,0.00,37.00,40.00,76.00,3.00,20.00,77.00,19.00,0.00,24.00,0.00,0.00,0.00,0.00,0.00,87.00,0.00,0.00,0.00,25.00,29.00,35.00,76.00,6.00,5.00,3.00,41.00,0.00,NaN,NaN,NaN,NaN,11.00,16.00,33.00,22.00,28.00,24.00,39.00,22.00,NaN,13.00,0.00,44.00,18.00,14.00,47.00,21.00,0.00,27.00,17.00,0.00,53.00,36.00,100.00,10.00,36.00,43.00,48.00,0.00,17.00,0.00,0.00,0.00,0.00,0.00,6.00,0.00,0.00,0.00,29.00,37.00,71.00,62.00,21.00,11.00,12.00,40.00,0.00,NaN,NaN,NaN,NaN,6.00,23.00,32.00,0.00,0.00,14.00,12.00,NaN,2.00,0.00,23.00,10.00,14.00,49.00,28.00,0.00,11.00,20.00,0.00,20.00,92.00,100.00,0.00,27.00,89.00,0.00,0.00,27.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,25.00,30.00,40.00,80.00,8.00,4.00,6.00,48.00,0.00,NaN,NaN,NaN,NaN,5.00,23.00,75.00,32.00,0.00,0.00,14.00,12.00,NaN,2.00,0.00,23.00,10.00,14.00,49.00,28.00,0.00,10.00,20.00,0.00,20.00,60.00,100.00,0.00,27.00,89.00,0.00,0.00,27.00,0.00,0.00,0.00,0.00,0.00,83.00,0.00,0.00,0.00,25.00,30.00,40.00,80.00,8.00,4.00,4.00,48.00,0.00,NaN,NaN,NaN,NaN,12.00,2.00,16.00,16.00,0.00,0.00,26.00,25.00,NaN,6.00,0.00,36.00,22.00,20.00,45.00,20.00,0.00,29.00,15.00,0.00,50.00,31.00,100.00,0.00,43.00,31.00,0.00,0.00,2.00,0.00,0.00,0.00,0.00,0.00,5.00,0.00,0.00,0.00,26.00,20.00,42.00,63.00,17.00,10.00,13.00,27.00,0.00,NaN,NaN,NaN,NaN

In [5]:
away_player = pd.read_csv("train_away_player_statistics_df.csv")
away_player.head()

,ID,LEAGUE,TEAM_NAME,POSITION,PLAYER_NAME,PLAYER_ACCURATE_CROSSES_season_sum,PLAYER_ACCURATE_PASSES_season_sum,PLAYER_AERIALS_WON_season_sum,PLAYER_ASSISTS_season_sum,PLAYER_BIG_CHANCES_CREATED_season_sum,PLAYER_BIG_CHANCES_MISSED_season_sum,PLAYER_BLOCKED_SHOTS_season_sum,PLAYER_CAPTAIN_season_sum,PLAYER_CLEARANCES_season_sum,PLAYER_CLEARANCE_OFFLINE_season_sum,PLAYER_DISPOSSESSED_season_sum,PLAYER_DRIBBLED_ATTEMPTS_season_sum,PLAYER_DRIBBLED_PAST_season_sum,PLAYER_DUELS_LOST_season_sum,PLAYER_DUELS_WON_season_sum,PLAYER_ERROR_LEAD_TO_GOAL_season_sum,PLAYER_FOULS_season_sum,PLAYER_FOULS_DRAWN_season_sum,PLAYER_GOALKEEPER_GOALS_CONCEDED_season_sum,PLAYER_GOALS_season_sum,PLAYER_GOALS_CONCEDED_season_sum,PLAYER_HIT_WOODWORK_season_sum,PLAYER_INTERCEPTIONS_season_sum,PLAYER_KEY_PASSES_season_sum,PLAYER_MINUTES_PLAYED_season_sum,PLAYER_OFFSIDES_season_sum,PLAYER_OWN_GOALS_season_sum,PLAYER_PASSES_season_sum,PLAYER_PENALTIES_COMMITTED_season_sum,PLAYER_PENALTIES_MISSES_season_sum,PLAYER_PENALTIES_SAVED_season_sum,PLAYER_PENALTIES_SCORED_season_sum,PLAYER_PENALTIES_WON_season_sum,PLAYER_REDCARDS_season_sum,PLAYER_SAVES_season_sum,PLAYER_SAVES_INSIDE_BOX_season_sum,PLAYER_SHOTS_BLOCKED_season_sum,PLAYER_SHOTS_ON_TARGET_season_sum,PLAYER_SHOTS_TOTAL_season_sum,PLAYER_STARTING_LINEUP_season_sum,PLAYER_SUCCESSFUL_DRIBBLES_season_sum,PLAYER_TACKLES_season_sum,PLAYER_TOTAL_CROSSES_season_sum,PLAYER_TOTAL_DUELS_season_sum,PLAYER_YELLOWCARDS_season_sum,PLAYER_PUNCHES_season_sum,PLAYER_LONG_BALLS_season_sum,PLAYER_LONG_BALLS_WON_season_sum,PLAYER_SHOTS_OFF_TARGET_season_sum,PLAYER_ACCURATE_CROSSES_season_average,PLAYER_ACCURATE_PASSES_season_average,PLAYER_ACCURATE_PASSES_PERCENTAGE_season_average,PLAYER_AERIALS_WON_season_average,PLAYER_ASSISTS_season_average,PLAYER_BIG_CHANCES_CREATED_season_average,PLAYER_BIG_CHANCES_MISSED_season_average,PLAYER_BLOCKED_SHOTS_season_average,PLAYER_CAPTAIN_season_average,PLAYER_CLEARANCES_season_average,PLAYER_CLEARANCE_OFFLINE_season_average,PLAYER_DISPOSSESSED_season_average,PLAYER_DRIBBLED_ATTEMPTS_season_average,PLAYER_DRIBBLED_PAST_season_average,PLAYER_DUELS_LOST_season_average,PLAYER_DUELS_WON_season_average,PLAYER_ERROR_LEAD_TO_GOAL_season_average,PLAYER_FOULS_season_average,PLAYER_FOULS_DRAWN_season_average,PLAYER_GOALKEEPER_GOALS_CONCEDED_season_average,PLAYER_GOALS_season_average,PLAYER_GOALS_CONCEDED_season_average,PLAYER_HIT_WOODWORK_season_average,PLAYER_INTERCEPTIONS_season_average,PLAYER_KEY_PASSES_season_average,PLAYER_MINUTES_PLAYED_season_average,PLAYER_OFFSIDES_season_average,PLAYER_OWN_GOALS_season_average,PLAYER_PASSES_season_average,PLAYER_PENALTIES_COMMITTED_season_average,PLAYER_PENALTIES_MISSES_season_average,PLAYER_PENALTIES_SAVED_season_average,PLAYER_PENALTIES_SCORED_season_average,PLAYER_PENALTIES_WON_season_average,PLAYER_RATING_season_average,PLAYER_REDCARDS_season_average,PLAYER_SAVES_season_average,PLAYER_SAVES_INSIDE_BOX_season_average,PLAYER_SHOTS_BLOCKED_season_average,PLAYER_SHOTS_ON_TARGET_season_average,PLAYER_SHOTS_TOTAL_season_average,PLAYER_STARTING_LINEUP_season_average,PLAYER_SUCCESSFUL_DRIBBLES_season_average,PLAYER_TACKLES_season_average,PLAYER_TOTAL_CROSSES_season_average,PLAYER_TOTAL_DUELS_season_average,PLAYER_YELLOWCARDS_season_average,PLAYER_PUNCHES_season_average,PLAYER_LONG_BALLS_season_average,PLAYER_LONG_BALLS_WON_season_average,PLAYER_SHOTS_OFF_TARGET_season_average,PLAYER_ACCURATE_CROSSES_season_std,PLAYER_ACCURATE_PASSES_season_std,PLAYER_ACCURATE_PASSES_PERCENTAGE_season_std,PLAYER_AERIALS_WON_season_std,PLAYER_ASSISTS_season_std,PLAYER_BIG_CHANCES_CREATED_season_std,PLAYER_BIG_CHANCES_MISSED_season_std,PLAYER_BLOCKED_SHOTS_season_std,PLAYER_CAPTAIN_season_std,PLAYER_CLEARANCES_season_std,PLAYER_CLEARANCE_OFFLINE_season_std,PLAYER_DISPOSSESSED_season_std,PLAYER_DRIBBLED_ATTEMPTS_season_std,PLAYER_DRIBBLED_PAST_season_std,PLAYER_DUELS_LOST_season_std,PLAYER_DUELS_WON_season_std,PLAYER_ERROR_LEAD_TO_GOAL_season_std,PLAYER_FOULS_season_std,PLAYER_FOULS_DRAWN_season_std,PLAYER_GOALKEEPER_GOALS_CONCEDED_season_std,PLAYER_GOALS_season_std,PLAYER_GOALS_CONCEDED_season_std,PLAYER_HIT_WOODWORK_season_std,PLAYER_INTERCEPTIONS_season_std,PLAYER_KEY_PASSES_season_std,PLAYER_MINUTES_PLAYED_season_std,PLAYER_OFFSIDES_season_std,PLAYER_OWN_GOALS_season_std,PLAYER_PASSES_season_std,PLAYER_PENALTIES_COMMITTED_season_std,PLAYER_PENALTIES_MISSES_season_std,PLAYER_PENALTIES_SAVED_season_std,PLAYER_PENALTIES_SCORED_season_std,PLAYER_PENALTIES_WON_season_std,PLAYER_RATING_season_std,PLAYER_REDCARDS_season_std,PLAYER_SAVES_season_std,PLAYER_SAVES_INSIDE_BOX_season_std,PLAYER_SHOTS_BLOCKED_season_std,PLAYER_SHOTS_ON_TARGET_season_std,PLAYER_SHOTS_TOTAL_season_std,PLAYER_STARTING_LINEUP_season_std,PLAYER_SUCCESSFUL_DRIBBLES_season_std,PLAYER_TACKLES_season_std,PLAYER_TOTAL_CROSSES_season_std,PLAYER_TOTAL_DUELS_season_std,PLAYER_YELLOWCARDS_season_std,PLAYER_PUNCHES_season_std,PLAYER_LONG_BALLS_season_std,PLAYER_LONG_BALLS_WON_season_std,PLAYER_SHOTS_OFF_TARGET_season_std,PLAYER_ACCURATE_CROSSES_5_last_match_sum,PLAYER_ACCURATE_PASSES_5_last_match_sum,PLAYER_AERIALS_WON_5_last_match_sum,PLAYER_ASSISTS_5_last_match_sum,PLAYER_BIG_CHANCES_CREATED_5_last_match_sum,PLAYER_BIG_CHANCES_MISSED_5_last_match_sum,PLAYER_BLOCKED_SHOTS_5_last_match_sum,PLAYER_CAPTAIN_5_last_match_sum,PLAYER_CLEARANCES_5_last_match_sum,PLAYER_CLEARANCE_OFFLINE_5_last_match_sum,PLAYER_DISPOSSESSED_5_last_match_sum,PLAYER_DRIBBLED_ATTEMPTS_5_last_match_sum,PLAYER_DRIBBLED_PAST_5_last_match_sum,PLAYER_DUELS_LOST_5_last_match_sum,PLAYER_DUELS_WON_5_last_match_sum,PLAYER_ERROR_LEAD_TO_GOAL_5_last_match_sum,PLAYER_FOULS_5_last_match_sum,PLAYER_FOULS_DRAWN_5_last_match_sum,PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_sum,PLAYER_GOALS_5_last_match_sum,PLAYER_GOALS_CONCEDED_5_last_match_sum,PLAYER_HIT_WOODWORK_5_last_match_sum,PLAYER_INTERCEPTIONS_5_last_match_sum,PLAYER_KEY_PASSES_5_last_match_sum,PLAYER_MINUTES_PLAYED_5_last_match_sum,PLAYER_OFFSIDES_5_last_match_sum,PLAYER_OWN_GOALS_5_last_match_sum,PLAYER_PASSES_5_last_match_sum,PLAYER_PENALTIES_COMMITTED_5_last_match_sum,PLAYER_PENALTIES_MISSES_5_last_match_sum,PLAYER_PENALTIES_SAVED_5_last_match_sum,PLAYER_PENALTIES_SCORED_5_last_match_sum,PLAYER_PENALTIES_WON_5_last_match_sum,PLAYER_REDCARDS_5_last_match_sum,PLAYER_SAVES_5_last_match_sum,PLAYER_SAVES_INSIDE_BOX_5_last_match_sum,PLAYER_SHOTS_BLOCKED_5_last_match_sum,PLAYER_SHOTS_ON_TARGET_5_last_match_sum,PLAYER_SHOTS_TOTAL_5_last_match_sum,PLAYER_STARTING_LINEUP_5_last_match_sum,PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_sum,PLAYER_TACKLES_5_last_match_sum,PLAYER_TOTAL_CROSSES_5_last_match_sum,PLAYER_TOTAL_DUELS_5_last_match_sum,PLAYER_YELLOWCARDS_5_last_match_sum,PLAYER_PUNCHES_5_last_match_sum,PLAYER_LONG_BALLS_5_last_match_sum,PLAYER_LONG_BALLS_WON_5_last_match_sum,PLAYER_SHOTS_OFF_TARGET_5_last_match_sum,PLAYER_ACCURATE_CROSSES_5_last_match_average,PLAYER_ACCURATE_PASSES_5_last_match_average,PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_average,PLAYER_AERIALS_WON_5_last_match_average,PLAYER_ASSISTS_5_last_match_average,PLAYER_BIG_CHANCES_CREATED_5_last_match_average,PLAYER_BIG_CHANCES_MISSED_5_last_match_average,PLAYER_BLOCKED_SHOTS_5_last_match_average,PLAYER_CAPTAIN_5_last_match_average,PLAYER_CLEARANCES_5_last_match_average,PLAYER_CLEARANCE_OFFLINE_5_last_match_average,PLAYER_DISPOSSESSED_5_last_match_average,PLAYER_DRIBBLED_ATTEMPTS_5_last_match_average,PLAYER_DRIBBLED_PAST_5_last_match_average,PLAYER_DUELS_LOST_5_last_match_average,PLAYER_DUELS_WON_5_last_match_average,PLAYER_ERROR_LEAD_TO_GOAL_5_last_match_average,PLAYER_FOULS_5_last_match_average,PLAYER_FOULS_DRAWN_5_last_match_average,PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_average,PLAYER_GOALS_5_last_match_average,PLAYER_GOALS_CONCEDED_5_last_match_average,PLAYER_HIT_WOODWORK_5_last_match_average,PLAYER_INTERCEPTIONS_5_last_match_average,PLAYER_KEY_PASSES_5_last_match_average,PLAYER_MINUTES_PLAYED_5_last_match_average,PLAYER_OFFSIDES_5_last_match_average,PLAYER_OWN_GOALS_5_last_match_average,PLAYER_PASSES_5_last_match_average,PLAYER_PENALTIES_COMMITTED_5_last_match_average,PLAYER_PENALTIES_MISSES_5_last_match_average,PLAYER_PENALTIES_SAVED_5_last_match_average,PLAYER_PENALTIES_SCORED_5_last_match_average,PLAYER_PENALTIES_WON_5_last_match_average,PLAYER_RATING_5_last_match_average,PLAYER_REDCARDS_5_last_match_average,PLAYER_SAVES_5_last_match_average,PLAYER_SAVES_INSIDE_BOX_5_last_match_average,PLAYER_SHOTS_BLOCKED_5_last_match_average,PLAYER_SHOTS_ON_TARGET_5_last_match_average,PLAYER_SHOTS_TOTAL_5_last_match_average,PLAYER_STARTING_LINEUP_5_last_match_average,PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_average,PLAYER_TACKLES_5_last_match_average,PLAYER_TOTAL_CROSSES_5_last_match_average,PLAYER_TOTAL_DUELS_5_last_match_average,PLAYER_YELLOWCARDS_5_last_match_average,PLAYER_PUNCHES_5_last_match_average,PLAYER_LONG_BALLS_5_last_match_average,PLAYER_LONG_BALLS_WON_5_last_match_average,PLAYER_SHOTS_OFF_TARGET_5_last_match_average,PLAYER_ACCURATE_CROSSES_5_last_match_std,PLAYER_ACCURATE_PASSES_5_last_match_std,PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_std,PLAYER_AERIALS_WON_5_last_match_std,PLAYER_ASSISTS_5_last_match_std,PLAYER_BIG_CHANCES_CREATED_5_last_match_std,PLAYER_BIG_CHANCES_MISSED_5_last_match_std,PLAYER_BLOCKED_SHOTS_5_last_match_std,PLAYER_CAPTAIN_5_last_match_std,PLAYER_CLEARANCES_5_last_match_std,PLAYER_CLEARANCE_OFFLINE_5_last_match_std,PLAYER_DISPOSSESSED_5_last_match_std,PLAYER_DRIBBLED_ATTEMPTS_5_last_match_std,PLAYER_DRIBBLED_PAST_5_last_match_std,PLAYER_DUELS_LOST_5_last_match_std,PLAYER_DUELS_WON_5_last_match_std,PLAYER_ERROR_LEAD_TO_GOAL_5_last_match_std,PLAYER_FOULS_5_last_match_std,PLAYER_FOULS_DRAWN_5_last_match_std,PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_std,PLAYER_GOALS_5_last_match_std,PLAYER_GOALS_CONCEDED_5_last_match_std,PLAYER_HIT_WOODWORK_5_last_match_std,PLAYER_INTERCEPTIONS_5_last_match_std,PLAYER_KEY_PASSES_5_last_match_std,PLAYER_MINUTES_PLAYED_5_last_match_std,PLAYER_OFFSIDES_5_last_match_std,PLAYER_OWN_GOALS_5_last_match_std,PLAYER_PASSES_5_last_match_std,PLAYER_PENALTIES_COMMITTED_5_last_match_std,PLAYER_PENALTIES_MISSES_5_last_match_std,PLAYER_PENALTIES_SAVED_5_last_match_std,PLAYER_PENALTIES_SCORED_5_last_match_std,PLAYER_PENALTIES_WON_5_last_match_std,PLAYER_RATING_5_last_match_std,PLAYER_REDCARDS_5_last_match_std,PLAYER_SAVES_5_last_match_std,PLAYER_SAVES_INSIDE_BOX_5_last_match_std,PLAYER_SHOTS_BLOCKED_5_last_match_std,PLAYER_SHOTS_ON_TARGET_5_last_match_std,PLAYER_SHOTS_TOTAL_5_last_match_std,PLAYER_STARTING_LINEUP_5_last_match_std,PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_std,PLAYER_TACKLES_5_last_match_std,PLAYER_TOTAL_CROSSES_5_last_match_std,PLAYER_TOTAL_DUELS_5_last_match_std,PLAYER_YELLOWCARDS_5_last_match_std,PLAYER_PUNCHES_5_last_match_std,PLAYER_LONG_BALLS_5_last_match_std,PLAYER_LONG_BALLS_WON_5_last_match_std,PLAYER_SHOTS_OFF_TARGET_5_last_match_std
0,0,Ligue 1,Olympique Marseille,defender,Lucas Perrin,0.00,19.00,20.00,0.00,0.00,12.00,6.00,NaN,18.00,0.00,0.00,5.00,23.00,20.00,23.00,0.00,28.00,13.00,0.00,0.00,16.00,0.00,34.00,0.00,23.00,0.00,0.00,20.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,6.00,0.00,4.00,23.00,12.00,9.00,0.00,23.00,40.00,NaN,NaN,NaN,NaN,0.00,53.00,85.00,57.00,0.00,0.00,25.00,17.00,NaN,44.00,0.00,0.00,9.00,55.00,61.00,59.00,0.00,56.00,30.00,0.00,0.00,25.00,0.00,62.00,0.00,75.00,0.00,0.00,56.00,0.00,0.00,0.00,0.00,0.00,65.00,0.00,0.00,0.00,20.00,0.00,9.00,75.00,16.00,31.00,0.00,70.00,50.00,NaN,NaN,NaN,NaN,0.00,67.00,12.00,71.00,0.00,0.00,32.00,30.00,NaN,59.00,0.00,0.00,19.00,50.00,62.00,63.00,0.00,55.00,33.00,0.00,0.00,49.00,0.00,67.00,0.00,70.00,0.00,0.00,71.00,0.00,0.00,0.00,0.00,0.00,64.00,0.00,0.00,0.00,30.00,0.00,41.00,70.00,33.00,51.00,0.00,79.00,99.00,NaN,NaN,NaN,NaN,0.00,39.00,40.00,0.00,0.00,14.00,12.00,NaN,35.00,0.00,0.00,7.00,35.00,42.00,42.00,0.00,52.00,25.00,0.00,0.00,30.00,0.00,66.00,0.00,60.00,0.00,0.00,41.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,12.00,0.00,7.00,60.00,13.00,20.00,0.00,52.00,50.00,NaN,NaN,NaN,NaN,0.00,49.00,85.00,50.00,0.00,0.00,17.00,15.00,NaN,44.00,0.00,0.00,9.00,44.00,53.00,53.00,0.00,56.00,31.00,0.00,0.00,25.00,0.00,62.00,0.00,75.00,0.00,0.00,52.00,0.00,0.00,0.00,0.00,0.00,61.00,0.00,0.00,0.00,15.00,0.00,9.00,75.00,16.00,26.00,0.00,66.00,50.00,NaN,NaN,NaN,NaN,0.00,60.00,9.00,60.00,0.00,0.00,29.00,27.00,NaN,42.00,0.00,0.00,19.00,46.00,83.00,63.00,0.00,55.00,33.00,0.00,0.00,49.00,0.00,67.00,0.00,70.00,0.00,0.00,60.00,0.00,0.00,0.00,0.00,0.00,64.00,0.00,0.00,0.00,24.00,0.00,32.00,70.00,30.00,46.00,0.00,79.00,99.00,NaN,NaN,NaN,NaN
1,0,Ligue 1,Olympique Marseille,midfielder,Kevin Strootman,2.00,48.00,19.00,28.00,8.00,12.00,6.00,NaN,21.00,0.00,4.00,3.00,47.00,39.00,37.00,0.00,56.00,18.00,0.00,11.00,52.00,25.00,24.00,24.00,72.00,6.00,0.00,51.00,0.00,0.00,0.00,33.00,0.00,0.00,0.00,0.00,20.00,5.00,16.00,69.00,4.00,40.00,3.00,41.00,80.00,NaN,NaN,NaN,NaN,2.00,44.00,79.00,17.00,16.00,8.00,8.00,5.00,NaN,17.00,0.00,4.00,2.00,37.00,39.00,31.00,0.00,37.00,14.00,0.00,10.00,27.00,20.00,14.00,21.00,78.00,7.00,0.00,47.00,0.00,0.00,0.00,33.00,0.00,79.00,0.00,0.00,0.00,20.00,3.00,10.00,75.00,1.00,43.00,2.00,41.00,33.00,NaN,NaN,NaN,NaN,12.00,48.00,41.00,37.00,40.00,25.00,18.00,17.00,NaN,36.00,0.00,24.00,8.00,44.00,32.00,41.00,0.00,40.00,34.00,0.00,31.00,45.00,45.00,25.00,34.00,53.00,23.00,0.00,50.00,0.00,0.00,0.00,63.00,0.00,37.00,0.00,0.00,0.00,27.00,14.00,33.00,63.00,10.00,43.00,12.00,41.00,85.00,NaN,NaN,NaN,NaN,0.00,32.00,0.00,16.00,0.00,0.00,0.00,NaN,20.00,0.00,9.00,2.00,35.00,34.00,14.00,0.00,47.00,10.00,0.00,20.00,46.00,0.00,6.00,13.00,65.00,12.00,0.00,35.00,0.00,0.00,0.00,100.00,0.00,0.00,0.00,0.00,12.00,7.00,7.00,60.00,0.00,29.00,2.00,30.00,25.00,NaN,NaN,NaN,NaN,0.00,32.00,75.00,0.00,16.00,0.00,0.00,0.00,NaN,20.00,0.00,9.00,2.00,35.00,34.00,14.00,0.00,40.00,10.00,0.00,20.00,30.00,0.00,5.00,13.00,65.00,12.00,0.00,35.00,0.00,0.00,0.00,100.00,0.00,65.00,0.00,0.00,0.00,12.00,7.00,7.00,60.00,0.00,29.00,1.00,30.00,20.00,NaN,NaN,NaN,NaN,0.00,46.00,41.00,0.00,40.00,0.00,0.00,0.00,NaN,37.00,0.00,32.00,9.00,52.00,58.00,29.00,0.00,43.00,18.00,0.00,50.00,57.00,0.00,12.00,18.00,67.00,34.00,0.00,47.00,0.00,0.00,0.00,99.00,0.00,57.00,0.00,0.00,0.00,21.00,20.00,17.00,77.00,0.00,40.00,6.00,46.00,77.00,NaN,NaN,NaN,NaN
2,0,Ligue 1,Olympique Marseille,goalkeeper,Yohann Pelé,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,68.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,0.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,32.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,0.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,45.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,69.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,0.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,45.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,0.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,57.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN
3,0,Ligue 1,Olympique Marseille,defender,Abdallah Ali Mohamed,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,4.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,0.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,25.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,7.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,0.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,25.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,Ligue 1,Olympique Marseille,NaN,Nemanja Radonjic,8.00,11.00,4.00,0.00,0.00,12.00,0.00,NaN,6.00,0.00,19.00,27.00,9.00,25.00,24.00,0.00,31.00,18.00,0.00,0.00,60.00,25.00,6.00,10.00,28.00,6.00,0.00,14.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,13.00,17.00,16.00,23.00,44.00,9.00,6.00,27.00,20.00,NaN,NaN,NaN,NaN,6.00,9.00,68.00,3.00,0.00,0.00,7.00,0.00,NaN,4.00,0.00,17.00,15.00,6.00,23.00,19.00,0.00,19.00,12.00,0.00,0.00,28.00,19.00,3.00,8.00,28.00,6.00,0.00,12.00,0.00,0.00,0.00,0.00,0.00,51.00,0.00,0.00,0.00,12.00,8.00,9.00,23.00,18.00,9.00,4.00,24.00,7.00,NaN,NaN,NaN,NaN,18.00,22.00,47.00,9.00,0.00,0.00,18.00,0.00,NaN,12.00,0.00,51.00,54.00,22.00,38.00,38.00,0.00,33.00,26.00,0.00,0.00,46.00,43.00,15.00,22.00,47.00,22.00,0.00,26.00,0.00,0.00,0.00,0.00,0.00,62.00,0.00,0.00,0.00,34.00,22.00,40.00,62.00,54.00,17.00,15.00,47.00,48.00,NaN,NaN,NaN,NaN,12.00,10.00,2.00,0.00,0.00,14.00,0.00,NaN,0.00,0.00,23.00,27.00,0.00,23.00,23.00,0.00,23.00,20.00,0.00,0.00,69.00,33.00,0.00,13.00,38.00,12.00,0.00,13.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,15.00,14.00,40.00,30.00,12.00,6.00,29.00,0.00,NaN,NaN,NaN,NaN,11.00,10.00,70.00,2.00,0.00,0.00,14.00,0.00,NaN,0.00,0.00,23.00,27.00,0.00,23.00,23.00,0.00,20.00,20.00,0.00,0.00,45.00,33.00,0.00,13.00,38.00,12.00,0.00,13.00,0.00,0.00,0.00,0.00,0.00,48.00,0.00,0.00,0.00,0.00,15.00,14.00,40.00,30.00,12.00,4.00,29.00,0.00,NaN,NaN,NaN,NaN,15.00,23.00,42.00,8.00,0.00,0.00,26.00,0.00,NaN,0.00,0.00,51.00,79.00,0.00,61.00,57.00,0.00,42.00,37.00,0.00,0.00,57.00,50.00,0.00,30.00,64.00,34.00,0.00,27.00,0.00,0.00,0.00,0.00,0.00,68.00,0.00,0.00,0.00,0.00,25.00,42.00,77.00,69.00,21.00,13.00,66.00,0.00,NaN,NaN,NaN,NaN

In [6]:
y_train = pd.read_csv("Y_train_1rknArQ.csv")
y_train.head()

   ID  HOME_WINS  DRAW  AWAY_WINS
0   0          0     0          1
1   1          0     1          0
2   2          0     0          1
3   3          1     0          0
4   4          0     1          0

In [7]:
y_train_supp = pd.read_csv("Y_train_supp.csv")
y_train_supp.head()

   ID  GOAL_DIFF_HOME_AWAY
0   0                -2.00
1   1                 0.00
2   2                -1.00
3   3                 1.00
4   4                 0.00

In [8]:
home_team["LEAGUE"].nunique()

13

In [9]:
home_team["TEAM_NAME"].nunique()

350

In [10]:
# Understanding the Data
def dataset_summary(df, name):
    print("=" * 80)
    print(f"{name}")
    print("=" * 80)

    print(f"Rows    : {df.shape[0]:,}")
    print(f"Columns : {df.shape[1]:,}")

    print("\nFirst 5 rows")
    display(df.head())

    print("\nData Types")
    display(df.dtypes.value_counts())

    print("\nMemory Usage")

    memory = df.memory_usage(deep=True).sum() / (1024**2)

    print(f"{memory:.2f} MB")

In [11]:
dataset_summary(home_team,"HOME TEAM")

dataset_summary(away_team,"AWAY TEAM")

dataset_summary(home_player,"HOME PLAYER")

dataset_summary(away_player,"AWAY PLAYER")

dataset_summary(y_train,"Y TRAIN")

dataset_summary(y_train_supp,"Y TRAIN SUPPLEMENT")

================================================================================
HOME TEAM
================================================================================
Rows    : 12,303
Columns : 143

First 5 rows

,ID,LEAGUE,TEAM_NAME,TEAM_SHOTS_TOTAL_season_sum,TEAM_SHOTS_INSIDEBOX_season_sum,TEAM_SHOTS_OFF_TARGET_season_sum,TEAM_SHOTS_ON_TARGET_season_sum,TEAM_SHOTS_OUTSIDEBOX_season_sum,TEAM_PASSES_season_sum,TEAM_SUCCESSFUL_PASSES_season_sum,TEAM_SAVES_season_sum,TEAM_CORNERS_season_sum,TEAM_FOULS_season_sum,TEAM_YELLOWCARDS_season_sum,TEAM_REDCARDS_season_sum,TEAM_OFFSIDES_season_sum,TEAM_ATTACKS_season_sum,TEAM_PENALTIES_season_sum,TEAM_SUBSTITUTIONS_season_sum,TEAM_BALL_SAFE_season_sum,TEAM_DANGEROUS_ATTACKS_season_sum,TEAM_INJURIES_season_sum,TEAM_GOALS_season_sum,TEAM_GAME_WON_season_sum,TEAM_GAME_DRAW_season_sum,TEAM_GAME_LOST_season_sum,TEAM_SHOTS_TOTAL_season_average,TEAM_SHOTS_INSIDEBOX_season_average,TEAM_SHOTS_OFF_TARGET_season_average,TEAM_SHOTS_ON_TARGET_season_average,TEAM_SHOTS_OUTSIDEBOX_season_average,TEAM_PASSES_season_average,TEAM_SUCCESSFUL_PASSES_season_average,TEAM_SUCCESSFUL_PASSES_PERCENTAGE_season_average,TEAM_SAVES_season_average,TEAM_CORNERS_season_average,TEAM_BALL_POSSESSION_season_average,TEAM_FOULS_season_average,TEAM_YELLOWCARDS_season_average,TEAM_REDCARDS_season_average,TEAM_OFFSIDES_season_average,TEAM_ATTACKS_season_average,TEAM_PENALTIES_season_average,TEAM_SUBSTITUTIONS_season_average,TEAM_BALL_SAFE_season_average,TEAM_DANGEROUS_ATTACKS_season_average,TEAM_INJURIES_season_average,TEAM_GOALS_season_average,TEAM_GAME_WON_season_average,TEAM_GAME_DRAW_season_average,TEAM_GAME_LOST_season_average,TEAM_SHOTS_TOTAL_season_std,TEAM_SHOTS_INSIDEBOX_season_std,TEAM_SHOTS_OFF_TARGET_season_std,TEAM_SHOTS_ON_TARGET_season_std,TEAM_SHOTS_OUTSIDEBOX_season_std,TEAM_PASSES_season_std,TEAM_SUCCESSFUL_PASSES_season_std,TEAM_SUCCESSFUL_PASSES_PERCENTAGE_season_std,TEAM_SAVES_season_std,TEAM_CORNERS_season_std,TEAM_BALL_POSSESSION_season_std,TEAM_FOULS_season_std,TEAM_YELLOWCARDS_season_std,TEAM_REDCARDS_season_std,TEAM_OFFSIDES_season_std,TEAM_ATTACKS_season_std,TEAM_PENALTIES_season_std,TEAM_SUBSTITUTIONS_season_std,TEAM_BALL_SAFE_season_std,TEAM_DANGEROUS_ATTACKS_season_std,TEAM_INJURIES_season_std,TEAM_GOALS_season_std,TEAM_SHOTS_TOTAL_5_last_match_sum,TEAM_SHOTS_INSIDEBOX_5_last_match_sum,TEAM_SHOTS_OFF_TARGET_5_last_match_sum,TEAM_SHOTS_ON_TARGET_5_last_match_sum,TEAM_SHOTS_OUTSIDEBOX_5_last_match_sum,TEAM_PASSES_5_last_match_sum,TEAM_SUCCESSFUL_PASSES_5_last_match_sum,TEAM_SAVES_5_last_match_sum,TEAM_CORNERS_5_last_match_sum,TEAM_FOULS_5_last_match_sum,TEAM_YELLOWCARDS_5_last_match_sum,TEAM_REDCARDS_5_last_match_sum,TEAM_OFFSIDES_5_last_match_sum,TEAM_ATTACKS_5_last_match_sum,TEAM_PENALTIES_5_last_match_sum,TEAM_SUBSTITUTIONS_5_last_match_sum,TEAM_BALL_SAFE_5_last_match_sum,TEAM_DANGEROUS_ATTACKS_5_last_match_sum,TEAM_INJURIES_5_last_match_sum,TEAM_GOALS_5_last_match_sum,TEAM_GAME_WON_5_last_match_sum,TEAM_GAME_DRAW_5_last_match_sum,TEAM_GAME_LOST_5_last_match_sum,TEAM_SHOTS_TOTAL_5_last_match_average,TEAM_SHOTS_INSIDEBOX_5_last_match_average,TEAM_SHOTS_OFF_TARGET_5_last_match_average,TEAM_SHOTS_ON_TARGET_5_last_match_average,TEAM_SHOTS_OUTSIDEBOX_5_last_match_average,TEAM_PASSES_5_last_match_average,TEAM_SUCCESSFUL_PASSES_5_last_match_average,TEAM_SUCCESSFUL_PASSES_PERCENTAGE_5_last_match_average,TEAM_SAVES_5_last_match_average,TEAM_CORNERS_5_last_match_average,TEAM_BALL_POSSESSION_5_last_match_average,TEAM_FOULS_5_last_match_average,TEAM_YELLOWCARDS_5_last_match_average,TEAM_REDCARDS_5_last_match_average,TEAM_OFFSIDES_5_last_match_average,TEAM_ATTACKS_5_last_match_average,TEAM_PENALTIES_5_last_match_average,TEAM_SUBSTITUTIONS_5_last_match_average,TEAM_BALL_SAFE_5_last_match_average,TEAM_DANGEROUS_ATTACKS_5_last_match_average,TEAM_INJURIES_5_last_match_average,TEAM_GOALS_5_last_match_average,TEAM_GAME_WON_5_last_match_average,TEAM_GAME_DRAW_5_last_match_average,TEAM_GAME_LOST_5_last_match_average,TEAM_SHOTS_TOTAL_5_last_match_std,TEAM_SHOTS_INSIDEBOX_5_last_match_std,TEAM_SHOTS_OFF_TARGET_5_last_match_std,TEAM_SHOTS_ON_TARGET_5_last_match_std,TEAM_SHOTS_OUTSIDEBOX_5_last_match_std,TEAM_PASSES_5_last_match_std,TEAM_SUCCESSFUL_PASSES_5_last_match_std,TEAM_SUCCESSFUL_PASSES_PERCENTAGE_5_last_match_std,TEAM_SAVES_5_last_match_std,TEAM_CORNERS_5_last_match_std,TEAM_BALL_POSSESSION_5_last_match_std,TEAM_FOULS_5_last_match_std,TEAM_YELLOWCARDS_5_last_match_std,TEAM_REDCARDS_5_last_match_std,TEAM_OFFSIDES_5_last_match_std,TEAM_ATTACKS_5_last_match_std,TEAM_PENALTIES_5_last_match_std,TEAM_SUBSTITUTIONS_5_last_match_std,TEAM_BALL_SAFE_5_last_match_std,TEAM_DANGEROUS_ATTACKS_5_last_match_std,TEAM_INJURIES_5_last_match_std,TEAM_GOALS_5_last_match_std
0,0,Ligue 1,Toulouse,3.00,2.00,5.00,2.00,1.00,2.00,2.00,5.00,3.00,6.00,2.00,2.00,1.00,2.00,6.00,8.00,4.00,4.00,0.00,3.00,1.00,6.00,10.00,3.00,2.00,4.00,2.00,1.00,2.00,1.00,2.00,5.00,3.00,1.00,6.00,2.00,2.00,1.00,1.00,6.00,8.00,2.00,4.00,0.00,3.00,1.00,5.00,10.00,5.00,4.00,3.00,5.00,3.00,10.00,9.00,7.00,8.00,1.00,10.00,3.00,7.00,4.00,4.00,2.00,10.00,4.00,4.00,4.00,0.00,1.00,4.00,3.00,6.00,3.00,6.00,0.00,0.00,0.00,2.00,8.00,8.00,0.00,2.00,2.00,10.00,5.00,5.00,6.00,1.00,4.00,2.00,0.00,10.00,4.00,3.00,6.00,3.00,6.00,0.00,0.00,1.00,0.00,2.00,0.00,8.00,8.00,0.00,2.00,2.00,10.00,4.00,5.00,6.00,2.00,4.00,2.00,0.00,10.00,4.00,4.00,7.00,1.00,5.00,4.00,2.00,2.00,4.00,0.00,6.00,6.00,3.00,0.00,6.00,0.00,10.00,8.00,7.00,2.00,4.00,3.00
1,1,Ligue 2,Brest,6.00,8.00,3.00,6.00,5.00,8.00,7.00,10.00,6.00,8.00,3.00,0.00,7.00,7.00,6.00,10.00,9.00,6.00,2.00,10.00,8.00,4.00,1.00,5.00,7.00,2.00,5.00,2.00,5.00,5.00,6.00,9.00,5.00,6.00,5.00,3.00,0.00,5.00,4.00,6.00,7.00,5.00,4.00,2.00,9.00,7.00,3.00,1.00,4.00,3.00,1.00,5.00,6.00,1.00,1.00,0.00,10.00,6.00,3.00,4.00,4.00,0.00,3.00,6.00,8.00,4.00,2.00,4.00,3.00,10.00,5.00,6.00,1.00,7.00,3.00,4.00,4.00,5.00,1.00,2.00,4.00,0.00,7.00,8.00,10.00,10.00,5.00,3.00,3.00,10.00,8.00,3.00,0.00,5.00,6.00,1.00,7.00,3.00,4.00,4.00,5.00,5.00,1.00,5.00,1.00,4.00,0.00,7.00,8.00,10.00,10.00,5.00,3.00,3.00,10.00,8.00,3.00,0.00,5.00,2.00,1.00,3.00,7.00,5.00,5.00,3.00,7.00,2.00,6.00,3.00,4.00,0.00,4.00,3.00,10.00,0.00,1.00,2.00,8.00,4.00
2,2,Serie A,Sampdoria,4.00,2.00,5.00,2.00,8.00,1.00,1.00,2.00,2.00,7.00,7.00,6.00,3.00,4.00,5.00,10.00,5.00,3.00,8.00,1.00,1.00,2.00,8.00,4.00,2.00,4.00,2.00,7.00,1.00,1.00,1.00,2.00,2.00,1.00,7.00,7.00,6.00,3.00,4.00,5.00,10.00,3.00,3.00,7.00,1.00,1.00,2.00,7.00,6.00,6.00,7.00,5.00,5.00,4.00,4.00,9.00,2.00,0.00,6.00,6.00,3.00,5.00,4.00,7.00,6.00,4.00,3.00,5.00,7.00,3.00,5.00,4.00,2.00,4.00,4.00,1.00,1.00,3.00,2.00,7.00,7.00,3.00,4.00,3.00,5.00,10.00,1.00,4.00,2.00,3.00,4.00,0.00,7.00,5.00,4.00,2.00,4.00,4.00,1.00,1.00,2.00,3.00,2.00,2.00,7.00,7.00,3.00,4.00,3.00,5.00,10.00,1.00,4.00,2.00,3.00,4.00,0.00,7.00,3.00,4.00,1.00,4.00,1.00,5.00,4.00,6.00,7.00,4.00,5.00,3.00,4.00,5.00,6.00,3.00,6.00,7.00,2.00,3.00,2.00,4.00
3,3,League One,Coventry City,7.00,5.00,5.00,6.00,6.00,9.00,9.00,2.00,2.00,0.00,0.00,6.00,8.00,6.00,5.00,3.00,3.00,3.00,0.00,5.00,6.00,10.00,0.00,7.00,5.00,6.00,7.00,6.00,9.00,9.00,9.00,2.00,3.00,9.00,1.00,0.00,6.00,8.00,8.00,5.00,4.00,7.00,3.00,0.00,5.00,7.00,10.00,0.00,5.00,8.00,7.00,4.00,4.00,5.00,5.00,0.00,4.00,2.00,4.00,3.00,0.00,9.00,7.00,9.00,6.00,5.00,9.00,6.00,NaN,5.00,3.00,2.00,1.00,4.00,3.00,7.00,7.00,5.00,5.00,3.00,3.00,0.00,5.00,2.00,5.00,10.00,3.00,0.00,NaN,7.00,7.00,5.00,0.00,3.00,1.00,1.00,4.00,3.00,7.00,7.00,6.00,5.00,5.00,7.00,3.00,3.00,0.00,5.00,2.00,5.00,10.00,7.00,0.00,NaN,7.00,7.00,5.00,0.00,5.00,7.00,6.00,2.00,5.00,5.00,6.00,1.00,2.00,10.00,4.00,8.00,4.00,0.00,1.00,8.00,8.00,5.00,5.00,5.00,NaN,6.00
4,4,Premier League,Wolverhampton Wanderers,3.00,3.00,2.00,3.00,4.00,4.00,3.00,4.00,4.00,7.00,4.00,6.00,2.00,4.00,3.00,3.00,5.00,4.00,4.00,3.00,2.00,9.00,4.00,2.00,3.00,1.00,2.00,3.00,3.00,3.00,5.00,4.00,4.00,4.00,6.00,4.00,6.00,2.00,3.00,3.00,2.00,2.00,3.00,4.00,2.00,1.00,8.00,3.00,5.00,1.00,1.00,2.00,7.00,3.00,4.00,8.00,2.00,2.00,8.00,7.00,6.00,8.00,1.00,5.00,5.00,10.00,2.00,2.00,3.00,0.00,3.00,4.00,2.00,3.00,3.00,3.00,3.00,4.00,2.00,3.00,0.00,0.00,0.00,1.00,5.00,3.00,4.00,3.00,7.00,3.00,2.00,6.00,6.00,3.00,4.00,2.00,3.00,3.00,3.00,3.00,5.00,4.00,2.00,4.00,3.00,0.00,0.00,0.00,1.00,5.00,3.00,4.00,3.00,5.00,3.00,2.00,6.00,6.00,4.00,3.00,2.00,0.00,5.00,5.00,5.00,8.00,7.00,2.00,8.00,4.00,1.00,0.00,2.00,5.00,8.00,7.00,2.00,6.00,4.00,4.00

Data Types

float64    140
object       2
int64        1
Name: count, dtype: int64

Memory Usage
14.65 MB
================================================================================
AWAY TEAM
================================================================================
Rows    : 12,303
Columns : 143

First 5 rows

,ID,LEAGUE,TEAM_NAME,TEAM_SHOTS_TOTAL_season_sum,TEAM_SHOTS_INSIDEBOX_season_sum,TEAM_SHOTS_OFF_TARGET_season_sum,TEAM_SHOTS_ON_TARGET_season_sum,TEAM_SHOTS_OUTSIDEBOX_season_sum,TEAM_PASSES_season_sum,TEAM_SUCCESSFUL_PASSES_season_sum,TEAM_SAVES_season_sum,TEAM_CORNERS_season_sum,TEAM_FOULS_season_sum,TEAM_YELLOWCARDS_season_sum,TEAM_REDCARDS_season_sum,TEAM_OFFSIDES_season_sum,TEAM_ATTACKS_season_sum,TEAM_PENALTIES_season_sum,TEAM_SUBSTITUTIONS_season_sum,TEAM_BALL_SAFE_season_sum,TEAM_DANGEROUS_ATTACKS_season_sum,TEAM_INJURIES_season_sum,TEAM_GOALS_season_sum,TEAM_GAME_WON_season_sum,TEAM_GAME_DRAW_season_sum,TEAM_GAME_LOST_season_sum,TEAM_SHOTS_TOTAL_season_average,TEAM_SHOTS_INSIDEBOX_season_average,TEAM_SHOTS_OFF_TARGET_season_average,TEAM_SHOTS_ON_TARGET_season_average,TEAM_SHOTS_OUTSIDEBOX_season_average,TEAM_PASSES_season_average,TEAM_SUCCESSFUL_PASSES_season_average,TEAM_SUCCESSFUL_PASSES_PERCENTAGE_season_average,TEAM_SAVES_season_average,TEAM_CORNERS_season_average,TEAM_BALL_POSSESSION_season_average,TEAM_FOULS_season_average,TEAM_YELLOWCARDS_season_average,TEAM_REDCARDS_season_average,TEAM_OFFSIDES_season_average,TEAM_ATTACKS_season_average,TEAM_PENALTIES_season_average,TEAM_SUBSTITUTIONS_season_average,TEAM_BALL_SAFE_season_average,TEAM_DANGEROUS_ATTACKS_season_average,TEAM_INJURIES_season_average,TEAM_GOALS_season_average,TEAM_GAME_WON_season_average,TEAM_GAME_DRAW_season_average,TEAM_GAME_LOST_season_average,TEAM_SHOTS_TOTAL_season_std,TEAM_SHOTS_INSIDEBOX_season_std,TEAM_SHOTS_OFF_TARGET_season_std,TEAM_SHOTS_ON_TARGET_season_std,TEAM_SHOTS_OUTSIDEBOX_season_std,TEAM_PASSES_season_std,TEAM_SUCCESSFUL_PASSES_season_std,TEAM_SUCCESSFUL_PASSES_PERCENTAGE_season_std,TEAM_SAVES_season_std,TEAM_CORNERS_season_std,TEAM_BALL_POSSESSION_season_std,TEAM_FOULS_season_std,TEAM_YELLOWCARDS_season_std,TEAM_REDCARDS_season_std,TEAM_OFFSIDES_season_std,TEAM_ATTACKS_season_std,TEAM_PENALTIES_season_std,TEAM_SUBSTITUTIONS_season_std,TEAM_BALL_SAFE_season_std,TEAM_DANGEROUS_ATTACKS_season_std,TEAM_INJURIES_season_std,TEAM_GOALS_season_std,TEAM_SHOTS_TOTAL_5_last_match_sum,TEAM_SHOTS_INSIDEBOX_5_last_match_sum,TEAM_SHOTS_OFF_TARGET_5_last_match_sum,TEAM_SHOTS_ON_TARGET_5_last_match_sum,TEAM_SHOTS_OUTSIDEBOX_5_last_match_sum,TEAM_PASSES_5_last_match_sum,TEAM_SUCCESSFUL_PASSES_5_last_match_sum,TEAM_SAVES_5_last_match_sum,TEAM_CORNERS_5_last_match_sum,TEAM_FOULS_5_last_match_sum,TEAM_YELLOWCARDS_5_last_match_sum,TEAM_REDCARDS_5_last_match_sum,TEAM_OFFSIDES_5_last_match_sum,TEAM_ATTACKS_5_last_match_sum,TEAM_PENALTIES_5_last_match_sum,TEAM_SUBSTITUTIONS_5_last_match_sum,TEAM_BALL_SAFE_5_last_match_sum,TEAM_DANGEROUS_ATTACKS_5_last_match_sum,TEAM_INJURIES_5_last_match_sum,TEAM_GOALS_5_last_match_sum,TEAM_GAME_WON_5_last_match_sum,TEAM_GAME_DRAW_5_last_match_sum,TEAM_GAME_LOST_5_last_match_sum,TEAM_SHOTS_TOTAL_5_last_match_average,TEAM_SHOTS_INSIDEBOX_5_last_match_average,TEAM_SHOTS_OFF_TARGET_5_last_match_average,TEAM_SHOTS_ON_TARGET_5_last_match_average,TEAM_SHOTS_OUTSIDEBOX_5_last_match_average,TEAM_PASSES_5_last_match_average,TEAM_SUCCESSFUL_PASSES_5_last_match_average,TEAM_SUCCESSFUL_PASSES_PERCENTAGE_5_last_match_average,TEAM_SAVES_5_last_match_average,TEAM_CORNERS_5_last_match_average,TEAM_BALL_POSSESSION_5_last_match_average,TEAM_FOULS_5_last_match_average,TEAM_YELLOWCARDS_5_last_match_average,TEAM_REDCARDS_5_last_match_average,TEAM_OFFSIDES_5_last_match_average,TEAM_ATTACKS_5_last_match_average,TEAM_PENALTIES_5_last_match_average,TEAM_SUBSTITUTIONS_5_last_match_average,TEAM_BALL_SAFE_5_last_match_average,TEAM_DANGEROUS_ATTACKS_5_last_match_average,TEAM_INJURIES_5_last_match_average,TEAM_GOALS_5_last_match_average,TEAM_GAME_WON_5_last_match_average,TEAM_GAME_DRAW_5_last_match_average,TEAM_GAME_LOST_5_last_match_average,TEAM_SHOTS_TOTAL_5_last_match_std,TEAM_SHOTS_INSIDEBOX_5_last_match_std,TEAM_SHOTS_OFF_TARGET_5_last_match_std,TEAM_SHOTS_ON_TARGET_5_last_match_std,TEAM_SHOTS_OUTSIDEBOX_5_last_match_std,TEAM_PASSES_5_last_match_std,TEAM_SUCCESSFUL_PASSES_5_last_match_std,TEAM_SUCCESSFUL_PASSES_PERCENTAGE_5_last_match_std,TEAM_SAVES_5_last_match_std,TEAM_CORNERS_5_last_match_std,TEAM_BALL_POSSESSION_5_last_match_std,TEAM_FOULS_5_last_match_std,TEAM_YELLOWCARDS_5_last_match_std,TEAM_REDCARDS_5_last_match_std,TEAM_OFFSIDES_5_last_match_std,TEAM_ATTACKS_5_last_match_std,TEAM_PENALTIES_5_last_match_std,TEAM_SUBSTITUTIONS_5_last_match_std,TEAM_BALL_SAFE_5_last_match_std,TEAM_DANGEROUS_ATTACKS_5_last_match_std,TEAM_INJURIES_5_last_match_std,TEAM_GOALS_5_last_match_std
0,0,Ligue 1,Olympique Marseille,4.00,1.00,4.00,1.00,5.00,4.00,3.00,6.00,4.00,6.00,10.00,6.00,1.00,4.00,10.00,8.00,2.00,4.00,1.00,4.00,5.00,8.00,0.00,4.00,1.00,4.00,1.00,5.00,3.00,3.00,5.00,6.00,4.00,3.00,6.00,10.00,6.00,1.00,4.00,10.00,8.00,0.00,4.00,0.00,4.00,4.00,7.00,0.00,4.00,1.00,0.00,3.00,10.00,7.00,7.00,5.00,4.00,6.00,7.00,2.00,7.00,9.00,1.00,1.00,6.00,4.00,3.00,10.00,1.00,4.00,2.00,2.00,2.00,1.00,4.00,2.00,3.00,2.00,4.00,4.00,6.00,3.00,5.00,4.00,10.00,5.00,0.00,6.00,0.00,4.00,7.00,0.00,5.00,2.00,2.00,2.00,1.00,4.00,2.00,3.00,5.00,2.00,4.00,3.00,4.00,6.00,3.00,4.00,4.00,10.00,4.00,0.00,6.00,0.00,4.00,7.00,0.00,5.00,0.00,3.00,2.00,3.00,7.00,6.00,6.00,6.00,0.00,1.00,8.00,2.00,5.00,5.00,4.00,0.00,6.00,8.00,4.00,3.00,2.00,3.00
1,1,Ligue 2,Red Star,4.00,3.00,4.00,3.00,8.00,8.00,7.00,8.00,5.00,8.00,3.00,2.00,5.00,5.00,3.00,10.00,4.00,7.00,5.00,2.00,1.00,4.00,8.00,3.00,2.00,2.00,2.00,6.00,4.00,4.00,5.00,8.00,4.00,4.00,5.00,3.00,1.00,3.00,2.00,3.00,7.00,0.00,5.00,6.00,2.00,1.00,3.00,7.00,5.00,0.00,4.00,2.00,8.00,6.00,5.00,3.00,7.00,1.00,5.00,9.00,2.00,4.00,3.00,7.00,6.00,4.00,10.00,6.00,4.00,2.00,3.00,2.00,0.00,3.00,5.00,5.00,5.00,7.00,3.00,5.00,3.00,0.00,5.00,3.00,5.00,5.00,0.00,4.00,3.00,2.00,2.00,3.00,7.00,3.00,2.00,0.00,3.00,5.00,5.00,5.00,6.00,7.00,3.00,5.00,5.00,3.00,0.00,4.00,3.00,5.00,4.00,0.00,4.00,3.00,2.00,2.00,3.00,7.00,4.00,0.00,3.00,3.00,4.00,9.00,8.00,5.00,5.00,1.00,6.00,10.00,0.00,0.00,3.00,1.00,8.00,4.00,10.00,0.00,5.00,3.00
2,2,Serie A,Bologna,4.00,3.00,4.00,2.00,6.00,4.00,4.00,1.00,6.00,8.00,10.00,7.00,7.00,5.00,3.00,7.00,4.00,7.00,2.00,3.00,2.00,5.00,5.00,4.00,3.00,4.00,2.00,5.00,4.00,4.00,5.00,1.00,6.00,6.00,8.00,10.00,7.00,6.00,5.00,3.00,7.00,3.00,6.00,2.00,3.00,2.00,5.00,5.00,2.00,7.00,2.00,6.00,5.00,4.00,4.00,5.00,3.00,7.00,10.00,0.00,6.00,7.00,6.00,7.00,5.00,5.00,9.00,7.00,4.00,2.00,7.00,5.00,6.00,0.00,7.00,3.00,3.00,2.00,5.00,6.00,3.00,6.00,4.00,8.00,0.00,6.00,4.00,8.00,6.00,1.00,2.00,2.00,7.00,7.00,5.00,6.00,0.00,7.00,3.00,3.00,5.00,2.00,5.00,6.00,6.00,3.00,6.00,4.00,8.00,0.00,6.00,4.00,8.00,6.00,1.00,2.00,2.00,7.00,1.00,5.00,2.00,0.00,10.00,3.00,4.00,3.00,8.00,1.00,4.00,2.00,6.00,10.00,4.00,4.00,0.00,8.00,3.00,0.00,9.00,6.00
3,3,League One,Bolton Wanderers,0.00,0.00,0.00,0.00,1.00,3.00,3.00,8.00,1.00,3.00,0.00,5.00,2.00,2.00,0.00,0.00,10.00,0.00,NaN,0.00,1.00,5.00,6.00,0.00,0.00,2.00,0.00,2.00,4.00,4.00,5.00,8.00,2.00,4.00,5.00,0.00,5.00,2.00,5.00,0.00,1.00,8.00,0.00,NaN,0.00,1.00,5.00,7.00,4.00,5.00,3.00,2.00,3.00,7.00,4.00,6.00,8.00,5.00,6.00,7.00,1.00,6.00,3.00,4.00,0.00,5.00,4.00,3.00,NaN,1.00,7.00,3.00,5.00,1.00,10.00,5.00,4.00,3.00,5.00,3.00,2.00,0.00,0.00,7.00,0.00,5.00,2.00,5.00,NaN,3.00,2.00,2.00,7.00,7.00,3.00,5.00,1.00,10.00,5.00,4.00,5.00,3.00,5.00,5.00,3.00,2.00,0.00,0.00,7.00,0.00,4.00,2.00,5.00,NaN,3.00,2.00,2.00,7.00,6.00,4.00,6.00,0.00,7.00,2.00,3.00,0.00,4.00,0.00,3.00,5.00,0.00,0.00,1.00,2.00,0.00,5.00,6.00,3.00,NaN,2.00
4,4,Premier League,Leicester City,5.00,4.00,5.00,6.00,5.00,6.00,6.00,4.00,5.00,5.00,0.00,0.00,6.00,6.00,6.00,7.00,6.00,5.00,2.00,7.00,5.00,2.00,4.00,4.00,4.00,5.00,6.00,5.00,6.00,5.00,6.00,3.00,5.00,7.00,4.00,0.00,0.00,6.00,5.00,6.00,5.00,3.00,4.00,2.00,7.00,5.00,2.00,3.00,8.00,10.00,4.00,10.00,8.00,5.00,5.00,3.00,6.00,2.00,6.00,9.00,2.00,0.00,4.00,7.00,7.00,4.00,4.00,1.00,5.00,10.00,6.00,6.00,1.00,10.00,6.00,5.00,5.00,4.00,2.00,4.00,0.00,0.00,3.00,5.00,10.00,7.00,1.00,4.00,4.00,8.00,4.00,3.00,6.00,6.00,6.00,1.00,10.00,6.00,5.00,5.00,6.00,4.00,2.00,7.00,4.00,0.00,0.00,3.00,5.00,10.00,7.00,1.00,4.00,3.00,8.00,4.00,3.00,6.00,8.00,4.00,3.00,7.00,4.00,8.00,8.00,6.00,10.00,2.00,7.00,2.00,1.00,0.00,4.00,4.00,9.00,4.00,1.00,4.00,6.00,5.00

Data Types

float64    140
object       2
int64        1
Name: count, dtype: int64

Memory Usage
14.64 MB
================================================================================
HOME PLAYER
================================================================================
Rows    : 237,079
Columns : 307

First 5 rows

,ID,LEAGUE,TEAM_NAME,POSITION,PLAYER_NAME,PLAYER_ACCURATE_CROSSES_season_sum,PLAYER_ACCURATE_PASSES_season_sum,PLAYER_AERIALS_WON_season_sum,PLAYER_ASSISTS_season_sum,PLAYER_BIG_CHANCES_CREATED_season_sum,PLAYER_BIG_CHANCES_MISSED_season_sum,PLAYER_BLOCKED_SHOTS_season_sum,PLAYER_CAPTAIN_season_sum,PLAYER_CLEARANCES_season_sum,PLAYER_CLEARANCE_OFFLINE_season_sum,PLAYER_DISPOSSESSED_season_sum,PLAYER_DRIBBLED_ATTEMPTS_season_sum,PLAYER_DRIBBLED_PAST_season_sum,PLAYER_DUELS_LOST_season_sum,PLAYER_DUELS_WON_season_sum,PLAYER_ERROR_LEAD_TO_GOAL_season_sum,PLAYER_FOULS_season_sum,PLAYER_FOULS_DRAWN_season_sum,PLAYER_GOALKEEPER_GOALS_CONCEDED_season_sum,PLAYER_GOALS_season_sum,PLAYER_GOALS_CONCEDED_season_sum,PLAYER_HIT_WOODWORK_season_sum,PLAYER_INTERCEPTIONS_season_sum,PLAYER_KEY_PASSES_season_sum,PLAYER_MINUTES_PLAYED_season_sum,PLAYER_OFFSIDES_season_sum,PLAYER_OWN_GOALS_season_sum,PLAYER_PASSES_season_sum,PLAYER_PENALTIES_COMMITTED_season_sum,PLAYER_PENALTIES_MISSES_season_sum,PLAYER_PENALTIES_SAVED_season_sum,PLAYER_PENALTIES_SCORED_season_sum,PLAYER_PENALTIES_WON_season_sum,PLAYER_REDCARDS_season_sum,PLAYER_SAVES_season_sum,PLAYER_SAVES_INSIDE_BOX_season_sum,PLAYER_SHOTS_BLOCKED_season_sum,PLAYER_SHOTS_ON_TARGET_season_sum,PLAYER_SHOTS_TOTAL_season_sum,PLAYER_STARTING_LINEUP_season_sum,PLAYER_SUCCESSFUL_DRIBBLES_season_sum,PLAYER_TACKLES_season_sum,PLAYER_TOTAL_CROSSES_season_sum,PLAYER_TOTAL_DUELS_season_sum,PLAYER_YELLOWCARDS_season_sum,PLAYER_PUNCHES_season_sum,PLAYER_LONG_BALLS_season_sum,PLAYER_LONG_BALLS_WON_season_sum,PLAYER_SHOTS_OFF_TARGET_season_sum,PLAYER_ACCURATE_CROSSES_season_average,PLAYER_ACCURATE_PASSES_season_average,PLAYER_ACCURATE_PASSES_PERCENTAGE_season_average,PLAYER_AERIALS_WON_season_average,PLAYER_ASSISTS_season_average,PLAYER_BIG_CHANCES_CREATED_season_average,PLAYER_BIG_CHANCES_MISSED_season_average,PLAYER_BLOCKED_SHOTS_season_average,PLAYER_CAPTAIN_season_average,PLAYER_CLEARANCES_season_average,PLAYER_CLEARANCE_OFFLINE_season_average,PLAYER_DISPOSSESSED_season_average,PLAYER_DRIBBLED_ATTEMPTS_season_average,PLAYER_DRIBBLED_PAST_season_average,PLAYER_DUELS_LOST_season_average,PLAYER_DUELS_WON_season_average,PLAYER_ERROR_LEAD_TO_GOAL_season_average,PLAYER_FOULS_season_average,PLAYER_FOULS_DRAWN_season_average,PLAYER_GOALKEEPER_GOALS_CONCEDED_season_average,PLAYER_GOALS_season_average,PLAYER_GOALS_CONCEDED_season_average,PLAYER_HIT_WOODWORK_season_average,PLAYER_INTERCEPTIONS_season_average,PLAYER_KEY_PASSES_season_average,PLAYER_MINUTES_PLAYED_season_average,PLAYER_OFFSIDES_season_average,PLAYER_OWN_GOALS_season_average,PLAYER_PASSES_season_average,PLAYER_PENALTIES_COMMITTED_season_average,PLAYER_PENALTIES_MISSES_season_average,PLAYER_PENALTIES_SAVED_season_average,PLAYER_PENALTIES_SCORED_season_average,PLAYER_PENALTIES_WON_season_average,PLAYER_RATING_season_average,PLAYER_REDCARDS_season_average,PLAYER_SAVES_season_average,PLAYER_SAVES_INSIDE_BOX_season_average,PLAYER_SHOTS_BLOCKED_season_average,PLAYER_SHOTS_ON_TARGET_season_average,PLAYER_SHOTS_TOTAL_season_average,PLAYER_STARTING_LINEUP_season_average,PLAYER_SUCCESSFUL_DRIBBLES_season_average,PLAYER_TACKLES_season_average,PLAYER_TOTAL_CROSSES_season_average,PLAYER_TOTAL_DUELS_season_average,PLAYER_YELLOWCARDS_season_average,PLAYER_PUNCHES_season_average,PLAYER_LONG_BALLS_season_average,PLAYER_LONG_BALLS_WON_season_average,PLAYER_SHOTS_OFF_TARGET_season_average,PLAYER_ACCURATE_CROSSES_season_std,PLAYER_ACCURATE_PASSES_season_std,PLAYER_ACCURATE_PASSES_PERCENTAGE_season_std,PLAYER_AERIALS_WON_season_std,PLAYER_ASSISTS_season_std,PLAYER_BIG_CHANCES_CREATED_season_std,PLAYER_BIG_CHANCES_MISSED_season_std,PLAYER_BLOCKED_SHOTS_season_std,PLAYER_CAPTAIN_season_std,PLAYER_CLEARANCES_season_std,PLAYER_CLEARANCE_OFFLINE_season_std,PLAYER_DISPOSSESSED_season_std,PLAYER_DRIBBLED_ATTEMPTS_season_std,PLAYER_DRIBBLED_PAST_season_std,PLAYER_DUELS_LOST_season_std,PLAYER_DUELS_WON_season_std,PLAYER_ERROR_LEAD_TO_GOAL_season_std,PLAYER_FOULS_season_std,PLAYER_FOULS_DRAWN_season_std,PLAYER_GOALKEEPER_GOALS_CONCEDED_season_std,PLAYER_GOALS_season_std,PLAYER_GOALS_CONCEDED_season_std,PLAYER_HIT_WOODWORK_season_std,PLAYER_INTERCEPTIONS_season_std,PLAYER_KEY_PASSES_season_std,PLAYER_MINUTES_PLAYED_season_std,PLAYER_OFFSIDES_season_std,PLAYER_OWN_GOALS_season_std,PLAYER_PASSES_season_std,PLAYER_PENALTIES_COMMITTED_season_std,PLAYER_PENALTIES_MISSES_season_std,PLAYER_PENALTIES_SAVED_season_std,PLAYER_PENALTIES_SCORED_season_std,PLAYER_PENALTIES_WON_season_std,PLAYER_RATING_season_std,PLAYER_REDCARDS_season_std,PLAYER_SAVES_season_std,PLAYER_SAVES_INSIDE_BOX_season_std,PLAYER_SHOTS_BLOCKED_season_std,PLAYER_SHOTS_ON_TARGET_season_std,PLAYER_SHOTS_TOTAL_season_std,PLAYER_STARTING_LINEUP_season_std,PLAYER_SUCCESSFUL_DRIBBLES_season_std,PLAYER_TACKLES_season_std,PLAYER_TOTAL_CROSSES_season_std,PLAYER_TOTAL_DUELS_season_std,PLAYER_YELLOWCARDS_season_std,PLAYER_PUNCHES_season_std,PLAYER_LONG_BALLS_season_std,PLAYER_LONG_BALLS_WON_season_std,PLAYER_SHOTS_OFF_TARGET_season_std,PLAYER_ACCURATE_CROSSES_5_last_match_sum,PLAYER_ACCURATE_PASSES_5_last_match_sum,PLAYER_AERIALS_WON_5_last_match_sum,PLAYER_ASSISTS_5_last_match_sum,PLAYER_BIG_CHANCES_CREATED_5_last_match_sum,PLAYER_BIG_CHANCES_MISSED_5_last_match_sum,PLAYER_BLOCKED_SHOTS_5_last_match_sum,PLAYER_CAPTAIN_5_last_match_sum,PLAYER_CLEARANCES_5_last_match_sum,PLAYER_CLEARANCE_OFFLINE_5_last_match_sum,PLAYER_DISPOSSESSED_5_last_match_sum,PLAYER_DRIBBLED_ATTEMPTS_5_last_match_sum,PLAYER_DRIBBLED_PAST_5_last_match_sum,PLAYER_DUELS_LOST_5_last_match_sum,PLAYER_DUELS_WON_5_last_match_sum,PLAYER_ERROR_LEAD_TO_GOAL_5_last_match_sum,PLAYER_FOULS_5_last_match_sum,PLAYER_FOULS_DRAWN_5_last_match_sum,PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_sum,PLAYER_GOALS_5_last_match_sum,PLAYER_GOALS_CONCEDED_5_last_match_sum,PLAYER_HIT_WOODWORK_5_last_match_sum,PLAYER_INTERCEPTIONS_5_last_match_sum,PLAYER_KEY_PASSES_5_last_match_sum,PLAYER_MINUTES_PLAYED_5_last_match_sum,PLAYER_OFFSIDES_5_last_match_sum,PLAYER_OWN_GOALS_5_last_match_sum,PLAYER_PASSES_5_last_match_sum,PLAYER_PENALTIES_COMMITTED_5_last_match_sum,PLAYER_PENALTIES_MISSES_5_last_match_sum,PLAYER_PENALTIES_SAVED_5_last_match_sum,PLAYER_PENALTIES_SCORED_5_last_match_sum,PLAYER_PENALTIES_WON_5_last_match_sum,PLAYER_REDCARDS_5_last_match_sum,PLAYER_SAVES_5_last_match_sum,PLAYER_SAVES_INSIDE_BOX_5_last_match_sum,PLAYER_SHOTS_BLOCKED_5_last_match_sum,PLAYER_SHOTS_ON_TARGET_5_last_match_sum,PLAYER_SHOTS_TOTAL_5_last_match_sum,PLAYER_STARTING_LINEUP_5_last_match_sum,PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_sum,PLAYER_TACKLES_5_last_match_sum,PLAYER_TOTAL_CROSSES_5_last_match_sum,PLAYER_TOTAL_DUELS_5_last_match_sum,PLAYER_YELLOWCARDS_5_last_match_sum,PLAYER_PUNCHES_5_last_match_sum,PLAYER_LONG_BALLS_5_last_match_sum,PLAYER_LONG_BALLS_WON_5_last_match_sum,PLAYER_SHOTS_OFF_TARGET_5_last_match_sum,PLAYER_ACCURATE_CROSSES_5_last_match_average,PLAYER_ACCURATE_PASSES_5_last_match_average,PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_average,PLAYER_AERIALS_WON_5_last_match_average,PLAYER_ASSISTS_5_last_match_average,PLAYER_BIG_CHANCES_CREATED_5_last_match_average,PLAYER_BIG_CHANCES_MISSED_5_last_match_average,PLAYER_BLOCKED_SHOTS_5_last_match_average,PLAYER_CAPTAIN_5_last_match_average,PLAYER_CLEARANCES_5_last_match_average,PLAYER_CLEARANCE_OFFLINE_5_last_match_average,PLAYER_DISPOSSESSED_5_last_match_average,PLAYER_DRIBBLED_ATTEMPTS_5_last_match_average,PLAYER_DRIBBLED_PAST_5_last_match_average,PLAYER_DUELS_LOST_5_last_match_average,PLAYER_DUELS_WON_5_last_match_average,PLAYER_ERROR_LEAD_TO_GOAL_5_last_match_average,PLAYER_FOULS_5_last_match_average,PLAYER_FOULS_DRAWN_5_last_match_average,PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_average,PLAYER_GOALS_5_last_match_average,PLAYER_GOALS_CONCEDED_5_last_match_average,PLAYER_HIT_WOODWORK_5_last_match_average,PLAYER_INTERCEPTIONS_5_last_match_average,PLAYER_KEY_PASSES_5_last_match_average,PLAYER_MINUTES_PLAYED_5_last_match_average,PLAYER_OFFSIDES_5_last_match_average,PLAYER_OWN_GOALS_5_last_match_average,PLAYER_PASSES_5_last_match_average,PLAYER_PENALTIES_COMMITTED_5_last_match_average,PLAYER_PENALTIES_MISSES_5_last_match_average,PLAYER_PENALTIES_SAVED_5_last_match_average,PLAYER_PENALTIES_SCORED_5_last_match_average,PLAYER_PENALTIES_WON_5_last_match_average,PLAYER_RATING_5_last_match_average,PLAYER_REDCARDS_5_last_match_average,PLAYER_SAVES_5_last_match_average,PLAYER_SAVES_INSIDE_BOX_5_last_match_average,PLAYER_SHOTS_BLOCKED_5_last_match_average,PLAYER_SHOTS_ON_TARGET_5_last_match_average,PLAYER_SHOTS_TOTAL_5_last_match_average,PLAYER_STARTING_LINEUP_5_last_match_average,PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_average,PLAYER_TACKLES_5_last_match_average,PLAYER_TOTAL_CROSSES_5_last_match_average,PLAYER_TOTAL_DUELS_5_last_match_average,PLAYER_YELLOWCARDS_5_last_match_average,PLAYER_PUNCHES_5_last_match_average,PLAYER_LONG_BALLS_5_last_match_average,PLAYER_LONG_BALLS_WON_5_last_match_average,PLAYER_SHOTS_OFF_TARGET_5_last_match_average,PLAYER_ACCURATE_CROSSES_5_last_match_std,PLAYER_ACCURATE_PASSES_5_last_match_std,PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_std,PLAYER_AERIALS_WON_5_last_match_std,PLAYER_ASSISTS_5_last_match_std,PLAYER_BIG_CHANCES_CREATED_5_last_match_std,PLAYER_BIG_CHANCES_MISSED_5_last_match_std,PLAYER_BLOCKED_SHOTS_5_last_match_std,PLAYER_CAPTAIN_5_last_match_std,PLAYER_CLEARANCES_5_last_match_std,PLAYER_CLEARANCE_OFFLINE_5_last_match_std,PLAYER_DISPOSSESSED_5_last_match_std,PLAYER_DRIBBLED_ATTEMPTS_5_last_match_std,PLAYER_DRIBBLED_PAST_5_last_match_std,PLAYER_DUELS_LOST_5_last_match_std,PLAYER_DUELS_WON_5_last_match_std,PLAYER_ERROR_LEAD_TO_GOAL_5_last_match_std,PLAYER_FOULS_5_last_match_std,PLAYER_FOULS_DRAWN_5_last_match_std,PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_std,PLAYER_GOALS_5_last_match_std,PLAYER_GOALS_CONCEDED_5_last_match_std,PLAYER_HIT_WOODWORK_5_last_match_std,PLAYER_INTERCEPTIONS_5_last_match_std,PLAYER_KEY_PASSES_5_last_match_std,PLAYER_MINUTES_PLAYED_5_last_match_std,PLAYER_OFFSIDES_5_last_match_std,PLAYER_OWN_GOALS_5_last_match_std,PLAYER_PASSES_5_last_match_std,PLAYER_PENALTIES_COMMITTED_5_last_match_std,PLAYER_PENALTIES_MISSES_5_last_match_std,PLAYER_PENALTIES_SAVED_5_last_match_std,PLAYER_PENALTIES_SCORED_5_last_match_std,PLAYER_PENALTIES_WON_5_last_match_std,PLAYER_RATING_5_last_match_std,PLAYER_REDCARDS_5_last_match_std,PLAYER_SAVES_5_last_match_std,PLAYER_SAVES_INSIDE_BOX_5_last_match_std,PLAYER_SHOTS_BLOCKED_5_last_match_std,PLAYER_SHOTS_ON_TARGET_5_last_match_std,PLAYER_SHOTS_TOTAL_5_last_match_std,PLAYER_STARTING_LINEUP_5_last_match_std,PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_std,PLAYER_TACKLES_5_last_match_std,PLAYER_TOTAL_CROSSES_5_last_match_std,PLAYER_TOTAL_DUELS_5_last_match_std,PLAYER_YELLOWCARDS_5_last_match_std,PLAYER_PUNCHES_5_last_match_std,PLAYER_LONG_BALLS_5_last_match_std,PLAYER_LONG_BALLS_WON_5_last_match_std,PLAYER_SHOTS_OFF_TARGET_5_last_match_std
0,0,Ligue 1,Toulouse,defender,Agustín Rogel,0.00,8.00,5.00,0.00,0.00,0.00,0.00,NaN,4.00,0.00,0.00,0.00,0.00,0.00,3.00,0.00,0.00,0.00,0.00,0.00,4.00,0.00,0.00,0.00,6.00,0.00,0.00,7.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2.00,7.00,0.00,0.00,0.00,1.00,0.00,NaN,NaN,NaN,NaN,0.00,89.00,NaN,61.00,0.00,0.00,0.00,0.00,NaN,44.00,0.00,0.00,0.00,0.00,0.00,35.00,0.00,0.00,0.00,0.00,0.00,25.00,0.00,0.00,0.00,86.00,0.00,0.00,88.00,0.00,0.00,0.00,0.00,0.00,86.00,0.00,0.00,0.00,0.00,0.00,18.00,100.00,0.00,0.00,0.00,20.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,16.00,10.00,0.00,0.00,0.00,0.00,NaN,8.00,0.00,0.00,0.00,0.00,0.00,6.00,0.00,0.00,0.00,0.00,0.00,7.00,0.00,0.00,0.00,17.00,0.00,0.00,16.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,3.00,20.00,0.00,0.00,0.00,3.00,0.00,NaN,NaN,NaN,NaN,0.00,81.00,NaN,54.00,0.00,0.00,0.00,0.00,NaN,44.00,0.00,0.00,0.00,0.00,0.00,31.00,0.00,0.00,0.00,0.00,0.00,25.00,0.00,0.00,0.00,86.00,0.00,0.00,82.00,0.00,0.00,0.00,0.00,0.00,82.00,0.00,0.00,0.00,0.00,0.00,18.00,100.00,0.00,0.00,0.00,19.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,Ligue 1,Toulouse,defender,Mathieu Goncalves,0.00,7.00,4.00,0.00,0.00,0.00,6.00,NaN,12.00,0.00,4.00,1.00,19.00,8.00,7.00,0.00,9.00,2.00,0.00,0.00,64.00,0.00,3.00,0.00,20.00,0.00,100.00,8.00,50.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,6.00,0.00,0.00,15.00,4.00,5.00,0.00,8.00,20.00,NaN,NaN,NaN,NaN,0.00,11.00,75.00,6.00,0.00,0.00,0.00,9.00,NaN,17.00,0.00,8.00,1.00,25.00,14.00,11.00,0.00,10.00,3.00,0.00,0.00,57.00,0.00,3.00,0.00,38.00,0.00,42.00,14.00,71.00,0.00,0.00,0.00,0.00,32.00,0.00,0.00,0.00,11.00,0.00,0.00,28.00,3.00,10.00,0.00,14.00,14.00,NaN,NaN,NaN,NaN,0.00,26.00,31.00,16.00,0.00,0.00,0.00,23.00,NaN,33.00,0.00,32.00,7.00,45.00,30.00,21.00,0.00,17.00,13.00,0.00,0.00,48.00,0.00,10.00,0.00,69.00,0.00,65.00,35.00,59.00,0.00,0.00,0.00,0.00,59.00,0.00,0.00,0.00,23.00,0.00,0.00,69.00,13.00,14.00,0.00,32.00,65.00,NaN,NaN,NaN,NaN,0.00,10.00,8.00,0.00,0.00,0.00,12.00,NaN,14.00,0.00,0.00,2.00,28.00,14.00,9.00,0.00,11.00,0.00,0.00,0.00,92.00,0.00,0.00,0.00,34.00,0.00,0.00,12.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,12.00,0.00,0.00,20.00,4.00,8.00,0.00,14.00,25.00,NaN,NaN,NaN,NaN,0.00,10.00,75.00,8.00,0.00,0.00,0.00,12.00,NaN,14.00,0.00,0.00,2.00,28.00,14.00,9.00,0.00,10.00,0.00,0.00,0.00,60.00,0.00,0.00,0.00,34.00,0.00,0.00,12.00,0.00,0.00,0.00,0.00,0.00,29.00,0.00,0.00,0.00,12.00,0.00,0.00,20.00,4.00,8.00,0.00,14.00,20.00,NaN,NaN,NaN,NaN,0.00,26.00,25.00,16.00,0.00,0.00,0.00,25.00,NaN,24.00,0.00,0.00,9.00,48.00,47.00,22.00,0.00,17.00,0.00,0.00,0.00,31.00,0.00,0.00,0.00,67.00,0.00,0.00,31.00,0.00,0.00,0.00,0.00,0.00,62.00,0.00,0.00,0.00,21.00,0.00,0.00,63.00,14.00,13.00,0.00,36.00,77.00,NaN,NaN,NaN,NaN
2,0,Ligue 1,Toulouse,goalkeeper,Baptiste Reynet,0.00,33.00,2.00,0.00,0.00,0.00,0.00,NaN,16.00,0.00,0.00,0.00,0.00,1.00,2.00,0.00,0.00,0.00,100.00,0.00,100.00,0.00,0.00,2.00,100.00,0.00,0.00,48.00,0.00,0.00,100.00,0.00,0.00,0.00,78.00,84.00,0.00,0.00,0.00,100.00,0.00,1.00,0.00,2.00,20.00,NaN,NaN,NaN,NaN,0.00,27.00,53.00,2.00,0.00,0.00,0.00,0.00,NaN,12.00,0.00,0.00,0.00,0.00,1.00,2.00,0.00,0.00,0.00,100.00,0.00,48.00,0.00,0.00,2.00,100.00,0.00,0.00,41.00,0.00,0.00,100.00,0.00,0.00,86.00,0.00,66.00,76.00,0.00,0.00,0.00,100.00,0.00,1.00,0.00,2.00,7.00,NaN,NaN,NaN,NaN,0.00,18.00,42.00,8.00,0.00,0.00,0.00,0.00,NaN,18.00,0.00,0.00,0.00,0.00,5.00,8.00,0.00,0.00,0.00,62.00,0.00,43.00,0.00,0.00,9.00,0.00,0.00,0.00,12.00,0.00,0.00,100.00,0.00,0.00,13.00,0.00,77.00,84.00,0.00,0.00,0.00,0.00,0.00,7.00,0.00,6.00,48.00,NaN,NaN,NaN,NaN,0.00,19.00,0.00,0.00,0.00,0.00,0.00,NaN,11.00,0.00,0.00,0.00,0.00,1.00,0.00,0.00,0.00,0.00,100.00,0.00,100.00,0.00,0.00,0.00,100.00,0.00,0.00,34.00,0.00,0.00,0.00,0.00,0.00,0.00,34.00,27.00,0.00,0.00,0.00,100.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,0.00,19.00,43.00,0.00,0.00,0.00,0.00,0.00,NaN,11.00,0.00,0.00,0.00,0.00,1.00,0.00,0.00,0.00,0.00,100.00,0.00,65.00,0.00,0.00,0.00,100.00,0.00,0.00,34.00,0.00,0.00,0.00,0.00,0.00,74.00,0.00,34.00,27.00,0.00,0.00,0.00,100.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,0.00,11.00,31.00,0.00,0.00,0.00,0.00,0.00,NaN,6.00,0.00,0.00,0.00,0.00,7.00,0.00,0.00,0.00,0.00,51.00,0.00,31.00,0.00,0.00,0.00,0.00,0.00,0.00,7.00,0.00,0.00,0.00,0.00,0.00,9.00,0.00,61.00,38.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,3.00,0.00,NaN,NaN,NaN,NaN
3,0,Ligue 1,Toulouse,midfielder,Jean-Victor Makengo,8.00,27.00,2.00,0.00,8.00,0.00,6.00,NaN,1.00,0.00,28.00,6.00,4.00,32.00,23.00,0.00,37.00,32.00,0.00,22.00,80.00,0.00,3.00,24.00,53.00,6.00,0.00,29.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,20.00,11.00,16.00,61.00,8.00,13.00,3.00,30.00,0.00,NaN,NaN,NaN,NaN,6.00,23.00,68.00,2.00,0.00,7.00,0.00,5.00,NaN,1.00,0.00,26.00,3.00,3.00,30.00,17.00,0.00,23.00,22.00,0.00,18.00,38.00,0.00,1.00,20.00,53.00,6.00,0.00,25.00,0.00,0.00,0.00,0.00,0.00,63.00,0.00,0.00,0.00,19.00,5.00,9.00,61.00,3.00,13.00,2.00,27.00,0.00,NaN,NaN,NaN,NaN,18.00,38.00,46.00,8.00,0.00,24.00,0.00,16.00,NaN,5.00,0.00,51.00,17.00,11.00,39.00,26.00,0.00,36.00,41.00,0.00,41.00,39.00,0.00,7.00,30.00,59.00,22.00,0.00,42.00,0.00,0.00,0.00,0.00,0.00,53.00,0.00,0.00,0.00,26.00,19.00,40.00,71.00,19.00,23.00,9.00,36.00,0.00,NaN,NaN,NaN,NaN,6.00,3.00,0.00,0.00,0.00,0.00,12.00,NaN,2.00,0.00,9.00,0.00,7.00,9.00,6.00,0.00,11.00,10.00,0.00,0.00,61.00,0.00,0.00,4.00,15.00,0.00,0.00,5.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,12.00,0.00,3.00,20.00,0.00,8.00,2.00,9.00,0.00,NaN,NaN,NaN,NaN,5.00,3.00,55.00,0.00,0.00,0.00,0.00,12.00,NaN,2.00,0.00,9.00,0.00,7.00,9.00,6.00,0.00,10.00,10.00,0.00,0.00,40.00,0.00,0.00,4.00,15.00,0.00,0.00,5.00,0.00,0.00,0.00,0.00,0.00,46.00,0.00,0.00,0.00,12.00,0.00,3.00,20.00,0.00,8.00,1.00,9.00,0.00,NaN,NaN,NaN,NaN,12.00,7.00,30.00,0.00,0.00,0.00,0.00,25.00,NaN,6.00,0.00,19.00,0.00,16.00,29.00,11.00,0.00,17.00,18.00,0.00,0.00,31.00,0.00,0.00,15.00,29.00,0.00,0.00,9.00,0.00,0.00,0.00,0.00,0.00,64.00,0.00,0.00,0.00,21.00,0.00,14.00,63.00,0.00,13.00,6.00,17.00,0.00,NaN,NaN,NaN,NaN
4,0,Ligue 1,Toulouse,NaN,Efthymios Koulouris,2.00,23.00,27.00,14.00,8.00,37.00,12.00,NaN,7.00,0.00,33.00,11.00,9.00,53.00,29.00,0.00,28.00,16.00,0.00,44.00,84.00,100.00,6.00,24.00,77.00,20.00,0.00,28.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,26.00,58.00,59.00,76.00,16.00,5.00,4.00,44.00,0.00,NaN,NaN,NaN,NaN,2.00,19.00,72.00,23.00,7.00,7.00,23.00,10.00,NaN,5.00,0.00,30.00,6.00,6.00,49.00,22.00,0.00,17.00,11.00,0.00,37.00,40.00,76.00,3.00,20.00,77.00,19.00,0.00,24.00,0.00,0.00,0.00,0.00,0.00,87.00,0.00,0.00,0.00,25.00,29.00,35.00,76.00,6.00,5.00,3.00,41.00,0.00,NaN,NaN,NaN,NaN,11.00,16.00,33.00,22.00,28.00,24.00,39.00,22.00,NaN,13.00,0.00,44.00,18.00,14.00,47.00,21.00,0.00,27.00,17.00,0.00,53.00,36.00,100.00,10.00,36.00,43.00,48.00,0.00,17.00,0.00,0.00,0.00,0.00,0.00,6.00,0.00,0.00,0.00,29.00,37.00,71.00,62.00,21.00,11.00,12.00,40.00,0.00,NaN,NaN,NaN,NaN,6.00,23.00,32.00,0.00,0.00,14.00,12.00,NaN,2.00,0.00,23.00,10.00,14.00,49.00,28.00,0.00,11.00,20.00,0.00,20.00,92.00,100.00,0.00,27.00,89.00,0.00,0.00,27.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,25.00,30.00,40.00,80.00,8.00,4.00,6.00,48.00,0.00,NaN,NaN,NaN,NaN,5.00,23.00,75.00,32.00,0.00,0.00,14.00,12.00,NaN,2.00,0.00,23.00,10.00,14.00,49.00,28.00,0.00,10.00,20.00,0.00,20.00,60.00,100.00,0.00,27.00,89.00,0.00,0.00,27.00,0.00,0.00,0.00,0.00,0.00,83.00,0.00,0.00,0.00,25.00,30.00,40.00,80.00,8.00,4.00,4.00,48.00,0.00,NaN,NaN,NaN,NaN,12.00,2.00,16.00,16.00,0.00,0.00,26.00,25.00,NaN,6.00,0.00,36.00,22.00,20.00,45.00,20.00,0.00,29.00,15.00,0.00,50.00,31.00,100.00,0.00,43.00,31.00,0.00,0.00,2.00,0.00,0.00,0.00,0.00,0.00,5.00,0.00,0.00,0.00,26.00,20.00,42.00,63.00,17.00,10.00,13.00,27.00,0.00,NaN,NaN,NaN,NaN

Data Types

float64    302
object       4
int64        1
Name: count, dtype: int64

Memory Usage
601.93 MB
================================================================================
AWAY PLAYER
================================================================================
Rows    : 236,132
Columns : 307

First 5 rows

,ID,LEAGUE,TEAM_NAME,POSITION,PLAYER_NAME,PLAYER_ACCURATE_CROSSES_season_sum,PLAYER_ACCURATE_PASSES_season_sum,PLAYER_AERIALS_WON_season_sum,PLAYER_ASSISTS_season_sum,PLAYER_BIG_CHANCES_CREATED_season_sum,PLAYER_BIG_CHANCES_MISSED_season_sum,PLAYER_BLOCKED_SHOTS_season_sum,PLAYER_CAPTAIN_season_sum,PLAYER_CLEARANCES_season_sum,PLAYER_CLEARANCE_OFFLINE_season_sum,PLAYER_DISPOSSESSED_season_sum,PLAYER_DRIBBLED_ATTEMPTS_season_sum,PLAYER_DRIBBLED_PAST_season_sum,PLAYER_DUELS_LOST_season_sum,PLAYER_DUELS_WON_season_sum,PLAYER_ERROR_LEAD_TO_GOAL_season_sum,PLAYER_FOULS_season_sum,PLAYER_FOULS_DRAWN_season_sum,PLAYER_GOALKEEPER_GOALS_CONCEDED_season_sum,PLAYER_GOALS_season_sum,PLAYER_GOALS_CONCEDED_season_sum,PLAYER_HIT_WOODWORK_season_sum,PLAYER_INTERCEPTIONS_season_sum,PLAYER_KEY_PASSES_season_sum,PLAYER_MINUTES_PLAYED_season_sum,PLAYER_OFFSIDES_season_sum,PLAYER_OWN_GOALS_season_sum,PLAYER_PASSES_season_sum,PLAYER_PENALTIES_COMMITTED_season_sum,PLAYER_PENALTIES_MISSES_season_sum,PLAYER_PENALTIES_SAVED_season_sum,PLAYER_PENALTIES_SCORED_season_sum,PLAYER_PENALTIES_WON_season_sum,PLAYER_REDCARDS_season_sum,PLAYER_SAVES_season_sum,PLAYER_SAVES_INSIDE_BOX_season_sum,PLAYER_SHOTS_BLOCKED_season_sum,PLAYER_SHOTS_ON_TARGET_season_sum,PLAYER_SHOTS_TOTAL_season_sum,PLAYER_STARTING_LINEUP_season_sum,PLAYER_SUCCESSFUL_DRIBBLES_season_sum,PLAYER_TACKLES_season_sum,PLAYER_TOTAL_CROSSES_season_sum,PLAYER_TOTAL_DUELS_season_sum,PLAYER_YELLOWCARDS_season_sum,PLAYER_PUNCHES_season_sum,PLAYER_LONG_BALLS_season_sum,PLAYER_LONG_BALLS_WON_season_sum,PLAYER_SHOTS_OFF_TARGET_season_sum,PLAYER_ACCURATE_CROSSES_season_average,PLAYER_ACCURATE_PASSES_season_average,PLAYER_ACCURATE_PASSES_PERCENTAGE_season_average,PLAYER_AERIALS_WON_season_average,PLAYER_ASSISTS_season_average,PLAYER_BIG_CHANCES_CREATED_season_average,PLAYER_BIG_CHANCES_MISSED_season_average,PLAYER_BLOCKED_SHOTS_season_average,PLAYER_CAPTAIN_season_average,PLAYER_CLEARANCES_season_average,PLAYER_CLEARANCE_OFFLINE_season_average,PLAYER_DISPOSSESSED_season_average,PLAYER_DRIBBLED_ATTEMPTS_season_average,PLAYER_DRIBBLED_PAST_season_average,PLAYER_DUELS_LOST_season_average,PLAYER_DUELS_WON_season_average,PLAYER_ERROR_LEAD_TO_GOAL_season_average,PLAYER_FOULS_season_average,PLAYER_FOULS_DRAWN_season_average,PLAYER_GOALKEEPER_GOALS_CONCEDED_season_average,PLAYER_GOALS_season_average,PLAYER_GOALS_CONCEDED_season_average,PLAYER_HIT_WOODWORK_season_average,PLAYER_INTERCEPTIONS_season_average,PLAYER_KEY_PASSES_season_average,PLAYER_MINUTES_PLAYED_season_average,PLAYER_OFFSIDES_season_average,PLAYER_OWN_GOALS_season_average,PLAYER_PASSES_season_average,PLAYER_PENALTIES_COMMITTED_season_average,PLAYER_PENALTIES_MISSES_season_average,PLAYER_PENALTIES_SAVED_season_average,PLAYER_PENALTIES_SCORED_season_average,PLAYER_PENALTIES_WON_season_average,PLAYER_RATING_season_average,PLAYER_REDCARDS_season_average,PLAYER_SAVES_season_average,PLAYER_SAVES_INSIDE_BOX_season_average,PLAYER_SHOTS_BLOCKED_season_average,PLAYER_SHOTS_ON_TARGET_season_average,PLAYER_SHOTS_TOTAL_season_average,PLAYER_STARTING_LINEUP_season_average,PLAYER_SUCCESSFUL_DRIBBLES_season_average,PLAYER_TACKLES_season_average,PLAYER_TOTAL_CROSSES_season_average,PLAYER_TOTAL_DUELS_season_average,PLAYER_YELLOWCARDS_season_average,PLAYER_PUNCHES_season_average,PLAYER_LONG_BALLS_season_average,PLAYER_LONG_BALLS_WON_season_average,PLAYER_SHOTS_OFF_TARGET_season_average,PLAYER_ACCURATE_CROSSES_season_std,PLAYER_ACCURATE_PASSES_season_std,PLAYER_ACCURATE_PASSES_PERCENTAGE_season_std,PLAYER_AERIALS_WON_season_std,PLAYER_ASSISTS_season_std,PLAYER_BIG_CHANCES_CREATED_season_std,PLAYER_BIG_CHANCES_MISSED_season_std,PLAYER_BLOCKED_SHOTS_season_std,PLAYER_CAPTAIN_season_std,PLAYER_CLEARANCES_season_std,PLAYER_CLEARANCE_OFFLINE_season_std,PLAYER_DISPOSSESSED_season_std,PLAYER_DRIBBLED_ATTEMPTS_season_std,PLAYER_DRIBBLED_PAST_season_std,PLAYER_DUELS_LOST_season_std,PLAYER_DUELS_WON_season_std,PLAYER_ERROR_LEAD_TO_GOAL_season_std,PLAYER_FOULS_season_std,PLAYER_FOULS_DRAWN_season_std,PLAYER_GOALKEEPER_GOALS_CONCEDED_season_std,PLAYER_GOALS_season_std,PLAYER_GOALS_CONCEDED_season_std,PLAYER_HIT_WOODWORK_season_std,PLAYER_INTERCEPTIONS_season_std,PLAYER_KEY_PASSES_season_std,PLAYER_MINUTES_PLAYED_season_std,PLAYER_OFFSIDES_season_std,PLAYER_OWN_GOALS_season_std,PLAYER_PASSES_season_std,PLAYER_PENALTIES_COMMITTED_season_std,PLAYER_PENALTIES_MISSES_season_std,PLAYER_PENALTIES_SAVED_season_std,PLAYER_PENALTIES_SCORED_season_std,PLAYER_PENALTIES_WON_season_std,PLAYER_RATING_season_std,PLAYER_REDCARDS_season_std,PLAYER_SAVES_season_std,PLAYER_SAVES_INSIDE_BOX_season_std,PLAYER_SHOTS_BLOCKED_season_std,PLAYER_SHOTS_ON_TARGET_season_std,PLAYER_SHOTS_TOTAL_season_std,PLAYER_STARTING_LINEUP_season_std,PLAYER_SUCCESSFUL_DRIBBLES_season_std,PLAYER_TACKLES_season_std,PLAYER_TOTAL_CROSSES_season_std,PLAYER_TOTAL_DUELS_season_std,PLAYER_YELLOWCARDS_season_std,PLAYER_PUNCHES_season_std,PLAYER_LONG_BALLS_season_std,PLAYER_LONG_BALLS_WON_season_std,PLAYER_SHOTS_OFF_TARGET_season_std,PLAYER_ACCURATE_CROSSES_5_last_match_sum,PLAYER_ACCURATE_PASSES_5_last_match_sum,PLAYER_AERIALS_WON_5_last_match_sum,PLAYER_ASSISTS_5_last_match_sum,PLAYER_BIG_CHANCES_CREATED_5_last_match_sum,PLAYER_BIG_CHANCES_MISSED_5_last_match_sum,PLAYER_BLOCKED_SHOTS_5_last_match_sum,PLAYER_CAPTAIN_5_last_match_sum,PLAYER_CLEARANCES_5_last_match_sum,PLAYER_CLEARANCE_OFFLINE_5_last_match_sum,PLAYER_DISPOSSESSED_5_last_match_sum,PLAYER_DRIBBLED_ATTEMPTS_5_last_match_sum,PLAYER_DRIBBLED_PAST_5_last_match_sum,PLAYER_DUELS_LOST_5_last_match_sum,PLAYER_DUELS_WON_5_last_match_sum,PLAYER_ERROR_LEAD_TO_GOAL_5_last_match_sum,PLAYER_FOULS_5_last_match_sum,PLAYER_FOULS_DRAWN_5_last_match_sum,PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_sum,PLAYER_GOALS_5_last_match_sum,PLAYER_GOALS_CONCEDED_5_last_match_sum,PLAYER_HIT_WOODWORK_5_last_match_sum,PLAYER_INTERCEPTIONS_5_last_match_sum,PLAYER_KEY_PASSES_5_last_match_sum,PLAYER_MINUTES_PLAYED_5_last_match_sum,PLAYER_OFFSIDES_5_last_match_sum,PLAYER_OWN_GOALS_5_last_match_sum,PLAYER_PASSES_5_last_match_sum,PLAYER_PENALTIES_COMMITTED_5_last_match_sum,PLAYER_PENALTIES_MISSES_5_last_match_sum,PLAYER_PENALTIES_SAVED_5_last_match_sum,PLAYER_PENALTIES_SCORED_5_last_match_sum,PLAYER_PENALTIES_WON_5_last_match_sum,PLAYER_REDCARDS_5_last_match_sum,PLAYER_SAVES_5_last_match_sum,PLAYER_SAVES_INSIDE_BOX_5_last_match_sum,PLAYER_SHOTS_BLOCKED_5_last_match_sum,PLAYER_SHOTS_ON_TARGET_5_last_match_sum,PLAYER_SHOTS_TOTAL_5_last_match_sum,PLAYER_STARTING_LINEUP_5_last_match_sum,PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_sum,PLAYER_TACKLES_5_last_match_sum,PLAYER_TOTAL_CROSSES_5_last_match_sum,PLAYER_TOTAL_DUELS_5_last_match_sum,PLAYER_YELLOWCARDS_5_last_match_sum,PLAYER_PUNCHES_5_last_match_sum,PLAYER_LONG_BALLS_5_last_match_sum,PLAYER_LONG_BALLS_WON_5_last_match_sum,PLAYER_SHOTS_OFF_TARGET_5_last_match_sum,PLAYER_ACCURATE_CROSSES_5_last_match_average,PLAYER_ACCURATE_PASSES_5_last_match_average,PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_average,PLAYER_AERIALS_WON_5_last_match_average,PLAYER_ASSISTS_5_last_match_average,PLAYER_BIG_CHANCES_CREATED_5_last_match_average,PLAYER_BIG_CHANCES_MISSED_5_last_match_average,PLAYER_BLOCKED_SHOTS_5_last_match_average,PLAYER_CAPTAIN_5_last_match_average,PLAYER_CLEARANCES_5_last_match_average,PLAYER_CLEARANCE_OFFLINE_5_last_match_average,PLAYER_DISPOSSESSED_5_last_match_average,PLAYER_DRIBBLED_ATTEMPTS_5_last_match_average,PLAYER_DRIBBLED_PAST_5_last_match_average,PLAYER_DUELS_LOST_5_last_match_average,PLAYER_DUELS_WON_5_last_match_average,PLAYER_ERROR_LEAD_TO_GOAL_5_last_match_average,PLAYER_FOULS_5_last_match_average,PLAYER_FOULS_DRAWN_5_last_match_average,PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_average,PLAYER_GOALS_5_last_match_average,PLAYER_GOALS_CONCEDED_5_last_match_average,PLAYER_HIT_WOODWORK_5_last_match_average,PLAYER_INTERCEPTIONS_5_last_match_average,PLAYER_KEY_PASSES_5_last_match_average,PLAYER_MINUTES_PLAYED_5_last_match_average,PLAYER_OFFSIDES_5_last_match_average,PLAYER_OWN_GOALS_5_last_match_average,PLAYER_PASSES_5_last_match_average,PLAYER_PENALTIES_COMMITTED_5_last_match_average,PLAYER_PENALTIES_MISSES_5_last_match_average,PLAYER_PENALTIES_SAVED_5_last_match_average,PLAYER_PENALTIES_SCORED_5_last_match_average,PLAYER_PENALTIES_WON_5_last_match_average,PLAYER_RATING_5_last_match_average,PLAYER_REDCARDS_5_last_match_average,PLAYER_SAVES_5_last_match_average,PLAYER_SAVES_INSIDE_BOX_5_last_match_average,PLAYER_SHOTS_BLOCKED_5_last_match_average,PLAYER_SHOTS_ON_TARGET_5_last_match_average,PLAYER_SHOTS_TOTAL_5_last_match_average,PLAYER_STARTING_LINEUP_5_last_match_average,PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_average,PLAYER_TACKLES_5_last_match_average,PLAYER_TOTAL_CROSSES_5_last_match_average,PLAYER_TOTAL_DUELS_5_last_match_average,PLAYER_YELLOWCARDS_5_last_match_average,PLAYER_PUNCHES_5_last_match_average,PLAYER_LONG_BALLS_5_last_match_average,PLAYER_LONG_BALLS_WON_5_last_match_average,PLAYER_SHOTS_OFF_TARGET_5_last_match_average,PLAYER_ACCURATE_CROSSES_5_last_match_std,PLAYER_ACCURATE_PASSES_5_last_match_std,PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_std,PLAYER_AERIALS_WON_5_last_match_std,PLAYER_ASSISTS_5_last_match_std,PLAYER_BIG_CHANCES_CREATED_5_last_match_std,PLAYER_BIG_CHANCES_MISSED_5_last_match_std,PLAYER_BLOCKED_SHOTS_5_last_match_std,PLAYER_CAPTAIN_5_last_match_std,PLAYER_CLEARANCES_5_last_match_std,PLAYER_CLEARANCE_OFFLINE_5_last_match_std,PLAYER_DISPOSSESSED_5_last_match_std,PLAYER_DRIBBLED_ATTEMPTS_5_last_match_std,PLAYER_DRIBBLED_PAST_5_last_match_std,PLAYER_DUELS_LOST_5_last_match_std,PLAYER_DUELS_WON_5_last_match_std,PLAYER_ERROR_LEAD_TO_GOAL_5_last_match_std,PLAYER_FOULS_5_last_match_std,PLAYER_FOULS_DRAWN_5_last_match_std,PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_std,PLAYER_GOALS_5_last_match_std,PLAYER_GOALS_CONCEDED_5_last_match_std,PLAYER_HIT_WOODWORK_5_last_match_std,PLAYER_INTERCEPTIONS_5_last_match_std,PLAYER_KEY_PASSES_5_last_match_std,PLAYER_MINUTES_PLAYED_5_last_match_std,PLAYER_OFFSIDES_5_last_match_std,PLAYER_OWN_GOALS_5_last_match_std,PLAYER_PASSES_5_last_match_std,PLAYER_PENALTIES_COMMITTED_5_last_match_std,PLAYER_PENALTIES_MISSES_5_last_match_std,PLAYER_PENALTIES_SAVED_5_last_match_std,PLAYER_PENALTIES_SCORED_5_last_match_std,PLAYER_PENALTIES_WON_5_last_match_std,PLAYER_RATING_5_last_match_std,PLAYER_REDCARDS_5_last_match_std,PLAYER_SAVES_5_last_match_std,PLAYER_SAVES_INSIDE_BOX_5_last_match_std,PLAYER_SHOTS_BLOCKED_5_last_match_std,PLAYER_SHOTS_ON_TARGET_5_last_match_std,PLAYER_SHOTS_TOTAL_5_last_match_std,PLAYER_STARTING_LINEUP_5_last_match_std,PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_std,PLAYER_TACKLES_5_last_match_std,PLAYER_TOTAL_CROSSES_5_last_match_std,PLAYER_TOTAL_DUELS_5_last_match_std,PLAYER_YELLOWCARDS_5_last_match_std,PLAYER_PUNCHES_5_last_match_std,PLAYER_LONG_BALLS_5_last_match_std,PLAYER_LONG_BALLS_WON_5_last_match_std,PLAYER_SHOTS_OFF_TARGET_5_last_match_std
0,0,Ligue 1,Olympique Marseille,defender,Lucas Perrin,0.00,19.00,20.00,0.00,0.00,12.00,6.00,NaN,18.00,0.00,0.00,5.00,23.00,20.00,23.00,0.00,28.00,13.00,0.00,0.00,16.00,0.00,34.00,0.00,23.00,0.00,0.00,20.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,6.00,0.00,4.00,23.00,12.00,9.00,0.00,23.00,40.00,NaN,NaN,NaN,NaN,0.00,53.00,85.00,57.00,0.00,0.00,25.00,17.00,NaN,44.00,0.00,0.00,9.00,55.00,61.00,59.00,0.00,56.00,30.00,0.00,0.00,25.00,0.00,62.00,0.00,75.00,0.00,0.00,56.00,0.00,0.00,0.00,0.00,0.00,65.00,0.00,0.00,0.00,20.00,0.00,9.00,75.00,16.00,31.00,0.00,70.00,50.00,NaN,NaN,NaN,NaN,0.00,67.00,12.00,71.00,0.00,0.00,32.00,30.00,NaN,59.00,0.00,0.00,19.00,50.00,62.00,63.00,0.00,55.00,33.00,0.00,0.00,49.00,0.00,67.00,0.00,70.00,0.00,0.00,71.00,0.00,0.00,0.00,0.00,0.00,64.00,0.00,0.00,0.00,30.00,0.00,41.00,70.00,33.00,51.00,0.00,79.00,99.00,NaN,NaN,NaN,NaN,0.00,39.00,40.00,0.00,0.00,14.00,12.00,NaN,35.00,0.00,0.00,7.00,35.00,42.00,42.00,0.00,52.00,25.00,0.00,0.00,30.00,0.00,66.00,0.00,60.00,0.00,0.00,41.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,12.00,0.00,7.00,60.00,13.00,20.00,0.00,52.00,50.00,NaN,NaN,NaN,NaN,0.00,49.00,85.00,50.00,0.00,0.00,17.00,15.00,NaN,44.00,0.00,0.00,9.00,44.00,53.00,53.00,0.00,56.00,31.00,0.00,0.00,25.00,0.00,62.00,0.00,75.00,0.00,0.00,52.00,0.00,0.00,0.00,0.00,0.00,61.00,0.00,0.00,0.00,15.00,0.00,9.00,75.00,16.00,26.00,0.00,66.00,50.00,NaN,NaN,NaN,NaN,0.00,60.00,9.00,60.00,0.00,0.00,29.00,27.00,NaN,42.00,0.00,0.00,19.00,46.00,83.00,63.00,0.00,55.00,33.00,0.00,0.00,49.00,0.00,67.00,0.00,70.00,0.00,0.00,60.00,0.00,0.00,0.00,0.00,0.00,64.00,0.00,0.00,0.00,24.00,0.00,32.00,70.00,30.00,46.00,0.00,79.00,99.00,NaN,NaN,NaN,NaN
1,0,Ligue 1,Olympique Marseille,midfielder,Kevin Strootman,2.00,48.00,19.00,28.00,8.00,12.00,6.00,NaN,21.00,0.00,4.00,3.00,47.00,39.00,37.00,0.00,56.00,18.00,0.00,11.00,52.00,25.00,24.00,24.00,72.00,6.00,0.00,51.00,0.00,0.00,0.00,33.00,0.00,0.00,0.00,0.00,20.00,5.00,16.00,69.00,4.00,40.00,3.00,41.00,80.00,NaN,NaN,NaN,NaN,2.00,44.00,79.00,17.00,16.00,8.00,8.00,5.00,NaN,17.00,0.00,4.00,2.00,37.00,39.00,31.00,0.00,37.00,14.00,0.00,10.00,27.00,20.00,14.00,21.00,78.00,7.00,0.00,47.00,0.00,0.00,0.00,33.00,0.00,79.00,0.00,0.00,0.00,20.00,3.00,10.00,75.00,1.00,43.00,2.00,41.00,33.00,NaN,NaN,NaN,NaN,12.00,48.00,41.00,37.00,40.00,25.00,18.00,17.00,NaN,36.00,0.00,24.00,8.00,44.00,32.00,41.00,0.00,40.00,34.00,0.00,31.00,45.00,45.00,25.00,34.00,53.00,23.00,0.00,50.00,0.00,0.00,0.00,63.00,0.00,37.00,0.00,0.00,0.00,27.00,14.00,33.00,63.00,10.00,43.00,12.00,41.00,85.00,NaN,NaN,NaN,NaN,0.00,32.00,0.00,16.00,0.00,0.00,0.00,NaN,20.00,0.00,9.00,2.00,35.00,34.00,14.00,0.00,47.00,10.00,0.00,20.00,46.00,0.00,6.00,13.00,65.00,12.00,0.00,35.00,0.00,0.00,0.00,100.00,0.00,0.00,0.00,0.00,12.00,7.00,7.00,60.00,0.00,29.00,2.00,30.00,25.00,NaN,NaN,NaN,NaN,0.00,32.00,75.00,0.00,16.00,0.00,0.00,0.00,NaN,20.00,0.00,9.00,2.00,35.00,34.00,14.00,0.00,40.00,10.00,0.00,20.00,30.00,0.00,5.00,13.00,65.00,12.00,0.00,35.00,0.00,0.00,0.00,100.00,0.00,65.00,0.00,0.00,0.00,12.00,7.00,7.00,60.00,0.00,29.00,1.00,30.00,20.00,NaN,NaN,NaN,NaN,0.00,46.00,41.00,0.00,40.00,0.00,0.00,0.00,NaN,37.00,0.00,32.00,9.00,52.00,58.00,29.00,0.00,43.00,18.00,0.00,50.00,57.00,0.00,12.00,18.00,67.00,34.00,0.00,47.00,0.00,0.00,0.00,99.00,0.00,57.00,0.00,0.00,0.00,21.00,20.00,17.00,77.00,0.00,40.00,6.00,46.00,77.00,NaN,NaN,NaN,NaN
2,0,Ligue 1,Olympique Marseille,goalkeeper,Yohann Pelé,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,68.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,0.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,32.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,0.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,45.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,69.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,0.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,45.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,0.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,57.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN
3,0,Ligue 1,Olympique Marseille,defender,Abdallah Ali Mohamed,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,4.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,0.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,25.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,7.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,0.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,25.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,Ligue 1,Olympique Marseille,NaN,Nemanja Radonjic,8.00,11.00,4.00,0.00,0.00,12.00,0.00,NaN,6.00,0.00,19.00,27.00,9.00,25.00,24.00,0.00,31.00,18.00,0.00,0.00,60.00,25.00,6.00,10.00,28.00,6.00,0.00,14.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,13.00,17.00,16.00,23.00,44.00,9.00,6.00,27.00,20.00,NaN,NaN,NaN,NaN,6.00,9.00,68.00,3.00,0.00,0.00,7.00,0.00,NaN,4.00,0.00,17.00,15.00,6.00,23.00,19.00,0.00,19.00,12.00,0.00,0.00,28.00,19.00,3.00,8.00,28.00,6.00,0.00,12.00,0.00,0.00,0.00,0.00,0.00,51.00,0.00,0.00,0.00,12.00,8.00,9.00,23.00,18.00,9.00,4.00,24.00,7.00,NaN,NaN,NaN,NaN,18.00,22.00,47.00,9.00,0.00,0.00,18.00,0.00,NaN,12.00,0.00,51.00,54.00,22.00,38.00,38.00,0.00,33.00,26.00,0.00,0.00,46.00,43.00,15.00,22.00,47.00,22.00,0.00,26.00,0.00,0.00,0.00,0.00,0.00,62.00,0.00,0.00,0.00,34.00,22.00,40.00,62.00,54.00,17.00,15.00,47.00,48.00,NaN,NaN,NaN,NaN,12.00,10.00,2.00,0.00,0.00,14.00,0.00,NaN,0.00,0.00,23.00,27.00,0.00,23.00,23.00,0.00,23.00,20.00,0.00,0.00,69.00,33.00,0.00,13.00,38.00,12.00,0.00,13.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,15.00,14.00,40.00,30.00,12.00,6.00,29.00,0.00,NaN,NaN,NaN,NaN,11.00,10.00,70.00,2.00,0.00,0.00,14.00,0.00,NaN,0.00,0.00,23.00,27.00,0.00,23.00,23.00,0.00,20.00,20.00,0.00,0.00,45.00,33.00,0.00,13.00,38.00,12.00,0.00,13.00,0.00,0.00,0.00,0.00,0.00,48.00,0.00,0.00,0.00,0.00,15.00,14.00,40.00,30.00,12.00,4.00,29.00,0.00,NaN,NaN,NaN,NaN,15.00,23.00,42.00,8.00,0.00,0.00,26.00,0.00,NaN,0.00,0.00,51.00,79.00,0.00,61.00,57.00,0.00,42.00,37.00,0.00,0.00,57.00,50.00,0.00,30.00,64.00,34.00,0.00,27.00,0.00,0.00,0.00,0.00,0.00,68.00,0.00,0.00,0.00,0.00,25.00,42.00,77.00,69.00,21.00,13.00,66.00,0.00,NaN,NaN,NaN,NaN

Data Types

float64    302
object       4
int64        1
Name: count, dtype: int64

Memory Usage
599.54 MB
================================================================================
Y TRAIN
================================================================================
Rows    : 12,303
Columns : 4

First 5 rows

   ID  HOME_WINS  DRAW  AWAY_WINS
0   0          0     0          1
1   1          0     1          0
2   2          0     0          1
3   3          1     0          0
4   4          0     1          0

Data Types

int64    4
Name: count, dtype: int64

Memory Usage
0.38 MB
================================================================================
Y TRAIN SUPPLEMENT
================================================================================
Rows    : 12,303
Columns : 2

First 5 rows

   ID  GOAL_DIFF_HOME_AWAY
0   0                -2.00
1   1                 0.00
2   2                -1.00
3   3                 1.00
4   4                 0.00

Data Types

int64      1
float64    1
Name: count, dtype: int64

Memory Usage
0.19 MB

In [12]:
# Column Inspection
for col in home_team.columns:
    print(col)

ID
LEAGUE
TEAM_NAME
TEAM_SHOTS_TOTAL_season_sum
TEAM_SHOTS_INSIDEBOX_season_sum
TEAM_SHOTS_OFF_TARGET_season_sum
TEAM_SHOTS_ON_TARGET_season_sum
TEAM_SHOTS_OUTSIDEBOX_season_sum
TEAM_PASSES_season_sum
TEAM_SUCCESSFUL_PASSES_season_sum
TEAM_SAVES_season_sum
TEAM_CORNERS_season_sum
TEAM_FOULS_season_sum
TEAM_YELLOWCARDS_season_sum
TEAM_REDCARDS_season_sum
TEAM_OFFSIDES_season_sum
TEAM_ATTACKS_season_sum
TEAM_PENALTIES_season_sum
TEAM_SUBSTITUTIONS_season_sum
TEAM_BALL_SAFE_season_sum
TEAM_DANGEROUS_ATTACKS_season_sum
TEAM_INJURIES_season_sum
TEAM_GOALS_season_sum
TEAM_GAME_WON_season_sum
TEAM_GAME_DRAW_season_sum
TEAM_GAME_LOST_season_sum
TEAM_SHOTS_TOTAL_season_average
TEAM_SHOTS_INSIDEBOX_season_average
TEAM_SHOTS_OFF_TARGET_season_average
TEAM_SHOTS_ON_TARGET_season_average
TEAM_SHOTS_OUTSIDEBOX_season_average
TEAM_PASSES_season_average
TEAM_SUCCESSFUL_PASSES_season_average
TEAM_SUCCESSFUL_PASSES_PERCENTAGE_season_average
TEAM_SAVES_season_average
TEAM_CORNERS_season_average
TEAM_BALL_POSSESSION_season_average
TEAM_FOULS_season_average
TEAM_YELLOWCARDS_season_average
TEAM_REDCARDS_season_average
TEAM_OFFSIDES_season_average
TEAM_ATTACKS_season_average
TEAM_PENALTIES_season_average
TEAM_SUBSTITUTIONS_season_average
TEAM_BALL_SAFE_season_average
TEAM_DANGEROUS_ATTACKS_season_average
TEAM_INJURIES_season_average
TEAM_GOALS_season_average
TEAM_GAME_WON_season_average
TEAM_GAME_DRAW_season_average
TEAM_GAME_LOST_season_average
TEAM_SHOTS_TOTAL_season_std
TEAM_SHOTS_INSIDEBOX_season_std
TEAM_SHOTS_OFF_TARGET_season_std
TEAM_SHOTS_ON_TARGET_season_std
TEAM_SHOTS_OUTSIDEBOX_season_std
TEAM_PASSES_season_std
TEAM_SUCCESSFUL_PASSES_season_std
TEAM_SUCCESSFUL_PASSES_PERCENTAGE_season_std
TEAM_SAVES_season_std
TEAM_CORNERS_season_std
TEAM_BALL_POSSESSION_season_std
TEAM_FOULS_season_std
TEAM_YELLOWCARDS_season_std
TEAM_REDCARDS_season_std
TEAM_OFFSIDES_season_std
TEAM_ATTACKS_season_std
TEAM_PENALTIES_season_std
TEAM_SUBSTITUTIONS_season_std
TEAM_BALL_SAFE_season_std
TEAM_DANGEROUS_ATTACKS_season_std
TEAM_INJURIES_season_std
TEAM_GOALS_season_std
TEAM_SHOTS_TOTAL_5_last_match_sum
TEAM_SHOTS_INSIDEBOX_5_last_match_sum
TEAM_SHOTS_OFF_TARGET_5_last_match_sum
TEAM_SHOTS_ON_TARGET_5_last_match_sum
TEAM_SHOTS_OUTSIDEBOX_5_last_match_sum
TEAM_PASSES_5_last_match_sum
TEAM_SUCCESSFUL_PASSES_5_last_match_sum
TEAM_SAVES_5_last_match_sum
TEAM_CORNERS_5_last_match_sum
TEAM_FOULS_5_last_match_sum
TEAM_YELLOWCARDS_5_last_match_sum
TEAM_REDCARDS_5_last_match_sum
TEAM_OFFSIDES_5_last_match_sum
TEAM_ATTACKS_5_last_match_sum
TEAM_PENALTIES_5_last_match_sum
TEAM_SUBSTITUTIONS_5_last_match_sum
TEAM_BALL_SAFE_5_last_match_sum
TEAM_DANGEROUS_ATTACKS_5_last_match_sum
TEAM_INJURIES_5_last_match_sum
TEAM_GOALS_5_last_match_sum
TEAM_GAME_WON_5_last_match_sum
TEAM_GAME_DRAW_5_last_match_sum
TEAM_GAME_LOST_5_last_match_sum
TEAM_SHOTS_TOTAL_5_last_match_average
TEAM_SHOTS_INSIDEBOX_5_last_match_average
TEAM_SHOTS_OFF_TARGET_5_last_match_average
TEAM_SHOTS_ON_TARGET_5_last_match_average
TEAM_SHOTS_OUTSIDEBOX_5_last_match_average
TEAM_PASSES_5_last_match_average
TEAM_SUCCESSFUL_PASSES_5_last_match_average
TEAM_SUCCESSFUL_PASSES_PERCENTAGE_5_last_match_average
TEAM_SAVES_5_last_match_average
TEAM_CORNERS_5_last_match_average
TEAM_BALL_POSSESSION_5_last_match_average
TEAM_FOULS_5_last_match_average
TEAM_YELLOWCARDS_5_last_match_average
TEAM_REDCARDS_5_last_match_average
TEAM_OFFSIDES_5_last_match_average
TEAM_ATTACKS_5_last_match_average
TEAM_PENALTIES_5_last_match_average
TEAM_SUBSTITUTIONS_5_last_match_average
TEAM_BALL_SAFE_5_last_match_average
TEAM_DANGEROUS_ATTACKS_5_last_match_average
TEAM_INJURIES_5_last_match_average
TEAM_GOALS_5_last_match_average
TEAM_GAME_WON_5_last_match_average
TEAM_GAME_DRAW_5_last_match_average
TEAM_GAME_LOST_5_last_match_average
TEAM_SHOTS_TOTAL_5_last_match_std
TEAM_SHOTS_INSIDEBOX_5_last_match_std
TEAM_SHOTS_OFF_TARGET_5_last_match_std
TEAM_SHOTS_ON_TARGET_5_last_match_std
TEAM_SHOTS_OUTSIDEBOX_5_last_match_std
TEAM_PASSES_5_last_match_std
TEAM_SUCCESSFUL_PASSES_5_last_match_std
TEAM_SUCCESSFUL_PASSES_PERCENTAGE_5_last_match_std
TEAM_SAVES_5_last_match_std
TEAM_CORNERS_5_last_match_std
TEAM_BALL_POSSESSION_5_last_match_std
TEAM_FOULS_5_last_match_std
TEAM_YELLOWCARDS_5_last_match_std
TEAM_REDCARDS_5_last_match_std
TEAM_OFFSIDES_5_last_match_std
TEAM_ATTACKS_5_last_match_std
TEAM_PENALTIES_5_last_match_std
TEAM_SUBSTITUTIONS_5_last_match_std
TEAM_BALL_SAFE_5_last_match_std
TEAM_DANGEROUS_ATTACKS_5_last_match_std
TEAM_INJURIES_5_last_match_std
TEAM_GOALS_5_last_match_std

In [13]:
for col in away_team.columns:
    print(col)

ID
LEAGUE
TEAM_NAME
TEAM_SHOTS_TOTAL_season_sum
TEAM_SHOTS_INSIDEBOX_season_sum
TEAM_SHOTS_OFF_TARGET_season_sum
TEAM_SHOTS_ON_TARGET_season_sum
TEAM_SHOTS_OUTSIDEBOX_season_sum
TEAM_PASSES_season_sum
TEAM_SUCCESSFUL_PASSES_season_sum
TEAM_SAVES_season_sum
TEAM_CORNERS_season_sum
TEAM_FOULS_season_sum
TEAM_YELLOWCARDS_season_sum
TEAM_REDCARDS_season_sum
TEAM_OFFSIDES_season_sum
TEAM_ATTACKS_season_sum
TEAM_PENALTIES_season_sum
TEAM_SUBSTITUTIONS_season_sum
TEAM_BALL_SAFE_season_sum
TEAM_DANGEROUS_ATTACKS_season_sum
TEAM_INJURIES_season_sum
TEAM_GOALS_season_sum
TEAM_GAME_WON_season_sum
TEAM_GAME_DRAW_season_sum
TEAM_GAME_LOST_season_sum
TEAM_SHOTS_TOTAL_season_average
TEAM_SHOTS_INSIDEBOX_season_average
TEAM_SHOTS_OFF_TARGET_season_average
TEAM_SHOTS_ON_TARGET_season_average
TEAM_SHOTS_OUTSIDEBOX_season_average
TEAM_PASSES_season_average
TEAM_SUCCESSFUL_PASSES_season_average
TEAM_SUCCESSFUL_PASSES_PERCENTAGE_season_average
TEAM_SAVES_season_average
TEAM_CORNERS_season_average
TEAM_BALL_POSSESSION_season_average
TEAM_FOULS_season_average
TEAM_YELLOWCARDS_season_average
TEAM_REDCARDS_season_average
TEAM_OFFSIDES_season_average
TEAM_ATTACKS_season_average
TEAM_PENALTIES_season_average
TEAM_SUBSTITUTIONS_season_average
TEAM_BALL_SAFE_season_average
TEAM_DANGEROUS_ATTACKS_season_average
TEAM_INJURIES_season_average
TEAM_GOALS_season_average
TEAM_GAME_WON_season_average
TEAM_GAME_DRAW_season_average
TEAM_GAME_LOST_season_average
TEAM_SHOTS_TOTAL_season_std
TEAM_SHOTS_INSIDEBOX_season_std
TEAM_SHOTS_OFF_TARGET_season_std
TEAM_SHOTS_ON_TARGET_season_std
TEAM_SHOTS_OUTSIDEBOX_season_std
TEAM_PASSES_season_std
TEAM_SUCCESSFUL_PASSES_season_std
TEAM_SUCCESSFUL_PASSES_PERCENTAGE_season_std
TEAM_SAVES_season_std
TEAM_CORNERS_season_std
TEAM_BALL_POSSESSION_season_std
TEAM_FOULS_season_std
TEAM_YELLOWCARDS_season_std
TEAM_REDCARDS_season_std
TEAM_OFFSIDES_season_std
TEAM_ATTACKS_season_std
TEAM_PENALTIES_season_std
TEAM_SUBSTITUTIONS_season_std
TEAM_BALL_SAFE_season_std
TEAM_DANGEROUS_ATTACKS_season_std
TEAM_INJURIES_season_std
TEAM_GOALS_season_std
TEAM_SHOTS_TOTAL_5_last_match_sum
TEAM_SHOTS_INSIDEBOX_5_last_match_sum
TEAM_SHOTS_OFF_TARGET_5_last_match_sum
TEAM_SHOTS_ON_TARGET_5_last_match_sum
TEAM_SHOTS_OUTSIDEBOX_5_last_match_sum
TEAM_PASSES_5_last_match_sum
TEAM_SUCCESSFUL_PASSES_5_last_match_sum
TEAM_SAVES_5_last_match_sum
TEAM_CORNERS_5_last_match_sum
TEAM_FOULS_5_last_match_sum
TEAM_YELLOWCARDS_5_last_match_sum
TEAM_REDCARDS_5_last_match_sum
TEAM_OFFSIDES_5_last_match_sum
TEAM_ATTACKS_5_last_match_sum
TEAM_PENALTIES_5_last_match_sum
TEAM_SUBSTITUTIONS_5_last_match_sum
TEAM_BALL_SAFE_5_last_match_sum
TEAM_DANGEROUS_ATTACKS_5_last_match_sum
TEAM_INJURIES_5_last_match_sum
TEAM_GOALS_5_last_match_sum
TEAM_GAME_WON_5_last_match_sum
TEAM_GAME_DRAW_5_last_match_sum
TEAM_GAME_LOST_5_last_match_sum
TEAM_SHOTS_TOTAL_5_last_match_average
TEAM_SHOTS_INSIDEBOX_5_last_match_average
TEAM_SHOTS_OFF_TARGET_5_last_match_average
TEAM_SHOTS_ON_TARGET_5_last_match_average
TEAM_SHOTS_OUTSIDEBOX_5_last_match_average
TEAM_PASSES_5_last_match_average
TEAM_SUCCESSFUL_PASSES_5_last_match_average
TEAM_SUCCESSFUL_PASSES_PERCENTAGE_5_last_match_average
TEAM_SAVES_5_last_match_average
TEAM_CORNERS_5_last_match_average
TEAM_BALL_POSSESSION_5_last_match_average
TEAM_FOULS_5_last_match_average
TEAM_YELLOWCARDS_5_last_match_average
TEAM_REDCARDS_5_last_match_average
TEAM_OFFSIDES_5_last_match_average
TEAM_ATTACKS_5_last_match_average
TEAM_PENALTIES_5_last_match_average
TEAM_SUBSTITUTIONS_5_last_match_average
TEAM_BALL_SAFE_5_last_match_average
TEAM_DANGEROUS_ATTACKS_5_last_match_average
TEAM_INJURIES_5_last_match_average
TEAM_GOALS_5_last_match_average
TEAM_GAME_WON_5_last_match_average
TEAM_GAME_DRAW_5_last_match_average
TEAM_GAME_LOST_5_last_match_average
TEAM_SHOTS_TOTAL_5_last_match_std
TEAM_SHOTS_INSIDEBOX_5_last_match_std
TEAM_SHOTS_OFF_TARGET_5_last_match_std
TEAM_SHOTS_ON_TARGET_5_last_match_std
TEAM_SHOTS_OUTSIDEBOX_5_last_match_std
TEAM_PASSES_5_last_match_std
TEAM_SUCCESSFUL_PASSES_5_last_match_std
TEAM_SUCCESSFUL_PASSES_PERCENTAGE_5_last_match_std
TEAM_SAVES_5_last_match_std
TEAM_CORNERS_5_last_match_std
TEAM_BALL_POSSESSION_5_last_match_std
TEAM_FOULS_5_last_match_std
TEAM_YELLOWCARDS_5_last_match_std
TEAM_REDCARDS_5_last_match_std
TEAM_OFFSIDES_5_last_match_std
TEAM_ATTACKS_5_last_match_std
TEAM_PENALTIES_5_last_match_std
TEAM_SUBSTITUTIONS_5_last_match_std
TEAM_BALL_SAFE_5_last_match_std
TEAM_DANGEROUS_ATTACKS_5_last_match_std
TEAM_INJURIES_5_last_match_std
TEAM_GOALS_5_last_match_std

In [14]:
for col in home_player.columns:
    print(col)

ID
LEAGUE
TEAM_NAME
POSITION
PLAYER_NAME
PLAYER_ACCURATE_CROSSES_season_sum
PLAYER_ACCURATE_PASSES_season_sum
PLAYER_AERIALS_WON_season_sum
PLAYER_ASSISTS_season_sum
PLAYER_BIG_CHANCES_CREATED_season_sum
PLAYER_BIG_CHANCES_MISSED_season_sum
PLAYER_BLOCKED_SHOTS_season_sum
PLAYER_CAPTAIN_season_sum
PLAYER_CLEARANCES_season_sum
PLAYER_CLEARANCE_OFFLINE_season_sum
PLAYER_DISPOSSESSED_season_sum
PLAYER_DRIBBLED_ATTEMPTS_season_sum
PLAYER_DRIBBLED_PAST_season_sum
PLAYER_DUELS_LOST_season_sum
PLAYER_DUELS_WON_season_sum
PLAYER_ERROR_LEAD_TO_GOAL_season_sum
PLAYER_FOULS_season_sum
PLAYER_FOULS_DRAWN_season_sum
PLAYER_GOALKEEPER_GOALS_CONCEDED_season_sum
PLAYER_GOALS_season_sum
PLAYER_GOALS_CONCEDED_season_sum
PLAYER_HIT_WOODWORK_season_sum
PLAYER_INTERCEPTIONS_season_sum
PLAYER_KEY_PASSES_season_sum
PLAYER_MINUTES_PLAYED_season_sum
PLAYER_OFFSIDES_season_sum
PLAYER_OWN_GOALS_season_sum
PLAYER_PASSES_season_sum
PLAYER_PENALTIES_COMMITTED_season_sum
PLAYER_PENALTIES_MISSES_season_sum
PLAYER_PENALTIES_SAVED_season_sum
PLAYER_PENALTIES_SCORED_season_sum
PLAYER_PENALTIES_WON_season_sum
PLAYER_REDCARDS_season_sum
PLAYER_SAVES_season_sum
PLAYER_SAVES_INSIDE_BOX_season_sum
PLAYER_SHOTS_BLOCKED_season_sum
PLAYER_SHOTS_ON_TARGET_season_sum
PLAYER_SHOTS_TOTAL_season_sum
PLAYER_STARTING_LINEUP_season_sum
PLAYER_SUCCESSFUL_DRIBBLES_season_sum
PLAYER_TACKLES_season_sum
PLAYER_TOTAL_CROSSES_season_sum
PLAYER_TOTAL_DUELS_season_sum
PLAYER_YELLOWCARDS_season_sum
PLAYER_PUNCHES_season_sum
PLAYER_LONG_BALLS_season_sum
PLAYER_LONG_BALLS_WON_season_sum
PLAYER_SHOTS_OFF_TARGET_season_sum
PLAYER_ACCURATE_CROSSES_season_average
PLAYER_ACCURATE_PASSES_season_average
PLAYER_ACCURATE_PASSES_PERCENTAGE_season_average
PLAYER_AERIALS_WON_season_average
PLAYER_ASSISTS_season_average
PLAYER_BIG_CHANCES_CREATED_season_average
PLAYER_BIG_CHANCES_MISSED_season_average
PLAYER_BLOCKED_SHOTS_season_average
PLAYER_CAPTAIN_season_average
PLAYER_CLEARANCES_season_average
PLAYER_CLEARANCE_OFFLINE_season_average
PLAYER_DISPOSSESSED_season_average
PLAYER_DRIBBLED_ATTEMPTS_season_average
PLAYER_DRIBBLED_PAST_season_average
PLAYER_DUELS_LOST_season_average
PLAYER_DUELS_WON_season_average
PLAYER_ERROR_LEAD_TO_GOAL_season_average
PLAYER_FOULS_season_average
PLAYER_FOULS_DRAWN_season_average
PLAYER_GOALKEEPER_GOALS_CONCEDED_season_average
PLAYER_GOALS_season_average
PLAYER_GOALS_CONCEDED_season_average
PLAYER_HIT_WOODWORK_season_average
PLAYER_INTERCEPTIONS_season_average
PLAYER_KEY_PASSES_season_average
PLAYER_MINUTES_PLAYED_season_average
PLAYER_OFFSIDES_season_average
PLAYER_OWN_GOALS_season_average
PLAYER_PASSES_season_average
PLAYER_PENALTIES_COMMITTED_season_average
PLAYER_PENALTIES_MISSES_season_average
PLAYER_PENALTIES_SAVED_season_average
PLAYER_PENALTIES_SCORED_season_average
PLAYER_PENALTIES_WON_season_average
PLAYER_RATING_season_average
PLAYER_REDCARDS_season_average
PLAYER_SAVES_season_average
PLAYER_SAVES_INSIDE_BOX_season_average
PLAYER_SHOTS_BLOCKED_season_average
PLAYER_SHOTS_ON_TARGET_season_average
PLAYER_SHOTS_TOTAL_season_average
PLAYER_STARTING_LINEUP_season_average
PLAYER_SUCCESSFUL_DRIBBLES_season_average
PLAYER_TACKLES_season_average
PLAYER_TOTAL_CROSSES_season_average
PLAYER_TOTAL_DUELS_season_average
PLAYER_YELLOWCARDS_season_average
PLAYER_PUNCHES_season_average
PLAYER_LONG_BALLS_season_average
PLAYER_LONG_BALLS_WON_season_average
PLAYER_SHOTS_OFF_TARGET_season_average
PLAYER_ACCURATE_CROSSES_season_std
PLAYER_ACCURATE_PASSES_season_std
PLAYER_ACCURATE_PASSES_PERCENTAGE_season_std
PLAYER_AERIALS_WON_season_std
PLAYER_ASSISTS_season_std
PLAYER_BIG_CHANCES_CREATED_season_std
PLAYER_BIG_CHANCES_MISSED_season_std
PLAYER_BLOCKED_SHOTS_season_std
PLAYER_CAPTAIN_season_std
PLAYER_CLEARANCES_season_std
PLAYER_CLEARANCE_OFFLINE_season_std
PLAYER_DISPOSSESSED_season_std
PLAYER_DRIBBLED_ATTEMPTS_season_std
PLAYER_DRIBBLED_PAST_season_std
PLAYER_DUELS_LOST_season_std
PLAYER_DUELS_WON_season_std
PLAYER_ERROR_LEAD_TO_GOAL_season_std
PLAYER_FOULS_season_std
PLAYER_FOULS_DRAWN_season_std
PLAYER_GOALKEEPER_GOALS_CONCEDED_season_std
PLAYER_GOALS_season_std
PLAYER_GOALS_CONCEDED_season_std
PLAYER_HIT_WOODWORK_season_std
PLAYER_INTERCEPTIONS_season_std
PLAYER_KEY_PASSES_season_std
PLAYER_MINUTES_PLAYED_season_std
PLAYER_OFFSIDES_season_std
PLAYER_OWN_GOALS_season_std
PLAYER_PASSES_season_std
PLAYER_PENALTIES_COMMITTED_season_std
PLAYER_PENALTIES_MISSES_season_std
PLAYER_PENALTIES_SAVED_season_std
PLAYER_PENALTIES_SCORED_season_std
PLAYER_PENALTIES_WON_season_std
PLAYER_RATING_season_std
PLAYER_REDCARDS_season_std
PLAYER_SAVES_season_std
PLAYER_SAVES_INSIDE_BOX_season_std
PLAYER_SHOTS_BLOCKED_season_std
PLAYER_SHOTS_ON_TARGET_season_std
PLAYER_SHOTS_TOTAL_season_std
PLAYER_STARTING_LINEUP_season_std
PLAYER_SUCCESSFUL_DRIBBLES_season_std
PLAYER_TACKLES_season_std
PLAYER_TOTAL_CROSSES_season_std
PLAYER_TOTAL_DUELS_season_std
PLAYER_YELLOWCARDS_season_std
PLAYER_PUNCHES_season_std
PLAYER_LONG_BALLS_season_std
PLAYER_LONG_BALLS_WON_season_std
PLAYER_SHOTS_OFF_TARGET_season_std
PLAYER_ACCURATE_CROSSES_5_last_match_sum
PLAYER_ACCURATE_PASSES_5_last_match_sum
PLAYER_AERIALS_WON_5_last_match_sum
PLAYER_ASSISTS_5_last_match_sum
PLAYER_BIG_CHANCES_CREATED_5_last_match_sum
PLAYER_BIG_CHANCES_MISSED_5_last_match_sum
PLAYER_BLOCKED_SHOTS_5_last_match_sum
PLAYER_CAPTAIN_5_last_match_sum
PLAYER_CLEARANCES_5_last_match_sum
PLAYER_CLEARANCE_OFFLINE_5_last_match_sum
PLAYER_DISPOSSESSED_5_last_match_sum
PLAYER_DRIBBLED_ATTEMPTS_5_last_match_sum
PLAYER_DRIBBLED_PAST_5_last_match_sum
PLAYER_DUELS_LOST_5_last_match_sum
PLAYER_DUELS_WON_5_last_match_sum
PLAYER_ERROR_LEAD_TO_GOAL_5_last_match_sum
PLAYER_FOULS_5_last_match_sum
PLAYER_FOULS_DRAWN_5_last_match_sum
PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_sum
PLAYER_GOALS_5_last_match_sum
PLAYER_GOALS_CONCEDED_5_last_match_sum
PLAYER_HIT_WOODWORK_5_last_match_sum
PLAYER_INTERCEPTIONS_5_last_match_sum
PLAYER_KEY_PASSES_5_last_match_sum
PLAYER_MINUTES_PLAYED_5_last_match_sum
PLAYER_OFFSIDES_5_last_match_sum
PLAYER_OWN_GOALS_5_last_match_sum
PLAYER_PASSES_5_last_match_sum
PLAYER_PENALTIES_COMMITTED_5_last_match_sum
PLAYER_PENALTIES_MISSES_5_last_match_sum
PLAYER_PENALTIES_SAVED_5_last_match_sum
PLAYER_PENALTIES_SCORED_5_last_match_sum
PLAYER_PENALTIES_WON_5_last_match_sum
PLAYER_REDCARDS_5_last_match_sum
PLAYER_SAVES_5_last_match_sum
PLAYER_SAVES_INSIDE_BOX_5_last_match_sum
PLAYER_SHOTS_BLOCKED_5_last_match_sum
PLAYER_SHOTS_ON_TARGET_5_last_match_sum
PLAYER_SHOTS_TOTAL_5_last_match_sum
PLAYER_STARTING_LINEUP_5_last_match_sum
PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_sum
PLAYER_TACKLES_5_last_match_sum
PLAYER_TOTAL_CROSSES_5_last_match_sum
PLAYER_TOTAL_DUELS_5_last_match_sum
PLAYER_YELLOWCARDS_5_last_match_sum
PLAYER_PUNCHES_5_last_match_sum
PLAYER_LONG_BALLS_5_last_match_sum
PLAYER_LONG_BALLS_WON_5_last_match_sum
PLAYER_SHOTS_OFF_TARGET_5_last_match_sum
PLAYER_ACCURATE_CROSSES_5_last_match_average
PLAYER_ACCURATE_PASSES_5_last_match_average
PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_average
PLAYER_AERIALS_WON_5_last_match_average
PLAYER_ASSISTS_5_last_match_average
PLAYER_BIG_CHANCES_CREATED_5_last_match_average
PLAYER_BIG_CHANCES_MISSED_5_last_match_average
PLAYER_BLOCKED_SHOTS_5_last_match_average
PLAYER_CAPTAIN_5_last_match_average
PLAYER_CLEARANCES_5_last_match_average
PLAYER_CLEARANCE_OFFLINE_5_last_match_average
PLAYER_DISPOSSESSED_5_last_match_average
PLAYER_DRIBBLED_ATTEMPTS_5_last_match_average
PLAYER_DRIBBLED_PAST_5_last_match_average
PLAYER_DUELS_LOST_5_last_match_average
PLAYER_DUELS_WON_5_last_match_average
PLAYER_ERROR_LEAD_TO_GOAL_5_last_match_average
PLAYER_FOULS_5_last_match_average
PLAYER_FOULS_DRAWN_5_last_match_average
PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_average
PLAYER_GOALS_5_last_match_average
PLAYER_GOALS_CONCEDED_5_last_match_average
PLAYER_HIT_WOODWORK_5_last_match_average
PLAYER_INTERCEPTIONS_5_last_match_average
PLAYER_KEY_PASSES_5_last_match_average
PLAYER_MINUTES_PLAYED_5_last_match_average
PLAYER_OFFSIDES_5_last_match_average
PLAYER_OWN_GOALS_5_last_match_average
PLAYER_PASSES_5_last_match_average
PLAYER_PENALTIES_COMMITTED_5_last_match_average
PLAYER_PENALTIES_MISSES_5_last_match_average
PLAYER_PENALTIES_SAVED_5_last_match_average
PLAYER_PENALTIES_SCORED_5_last_match_average
PLAYER_PENALTIES_WON_5_last_match_average
PLAYER_RATING_5_last_match_average
PLAYER_REDCARDS_5_last_match_average
PLAYER_SAVES_5_last_match_average
PLAYER_SAVES_INSIDE_BOX_5_last_match_average
PLAYER_SHOTS_BLOCKED_5_last_match_average
PLAYER_SHOTS_ON_TARGET_5_last_match_average
PLAYER_SHOTS_TOTAL_5_last_match_average
PLAYER_STARTING_LINEUP_5_last_match_average
PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_average
PLAYER_TACKLES_5_last_match_average
PLAYER_TOTAL_CROSSES_5_last_match_average
PLAYER_TOTAL_DUELS_5_last_match_average
PLAYER_YELLOWCARDS_5_last_match_average
PLAYER_PUNCHES_5_last_match_average
PLAYER_LONG_BALLS_5_last_match_average
PLAYER_LONG_BALLS_WON_5_last_match_average
PLAYER_SHOTS_OFF_TARGET_5_last_match_average
PLAYER_ACCURATE_CROSSES_5_last_match_std
PLAYER_ACCURATE_PASSES_5_last_match_std
PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_std
PLAYER_AERIALS_WON_5_last_match_std
PLAYER_ASSISTS_5_last_match_std
PLAYER_BIG_CHANCES_CREATED_5_last_match_std
PLAYER_BIG_CHANCES_MISSED_5_last_match_std
PLAYER_BLOCKED_SHOTS_5_last_match_std
PLAYER_CAPTAIN_5_last_match_std
PLAYER_CLEARANCES_5_last_match_std
PLAYER_CLEARANCE_OFFLINE_5_last_match_std
PLAYER_DISPOSSESSED_5_last_match_std
PLAYER_DRIBBLED_ATTEMPTS_5_last_match_std
PLAYER_DRIBBLED_PAST_5_last_match_std
PLAYER_DUELS_LOST_5_last_match_std
PLAYER_DUELS_WON_5_last_match_std
PLAYER_ERROR_LEAD_TO_GOAL_5_last_match_std
PLAYER_FOULS_5_last_match_std
PLAYER_FOULS_DRAWN_5_last_match_std
PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_std
PLAYER_GOALS_5_last_match_std
PLAYER_GOALS_CONCEDED_5_last_match_std
PLAYER_HIT_WOODWORK_5_last_match_std
PLAYER_INTERCEPTIONS_5_last_match_std
PLAYER_KEY_PASSES_5_last_match_std
PLAYER_MINUTES_PLAYED_5_last_match_std
PLAYER_OFFSIDES_5_last_match_std
PLAYER_OWN_GOALS_5_last_match_std
PLAYER_PASSES_5_last_match_std
PLAYER_PENALTIES_COMMITTED_5_last_match_std
PLAYER_PENALTIES_MISSES_5_last_match_std
PLAYER_PENALTIES_SAVED_5_last_match_std
PLAYER_PENALTIES_SCORED_5_last_match_std
PLAYER_PENALTIES_WON_5_last_match_std
PLAYER_RATING_5_last_match_std
PLAYER_REDCARDS_5_last_match_std
PLAYER_SAVES_5_last_match_std
PLAYER_SAVES_INSIDE_BOX_5_last_match_std
PLAYER_SHOTS_BLOCKED_5_last_match_std
PLAYER_SHOTS_ON_TARGET_5_last_match_std
PLAYER_SHOTS_TOTAL_5_last_match_std
PLAYER_STARTING_LINEUP_5_last_match_std
PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_std
PLAYER_TACKLES_5_last_match_std
PLAYER_TOTAL_CROSSES_5_last_match_std
PLAYER_TOTAL_DUELS_5_last_match_std
PLAYER_YELLOWCARDS_5_last_match_std
PLAYER_PUNCHES_5_last_match_std
PLAYER_LONG_BALLS_5_last_match_std
PLAYER_LONG_BALLS_WON_5_last_match_std
PLAYER_SHOTS_OFF_TARGET_5_last_match_std

In [15]:
for col in away_player.columns:
    print(col)

ID
LEAGUE
TEAM_NAME
POSITION
PLAYER_NAME
PLAYER_ACCURATE_CROSSES_season_sum
PLAYER_ACCURATE_PASSES_season_sum
PLAYER_AERIALS_WON_season_sum
PLAYER_ASSISTS_season_sum
PLAYER_BIG_CHANCES_CREATED_season_sum
PLAYER_BIG_CHANCES_MISSED_season_sum
PLAYER_BLOCKED_SHOTS_season_sum
PLAYER_CAPTAIN_season_sum
PLAYER_CLEARANCES_season_sum
PLAYER_CLEARANCE_OFFLINE_season_sum
PLAYER_DISPOSSESSED_season_sum
PLAYER_DRIBBLED_ATTEMPTS_season_sum
PLAYER_DRIBBLED_PAST_season_sum
PLAYER_DUELS_LOST_season_sum
PLAYER_DUELS_WON_season_sum
PLAYER_ERROR_LEAD_TO_GOAL_season_sum
PLAYER_FOULS_season_sum
PLAYER_FOULS_DRAWN_season_sum
PLAYER_GOALKEEPER_GOALS_CONCEDED_season_sum
PLAYER_GOALS_season_sum
PLAYER_GOALS_CONCEDED_season_sum
PLAYER_HIT_WOODWORK_season_sum
PLAYER_INTERCEPTIONS_season_sum
PLAYER_KEY_PASSES_season_sum
PLAYER_MINUTES_PLAYED_season_sum
PLAYER_OFFSIDES_season_sum
PLAYER_OWN_GOALS_season_sum
PLAYER_PASSES_season_sum
PLAYER_PENALTIES_COMMITTED_season_sum
PLAYER_PENALTIES_MISSES_season_sum
PLAYER_PENALTIES_SAVED_season_sum
PLAYER_PENALTIES_SCORED_season_sum
PLAYER_PENALTIES_WON_season_sum
PLAYER_REDCARDS_season_sum
PLAYER_SAVES_season_sum
PLAYER_SAVES_INSIDE_BOX_season_sum
PLAYER_SHOTS_BLOCKED_season_sum
PLAYER_SHOTS_ON_TARGET_season_sum
PLAYER_SHOTS_TOTAL_season_sum
PLAYER_STARTING_LINEUP_season_sum
PLAYER_SUCCESSFUL_DRIBBLES_season_sum
PLAYER_TACKLES_season_sum
PLAYER_TOTAL_CROSSES_season_sum
PLAYER_TOTAL_DUELS_season_sum
PLAYER_YELLOWCARDS_season_sum
PLAYER_PUNCHES_season_sum
PLAYER_LONG_BALLS_season_sum
PLAYER_LONG_BALLS_WON_season_sum
PLAYER_SHOTS_OFF_TARGET_season_sum
PLAYER_ACCURATE_CROSSES_season_average
PLAYER_ACCURATE_PASSES_season_average
PLAYER_ACCURATE_PASSES_PERCENTAGE_season_average
PLAYER_AERIALS_WON_season_average
PLAYER_ASSISTS_season_average
PLAYER_BIG_CHANCES_CREATED_season_average
PLAYER_BIG_CHANCES_MISSED_season_average
PLAYER_BLOCKED_SHOTS_season_average
PLAYER_CAPTAIN_season_average
PLAYER_CLEARANCES_season_average
PLAYER_CLEARANCE_OFFLINE_season_average
PLAYER_DISPOSSESSED_season_average
PLAYER_DRIBBLED_ATTEMPTS_season_average
PLAYER_DRIBBLED_PAST_season_average
PLAYER_DUELS_LOST_season_average
PLAYER_DUELS_WON_season_average
PLAYER_ERROR_LEAD_TO_GOAL_season_average
PLAYER_FOULS_season_average
PLAYER_FOULS_DRAWN_season_average
PLAYER_GOALKEEPER_GOALS_CONCEDED_season_average
PLAYER_GOALS_season_average
PLAYER_GOALS_CONCEDED_season_average
PLAYER_HIT_WOODWORK_season_average
PLAYER_INTERCEPTIONS_season_average
PLAYER_KEY_PASSES_season_average
PLAYER_MINUTES_PLAYED_season_average
PLAYER_OFFSIDES_season_average
PLAYER_OWN_GOALS_season_average
PLAYER_PASSES_season_average
PLAYER_PENALTIES_COMMITTED_season_average
PLAYER_PENALTIES_MISSES_season_average
PLAYER_PENALTIES_SAVED_season_average
PLAYER_PENALTIES_SCORED_season_average
PLAYER_PENALTIES_WON_season_average
PLAYER_RATING_season_average
PLAYER_REDCARDS_season_average
PLAYER_SAVES_season_average
PLAYER_SAVES_INSIDE_BOX_season_average
PLAYER_SHOTS_BLOCKED_season_average
PLAYER_SHOTS_ON_TARGET_season_average
PLAYER_SHOTS_TOTAL_season_average
PLAYER_STARTING_LINEUP_season_average
PLAYER_SUCCESSFUL_DRIBBLES_season_average
PLAYER_TACKLES_season_average
PLAYER_TOTAL_CROSSES_season_average
PLAYER_TOTAL_DUELS_season_average
PLAYER_YELLOWCARDS_season_average
PLAYER_PUNCHES_season_average
PLAYER_LONG_BALLS_season_average
PLAYER_LONG_BALLS_WON_season_average
PLAYER_SHOTS_OFF_TARGET_season_average
PLAYER_ACCURATE_CROSSES_season_std
PLAYER_ACCURATE_PASSES_season_std
PLAYER_ACCURATE_PASSES_PERCENTAGE_season_std
PLAYER_AERIALS_WON_season_std
PLAYER_ASSISTS_season_std
PLAYER_BIG_CHANCES_CREATED_season_std
PLAYER_BIG_CHANCES_MISSED_season_std
PLAYER_BLOCKED_SHOTS_season_std
PLAYER_CAPTAIN_season_std
PLAYER_CLEARANCES_season_std
PLAYER_CLEARANCE_OFFLINE_season_std
PLAYER_DISPOSSESSED_season_std
PLAYER_DRIBBLED_ATTEMPTS_season_std
PLAYER_DRIBBLED_PAST_season_std
PLAYER_DUELS_LOST_season_std
PLAYER_DUELS_WON_season_std
PLAYER_ERROR_LEAD_TO_GOAL_season_std
PLAYER_FOULS_season_std
PLAYER_FOULS_DRAWN_season_std
PLAYER_GOALKEEPER_GOALS_CONCEDED_season_std
PLAYER_GOALS_season_std
PLAYER_GOALS_CONCEDED_season_std
PLAYER_HIT_WOODWORK_season_std
PLAYER_INTERCEPTIONS_season_std
PLAYER_KEY_PASSES_season_std
PLAYER_MINUTES_PLAYED_season_std
PLAYER_OFFSIDES_season_std
PLAYER_OWN_GOALS_season_std
PLAYER_PASSES_season_std
PLAYER_PENALTIES_COMMITTED_season_std
PLAYER_PENALTIES_MISSES_season_std
PLAYER_PENALTIES_SAVED_season_std
PLAYER_PENALTIES_SCORED_season_std
PLAYER_PENALTIES_WON_season_std
PLAYER_RATING_season_std
PLAYER_REDCARDS_season_std
PLAYER_SAVES_season_std
PLAYER_SAVES_INSIDE_BOX_season_std
PLAYER_SHOTS_BLOCKED_season_std
PLAYER_SHOTS_ON_TARGET_season_std
PLAYER_SHOTS_TOTAL_season_std
PLAYER_STARTING_LINEUP_season_std
PLAYER_SUCCESSFUL_DRIBBLES_season_std
PLAYER_TACKLES_season_std
PLAYER_TOTAL_CROSSES_season_std
PLAYER_TOTAL_DUELS_season_std
PLAYER_YELLOWCARDS_season_std
PLAYER_PUNCHES_season_std
PLAYER_LONG_BALLS_season_std
PLAYER_LONG_BALLS_WON_season_std
PLAYER_SHOTS_OFF_TARGET_season_std
PLAYER_ACCURATE_CROSSES_5_last_match_sum
PLAYER_ACCURATE_PASSES_5_last_match_sum
PLAYER_AERIALS_WON_5_last_match_sum
PLAYER_ASSISTS_5_last_match_sum
PLAYER_BIG_CHANCES_CREATED_5_last_match_sum
PLAYER_BIG_CHANCES_MISSED_5_last_match_sum
PLAYER_BLOCKED_SHOTS_5_last_match_sum
PLAYER_CAPTAIN_5_last_match_sum
PLAYER_CLEARANCES_5_last_match_sum
PLAYER_CLEARANCE_OFFLINE_5_last_match_sum
PLAYER_DISPOSSESSED_5_last_match_sum
PLAYER_DRIBBLED_ATTEMPTS_5_last_match_sum
PLAYER_DRIBBLED_PAST_5_last_match_sum
PLAYER_DUELS_LOST_5_last_match_sum
PLAYER_DUELS_WON_5_last_match_sum
PLAYER_ERROR_LEAD_TO_GOAL_5_last_match_sum
PLAYER_FOULS_5_last_match_sum
PLAYER_FOULS_DRAWN_5_last_match_sum
PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_sum
PLAYER_GOALS_5_last_match_sum
PLAYER_GOALS_CONCEDED_5_last_match_sum
PLAYER_HIT_WOODWORK_5_last_match_sum
PLAYER_INTERCEPTIONS_5_last_match_sum
PLAYER_KEY_PASSES_5_last_match_sum
PLAYER_MINUTES_PLAYED_5_last_match_sum
PLAYER_OFFSIDES_5_last_match_sum
PLAYER_OWN_GOALS_5_last_match_sum
PLAYER_PASSES_5_last_match_sum
PLAYER_PENALTIES_COMMITTED_5_last_match_sum
PLAYER_PENALTIES_MISSES_5_last_match_sum
PLAYER_PENALTIES_SAVED_5_last_match_sum
PLAYER_PENALTIES_SCORED_5_last_match_sum
PLAYER_PENALTIES_WON_5_last_match_sum
PLAYER_REDCARDS_5_last_match_sum
PLAYER_SAVES_5_last_match_sum
PLAYER_SAVES_INSIDE_BOX_5_last_match_sum
PLAYER_SHOTS_BLOCKED_5_last_match_sum
PLAYER_SHOTS_ON_TARGET_5_last_match_sum
PLAYER_SHOTS_TOTAL_5_last_match_sum
PLAYER_STARTING_LINEUP_5_last_match_sum
PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_sum
PLAYER_TACKLES_5_last_match_sum
PLAYER_TOTAL_CROSSES_5_last_match_sum
PLAYER_TOTAL_DUELS_5_last_match_sum
PLAYER_YELLOWCARDS_5_last_match_sum
PLAYER_PUNCHES_5_last_match_sum
PLAYER_LONG_BALLS_5_last_match_sum
PLAYER_LONG_BALLS_WON_5_last_match_sum
PLAYER_SHOTS_OFF_TARGET_5_last_match_sum
PLAYER_ACCURATE_CROSSES_5_last_match_average
PLAYER_ACCURATE_PASSES_5_last_match_average
PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_average
PLAYER_AERIALS_WON_5_last_match_average
PLAYER_ASSISTS_5_last_match_average
PLAYER_BIG_CHANCES_CREATED_5_last_match_average
PLAYER_BIG_CHANCES_MISSED_5_last_match_average
PLAYER_BLOCKED_SHOTS_5_last_match_average
PLAYER_CAPTAIN_5_last_match_average
PLAYER_CLEARANCES_5_last_match_average
PLAYER_CLEARANCE_OFFLINE_5_last_match_average
PLAYER_DISPOSSESSED_5_last_match_average
PLAYER_DRIBBLED_ATTEMPTS_5_last_match_average
PLAYER_DRIBBLED_PAST_5_last_match_average
PLAYER_DUELS_LOST_5_last_match_average
PLAYER_DUELS_WON_5_last_match_average
PLAYER_ERROR_LEAD_TO_GOAL_5_last_match_average
PLAYER_FOULS_5_last_match_average
PLAYER_FOULS_DRAWN_5_last_match_average
PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_average
PLAYER_GOALS_5_last_match_average
PLAYER_GOALS_CONCEDED_5_last_match_average
PLAYER_HIT_WOODWORK_5_last_match_average
PLAYER_INTERCEPTIONS_5_last_match_average
PLAYER_KEY_PASSES_5_last_match_average
PLAYER_MINUTES_PLAYED_5_last_match_average
PLAYER_OFFSIDES_5_last_match_average
PLAYER_OWN_GOALS_5_last_match_average
PLAYER_PASSES_5_last_match_average
PLAYER_PENALTIES_COMMITTED_5_last_match_average
PLAYER_PENALTIES_MISSES_5_last_match_average
PLAYER_PENALTIES_SAVED_5_last_match_average
PLAYER_PENALTIES_SCORED_5_last_match_average
PLAYER_PENALTIES_WON_5_last_match_average
PLAYER_RATING_5_last_match_average
PLAYER_REDCARDS_5_last_match_average
PLAYER_SAVES_5_last_match_average
PLAYER_SAVES_INSIDE_BOX_5_last_match_average
PLAYER_SHOTS_BLOCKED_5_last_match_average
PLAYER_SHOTS_ON_TARGET_5_last_match_average
PLAYER_SHOTS_TOTAL_5_last_match_average
PLAYER_STARTING_LINEUP_5_last_match_average
PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_average
PLAYER_TACKLES_5_last_match_average
PLAYER_TOTAL_CROSSES_5_last_match_average
PLAYER_TOTAL_DUELS_5_last_match_average
PLAYER_YELLOWCARDS_5_last_match_average
PLAYER_PUNCHES_5_last_match_average
PLAYER_LONG_BALLS_5_last_match_average
PLAYER_LONG_BALLS_WON_5_last_match_average
PLAYER_SHOTS_OFF_TARGET_5_last_match_average
PLAYER_ACCURATE_CROSSES_5_last_match_std
PLAYER_ACCURATE_PASSES_5_last_match_std
PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_std
PLAYER_AERIALS_WON_5_last_match_std
PLAYER_ASSISTS_5_last_match_std
PLAYER_BIG_CHANCES_CREATED_5_last_match_std
PLAYER_BIG_CHANCES_MISSED_5_last_match_std
PLAYER_BLOCKED_SHOTS_5_last_match_std
PLAYER_CAPTAIN_5_last_match_std
PLAYER_CLEARANCES_5_last_match_std
PLAYER_CLEARANCE_OFFLINE_5_last_match_std
PLAYER_DISPOSSESSED_5_last_match_std
PLAYER_DRIBBLED_ATTEMPTS_5_last_match_std
PLAYER_DRIBBLED_PAST_5_last_match_std
PLAYER_DUELS_LOST_5_last_match_std
PLAYER_DUELS_WON_5_last_match_std
PLAYER_ERROR_LEAD_TO_GOAL_5_last_match_std
PLAYER_FOULS_5_last_match_std
PLAYER_FOULS_DRAWN_5_last_match_std
PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_std
PLAYER_GOALS_5_last_match_std
PLAYER_GOALS_CONCEDED_5_last_match_std
PLAYER_HIT_WOODWORK_5_last_match_std
PLAYER_INTERCEPTIONS_5_last_match_std
PLAYER_KEY_PASSES_5_last_match_std
PLAYER_MINUTES_PLAYED_5_last_match_std
PLAYER_OFFSIDES_5_last_match_std
PLAYER_OWN_GOALS_5_last_match_std
PLAYER_PASSES_5_last_match_std
PLAYER_PENALTIES_COMMITTED_5_last_match_std
PLAYER_PENALTIES_MISSES_5_last_match_std
PLAYER_PENALTIES_SAVED_5_last_match_std
PLAYER_PENALTIES_SCORED_5_last_match_std
PLAYER_PENALTIES_WON_5_last_match_std
PLAYER_RATING_5_last_match_std
PLAYER_REDCARDS_5_last_match_std
PLAYER_SAVES_5_last_match_std
PLAYER_SAVES_INSIDE_BOX_5_last_match_std
PLAYER_SHOTS_BLOCKED_5_last_match_std
PLAYER_SHOTS_ON_TARGET_5_last_match_std
PLAYER_SHOTS_TOTAL_5_last_match_std
PLAYER_STARTING_LINEUP_5_last_match_std
PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_std
PLAYER_TACKLES_5_last_match_std
PLAYER_TOTAL_CROSSES_5_last_match_std
PLAYER_TOTAL_DUELS_5_last_match_std
PLAYER_YELLOWCARDS_5_last_match_std
PLAYER_PUNCHES_5_last_match_std
PLAYER_LONG_BALLS_5_last_match_std
PLAYER_LONG_BALLS_WON_5_last_match_std
PLAYER_SHOTS_OFF_TARGET_5_last_match_std

In [16]:
for col in y_train.columns:
    print(col)

ID
HOME_WINS
DRAW
AWAY_WINS

In [17]:
for col in y_train_supp.columns:
    print(col)

ID
GOAL_DIFF_HOME_AWAY

In [18]:
# Checking Data Types
def datatype_summary(df):

    summary = pd.DataFrame({
        "Data Type": df.dtypes,
        "Missing": df.isna().sum(),
        "Unique Values": df.nunique()
    })

    return summary

datatype_summary(home_team)

                                        Data Type  Missing  Unique Values
ID                                          int64        0          12303
LEAGUE                                     object        0             13
TEAM_NAME                                  object        0            350
TEAM_SHOTS_TOTAL_season_sum               float64      260             11
TEAM_SHOTS_INSIDEBOX_season_sum           float64     1385             11
...                                           ...      ...            ...
TEAM_SUBSTITUTIONS_5_last_match_std       float64       91             11
TEAM_BALL_SAFE_5_last_match_std           float64     1795             11
TEAM_DANGEROUS_ATTACKS_5_last_match_std   float64        0             11
TEAM_INJURIES_5_last_match_std            float64     3318             11
TEAM_GOALS_5_last_match_std               float64        2             11

[143 rows x 3 columns]

In [19]:
def datatype_summary(df):

    summary = pd.DataFrame({
        "Data Type": df.dtypes,
        "Missing": df.isna().sum(),
        "Unique Values": df.nunique()
    })

    return summary

datatype_summary(away_team)

                                        Data Type  Missing  Unique Values
ID                                          int64        0          12303
LEAGUE                                     object        0             13
TEAM_NAME                                  object        0            350
TEAM_SHOTS_TOTAL_season_sum               float64      259             11
TEAM_SHOTS_INSIDEBOX_season_sum           float64     1386             11
...                                           ...      ...            ...
TEAM_SUBSTITUTIONS_5_last_match_std       float64       91             11
TEAM_BALL_SAFE_5_last_match_std           float64     1836             11
TEAM_DANGEROUS_ATTACKS_5_last_match_std   float64        0             11
TEAM_INJURIES_5_last_match_std            float64     3313             11
TEAM_GOALS_5_last_match_std               float64        2             11

[143 rows x 3 columns]

In [20]:
def datatype_summary(df):

    summary = pd.DataFrame({
        "Data Type": df.dtypes,
        "Missing": df.isna().sum(),
        "Unique Values": df.nunique()
    })

    return summary

datatype_summary(home_player)

                                         Data Type  Missing  Unique Values
ID                                           int64        0          12303
LEAGUE                                      object        0             13
TEAM_NAME                                   object        0            350
POSITION                                    object    42820              4
PLAYER_NAME                                 object        0          13551
...                                            ...      ...            ...
PLAYER_YELLOWCARDS_5_last_match_std        float64     7443             35
PLAYER_PUNCHES_5_last_match_std            float64   170579             75
PLAYER_LONG_BALLS_5_last_match_std         float64   237079              0
PLAYER_LONG_BALLS_WON_5_last_match_std     float64   237079              0
PLAYER_SHOTS_OFF_TARGET_5_last_match_std   float64   237079              0

[307 rows x 3 columns]

In [21]:
def datatype_summary(df):

    summary = pd.DataFrame({
        "Data Type": df.dtypes,
        "Missing": df.isna().sum(),
        "Unique Values": df.nunique()
    })

    return summary

datatype_summary(away_player)

                                         Data Type  Missing  Unique Values
ID                                           int64        0          12303
LEAGUE                                      object        0             13
TEAM_NAME                                   object        0            350
POSITION                                    object    42255              4
PLAYER_NAME                                 object        0          13673
...                                            ...      ...            ...
PLAYER_YELLOWCARDS_5_last_match_std        float64     7687             35
PLAYER_PUNCHES_5_last_match_std            float64   170078             74
PLAYER_LONG_BALLS_5_last_match_std         float64   236132              0
PLAYER_LONG_BALLS_WON_5_last_match_std     float64   236132              0
PLAYER_SHOTS_OFF_TARGET_5_last_match_std   float64   236132              0

[307 rows x 3 columns]

In [22]:
def datatype_summary(df):

    summary = pd.DataFrame({
        "Data Type": df.dtypes,
        "Missing": df.isna().sum(),
        "Unique Values": df.nunique()
    })

    return summary

datatype_summary(y_train)

          Data Type  Missing  Unique Values
ID            int64        0          12303
HOME_WINS     int64        0              2
DRAW          int64        0              2
AWAY_WINS     int64        0              2

In [23]:
def datatype_summary(df):

    summary = pd.DataFrame({
        "Data Type": df.dtypes,
        "Missing": df.isna().sum(),
        "Unique Values": df.nunique()
    })

    return summary

datatype_summary(y_train_supp)

                    Data Type  Missing  Unique Values
ID                      int64        0          12303
GOAL_DIFF_HOME_AWAY   float64        0             21

In [24]:
# Duplicate Analysis

def check_duplicates(df, name):

    duplicate_rows = df.duplicated().sum()

    print("="*70)
    print(name)
    print("="*70)

    print(f"Duplicate Rows : {duplicate_rows:,}")

    if duplicate_rows > 0:
        print("\nExample Duplicate Rows")
        display(df[df.duplicated()].head())

In [25]:
check_duplicates(home_team,"HOME TEAM")

check_duplicates(away_team,"AWAY TEAM")

check_duplicates(home_player,"HOME PLAYER")

check_duplicates(away_player,"AWAY PLAYER")

check_duplicates(y_train,"Y TRAIN")

check_duplicates(y_train_supp,"Y TRAIN SUPP")

======================================================================
HOME TEAM
======================================================================
Duplicate Rows : 0
======================================================================
AWAY TEAM
======================================================================
Duplicate Rows : 0
======================================================================
HOME PLAYER
======================================================================
Duplicate Rows : 0
======================================================================
AWAY PLAYER
======================================================================
Duplicate Rows : 0
======================================================================
Y TRAIN
======================================================================
Duplicate Rows : 0
======================================================================
Y TRAIN SUPP
======================================================================
Duplicate Rows : 0

In [26]:
# ID Consistency
def check_id(df,name):

    print("="*70)
    print(name)
    print("="*70)

    print("Total Rows :",len(df))
    print("Unique IDs :",df["ID"].nunique())

    print("Duplicate IDs :",df["ID"].duplicated().sum())

In [27]:
check_id(home_team,"HOME TEAM")

check_id(away_team,"AWAY TEAM")

check_id(home_player,"HOME PLAYER")

check_id(away_player,"AWAY PLAYER")

check_id(y_train,"Y TRAIN")

check_id(y_train_supp,"Y TRAIN SUPP")

======================================================================
HOME TEAM
======================================================================
Total Rows : 12303
Unique IDs : 12303
Duplicate IDs : 0
======================================================================
AWAY TEAM
======================================================================
Total Rows : 12303
Unique IDs : 12303
Duplicate IDs : 0
======================================================================
HOME PLAYER
======================================================================
Total Rows : 237079
Unique IDs : 12303
Duplicate IDs : 224776
======================================================================
AWAY PLAYER
======================================================================
Total Rows : 236132
Unique IDs : 12303
Duplicate IDs : 223829
======================================================================
Y TRAIN
======================================================================
Total Rows : 12303
Unique IDs : 12303
Duplicate IDs : 0
======================================================================
Y TRAIN SUPP
======================================================================
Total Rows : 12303
Unique IDs : 12303
Duplicate IDs : 0

For Home team, Away Team, Y Train, Y Train Supp Duplicate IDs will be 0, whereas for player datasets duplicate IDs should be very large as one match contains many players.

In [28]:
# Missing Value Summary

def missing_summary(df):

    missing = pd.DataFrame({

        "Missing Count":df.isna().sum(),

        "Missing %":round(df.isna().mean()*100,2),

        "Data Type":df.dtypes

    })

    missing = missing[missing["Missing Count"]>0]

    return missing.sort_values(
        by="Missing %",
        ascending=False
    )

In [29]:
missing_summary(home_team)

                                    Missing Count  Missing % Data Type
TEAM_INJURIES_5_last_match_std               3318      26.97   float64
TEAM_INJURIES_5_last_match_sum               2932      23.83   float64
TEAM_INJURIES_5_last_match_average           2931      23.82   float64
TEAM_INJURIES_season_std                     2924      23.77   float64
TEAM_INJURIES_season_sum                     1960      15.93   float64
...                                           ...        ...       ...
TEAM_YELLOWCARDS_5_last_match_std               1       0.01   float64
TEAM_CORNERS_5_last_match_average               1       0.01   float64
TEAM_YELLOWCARDS_season_std                     1       0.01   float64
TEAM_CORNERS_season_sum                         1       0.01   float64
TEAM_CORNERS_5_last_match_sum                   1       0.01   float64

[118 rows x 3 columns]

In [30]:
missing_summary(away_team)

                                    Missing Count  Missing % Data Type
TEAM_INJURIES_5_last_match_std               3313      26.93   float64
TEAM_INJURIES_5_last_match_sum               2933      23.84   float64
TEAM_INJURIES_5_last_match_average           2932      23.83   float64
TEAM_INJURIES_season_std                     2926      23.78   float64
TEAM_INJURIES_season_sum                     1961      15.94   float64
...                                           ...        ...       ...
TEAM_YELLOWCARDS_5_last_match_std               1       0.01   float64
TEAM_CORNERS_5_last_match_average               1       0.01   float64
TEAM_YELLOWCARDS_season_std                     1       0.01   float64
TEAM_CORNERS_season_sum                         1       0.01   float64
TEAM_CORNERS_5_last_match_sum                   1       0.01   float64

[118 rows x 3 columns]

In [31]:
missing_summary(home_player)

                                        Missing Count  Missing % Data Type
PLAYER_SHOTS_OFF_TARGET_season_std             237079     100.00   float64
PLAYER_LONG_BALLS_5_last_match_sum             237079     100.00   float64
PLAYER_SHOTS_OFF_TARGET_season_sum             237079     100.00   float64
PLAYER_CAPTAIN_season_average                  237079     100.00   float64
PLAYER_LONG_BALLS_season_average               237079     100.00   float64
...                                               ...        ...       ...
PLAYER_ASSISTS_season_sum                        3597       1.52   float64
PLAYER_ASSISTS_season_average                    3597       1.52   float64
PLAYER_MINUTES_PLAYED_5_last_match_sum           3597       1.52   float64
PLAYER_GOALS_season_sum                          3597       1.52   float64
PLAYER_GOALS_season_average                      3597       1.52   float64

[303 rows x 3 columns]

In [32]:
missing_summary(away_player)

                                        Missing Count  Missing % Data Type
PLAYER_SHOTS_OFF_TARGET_season_std             236132     100.00   float64
PLAYER_LONG_BALLS_5_last_match_sum             236132     100.00   float64
PLAYER_SHOTS_OFF_TARGET_season_sum             236132     100.00   float64
PLAYER_CAPTAIN_season_average                  236132     100.00   float64
PLAYER_LONG_BALLS_season_average               236132     100.00   float64
...                                               ...        ...       ...
PLAYER_ASSISTS_season_sum                        3829       1.62   float64
PLAYER_ASSISTS_season_average                    3829       1.62   float64
PLAYER_MINUTES_PLAYED_5_last_match_sum           3829       1.62   float64
PLAYER_GOALS_season_sum                          3829       1.62   float64
PLAYER_GOALS_season_average                      3829       1.62   float64

[303 rows x 3 columns]

In [33]:
# Categorizing Missing Values

In [34]:
def classify_missing(df):

    missing = (
        df.isna().mean()*100
    )

    summary = pd.DataFrame({

        "Missing %":missing

    })

    summary["Category"] = pd.cut(

        summary["Missing %"],

        bins=[-1,0,5,20,50,80,100],

        labels=[
            "No Missing",
            "Very Low",
            "Low",
            "Moderate",
            "High",
            "Very High"
        ]

    )

    return summary.sort_values(
        by="Missing %",
        ascending=False
    )

In [35]:
classify_missing(home_team)

                                            Missing %    Category
TEAM_INJURIES_5_last_match_std                  26.97    Moderate
TEAM_INJURIES_5_last_match_sum                  23.83    Moderate
TEAM_INJURIES_5_last_match_average              23.82    Moderate
TEAM_INJURIES_season_std                        23.77    Moderate
TEAM_INJURIES_season_sum                        15.93         Low
...                                               ...         ...
TEAM_ATTACKS_5_last_match_average                0.00  No Missing
TEAM_ATTACKS_5_last_match_sum                    0.00  No Missing
TEAM_DANGEROUS_ATTACKS_5_last_match_sum          0.00  No Missing
TEAM_SHOTS_OFF_TARGET_5_last_match_average       0.00  No Missing
ID                                               0.00  No Missing

[143 rows x 2 columns]

In [36]:
classify_missing(away_team)

                                            Missing %    Category
TEAM_INJURIES_5_last_match_std                  26.93    Moderate
TEAM_INJURIES_5_last_match_sum                  23.84    Moderate
TEAM_INJURIES_5_last_match_average              23.83    Moderate
TEAM_INJURIES_season_std                        23.78    Moderate
TEAM_INJURIES_season_sum                        15.94         Low
...                                               ...         ...
TEAM_ATTACKS_5_last_match_average                0.00  No Missing
TEAM_ATTACKS_5_last_match_sum                    0.00  No Missing
TEAM_DANGEROUS_ATTACKS_5_last_match_sum          0.00  No Missing
TEAM_SHOTS_OFF_TARGET_5_last_match_average       0.00  No Missing
ID                                               0.00  No Missing

[143 rows x 2 columns]

In [37]:
classify_missing(home_player)

                                    Missing %    Category
PLAYER_LONG_BALLS_season_std           100.00   Very High
PLAYER_LONG_BALLS_5_last_match_sum     100.00   Very High
PLAYER_SHOTS_OFF_TARGET_season_sum     100.00   Very High
PLAYER_CAPTAIN_season_average          100.00   Very High
PLAYER_LONG_BALLS_season_average       100.00   Very High
...                                       ...         ...
PLAYER_GOALS_5_last_match_sum            1.52    Very Low
LEAGUE                                   0.00  No Missing
PLAYER_NAME                              0.00  No Missing
TEAM_NAME                                0.00  No Missing
ID                                       0.00  No Missing

[307 rows x 2 columns]

In [38]:
classify_missing(away_player)

                                    Missing %    Category
PLAYER_LONG_BALLS_season_std           100.00   Very High
PLAYER_LONG_BALLS_5_last_match_sum     100.00   Very High
PLAYER_SHOTS_OFF_TARGET_season_sum     100.00   Very High
PLAYER_CAPTAIN_season_average          100.00   Very High
PLAYER_LONG_BALLS_season_average       100.00   Very High
...                                       ...         ...
PLAYER_GOALS_5_last_match_sum            1.62    Very Low
LEAGUE                                   0.00  No Missing
PLAYER_NAME                              0.00  No Missing
TEAM_NAME                                0.00  No Missing
ID                                       0.00  No Missing

[307 rows x 2 columns]

In [39]:
# Constant Columns
def constant_columns(df):

    constant=[]

    for col in df.columns:

        if df[col].nunique()==1:

            constant.append(col)

    return constant

In [40]:
constant_columns(home_team)

[]

In [41]:
constant_columns(away_team)

[]

In [42]:
constant_columns(home_player)

[]

In [43]:
constant_columns(away_player)

[]

[] is the result for every dataset which means no useless columns, therefore nothing to drop.

In [44]:
# Numerical Summary
home_team.describe().T

,count,mean,std,min,25%,50%,75%,max
ID,12303.00,6151.00,3551.71,0.00,3075.50,6151.00,9226.50,12302.00
TEAM_SHOTS_TOTAL_season_sum,12043.00,4.39,2.87,0.00,2.00,4.00,6.00,10.00
TEAM_SHOTS_INSIDEBOX_season_sum,10918.00,4.30,2.93,0.00,2.00,4.00,6.00,10.00
TEAM_SHOTS_OFF_TARGET_season_sum,12303.00,4.51,2.81,0.00,2.00,4.00,6.00,10.00
TEAM_SHOTS_ON_TARGET_season_sum,12301.00,4.15,2.86,0.00,2.00,4.00,6.00,10.00
...,...,...,...,...,...,...,...,...
TEAM_SUBSTITUTIONS_5_last_match_std,12212.00,3.30,3.35,0.00,0.00,3.00,6.00,10.00
TEAM_BALL_SAFE_5_last_match_std,10508.00,3.80,2.87,0.00,1.00,3.00,6.00,10.00
TEAM_DANGEROUS_ATTACKS_5_last_match_std,12303.00,3.69,2.78,0.00,2.00,3.00,5.00,10.00
TEAM_INJURIES_5_last_match_std,8985.00,3.87,2.79,0.00,2.00,3.00,6.00,10.00
TEAM_GOALS_5_last_match_std,12301.00,3.63,2.85,0.00,1.00,3.00,5.00,10.00

In [45]:
away_team.describe().T

,count,mean,std,min,25%,50%,75%,max
ID,12303.00,6151.00,3551.71,0.00,3075.50,6151.00,9226.50,12302.00
TEAM_SHOTS_TOTAL_season_sum,12044.00,4.47,2.89,0.00,2.00,4.00,6.00,10.00
TEAM_SHOTS_INSIDEBOX_season_sum,10917.00,4.38,2.93,0.00,2.00,4.00,7.00,10.00
TEAM_SHOTS_OFF_TARGET_season_sum,12303.00,4.59,2.81,0.00,2.00,4.00,7.00,10.00
TEAM_SHOTS_ON_TARGET_season_sum,12301.00,4.22,2.87,0.00,2.00,4.00,6.00,10.00
...,...,...,...,...,...,...,...,...
TEAM_SUBSTITUTIONS_5_last_match_std,12212.00,3.27,3.34,0.00,0.00,3.00,6.00,10.00
TEAM_BALL_SAFE_5_last_match_std,10467.00,3.80,2.86,0.00,2.00,3.00,6.00,10.00
TEAM_DANGEROUS_ATTACKS_5_last_match_std,12303.00,3.76,2.81,0.00,2.00,3.00,6.00,10.00
TEAM_INJURIES_5_last_match_std,8990.00,3.89,2.80,0.00,2.00,3.00,6.00,10.00
TEAM_GOALS_5_last_match_std,12301.00,3.69,2.86,0.00,2.00,3.00,6.00,10.00

For team dataset the highest missing percentage is 26.9% and it comes team injuries which makes sense as not every team has injuries recorded so we will not drop these columns

In [46]:
home_player.describe().T

,count,mean,std,min,25%,50%,75%,max
ID,237079.00,6151.42,3552.22,0.00,3080.00,6152.00,9227.00,12302.00
PLAYER_ACCURATE_CROSSES_season_sum,208790.00,7.93,15.10,0.00,0.00,1.00,9.00,100.00
PLAYER_ACCURATE_PASSES_season_sum,208790.00,22.72,20.85,0.00,6.00,18.00,34.00,100.00
PLAYER_AERIALS_WON_season_sum,208790.00,12.72,16.20,0.00,1.00,7.00,18.00,100.00
PLAYER_ASSISTS_season_sum,233482.00,9.30,16.38,0.00,0.00,0.00,14.00,100.00
...,...,...,...,...,...,...,...,...
PLAYER_YELLOWCARDS_5_last_match_std,229636.00,25.54,33.78,0.00,0.00,0.00,63.00,100.00
PLAYER_PUNCHES_5_last_match_std,66500.00,2.12,11.19,0.00,0.00,0.00,0.00,100.00
PLAYER_LONG_BALLS_5_last_match_std,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PLAYER_LONG_BALLS_WON_5_last_match_std,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PLAYER_SHOTS_OFF_TARGET_5_last_match_std,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
away_player.describe().T

,count,mean,std,min,25%,50%,75%,max
ID,236132.00,6151.38,3551.67,0.00,3079.00,6150.00,9227.00,12302.00
PLAYER_ACCURATE_CROSSES_season_sum,207662.00,7.94,15.15,0.00,0.00,1.00,9.00,100.00
PLAYER_ACCURATE_PASSES_season_sum,207662.00,22.73,20.89,0.00,6.00,18.00,34.00,100.00
PLAYER_AERIALS_WON_season_sum,207662.00,12.70,16.17,0.00,1.00,7.00,18.00,100.00
PLAYER_ASSISTS_season_sum,232303.00,9.28,16.39,0.00,0.00,0.00,14.00,100.00
...,...,...,...,...,...,...,...,...
PLAYER_YELLOWCARDS_5_last_match_std,228445.00,25.17,33.65,0.00,0.00,0.00,63.00,100.00
PLAYER_PUNCHES_5_last_match_std,66054.00,2.10,11.14,0.00,0.00,0.00,0.00,100.00
PLAYER_LONG_BALLS_5_last_match_std,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PLAYER_LONG_BALLS_WON_5_last_match_std,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PLAYER_SHOTS_OFF_TARGET_5_last_match_std,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN

For player dataset many variables have 100% missing, eg player long balls, player captain, player shots off target,etc. and from numerical summary these columns contain absolutely no information, therefore these columns must be removed

In [48]:
# Data Cleaning
def remove_all_missing_columns(df):

    cols_to_drop = df.columns[df.isnull().all()]

    print(f"Columns removed : {len(cols_to_drop)}")

    return df.drop(columns=cols_to_drop), list(cols_to_drop)

In [49]:
home_player, dropped_home = remove_all_missing_columns(home_player)

away_player, dropped_away = remove_all_missing_columns(away_player)

Columns removed : 22
Columns removed : 22

In [50]:
home_player.shape

away_player.shape

(236132, 285)

In [51]:
missing_summary(home_player).head(20)

,Missing Count,Missing %,Data Type
PLAYER_CAPTAIN_5_last_match_sum,219006,92.38,float64
PLAYER_CAPTAIN_season_sum,211789,89.33,float64
PLAYER_PUNCHES_season_std,170579,71.95,float64
PLAYER_PUNCHES_5_last_match_std,170579,71.95,float64
PLAYER_PUNCHES_season_sum,169599,71.54,float64
PLAYER_PUNCHES_season_average,169599,71.54,float64
PLAYER_PUNCHES_5_last_match_average,169599,71.54,float64
PLAYER_PUNCHES_5_last_match_sum,169599,71.54,float64
PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_std,95161,40.14,float64
PLAYER_ACCURATE_PASSES_PERCENTAGE_season_std,81891,34.54,float64
PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_average,77848,32.84,float64
PLAYER_ACCURATE_PASSES_PERCENTAGE_season_average,70539,29.75,float64
PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_std,56915,24.01,float64
PLAYER_DRIBBLED_ATTEMPTS_5_last_match_std,56915,24.01,float64
PLAYER_SUCCESSFUL_DRIBBLES_season_std,56915,24.01,float64
PLAYER_DRIBBLED_PAST_5_last_match_std,56915,24.01,float64
PLAYER_DRIBBLED_PAST_season_std,56915,24.01,float64
PLAYER_DRIBBLED_ATTEMPTS_season_std,56915,24.01,float64
PLAYER_SUCCESSFUL_DRIBBLES_season_average,54107,22.82,float64
PLAYER_DRIBBLED_ATTEMPTS_season_sum,54107,22.82,float64

In [52]:
missing_summary(away_player).head(20)

,Missing Count,Missing %,Data Type
PLAYER_CAPTAIN_5_last_match_sum,218254,92.43,float64
PLAYER_CAPTAIN_season_sum,211147,89.42,float64
PLAYER_PUNCHES_season_std,170078,72.03,float64
PLAYER_PUNCHES_5_last_match_std,170078,72.03,float64
PLAYER_PUNCHES_season_sum,169063,71.60,float64
PLAYER_PUNCHES_season_average,169063,71.60,float64
PLAYER_PUNCHES_5_last_match_average,169063,71.60,float64
PLAYER_PUNCHES_5_last_match_sum,169063,71.60,float64
PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_std,95523,40.45,float64
PLAYER_ACCURATE_PASSES_PERCENTAGE_season_std,82102,34.77,float64
PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_average,78109,33.08,float64
PLAYER_ACCURATE_PASSES_PERCENTAGE_season_average,70770,29.97,float64
PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_std,57084,24.17,float64
PLAYER_DRIBBLED_ATTEMPTS_5_last_match_std,57084,24.17,float64
PLAYER_SUCCESSFUL_DRIBBLES_season_std,57084,24.17,float64
PLAYER_DRIBBLED_PAST_5_last_match_std,57084,24.17,float64
PLAYER_DRIBBLED_PAST_season_std,57084,24.17,float64
PLAYER_DRIBBLED_ATTEMPTS_season_std,57084,24.17,float64
PLAYER_SUCCESSFUL_DRIBBLES_season_average,54161,22.94,float64
PLAYER_DRIBBLED_ATTEMPTS_season_sum,54161,22.94,float64

We notice that the football specific variables for eg captain - only one player per team is captain so this varibale is naturally sparse, punches - only goalkeepers peform punches so outfield palkyers legitimately have missing values; so we don't drop these columns yet we make a more informed decision after we aggregate player data to match level.

In [53]:
home_team_clean = home_team.copy()

away_team_clean = away_team.copy()

home_player_clean = home_player.copy()

away_player_clean = away_player.copy()

In [54]:
# Remove columns that are 100% missing

home_team_clean, dropped_home_team = remove_all_missing_columns(home_team_clean)

away_team_clean, dropped_away_team = remove_all_missing_columns(away_team_clean)

home_player_clean, dropped_home_player = remove_all_missing_columns(home_player_clean)

away_player_clean, dropped_away_player = remove_all_missing_columns(away_player_clean)

Columns removed : 0
Columns removed : 0
Columns removed : 0
Columns removed : 0

## 6. Treating Missing Values

### 6.1.1 Home Team Dataset

In [55]:
# CREATE A COPY OF THE HOME TEAM DATASET

home_team_processed = home_team_clean.copy()

In [56]:
# Select numerical columns
numerical_columns = home_team_processed.select_dtypes(include=['number']).columns

print(f"Total numerical columns: {len(numerical_columns)}")

Total numerical columns: 141

In [57]:
# Missing values before imputation
missing_before = home_team_processed[numerical_columns].isnull().sum()

# Display only columns with missing values
missing_before = missing_before[missing_before > 0].sort_values(ascending=False)

print(f"Numerical columns with missing values: {len(missing_before)}")
missing_before.head(10)

Numerical columns with missing values: 118

TEAM_INJURIES_5_last_match_std                        3318
TEAM_INJURIES_5_last_match_sum                        2932
TEAM_INJURIES_5_last_match_average                    2931
TEAM_INJURIES_season_std                              2924
TEAM_INJURIES_season_sum                              1960
TEAM_INJURIES_season_average                          1959
TEAM_BALL_SAFE_5_last_match_std                       1795
TEAM_SUCCESSFUL_PASSES_PERCENTAGE_5_last_match_std    1589
TEAM_PASSES_5_last_match_std                          1589
TEAM_SUCCESSFUL_PASSES_PERCENTAGE_season_std          1529
dtype: int64

In [58]:
from sklearn.impute import SimpleImputer

# Create the imputer
median_imputer = SimpleImputer(strategy='median')

# Apply median imputation only to numerical columns
home_team_processed[numerical_columns] = median_imputer.fit_transform(
    home_team_processed[numerical_columns]
)

In [59]:
# Check remaining missing values
remaining_missing = (
    home_team_processed[numerical_columns]
    .isnull()
    .sum()
    .sum()
)

print(f"Remaining missing values in numerical columns: {remaining_missing}")

Remaining missing values in numerical columns: 0

In [60]:
home_team_processed["TEAM_INJURIES_5_last_match_std"].isna().sum()

np.int64(0)

In [61]:
home_team_processed["TEAM_INJURIES_5_last_match_std"].head(10)

0   4.00
1   8.00
2   2.00
3   3.00
4   4.00
5   2.00
6   4.00
7   5.00
8   3.00
9   7.00
Name: TEAM_INJURIES_5_last_match_std, dtype: float64

In [62]:
# Check for missing values in non-numerical (categorical/object) columns
categorical_columns = home_team_processed.select_dtypes(include=['object', 'category']).columns

home_team_processed[categorical_columns].isna().sum()

LEAGUE       0
TEAM_NAME    0
dtype: int64

In [63]:
home_team_processed.isnull().sum().sum()

np.int64(0)

### 6.1.2 Away Team Dataset

In [64]:
# Create a copy of the cleaned Away Team dataset
away_team_processed = away_team_clean.copy()

In [65]:
# Select numerical columns
numerical_columns = away_team_processed.select_dtypes(include=['number']).columns

print(f"Total numerical columns: {len(numerical_columns)}")

Total numerical columns: 141

In [66]:
# Missing values before imputation
missing_before = away_team_processed[numerical_columns].isnull().sum()

# Display only columns with missing values
missing_before = missing_before[missing_before > 0].sort_values(ascending=False)

print(f"Numerical columns with missing values: {len(missing_before)}")
missing_before.head(10)

Numerical columns with missing values: 118

TEAM_INJURIES_5_last_match_std                        3313
TEAM_INJURIES_5_last_match_sum                        2933
TEAM_INJURIES_5_last_match_average                    2932
TEAM_INJURIES_season_std                              2926
TEAM_INJURIES_season_sum                              1961
TEAM_INJURIES_season_average                          1960
TEAM_BALL_SAFE_5_last_match_std                       1836
TEAM_SUCCESSFUL_PASSES_PERCENTAGE_5_last_match_std    1588
TEAM_PASSES_5_last_match_std                          1588
TEAM_SUCCESSFUL_PASSES_PERCENTAGE_season_std          1529
dtype: int64

In [67]:
# Create the median imputer
median_imputer = SimpleImputer(strategy='median')

# Apply median imputation
away_team_processed[numerical_columns] = median_imputer.fit_transform(
    away_team_processed[numerical_columns]
)

In [68]:
remaining_missing = (
    away_team_processed[numerical_columns]
    .isnull()
    .sum()
    .sum()
)

print(f"Remaining numerical missing values: {remaining_missing}")

Remaining numerical missing values: 0

In [69]:
categorical_columns = away_team_processed.select_dtypes(
    include=['object', 'category']
).columns

print(away_team_processed[categorical_columns].isnull().sum())

LEAGUE       0
TEAM_NAME    0
dtype: int64

In [70]:
print("Total missing values:", away_team_processed.isnull().sum().sum())

Total missing values: 0

### 6.1.3 Home Player Dataset

In [71]:
# Percentage of missing values
missing_percent = (home_player.isnull().mean() * 100).sort_values(ascending=False)

# Show columns with more than 50% missing values
missing_percent[missing_percent > 50]

PLAYER_CAPTAIN_5_last_match_sum       92.38
PLAYER_CAPTAIN_season_sum             89.33
PLAYER_PUNCHES_5_last_match_std       71.95
PLAYER_PUNCHES_season_std             71.95
PLAYER_PUNCHES_5_last_match_sum       71.54
PLAYER_PUNCHES_season_sum             71.54
PLAYER_PUNCHES_5_last_match_average   71.54
PLAYER_PUNCHES_season_average         71.54
dtype: float64

In [72]:
print(home_player["POSITION"].value_counts(dropna=False))

POSITION
midfielder    78524
defender      67746
NaN           42820
goalkeeper    24298
attacker      23691
Name: count, dtype: int64

In [73]:
home_player[home_player["POSITION"].isnull()][
    ["PLAYER_NAME", "TEAM_NAME", "LEAGUE"]
].head(20)

             PLAYER_NAME    TEAM_NAME         LEAGUE
4    Efthymios Koulouris     Toulouse        Ligue 1
9       Aaron Leya Iseka     Toulouse        Ligue 1
10           Yaya Sanogo     Toulouse        Ligue 1
17           Wesley Saïd     Toulouse        Ligue 1
21         Édouard Butin        Brest        Ligue 2
27        Valentin Henry        Brest        Ligue 2
31    Gaëtan Charbonnier        Brest        Ligue 2
97         Gonzalo Plata  Sporting CP  Liga Portugal
100        Jovane Cabral  Sporting CP  Liga Portugal
108        Andraž Šporar  Sporting CP  Liga Portugal
110       Luciano Vietto  Sporting CP  Liga Portugal
117           Bryan Gil       Sevilla        La Liga
119        Quincy Promes      Sevilla        La Liga
121     Munir El Haddadi      Sevilla        La Liga
126          André Silva      Sevilla        La Liga
128    Wissam Ben Yedder      Sevilla        La Liga
132            Josh Maja     Bordeaux        Ligue 1
134         Yann Karamoh     Bordeaux        Ligue 1
137  Nicolas de Préville     Bordeaux        Ligue 1
143         Jimmy Briand     Bordeaux        Ligue 1

In [74]:
home_player.groupby("POSITION")[
    "PLAYER_PUNCHES_season_sum"
].apply(lambda x: x.notna().sum())

POSITION
attacker      14097
defender      21141
goalkeeper     7298
midfielder    23908
Name: PLAYER_PUNCHES_season_sum, dtype: int64

In [75]:
home_player.groupby("POSITION")[
    "PLAYER_CAPTAIN_season_sum"
].apply(lambda x: x.notna().sum())

POSITION
attacker      1605
defender      9516
goalkeeper    2105
midfielder    8124
Name: PLAYER_CAPTAIN_season_sum, dtype: int64

In [76]:
 home_player["PLAYER_PUNCHES_season_sum"].describe()

count   67480.00
mean        2.35
std        11.51
min         0.00
25%         0.00
50%         0.00
75%         0.00
max       100.00
Name: PLAYER_PUNCHES_season_sum, dtype: float64

In [77]:
home_player["PLAYER_CAPTAIN_season_sum"].describe()

count   25290.00
mean       34.37
std        35.10
min         0.00
25%         2.00
50%        20.00
75%        66.00
max       100.00
Name: PLAYER_CAPTAIN_season_sum, dtype: float64

In [78]:
home_player["PLAYER_CAPTAIN_5_last_match_sum"].describe()

count   18073.00
mean       52.43
std        41.23
min         0.00
25%         0.00
50%        50.00
75%       100.00
max       100.00
Name: PLAYER_CAPTAIN_5_last_match_sum, dtype: float64

In [79]:
home_player.groupby("POSITION")[
    "PLAYER_CAPTAIN_5_last_match_sum"
].apply(lambda x: x.notna().sum())

POSITION
attacker      1038
defender      6922
goalkeeper    1483
midfielder    5805
Name: PLAYER_CAPTAIN_5_last_match_sum, dtype: int64

In [80]:
home_player["PLAYER_PUNCHES_5_last_match_std"].describe()

count   66500.00
mean        2.12
std        11.19
min         0.00
25%         0.00
50%         0.00
75%         0.00
max       100.00
Name: PLAYER_PUNCHES_5_last_match_std, dtype: float64

In [81]:
home_player.groupby("POSITION")[
    "PLAYER_PUNCHES_5_last_match_std"
].apply(lambda x: x.notna().sum())

POSITION
attacker      13868
defender      20867
goalkeeper     7200
midfielder    23555
Name: PLAYER_PUNCHES_5_last_match_std, dtype: int64

In [82]:
home_player["PLAYER_PUNCHES_season_std"].describe()

count   66500.00
mean        3.05
std        13.32
min         0.00
25%         0.00
50%         0.00
75%         0.00
max       100.00
Name: PLAYER_PUNCHES_season_std, dtype: float64

In [83]:
home_player.groupby("POSITION")[
    "PLAYER_PUNCHES_season_std"
].apply(lambda x: x.notna().sum())

POSITION
attacker      13868
defender      20867
goalkeeper     7200
midfielder    23555
Name: PLAYER_PUNCHES_season_std, dtype: int64

In [84]:
home_player["PLAYER_PUNCHES_5_last_match_average"].describe()

count   67480.00
mean        1.73
std         9.85
min         0.00
25%         0.00
50%         0.00
75%         0.00
max       100.00
Name: PLAYER_PUNCHES_5_last_match_average, dtype: float64

In [85]:
home_player.groupby("POSITION")[
    "PLAYER_PUNCHES_5_last_match_average"
].apply(lambda x: x.notna().sum())

POSITION
attacker      14097
defender      21141
goalkeeper     7298
midfielder    23908
Name: PLAYER_PUNCHES_5_last_match_average, dtype: int64

In [86]:
home_player["PLAYER_PUNCHES_season_average"].describe()

count   67480.00
mean        2.18
std        10.71
min         0.00
25%         0.00
50%         0.00
75%         0.00
max       100.00
Name: PLAYER_PUNCHES_season_average, dtype: float64

In [87]:
home_player.groupby("POSITION")[
    "PLAYER_PUNCHES_season_average"
].apply(lambda x: x.notna().sum())

POSITION
attacker      14097
defender      21141
goalkeeper     7298
midfielder    23908
Name: PLAYER_PUNCHES_season_average, dtype: int64

Eight player-level variables with more than 70% missing values were removed prior to imputation. Two captain-related variables contained values only for players who served as team captains, meaning the missingness reflected the absence of the role rather than missing observations. Similarly, six goalkeeper-specific punching statistics exhibited more than 70% missing values and highly zero-inflated distributions (median = 0, 75th percentile = 0), indicating that the statistics were only relevant for a small subset of players. Imputing these variables would introduce artificial information and provide little predictive value. Consequently, these variables were excluded before median imputation was applied to the remaining numerical features.

In [88]:
# Create a copy of the Home Player dataset
home_player_processed = home_player.copy()

In [89]:
high_missing_cols = [
    "PLAYER_CAPTAIN_5_last_match_sum",
    "PLAYER_CAPTAIN_season_sum",
    "PLAYER_PUNCHES_5_last_match_std",
    "PLAYER_PUNCHES_season_std",
    "PLAYER_PUNCHES_5_last_match_sum",
    "PLAYER_PUNCHES_season_sum",
    "PLAYER_PUNCHES_5_last_match_average",
    "PLAYER_PUNCHES_season_average"
]

home_player_processed.drop(columns=high_missing_cols, inplace=True)

In [90]:
print(f"Columns remaining: {home_player_processed.shape[1]}")

missing_percent = (
    home_player_processed.isnull().mean() * 100
).sort_values(ascending=False)

missing_percent.head(20)

Columns remaining: 277

PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_std       40.14
PLAYER_ACCURATE_PASSES_PERCENTAGE_season_std             34.54
PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_average   32.84
PLAYER_ACCURATE_PASSES_PERCENTAGE_season_average         29.75
PLAYER_DRIBBLED_ATTEMPTS_5_last_match_std                24.01
PLAYER_DRIBBLED_ATTEMPTS_season_std                      24.01
PLAYER_DRIBBLED_PAST_season_std                          24.01
PLAYER_SUCCESSFUL_DRIBBLES_season_std                    24.01
PLAYER_DRIBBLED_PAST_5_last_match_std                    24.01
PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_std              24.01
PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_average          22.82
PLAYER_DRIBBLED_PAST_season_average                      22.82
PLAYER_DRIBBLED_ATTEMPTS_season_average                  22.82
PLAYER_SUCCESSFUL_DRIBBLES_season_sum                    22.82
PLAYER_DRIBBLED_ATTEMPTS_5_last_match_sum                22.82
PLAYER_DRIBBLED_PAST_5_last_match_sum                    22.82
PLAYER_SUCCESSFUL_DRIBBLES_season_average                22.82
PLAYER_DRIBBLED_ATTEMPTS_5_last_match_average            22.82
PLAYER_DRIBBLED_PAST_season_sum                          22.82
PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_sum              22.82
dtype: float64

In [91]:
missing_percent[missing_percent > 40]

PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_std   40.14
dtype: float64

In [92]:
# Columns with missing values between 13% and 22.82%
missing_13_22 = missing_percent[
    (missing_percent >= 13) & (missing_percent < 22.82)
]

print(f"Number of columns: {len(missing_13_22)}")

missing_13_22

Number of columns: 73

PLAYER_PENALTIES_SAVED_5_last_match_std          22.05
PLAYER_PENALTIES_SAVED_5_last_match_sum          20.79
PLAYER_PENALTIES_SAVED_5_last_match_average      20.79
POSITION                                         18.06
PLAYER_PENALTIES_SAVED_season_std                16.57
PLAYER_PENALTIES_SAVED_season_average            15.23
PLAYER_PENALTIES_SAVED_season_sum                15.23
PLAYER_CLEARANCE_OFFLINE_5_last_match_std        15.04
PLAYER_RATING_5_last_match_std                   14.55
PLAYER_RATING_season_std                         14.55
PLAYER_ERROR_LEAD_TO_GOAL_5_last_match_std       14.41
PLAYER_PENALTIES_WON_5_last_match_std            14.29
PLAYER_PENALTIES_COMMITTED_5_last_match_std      14.17
PLAYER_ERROR_LEAD_TO_GOAL_season_std             14.06
PLAYER_CLEARANCE_OFFLINE_season_std              14.05
PLAYER_DUELS_LOST_season_std                     14.02
PLAYER_BLOCKED_SHOTS_5_last_match_std            14.02
PLAYER_BLOCKED_SHOTS_season_std                  14.02
PLAYER_BIG_CHANCES_CREATED_season_std            14.02
PLAYER_BIG_CHANCES_CREATED_5_last_match_std      14.02
PLAYER_BIG_CHANCES_MISSED_5_last_match_std       14.02
PLAYER_DUELS_LOST_5_last_match_std               14.02
PLAYER_BIG_CHANCES_MISSED_season_std             14.02
PLAYER_OFFSIDES_season_std                       13.96
PLAYER_OFFSIDES_5_last_match_std                 13.96
PLAYER_PENALTIES_WON_season_std                  13.78
PLAYER_PENALTIES_COMMITTED_season_std            13.77
PLAYER_CLEARANCE_OFFLINE_5_last_match_sum        13.64
PLAYER_CLEARANCE_OFFLINE_5_last_match_average    13.64
PLAYER_HIT_WOODWORK_5_last_match_std             13.51
PLAYER_HIT_WOODWORK_season_std                   13.38
PLAYER_ACCURATE_PASSES_season_std                13.37
PLAYER_ACCURATE_CROSSES_season_std               13.37
PLAYER_KEY_PASSES_5_last_match_std               13.37
PLAYER_DISPOSSESSED_5_last_match_std             13.37
PLAYER_ACCURATE_CROSSES_5_last_match_std         13.37
PLAYER_AERIALS_WON_season_std                    13.37
PLAYER_INTERCEPTIONS_5_last_match_std            13.37
PLAYER_DUELS_WON_5_last_match_std                13.37
PLAYER_TOTAL_DUELS_season_std                    13.37
PLAYER_FOULS_5_last_match_std                    13.37
PLAYER_TACKLES_season_std                        13.37
PLAYER_CLEARANCES_season_std                     13.37
PLAYER_SHOTS_TOTAL_season_std                    13.37
PLAYER_DISPOSSESSED_season_std                   13.37
PLAYER_FOULS_DRAWN_5_last_match_std              13.37
PLAYER_PASSES_season_std                         13.37
PLAYER_SHOTS_ON_TARGET_season_std                13.37
PLAYER_ACCURATE_PASSES_5_last_match_std          13.37
PLAYER_AERIALS_WON_5_last_match_std              13.37
PLAYER_DUELS_WON_season_std                      13.37
PLAYER_SHOTS_BLOCKED_season_std                  13.37
PLAYER_FOULS_season_std                          13.37
PLAYER_FOULS_DRAWN_season_std                    13.37
PLAYER_INTERCEPTIONS_season_std                  13.37
PLAYER_SAVES_season_std                          13.37
PLAYER_KEY_PASSES_season_std                     13.37
PLAYER_CLEARANCES_5_last_match_std               13.37
PLAYER_SAVES_INSIDE_BOX_season_std               13.37
PLAYER_TOTAL_CROSSES_season_std                  13.37
PLAYER_TACKLES_5_last_match_std                  13.37
PLAYER_SAVES_5_last_match_std                    13.37
PLAYER_SAVES_INSIDE_BOX_5_last_match_std         13.37
PLAYER_SHOTS_TOTAL_5_last_match_std              13.37
PLAYER_SHOTS_BLOCKED_5_last_match_std            13.37
PLAYER_TOTAL_DUELS_5_last_match_std              13.37
PLAYER_PASSES_5_last_match_std                   13.37
PLAYER_SHOTS_ON_TARGET_5_last_match_std          13.37
PLAYER_TOTAL_CROSSES_5_last_match_std            13.37
PLAYER_RATING_season_average                     13.15
PLAYER_RATING_5_last_match_average               13.15
PLAYER_ERROR_LEAD_TO_GOAL_5_last_match_average   13.00
PLAYER_ERROR_LEAD_TO_GOAL_5_last_match_sum       13.00
dtype: float64

In [93]:
# Columns with missing values between 12% and 13%
missing_12_13 = missing_percent[
    (missing_percent >= 12) & (missing_percent < 13)
]

print(f"Number of columns: {len(missing_12_13)}")

missing_12_13

Number of columns: 34

PLAYER_PENALTIES_WON_5_last_match_sum             12.88
PLAYER_PENALTIES_WON_5_last_match_average         12.88
PLAYER_PENALTIES_COMMITTED_5_last_match_average   12.76
PLAYER_PENALTIES_COMMITTED_5_last_match_sum       12.76
PLAYER_ERROR_LEAD_TO_GOAL_season_average          12.65
PLAYER_ERROR_LEAD_TO_GOAL_season_sum              12.65
PLAYER_CLEARANCE_OFFLINE_season_sum               12.63
PLAYER_CLEARANCE_OFFLINE_season_average           12.63
PLAYER_BIG_CHANCES_MISSED_5_last_match_average    12.61
PLAYER_DUELS_LOST_5_last_match_average            12.61
PLAYER_BIG_CHANCES_CREATED_season_sum             12.61
PLAYER_BIG_CHANCES_MISSED_season_sum              12.61
PLAYER_BIG_CHANCES_CREATED_5_last_match_sum       12.61
PLAYER_BIG_CHANCES_CREATED_5_last_match_average   12.61
PLAYER_DUELS_LOST_season_sum                      12.61
PLAYER_BLOCKED_SHOTS_season_sum                   12.61
PLAYER_DUELS_LOST_5_last_match_sum                12.61
PLAYER_BLOCKED_SHOTS_5_last_match_sum             12.61
PLAYER_BIG_CHANCES_MISSED_5_last_match_sum        12.61
PLAYER_BIG_CHANCES_CREATED_season_average         12.61
PLAYER_BLOCKED_SHOTS_5_last_match_average         12.61
PLAYER_BIG_CHANCES_MISSED_season_average          12.61
PLAYER_DUELS_LOST_season_average                  12.61
PLAYER_BLOCKED_SHOTS_season_average               12.61
PLAYER_OFFSIDES_season_average                    12.55
PLAYER_OFFSIDES_season_sum                        12.55
PLAYER_OFFSIDES_5_last_match_average              12.55
PLAYER_OFFSIDES_5_last_match_sum                  12.55
PLAYER_PENALTIES_WON_season_sum                   12.36
PLAYER_PENALTIES_WON_season_average               12.36
PLAYER_PENALTIES_COMMITTED_season_sum             12.35
PLAYER_PENALTIES_COMMITTED_season_average         12.35
PLAYER_HIT_WOODWORK_5_last_match_average          12.08
PLAYER_HIT_WOODWORK_5_last_match_sum              12.08
dtype: float64

In [94]:
# Columns with missing values between 10% and 12%
missing_10_12 = missing_percent[
    (missing_percent >= 10) & (missing_percent < 12)
]

print(f"Number of columns: {len(missing_10_12)}")

missing_10_12

Number of columns: 80

PLAYER_HIT_WOODWORK_season_average                  11.95
PLAYER_HIT_WOODWORK_season_sum                      11.95
PLAYER_SHOTS_TOTAL_5_last_match_sum                 11.93
PLAYER_SAVES_5_last_match_average                   11.93
PLAYER_SHOTS_ON_TARGET_5_last_match_sum             11.93
PLAYER_SHOTS_BLOCKED_5_last_match_sum               11.93
PLAYER_SAVES_INSIDE_BOX_5_last_match_sum            11.93
PLAYER_SAVES_INSIDE_BOX_5_last_match_average        11.93
PLAYER_PASSES_5_last_match_sum                      11.93
PLAYER_TOTAL_CROSSES_5_last_match_average           11.93
PLAYER_FOULS_season_sum                             11.93
PLAYER_SHOTS_BLOCKED_5_last_match_average           11.93
PLAYER_TOTAL_DUELS_5_last_match_average             11.93
PLAYER_SAVES_5_last_match_sum                       11.93
PLAYER_DUELS_WON_season_sum                         11.93
PLAYER_SHOTS_ON_TARGET_5_last_match_average         11.93
PLAYER_SHOTS_TOTAL_5_last_match_average             11.93
PLAYER_CLEARANCES_5_last_match_average              11.93
PLAYER_FOULS_DRAWN_5_last_match_average             11.93
PLAYER_FOULS_5_last_match_average                   11.93
PLAYER_FOULS_DRAWN_season_sum                       11.93
PLAYER_AERIALS_WON_season_sum                       11.93
PLAYER_INTERCEPTIONS_5_last_match_average           11.93
PLAYER_AERIALS_WON_5_last_match_average             11.93
PLAYER_CLEARANCES_season_sum                        11.93
PLAYER_ACCURATE_PASSES_5_last_match_average         11.93
PLAYER_ACCURATE_CROSSES_5_last_match_average        11.93
PLAYER_KEY_PASSES_5_last_match_average              11.93
PLAYER_TOTAL_DUELS_5_last_match_sum                 11.93
PLAYER_ACCURATE_PASSES_season_sum                   11.93
PLAYER_DISPOSSESSED_5_last_match_average            11.93
PLAYER_TOTAL_CROSSES_5_last_match_sum               11.93
PLAYER_ACCURATE_CROSSES_season_sum                  11.93
PLAYER_DUELS_WON_5_last_match_average               11.93
PLAYER_DISPOSSESSED_season_sum                      11.93
PLAYER_PASSES_5_last_match_average                  11.93
PLAYER_TACKLES_5_last_match_sum                     11.93
PLAYER_DUELS_WON_5_last_match_sum                   11.93
PLAYER_SHOTS_TOTAL_season_sum                       11.93
PLAYER_INTERCEPTIONS_season_average                 11.93
PLAYER_TACKLES_season_sum                           11.93
PLAYER_TACKLES_season_average                       11.93
PLAYER_TOTAL_CROSSES_season_sum                     11.93
PLAYER_TOTAL_DUELS_season_sum                       11.93
PLAYER_TOTAL_CROSSES_season_average                 11.93
PLAYER_ACCURATE_CROSSES_season_average              11.93
PLAYER_KEY_PASSES_5_last_match_sum                  11.93
PLAYER_ACCURATE_PASSES_season_average               11.93
PLAYER_AERIALS_WON_season_average                   11.93
PLAYER_TOTAL_DUELS_season_average                   11.93
PLAYER_TACKLES_5_last_match_average                 11.93
PLAYER_CLEARANCES_season_average                    11.93
PLAYER_PASSES_season_average                        11.93
PLAYER_KEY_PASSES_season_average                    11.93
PLAYER_DISPOSSESSED_season_average                  11.93
PLAYER_DUELS_WON_season_average                     11.93
PLAYER_FOULS_season_average                         11.93
PLAYER_SHOTS_TOTAL_season_average                   11.93
PLAYER_FOULS_DRAWN_season_average                   11.93
PLAYER_SHOTS_ON_TARGET_season_average               11.93
PLAYER_DISPOSSESSED_5_last_match_sum                11.93
PLAYER_SAVES_season_average                         11.93
PLAYER_INTERCEPTIONS_5_last_match_sum               11.93
PLAYER_SAVES_INSIDE_BOX_season_average              11.93
PLAYER_SHOTS_BLOCKED_season_average                 11.93
PLAYER_FOULS_DRAWN_5_last_match_sum                 11.93
PLAYER_FOULS_5_last_match_sum                       11.93
PLAYER_INTERCEPTIONS_season_sum                     11.93
PLAYER_KEY_PASSES_season_sum                        11.93
PLAYER_CLEARANCES_5_last_match_sum                  11.93
PLAYER_SHOTS_ON_TARGET_season_sum                   11.93
PLAYER_AERIALS_WON_5_last_match_sum                 11.93
PLAYER_ACCURATE_PASSES_5_last_match_sum             11.93
PLAYER_ACCURATE_CROSSES_5_last_match_sum            11.93
PLAYER_PASSES_season_sum                            11.93
PLAYER_SAVES_season_sum                             11.93
PLAYER_SAVES_INSIDE_BOX_season_sum                  11.93
PLAYER_SHOTS_BLOCKED_season_sum                     11.93
PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_std   10.04
PLAYER_GOALKEEPER_GOALS_CONCEDED_season_std         10.04
dtype: float64

In [95]:
# Columns with missing values between 0% and 10%
missing_0_10 = missing_percent[
    (missing_percent >= 0) & (missing_percent < 10)
]

print(f"Number of columns: {len(missing_0_10)}")

missing_0_10

Number of columns: 68

PLAYER_GOALKEEPER_GOALS_CONCEDED_season_sum             8.57
PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_average   8.57
PLAYER_GOALKEEPER_GOALS_CONCEDED_season_average         8.57
PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_sum       8.57
PLAYER_PENALTIES_MISSES_5_last_match_std                5.65
PLAYER_REDCARDS_5_last_match_std                        4.61
PLAYER_PENALTIES_MISSES_5_last_match_sum                4.08
PLAYER_PENALTIES_MISSES_5_last_match_average            4.08
PLAYER_OWN_GOALS_5_last_match_std                       3.65
PLAYER_PENALTIES_MISSES_season_std                      3.60
PLAYER_REDCARDS_season_std                              3.42
PLAYER_OWN_GOALS_season_std                             3.24
PLAYER_STARTING_LINEUP_5_last_match_std                 3.14
PLAYER_PENALTIES_SCORED_5_last_match_std                3.14
PLAYER_MINUTES_PLAYED_5_last_match_std                  3.14
PLAYER_GOALS_CONCEDED_5_last_match_std                  3.14
PLAYER_ASSISTS_5_last_match_std                         3.14
PLAYER_GOALS_5_last_match_std                           3.14
PLAYER_YELLOWCARDS_5_last_match_std                     3.14
PLAYER_GOALS_season_std                                 3.14
PLAYER_ASSISTS_season_std                               3.14
PLAYER_GOALS_CONCEDED_season_std                        3.14
PLAYER_MINUTES_PLAYED_season_std                        3.14
PLAYER_PENALTIES_SCORED_season_std                      3.14
PLAYER_STARTING_LINEUP_season_std                       3.14
PLAYER_YELLOWCARDS_season_std                           3.14
PLAYER_REDCARDS_5_last_match_average                    3.04
PLAYER_REDCARDS_5_last_match_sum                        3.04
PLAYER_OWN_GOALS_5_last_match_sum                       2.04
PLAYER_OWN_GOALS_5_last_match_average                   2.04
PLAYER_PENALTIES_MISSES_season_average                  1.99
PLAYER_PENALTIES_MISSES_season_sum                      1.99
PLAYER_REDCARDS_season_average                          1.82
PLAYER_REDCARDS_season_sum                              1.82
PLAYER_OWN_GOALS_season_sum                             1.63
PLAYER_OWN_GOALS_season_average                         1.63
PLAYER_PENALTIES_SCORED_season_average                  1.52
PLAYER_ASSISTS_season_average                           1.52
PLAYER_GOALS_season_average                             1.52
PLAYER_GOALS_CONCEDED_season_average                    1.52
PLAYER_STARTING_LINEUP_season_sum                       1.52
PLAYER_MINUTES_PLAYED_season_average                    1.52
PLAYER_PENALTIES_SCORED_season_sum                      1.52
PLAYER_MINUTES_PLAYED_season_sum                        1.52
PLAYER_GOALS_CONCEDED_season_sum                        1.52
PLAYER_GOALS_season_sum                                 1.52
PLAYER_ASSISTS_season_sum                               1.52
PLAYER_YELLOWCARDS_season_sum                           1.52
PLAYER_STARTING_LINEUP_5_last_match_average             1.52
PLAYER_STARTING_LINEUP_season_average                   1.52
PLAYER_YELLOWCARDS_season_average                       1.52
PLAYER_YELLOWCARDS_5_last_match_average                 1.52
PLAYER_PENALTIES_SCORED_5_last_match_average            1.52
PLAYER_MINUTES_PLAYED_5_last_match_average              1.52
PLAYER_GOALS_CONCEDED_5_last_match_average              1.52
PLAYER_GOALS_5_last_match_average                       1.52
PLAYER_ASSISTS_5_last_match_average                     1.52
PLAYER_YELLOWCARDS_5_last_match_sum                     1.52
PLAYER_STARTING_LINEUP_5_last_match_sum                 1.52
PLAYER_PENALTIES_SCORED_5_last_match_sum                1.52
PLAYER_MINUTES_PLAYED_5_last_match_sum                  1.52
PLAYER_GOALS_CONCEDED_5_last_match_sum                  1.52
PLAYER_GOALS_5_last_match_sum                           1.52
PLAYER_ASSISTS_5_last_match_sum                         1.52
LEAGUE                                                  0.00
PLAYER_NAME                                             0.00
TEAM_NAME                                               0.00
ID                                                      0.00
dtype: float64

Investigating Goalkeeper Family Statistics

In [96]:
goalkeeper_cols = [col for col in home_player_processed.columns
                   if "GOALKEEPER" in col]

print(goalkeeper_cols)

['PLAYER_GOALKEEPER_GOALS_CONCEDED_season_sum', 'PLAYER_GOALKEEPER_GOALS_CONCEDED_season_average', 'PLAYER_GOALKEEPER_GOALS_CONCEDED_season_std', 'PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_sum', 'PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_average', 'PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_std']

In [97]:
missing_percent[goalkeeper_cols].sort_values(ascending=False)

PLAYER_GOALKEEPER_GOALS_CONCEDED_season_std             10.04
PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_std       10.04
PLAYER_GOALKEEPER_GOALS_CONCEDED_season_sum              8.57
PLAYER_GOALKEEPER_GOALS_CONCEDED_season_average          8.57
PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_sum        8.57
PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_average    8.57
dtype: float64

In [98]:
goalkeeper_rows = home_player_processed[
    home_player_processed["POSITION"] == "goalkeeper"
]

goalkeeper_rows[goalkeeper_cols].isnull().mean() * 100

PLAYER_GOALKEEPER_GOALS_CONCEDED_season_sum             3.50
PLAYER_GOALKEEPER_GOALS_CONCEDED_season_average         3.50
PLAYER_GOALKEEPER_GOALS_CONCEDED_season_std             4.85
PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_sum       3.50
PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_average   3.50
PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_std       4.85
dtype: float64

In [99]:
non_goalkeeper_rows = home_player_processed[
    home_player_processed["POSITION"] != "goalkeeper"
]

non_goalkeeper_rows[goalkeeper_cols].isnull().mean() * 100

PLAYER_GOALKEEPER_GOALS_CONCEDED_season_sum              9.15
PLAYER_GOALKEEPER_GOALS_CONCEDED_season_average          9.15
PLAYER_GOALKEEPER_GOALS_CONCEDED_season_std             10.63
PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_sum        9.15
PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_average    9.15
PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_std       10.63
dtype: float64

In [100]:
# Numerical columns
numerical_cols = home_player_processed.select_dtypes(include=['number']).columns.tolist()

# Categorical columns
categorical_cols = home_player_processed.select_dtypes(include=['object', 'category']).columns.tolist()

print("Numerical columns:", len(numerical_cols))
print("Categorical columns:", len(categorical_cols))

Numerical columns: 273
Categorical columns: 4

In [101]:
home_player_processed[categorical_cols].isnull().sum().sort_values(ascending=False)

POSITION       42820
LEAGUE             0
TEAM_NAME          0
PLAYER_NAME        0
dtype: int64

In [102]:
missing_numeric = (
    home_player_processed[numerical_cols]
    .isnull()
    .mean() * 100
).sort_values(ascending=False)

missing_numeric.head(30)

PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_std       40.14
PLAYER_ACCURATE_PASSES_PERCENTAGE_season_std             34.54
PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_average   32.84
PLAYER_ACCURATE_PASSES_PERCENTAGE_season_average         29.75
PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_std              24.01
PLAYER_DRIBBLED_PAST_5_last_match_std                    24.01
PLAYER_DRIBBLED_ATTEMPTS_5_last_match_std                24.01
PLAYER_DRIBBLED_PAST_season_std                          24.01
PLAYER_SUCCESSFUL_DRIBBLES_season_std                    24.01
PLAYER_DRIBBLED_ATTEMPTS_season_std                      24.01
PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_sum              22.82
PLAYER_DRIBBLED_PAST_5_last_match_sum                    22.82
PLAYER_DRIBBLED_ATTEMPTS_5_last_match_sum                22.82
PLAYER_SUCCESSFUL_DRIBBLES_season_sum                    22.82
PLAYER_DRIBBLED_ATTEMPTS_5_last_match_average            22.82
PLAYER_DRIBBLED_PAST_season_sum                          22.82
PLAYER_DRIBBLED_PAST_5_last_match_average                22.82
PLAYER_DRIBBLED_PAST_season_average                      22.82
PLAYER_SUCCESSFUL_DRIBBLES_season_average                22.82
PLAYER_DRIBBLED_ATTEMPTS_season_average                  22.82
PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_average          22.82
PLAYER_DRIBBLED_ATTEMPTS_season_sum                      22.82
PLAYER_PENALTIES_SAVED_5_last_match_std                  22.05
PLAYER_PENALTIES_SAVED_5_last_match_sum                  20.79
PLAYER_PENALTIES_SAVED_5_last_match_average              20.79
PLAYER_PENALTIES_SAVED_season_std                        16.57
PLAYER_PENALTIES_SAVED_season_sum                        15.23
PLAYER_PENALTIES_SAVED_season_average                    15.23
PLAYER_CLEARANCE_OFFLINE_5_last_match_std                15.04
PLAYER_RATING_season_std                                 14.55
dtype: float64

In [103]:
# Accurate Passes

In [104]:
pass_cols = [col for col in home_player_processed.columns
             if "ACCURATE_PASSES_PERCENTAGE" in col]

pass_cols

['PLAYER_ACCURATE_PASSES_PERCENTAGE_season_average',
 'PLAYER_ACCURATE_PASSES_PERCENTAGE_season_std',
 'PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_average',
 'PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_std']

In [105]:
missing_numeric[pass_cols]

PLAYER_ACCURATE_PASSES_PERCENTAGE_season_average         29.75
PLAYER_ACCURATE_PASSES_PERCENTAGE_season_std             34.54
PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_average   32.84
PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_std       40.14
dtype: float64

In [106]:
home_player_processed[pass_cols].describe()

,PLAYER_ACCURATE_PASSES_PERCENTAGE_season_average,PLAYER_ACCURATE_PASSES_PERCENTAGE_season_std,PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_average,PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_std
count,166540.00,155188.00,159231.00,141918.00
mean,64.77,27.42,66.45,23.28
std,15.33,14.41,16.29,15.30
min,0.00,0.00,0.00,0.00
25%,57.00,17.00,57.00,13.00
50%,67.00,25.00,69.00,20.00
75%,75.00,35.00,78.00,30.00
max,100.00,100.00,100.00,100.00

In [107]:
for col in pass_cols:
    print(f"\n{col}")
    print(
        home_player_processed
        .groupby("POSITION")[col]
        .apply(lambda x: x.notna().sum())
    )

PLAYER_ACCURATE_PASSES_PERCENTAGE_season_average
POSITION
attacker      19877
defender      51714
goalkeeper    13056
midfielder    61019
Name: PLAYER_ACCURATE_PASSES_PERCENTAGE_season_average, dtype: int64

PLAYER_ACCURATE_PASSES_PERCENTAGE_season_std
POSITION
attacker      19052
defender      48239
goalkeeper    11544
midfielder    57578
Name: PLAYER_ACCURATE_PASSES_PERCENTAGE_season_std, dtype: int64

PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_average
POSITION
attacker      19549
defender      49534
goalkeeper    10999
midfielder    59573
Name: PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_average, dtype: int64

PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_std
POSITION
attacker      18038
defender      43686
goalkeeper     9583
midfielder    53913
Name: PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_std, dtype: int64

In [108]:
home_player_processed.groupby("POSITION")[pass_cols].median()

,PLAYER_ACCURATE_PASSES_PERCENTAGE_season_average,PLAYER_ACCURATE_PASSES_PERCENTAGE_season_std,PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_average,PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_std
POSITION,,,,
attacker,62.00,33.00,64.00,25.00
defender,69.00,22.00,71.00,17.00
goalkeeper,46.00,33.00,48.00,27.00
midfielder,70.00,23.00,71.00,19.00

In [109]:
for col in pass_cols:
    home_player_processed[col] = (
        home_player_processed
        .groupby("POSITION")[col]
        .transform(lambda x: x.fillna(x.median()))
    )

In [110]:
home_player_processed[pass_cols].isnull().sum()

PLAYER_ACCURATE_PASSES_PERCENTAGE_season_average          42820
PLAYER_ACCURATE_PASSES_PERCENTAGE_season_std              42820
PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_average    42820
PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_std        42820
dtype: int64

In [111]:
home_player_processed.loc[
    home_player_processed["POSITION"].isna(),
    pass_cols
].isnull().sum()

PLAYER_ACCURATE_PASSES_PERCENTAGE_season_average          42820
PLAYER_ACCURATE_PASSES_PERCENTAGE_season_std              42820
PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_average    42820
PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_std        42820
dtype: int64

In [112]:
# Number of rows with missing POSITION
home_player_processed["POSITION"].isnull().sum()

np.int64(42820)

In [113]:
# Look at a few of those rows
home_player_processed[
    home_player_processed["POSITION"].isnull()
].head(10)

,ID,LEAGUE,TEAM_NAME,POSITION,PLAYER_NAME,PLAYER_ACCURATE_CROSSES_season_sum,PLAYER_ACCURATE_PASSES_season_sum,PLAYER_AERIALS_WON_season_sum,PLAYER_ASSISTS_season_sum,PLAYER_BIG_CHANCES_CREATED_season_sum,PLAYER_BIG_CHANCES_MISSED_season_sum,PLAYER_BLOCKED_SHOTS_season_sum,PLAYER_CLEARANCES_season_sum,PLAYER_CLEARANCE_OFFLINE_season_sum,PLAYER_DISPOSSESSED_season_sum,PLAYER_DRIBBLED_ATTEMPTS_season_sum,PLAYER_DRIBBLED_PAST_season_sum,PLAYER_DUELS_LOST_season_sum,PLAYER_DUELS_WON_season_sum,PLAYER_ERROR_LEAD_TO_GOAL_season_sum,PLAYER_FOULS_season_sum,PLAYER_FOULS_DRAWN_season_sum,PLAYER_GOALKEEPER_GOALS_CONCEDED_season_sum,PLAYER_GOALS_season_sum,PLAYER_GOALS_CONCEDED_season_sum,PLAYER_HIT_WOODWORK_season_sum,PLAYER_INTERCEPTIONS_season_sum,PLAYER_KEY_PASSES_season_sum,PLAYER_MINUTES_PLAYED_season_sum,PLAYER_OFFSIDES_season_sum,PLAYER_OWN_GOALS_season_sum,PLAYER_PASSES_season_sum,PLAYER_PENALTIES_COMMITTED_season_sum,PLAYER_PENALTIES_MISSES_season_sum,PLAYER_PENALTIES_SAVED_season_sum,PLAYER_PENALTIES_SCORED_season_sum,PLAYER_PENALTIES_WON_season_sum,PLAYER_REDCARDS_season_sum,PLAYER_SAVES_season_sum,PLAYER_SAVES_INSIDE_BOX_season_sum,PLAYER_SHOTS_BLOCKED_season_sum,PLAYER_SHOTS_ON_TARGET_season_sum,PLAYER_SHOTS_TOTAL_season_sum,PLAYER_STARTING_LINEUP_season_sum,PLAYER_SUCCESSFUL_DRIBBLES_season_sum,PLAYER_TACKLES_season_sum,PLAYER_TOTAL_CROSSES_season_sum,PLAYER_TOTAL_DUELS_season_sum,PLAYER_YELLOWCARDS_season_sum,PLAYER_ACCURATE_CROSSES_season_average,PLAYER_ACCURATE_PASSES_season_average,PLAYER_ACCURATE_PASSES_PERCENTAGE_season_average,PLAYER_AERIALS_WON_season_average,PLAYER_ASSISTS_season_average,PLAYER_BIG_CHANCES_CREATED_season_average,PLAYER_BIG_CHANCES_MISSED_season_average,PLAYER_BLOCKED_SHOTS_season_average,PLAYER_CLEARANCES_season_average,PLAYER_CLEARANCE_OFFLINE_season_average,PLAYER_DISPOSSESSED_season_average,PLAYER_DRIBBLED_ATTEMPTS_season_average,PLAYER_DRIBBLED_PAST_season_average,PLAYER_DUELS_LOST_season_average,PLAYER_DUELS_WON_season_average,PLAYER_ERROR_LEAD_TO_GOAL_season_average,PLAYER_FOULS_season_average,PLAYER_FOULS_DRAWN_season_average,PLAYER_GOALKEEPER_GOALS_CONCEDED_season_average,PLAYER_GOALS_season_average,PLAYER_GOALS_CONCEDED_season_average,PLAYER_HIT_WOODWORK_season_average,PLAYER_INTERCEPTIONS_season_average,PLAYER_KEY_PASSES_season_average,PLAYER_MINUTES_PLAYED_season_average,PLAYER_OFFSIDES_season_average,PLAYER_OWN_GOALS_season_average,PLAYER_PASSES_season_average,PLAYER_PENALTIES_COMMITTED_season_average,PLAYER_PENALTIES_MISSES_season_average,PLAYER_PENALTIES_SAVED_season_average,PLAYER_PENALTIES_SCORED_season_average,PLAYER_PENALTIES_WON_season_average,PLAYER_RATING_season_average,PLAYER_REDCARDS_season_average,PLAYER_SAVES_season_average,PLAYER_SAVES_INSIDE_BOX_season_average,PLAYER_SHOTS_BLOCKED_season_average,PLAYER_SHOTS_ON_TARGET_season_average,PLAYER_SHOTS_TOTAL_season_average,PLAYER_STARTING_LINEUP_season_average,PLAYER_SUCCESSFUL_DRIBBLES_season_average,PLAYER_TACKLES_season_average,PLAYER_TOTAL_CROSSES_season_average,PLAYER_TOTAL_DUELS_season_average,PLAYER_YELLOWCARDS_season_average,PLAYER_ACCURATE_CROSSES_season_std,PLAYER_ACCURATE_PASSES_season_std,PLAYER_ACCURATE_PASSES_PERCENTAGE_season_std,PLAYER_AERIALS_WON_season_std,PLAYER_ASSISTS_season_std,PLAYER_BIG_CHANCES_CREATED_season_std,PLAYER_BIG_CHANCES_MISSED_season_std,PLAYER_BLOCKED_SHOTS_season_std,PLAYER_CLEARANCES_season_std,PLAYER_CLEARANCE_OFFLINE_season_std,PLAYER_DISPOSSESSED_season_std,PLAYER_DRIBBLED_ATTEMPTS_season_std,PLAYER_DRIBBLED_PAST_season_std,PLAYER_DUELS_LOST_season_std,PLAYER_DUELS_WON_season_std,PLAYER_ERROR_LEAD_TO_GOAL_season_std,PLAYER_FOULS_season_std,PLAYER_FOULS_DRAWN_season_std,PLAYER_GOALKEEPER_GOALS_CONCEDED_season_std,PLAYER_GOALS_season_std,PLAYER_GOALS_CONCEDED_season_std,PLAYER_HIT_WOODWORK_season_std,PLAYER_INTERCEPTIONS_season_std,PLAYER_KEY_PASSES_season_std,PLAYER_MINUTES_PLAYED_season_std,PLAYER_OFFSIDES_season_std,PLAYER_OWN_GOALS_season_std,PLAYER_PASSES_season_std,PLAYER_PENALTIES_COMMITTED_season_std,PLAYER_PENALTIES_MISSES_season_std,PLAYER_PENALTIES_SAVED_season_std,PLAYER_PENALTIES_SCORED_season_std,PLAYER_PENALTIES_WON_season_std,PLAYER_RATING_season_std,PLAYER_REDCARDS_season_std,PLAYER_SAVES_season_std,PLAYER_SAVES_INSIDE_BOX_season_std,PLAYER_SHOTS_BLOCKED_season_std,PLAYER_SHOTS_ON_TARGET_season_std,PLAYER_SHOTS_TOTAL_season_std,PLAYER_STARTING_LINEUP_season_std,PLAYER_SUCCESSFUL_DRIBBLES_season_std,PLAYER_TACKLES_season_std,PLAYER_TOTAL_CROSSES_season_std,PLAYER_TOTAL_DUELS_season_std,PLAYER_YELLOWCARDS_season_std,PLAYER_ACCURATE_CROSSES_5_last_match_sum,PLAYER_ACCURATE_PASSES_5_last_match_sum,PLAYER_AERIALS_WON_5_last_match_sum,PLAYER_ASSISTS_5_last_match_sum,PLAYER_BIG_CHANCES_CREATED_5_last_match_sum,PLAYER_BIG_CHANCES_MISSED_5_last_match_sum,PLAYER_BLOCKED_SHOTS_5_last_match_sum,PLAYER_CLEARANCES_5_last_match_sum,PLAYER_CLEARANCE_OFFLINE_5_last_match_sum,PLAYER_DISPOSSESSED_5_last_match_sum,PLAYER_DRIBBLED_ATTEMPTS_5_last_match_sum,PLAYER_DRIBBLED_PAST_5_last_match_sum,PLAYER_DUELS_LOST_5_last_match_sum,PLAYER_DUELS_WON_5_last_match_sum,PLAYER_ERROR_LEAD_TO_GOAL_5_last_match_sum,PLAYER_FOULS_5_last_match_sum,PLAYER_FOULS_DRAWN_5_last_match_sum,PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_sum,PLAYER_GOALS_5_last_match_sum,PLAYER_GOALS_CONCEDED_5_last_match_sum,PLAYER_HIT_WOODWORK_5_last_match_sum,PLAYER_INTERCEPTIONS_5_last_match_sum,PLAYER_KEY_PASSES_5_last_match_sum,PLAYER_MINUTES_PLAYED_5_last_match_sum,PLAYER_OFFSIDES_5_last_match_sum,PLAYER_OWN_GOALS_5_last_match_sum,PLAYER_PASSES_5_last_match_sum,PLAYER_PENALTIES_COMMITTED_5_last_match_sum,PLAYER_PENALTIES_MISSES_5_last_match_sum,PLAYER_PENALTIES_SAVED_5_last_match_sum,PLAYER_PENALTIES_SCORED_5_last_match_sum,PLAYER_PENALTIES_WON_5_last_match_sum,PLAYER_REDCARDS_5_last_match_sum,PLAYER_SAVES_5_last_match_sum,PLAYER_SAVES_INSIDE_BOX_5_last_match_sum,PLAYER_SHOTS_BLOCKED_5_last_match_sum,PLAYER_SHOTS_ON_TARGET_5_last_match_sum,PLAYER_SHOTS_TOTAL_5_last_match_sum,PLAYER_STARTING_LINEUP_5_last_match_sum,PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_sum,PLAYER_TACKLES_5_last_match_sum,PLAYER_TOTAL_CROSSES_5_last_match_sum,PLAYER_TOTAL_DUELS_5_last_match_sum,PLAYER_YELLOWCARDS_5_last_match_sum,PLAYER_ACCURATE_CROSSES_5_last_match_average,PLAYER_ACCURATE_PASSES_5_last_match_average,PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_average,PLAYER_AERIALS_WON_5_last_match_average,PLAYER_ASSISTS_5_last_match_average,PLAYER_BIG_CHANCES_CREATED_5_last_match_average,PLAYER_BIG_CHANCES_MISSED_5_last_match_average,PLAYER_BLOCKED_SHOTS_5_last_match_average,PLAYER_CLEARANCES_5_last_match_average,PLAYER_CLEARANCE_OFFLINE_5_last_match_average,PLAYER_DISPOSSESSED_5_last_match_average,PLAYER_DRIBBLED_ATTEMPTS_5_last_match_average,PLAYER_DRIBBLED_PAST_5_last_match_average,PLAYER_DUELS_LOST_5_last_match_average,PLAYER_DUELS_WON_5_last_match_average,PLAYER_ERROR_LEAD_TO_GOAL_5_last_match_average,PLAYER_FOULS_5_last_match_average,PLAYER_FOULS_DRAWN_5_last_match_average,PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_average,PLAYER_GOALS_5_last_match_average,PLAYER_GOALS_CONCEDED_5_last_match_average,PLAYER_HIT_WOODWORK_5_last_match_average,PLAYER_INTERCEPTIONS_5_last_match_average,PLAYER_KEY_PASSES_5_last_match_average,PLAYER_MINUTES_PLAYED_5_last_match_average,PLAYER_OFFSIDES_5_last_match_average,PLAYER_OWN_GOALS_5_last_match_average,PLAYER_PASSES_5_last_match_average,PLAYER_PENALTIES_COMMITTED_5_last_match_average,PLAYER_PENALTIES_MISSES_5_last_match_average,PLAYER_PENALTIES_SAVED_5_last_match_average,PLAYER_PENALTIES_SCORED_5_last_match_average,PLAYER_PENALTIES_WON_5_last_match_average,PLAYER_RATING_5_last_match_average,PLAYER_REDCARDS_5_last_match_average,PLAYER_SAVES_5_last_match_average,PLAYER_SAVES_INSIDE_BOX_5_last_match_average,PLAYER_SHOTS_BLOCKED_5_last_match_average,PLAYER_SHOTS_ON_TARGET_5_last_match_average,PLAYER_SHOTS_TOTAL_5_last_match_average,PLAYER_STARTING_LINEUP_5_last_match_average,PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_average,PLAYER_TACKLES_5_last_match_average,PLAYER_TOTAL_CROSSES_5_last_match_average,PLAYER_TOTAL_DUELS_5_last_match_average,PLAYER_YELLOWCARDS_5_last_match_average,PLAYER_ACCURATE_CROSSES_5_last_match_std,PLAYER_ACCURATE_PASSES_5_last_match_std,PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_std,PLAYER_AERIALS_WON_5_last_match_std,PLAYER_ASSISTS_5_last_match_std,PLAYER_BIG_CHANCES_CREATED_5_last_match_std,PLAYER_BIG_CHANCES_MISSED_5_last_match_std,PLAYER_BLOCKED_SHOTS_5_last_match_std,PLAYER_CLEARANCES_5_last_match_std,PLAYER_CLEARANCE_OFFLINE_5_last_match_std,PLAYER_DISPOSSESSED_5_last_match_std,PLAYER_DRIBBLED_ATTEMPTS_5_last_match_std,PLAYER_DRIBBLED_PAST_5_last_match_std,PLAYER_DUELS_LOST_5_last_match_std,PLAYER_DUELS_WON_5_last_match_std,PLAYER_ERROR_LEAD_TO_GOAL_5_last_match_std,PLAYER_FOULS_5_last_match_std,PLAYER_FOULS_DRAWN_5_last_match_std,PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_std,PLAYER_GOALS_5_last_match_std,PLAYER_GOALS_CONCEDED_5_last_match_std,PLAYER_HIT_WOODWORK_5_last_match_std,PLAYER_INTERCEPTIONS_5_last_match_std,PLAYER_KEY_PASSES_5_last_match_std,PLAYER_MINUTES_PLAYED_5_last_match_std,PLAYER_OFFSIDES_5_last_match_std,PLAYER_OWN_GOALS_5_last_match_std,PLAYER_PASSES_5_last_match_std,PLAYER_PENALTIES_COMMITTED_5_last_match_std,PLAYER_PENALTIES_MISSES_5_last_match_std,PLAYER_PENALTIES_SAVED_5_last_match_std,PLAYER_PENALTIES_SCORED_5_last_match_std,PLAYER_PENALTIES_WON_5_last_match_std,PLAYER_RATING_5_last_match_std,PLAYER_REDCARDS_5_last_match_std,PLAYER_SAVES_5_last_match_std,PLAYER_SAVES_INSIDE_BOX_5_last_match_std,PLAYER_SHOTS_BLOCKED_5_last_match_std,PLAYER_SHOTS_ON_TARGET_5_last_match_std,PLAYER_SHOTS_TOTAL_5_last_match_std,PLAYER_STARTING_LINEUP_5_last_match_std,PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_std,PLAYER_TACKLES_5_last_match_std,PLAYER_TOTAL_CROSSES_5_last_match_std,PLAYER_TOTAL_DUELS_5_last_match_std,PLAYER_YELLOWCARDS_5_last_match_std
4,0,Ligue 1,Toulouse,NaN,Efthymios Koulouris,2.00,23.00,27.00,14.00,8.00,37.00,12.00,7.00,0.00,33.00,11.00,9.00,53.00,29.00,0.00,28.00,16.00,0.00,44.00,84.00,100.00,6.00,24.00,77.00,20.00,0.00,28.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,26.00,58.00,59.00,76.00,16.00,5.00,4.00,44.00,0.00,2.00,19.00,NaN,23.00,7.00,7.00,23.00,10.00,5.00,0.00,30.00,6.00,6.00,49.00,22.00,0.00,17.00,11.00,0.00,37.00,40.00,76.00,3.00,20.00,77.00,19.00,0.00,24.00,0.00,0.00,0.00,0.00,0.00,87.00,0.00,0.00,0.00,25.00,29.00,35.00,76.00,6.00,5.00,3.00,41.00,0.00,11.00,16.00,NaN,22.00,28.00,24.00,39.00,22.00,13.00,0.00,44.00,18.00,14.00,47.00,21.00,0.00,27.00,17.00,0.00,53.00,36.00,100.00,10.00,36.00,43.00,48.00,0.00,17.00,0.00,0.00,0.00,0.00,0.00,6.00,0.00,0.00,0.00,29.00,37.00,71.00,62.00,21.00,11.00,12.00,40.00,0.00,6.00,23.00,32.00,0.00,0.00,14.00,12.00,2.00,0.00,23.00,10.00,14.00,49.00,28.00,0.00,11.00,20.00,0.00,20.00,92.00,100.00,0.00,27.00,89.00,0.00,0.00,27.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,25.00,30.00,40.00,80.00,8.00,4.00,6.00,48.00,0.00,5.00,23.00,NaN,32.00,0.00,0.00,14.00,12.00,2.00,0.00,23.00,10.00,14.00,49.00,28.00,0.00,10.00,20.00,0.00,20.00,60.00,100.00,0.00,27.00,89.00,0.00,0.00,27.00,0.00,0.00,0.00,0.00,0.00,83.00,0.00,0.00,0.00,25.00,30.00,40.00,80.00,8.00,4.00,4.00,48.00,0.00,12.00,2.00,NaN,16.00,0.00,0.00,26.00,25.00,6.00,0.00,36.00,22.00,20.00,45.00,20.00,0.00,29.00,15.00,0.00,50.00,31.00,100.00,0.00,43.00,31.00,0.00,0.00,2.00,0.00,0.00,0.00,0.00,0.00,5.00,0.00,0.00,0.00,26.00,20.00,42.00,63.00,17.00,10.00,13.00,27.00,0.00
9,0,Ligue 1,Toulouse,NaN,Aaron Leya Iseka,0.00,5.00,10.00,0.00,0.00,0.00,0.00,6.00,0.00,30.00,0.00,9.00,32.00,11.00,0.00,28.00,16.00,0.00,11.00,56.00,0.00,0.00,5.00,25.00,6.00,0.00,7.00,0.00,0.00,0.00,0.00,100.00,0.00,0.00,0.00,13.00,29.00,19.00,15.00,0.00,0.00,0.00,24.00,0.00,0.00,5.00,NaN,10.00,0.00,0.00,0.00,0.00,5.00,0.00,30.00,0.00,7.00,32.00,9.00,0.00,18.00,12.00,0.00,10.00,29.00,0.00,0.00,4.00,27.00,7.00,0.00,6.00,0.00,0.00,0.00,0.00,75.00,55.00,0.00,0.00,0.00,13.00,16.00,12.00,16.00,0.00,0.00,0.00,24.00,0.00,0.00,12.00,NaN,23.00,0.00,0.00,0.00,0.00,13.00,0.00,50.00,0.00,23.00,42.00,21.00,0.00,31.00,23.00,0.00,31.00,24.00,0.00,0.00,13.00,40.00,23.00,0.00,15.00,0.00,0.00,0.00,0.00,86.00,60.00,0.00,0.00,0.00,23.00,34.00,41.00,55.00,0.00,0.00,5.00,40.00,0.00,0.00,7.00,13.00,0.00,0.00,0.00,0.00,8.00,0.00,33.00,0.00,14.00,30.00,11.00,0.00,11.00,10.00,0.00,0.00,46.00,0.00,0.00,4.00,30.00,0.00,0.00,8.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,12.00,7.00,11.00,20.00,0.00,0.00,2.00,25.00,0.00,0.00,7.00,NaN,13.00,0.00,0.00,0.00,0.00,8.00,0.00,33.00,0.00,14.00,30.00,11.00,0.00,10.00,10.00,0.00,0.00,30.00,0.00,0.00,4.00,30.00,0.00,0.00,8.00,0.00,0.00,0.00,0.00,0.00,46.00,0.00,0.00,0.00,12.00,7.00,11.00,20.00,0.00,0.00,1.00,25.00,0.00,0.00,16.00,NaN,25.00,0.00,0.00,0.00,0.00,12.00,0.00,61.00,0.00,33.00,69.00,26.00,0.00,17.00,18.00,0.00,0.00,15.00,0.00,0.00,15.00,50.00,0.00,0.00,18.00,0.00,0.00,0.00,0.00,0.00,65.00,0.00,0.00,0.00,21.00,20.00,43.00,63.00,0.00,0.00,6.00,49.00,0.00
10,0,Ligue 1,Toulouse,NaN,Yaya Sanogo,0.00,5.00,38.00,14.00,8.00,12.00,0.00,3.00,0.00,11.00,3.00,0.00,35.00,36.00,0.00,25.00,24.00,0.00,22.00,60.00,25.00,0.00,16.00,29.00,13.00,0.00,7.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,6.00,29.00,19.00,23.00,4.00,5.00,0.00,37.00,20.00,0.00,5.00,NaN,39.00,9.00,9.00,9.00,0.00,2.00,0.00,12.00,2.00,0.00,38.00,33.00,0.00,18.00,19.00,0.00,22.00,34.00,22.00,0.00,15.00,35.00,15.00,0.00,7.00,0.00,0.00,0.00,0.00,0.00,48.00,0.00,0.00,0.00,7.00,17.00,13.00,27.00,1.00,6.00,0.00,41.00,9.00,0.00,10.00,NaN,71.00,31.00,26.00,19.00,0.00,8.00,0.00,44.00,12.00,0.00,67.00,62.00,0.00,41.00,37.00,0.00,44.00,28.00,47.00,0.00,18.00,55.00,48.00,0.00,15.00,0.00,0.00,0.00,0.00,0.00,67.00,0.00,0.00,0.00,18.00,35.00,37.00,66.00,10.00,12.00,0.00,78.00,52.00,0.00,9.00,72.00,0.00,0.00,14.00,0.00,5.00,0.00,23.00,5.00,0.00,66.00,61.00,0.00,47.00,40.00,0.00,40.00,61.00,33.00,0.00,22.00,74.00,25.00,0.00,13.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,12.00,38.00,29.00,60.00,4.00,12.00,0.00,79.00,25.00,0.00,9.00,NaN,72.00,0.00,0.00,14.00,0.00,5.00,0.00,23.00,5.00,0.00,66.00,61.00,0.00,40.00,40.00,0.00,40.00,40.00,33.00,0.00,22.00,74.00,25.00,0.00,13.00,0.00,0.00,0.00,0.00,0.00,84.00,0.00,0.00,0.00,12.00,38.00,29.00,60.00,4.00,12.00,0.00,79.00,20.00,0.00,8.00,NaN,53.00,0.00,0.00,26.00,0.00,7.00,0.00,51.00,18.00,0.00,79.00,51.00,0.00,49.00,39.00,0.00,61.00,31.00,50.00,0.00,0.00,26.00,68.00,0.00,12.00,0.00,0.00,0.00,0.00,0.00,9.00,0.00,0.00,0.00,21.00,32.00,17.00,77.00,14.00,13.00,0.00,55.00,77.00
17,0,Ligue 1,Toulouse,NaN,Wesley Saïd,11.00,15.00,10.00,14.00,8.00,37.00,0.00,10.00,0.00,21.00,25.00,14.00,20.00,29.00,0.00,9.00,8.00,0.00,11.00,44.00,25.00,20.00,10.00,38.00,0.00,0.00,17.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,13.00,23.00,23.00,38.00,48.00,15.00,8.00,26.00,40.00,11.00,17.00,NaN,12.00,10.00,10.00,30.00,0.00,10.00,0.00,25.00,18.00,13.00,24.00,29.00,0.00,7.00,7.00,0.00,12.00,27.00,25.00,15.00,11.00,50.00,0.00,0.00,19.00,0.00,0.00,0.00,0.00,0.00,85.00,0.00,0.00,0.00,16.00,15.00,18.00,50.00,26.00,20.00,7.00,31.00,20.00,29.00,28.00,NaN,19.00,32.00,27.00,31.00,0.00,25.00,0.00,80.00,47.00,26.00,24.00,52.00,0.00,22.00,16.00,0.00,34.00,34.00,50.00,19.00,18.00,60.00,0.00,0.00,32.00,0.00,0.00,0.00,0.00,0.00,7.00,0.00,0.00,0.00,38.00,35.00,48.00,74.00,76.00,27.00,25.00,47.00,73.00,18.00,14.00,10.00,0.00,0.00,14.00,0.00,8.00,0.00,9.00,17.00,21.00,22.00,19.00,0.00,17.00,5.00,0.00,20.00,61.00,0.00,26.00,9.00,53.00,0.00,0.00,17.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,15.00,18.00,60.00,21.00,8.00,17.00,25.00,25.00,17.00,14.00,NaN,10.00,0.00,0.00,14.00,0.00,8.00,0.00,9.00,17.00,21.00,22.00,19.00,0.00,15.00,5.00,0.00,20.00,40.00,0.00,20.00,9.00,53.00,0.00,0.00,17.00,0.00,0.00,0.00,0.00,0.00,81.00,0.00,0.00,0.00,0.00,15.00,18.00,60.00,21.00,8.00,12.00,25.00,20.00,24.00,23.00,NaN,19.00,0.00,0.00,26.00,0.00,19.00,0.00,19.00,30.00,33.00,26.00,32.00,0.00,29.00,15.00,0.00,50.00,31.00,0.00,23.00,18.00,60.00,0.00,0.00,24.00,0.00,0.00,0.00,0.00,0.00,5.00,0.00,0.00,0.00,0.00,25.00,45.00,77.00,31.00,13.00,22.00,32.00,77.00
21,1,Ligue 2,Brest,NaN,Édouard Butin,3.00,9.00,10.00,20.00,12.00,16.00,0.00,2.00,0.00,18.00,5.00,15.00,24.00,19.00,0.00,17.00,35.00,0.00,9.00,57.00,0.00,7.00,9.00,34.00,25.00,0.00,11.00,0.00,0.00,0.00,33.00,0.00,0.00,0.00,0.00,10.00,11.00,20.00,25.00,0.00,5.00,8.00,25.00,0.00,3.00,7.00,NaN,11.00,9.00,12.00,13.00,0.00,2.00,0.00,15.00,4.00,9.00,25.00,19.00,0.00,14.00,29.00,0.00,9.00,21.00,0.00,6.00,9.00,37.00,15.00,0.00,9.00,0.00,0.00,0.00,33.00,0.00,78.00,0.00,0.00,0.00,4.00,11.00,16.00,27.00,0.00,5.00,7.00,25.00,0.00,12.00,10.00,NaN,22.00,44.00,36.00,29.00,0.00,7.00,0.00,34.00,7.00,23.00,27.00,25.00,0.00,22.00,35.00,0.00,25.00,24.00,0.00,14.00,27.00,61.00,19.00,0.00,14.00,0.00,0.00,0.00,64.00,0.00,41.00,0.00,0.00,0.00,16.00,29.00,39.00,66.00,0.00,17.00,20.00,32.00,0.00,0.00,4.00,4.00,0.00,0.00,0.00,0.00,0.00,0.00,10.00,3.00,7.00,17.00,16.00,0.00,5.00,41.00,0.00,20.00,43.00,0.00,6.00,0.00,19.00,28.00,0.00,6.00,0.00,0.00,0.00,50.00,0.00,0.00,0.00,0.00,0.00,12.00,11.00,0.00,0.00,0.00,2.00,18.00,0.00,0.00,4.00,NaN,4.00,0.00,0.00,0.00,0.00,0.00,0.00,10.00,3.00,6.00,17.00,16.00,0.00,5.00,41.00,0.00,20.00,27.00,0.00,6.00,0.00,19.00,22.00,0.00,6.00,0.00,0.00,0.00,50.00,0.00,86.00,0.00,0.00,0.00,0.00,12.00,11.00,0.00,0.00,0.00,2.00,18.00,0.00,0.00,5.00,NaN,12.00,0.00,0.00,0.00,0.00,0.00,0.00,29.00,7.00,20.00,13.00,22.00,0.00,14.00,47.00,0.00,50.00,19.00,0.00,14.00,0.00,8.00,23.00,0.00,7.00,0.00,0.00,0.00,81.00,0.00,4.00,0.00,0.00,0.00,0.00,25.00,16.00,0.00,0.00,0.00,7.00,19.00,0.00
27,1,Ligue 2,Brest,NaN,Valentin Henry,0.00,3.00,1.00,0.00,0.00,16.00,0.00,5.00,0.00,0.00,2.00,5.00,1.00,6.00,0.00,10.00,6.00,0.00,0.00,61.00,0.00,10.00,2.00,10.00,0.00,0.00,4.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,5.00,2.00,8.00,5.00,3.00,1.00,7.00,0.00,0.00,2.00,NaN,1.00,0.00,0.00,12.00,0.00,5.00,0.00,0.00,1.00,2.00,1.00,5.00,0.00,7.00,4.00,0.00,0.00,21.00,0.00,8.00,2.00,10.00,0.00,0.00,3.00,0.00,0.00,0.00,0.00,0.00,21.00,0.00,0.00,0.00,0.00,5.00,1.00,8.00,2.00,3.00,0.00,6.00,0.00,0.00,13.00,NaN,8.00,0.00,0.00,28.00,0.00,20.00,0.00,0.00,5.00,10.00,4.00,17.00,0.00,19.00,20.00,0.00,0.00,23.00,0.00,30.00,11.00,49.00,0.00,0.00,17.00,0.00,0.00,0.00,0.00,0.00,62.00,0.00,0.00,0.00,0.00,21.00,11.00,40.00,8.00,10.00,4.00,25.00,0.00,0.00,0.00,0.00,0.00,0.00,25.00,0.00,0.00,0.00,0.00,0.00,0.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,43.00,0.00,0.00,0.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,12.00,5.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,0.00,0.00,0.00,25.00,0.00,0.00,0.00,0.00,0.00,0.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,27.00,0.00,0.00,0.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,16.00,0.00,0.00,0.00,0.00,12.00,5.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,0.00,0.00,0.00,33.00,0.00,0.00,0.00,0.00,0.00,0.00,4.00,0.00,0.00,0.00,0.00,0.00,0.00,19.00,0.00,0.00,0.00,6.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,59.00,0.00,0.00,0.00,0.00,25.00,13.00,0.00,0.00,0.00,0.00,3.00,0.00

In [114]:
home_player_processed["POSITION"].value_counts(dropna=False)

POSITION
midfielder    78524
defender      67746
NaN           42820
goalkeeper    24298
attacker      23691
Name: count, dtype: int64

In [115]:
[col for col in home_player_processed.columns if "POSITION" in col.upper()]

['POSITION']

In [116]:
for col in pass_cols:

    # Step 1: position-wise median
    home_player_processed[col] = (
        home_player_processed
        .groupby("POSITION")[col]
        .transform(lambda x: x.fillna(x.median()))
    )

    # Step 2: remaining NaNs (missing POSITION rows)
    home_player_processed[col] = (
        home_player_processed[col]
        .fillna(home_player_processed[col].median())
    )

In [117]:
home_player_processed[pass_cols].isnull().sum()

PLAYER_ACCURATE_PASSES_PERCENTAGE_season_average          0
PLAYER_ACCURATE_PASSES_PERCENTAGE_season_std              0
PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_average    0
PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_std        0
dtype: int64

In [118]:
# Dribble

In [119]:
dribble_cols = [
    col for col in home_player_processed.columns
    if "DRIBBL" in col.upper()
]

dribble_cols

['PLAYER_DRIBBLED_ATTEMPTS_season_sum',
 'PLAYER_DRIBBLED_PAST_season_sum',
 'PLAYER_SUCCESSFUL_DRIBBLES_season_sum',
 'PLAYER_DRIBBLED_ATTEMPTS_season_average',
 'PLAYER_DRIBBLED_PAST_season_average',
 'PLAYER_SUCCESSFUL_DRIBBLES_season_average',
 'PLAYER_DRIBBLED_ATTEMPTS_season_std',
 'PLAYER_DRIBBLED_PAST_season_std',
 'PLAYER_SUCCESSFUL_DRIBBLES_season_std',
 'PLAYER_DRIBBLED_ATTEMPTS_5_last_match_sum',
 'PLAYER_DRIBBLED_PAST_5_last_match_sum',
 'PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_sum',
 'PLAYER_DRIBBLED_ATTEMPTS_5_last_match_average',
 'PLAYER_DRIBBLED_PAST_5_last_match_average',
 'PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_average',
 'PLAYER_DRIBBLED_ATTEMPTS_5_last_match_std',
 'PLAYER_DRIBBLED_PAST_5_last_match_std',
 'PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_std']

In [120]:
missing_numeric[dribble_cols]

PLAYER_DRIBBLED_ATTEMPTS_season_sum               22.82
PLAYER_DRIBBLED_PAST_season_sum                   22.82
PLAYER_SUCCESSFUL_DRIBBLES_season_sum             22.82
PLAYER_DRIBBLED_ATTEMPTS_season_average           22.82
PLAYER_DRIBBLED_PAST_season_average               22.82
PLAYER_SUCCESSFUL_DRIBBLES_season_average         22.82
PLAYER_DRIBBLED_ATTEMPTS_season_std               24.01
PLAYER_DRIBBLED_PAST_season_std                   24.01
PLAYER_SUCCESSFUL_DRIBBLES_season_std             24.01
PLAYER_DRIBBLED_ATTEMPTS_5_last_match_sum         22.82
PLAYER_DRIBBLED_PAST_5_last_match_sum             22.82
PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_sum       22.82
PLAYER_DRIBBLED_ATTEMPTS_5_last_match_average     22.82
PLAYER_DRIBBLED_PAST_5_last_match_average         22.82
PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_average   22.82
PLAYER_DRIBBLED_ATTEMPTS_5_last_match_std         24.01
PLAYER_DRIBBLED_PAST_5_last_match_std             24.01
PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_std       24.01
dtype: float64

In [121]:
home_player_processed[dribble_cols].describe()

,PLAYER_DRIBBLED_ATTEMPTS_season_sum,PLAYER_DRIBBLED_PAST_season_sum,PLAYER_SUCCESSFUL_DRIBBLES_season_sum,PLAYER_DRIBBLED_ATTEMPTS_season_average,PLAYER_DRIBBLED_PAST_season_average,PLAYER_SUCCESSFUL_DRIBBLES_season_average,PLAYER_DRIBBLED_ATTEMPTS_season_std,PLAYER_DRIBBLED_PAST_season_std,PLAYER_SUCCESSFUL_DRIBBLES_season_std,PLAYER_DRIBBLED_ATTEMPTS_5_last_match_sum,PLAYER_DRIBBLED_PAST_5_last_match_sum,PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_sum,PLAYER_DRIBBLED_ATTEMPTS_5_last_match_average,PLAYER_DRIBBLED_PAST_5_last_match_average,PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_average,PLAYER_DRIBBLED_ATTEMPTS_5_last_match_std,PLAYER_DRIBBLED_PAST_5_last_match_std,PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_std
count,182972.00,182972.00,182972.00,182972.00,182972.00,182972.00,180164.00,180164.00,180164.00,182972.00,182972.00,182972.00,182972.00,182972.00,182972.00,180164.00,180164.00,180164.00
mean,11.76,17.29,11.40,11.23,15.38,10.65,18.62,24.28,18.72,10.73,14.51,10.24,10.50,13.94,10.00,15.33,18.72,14.63
std,16.13,19.07,15.86,14.99,16.80,14.58,17.88,19.62,18.31,15.43,17.96,15.40,15.07,17.30,15.05,17.24,19.09,17.54
min,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,0.00,1.00,0.00,0.00,1.00,0.00,4.00,9.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
50%,6.00,12.00,5.00,6.00,11.00,5.00,15.00,23.00,15.00,4.00,8.00,4.00,4.00,8.00,4.00,11.00,17.00,12.00
75%,17.00,26.00,16.00,16.00,23.00,15.00,28.00,37.00,29.00,15.00,23.00,15.00,15.00,21.00,14.00,24.00,30.00,23.00
max,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00

In [122]:
for col in dribble_cols:
    print(f"\n{col}")
    print(
        home_player_processed
        .groupby("POSITION")[col]
        .apply(lambda x: x.notna().sum())
    )

PLAYER_DRIBBLED_ATTEMPTS_season_sum
POSITION
attacker      20493
defender      55405
goalkeeper    19827
midfielder    64147
Name: PLAYER_DRIBBLED_ATTEMPTS_season_sum, dtype: int64

PLAYER_DRIBBLED_PAST_season_sum
POSITION
attacker      20493
defender      55405
goalkeeper    19827
midfielder    64147
Name: PLAYER_DRIBBLED_PAST_season_sum, dtype: int64

PLAYER_SUCCESSFUL_DRIBBLES_season_sum
POSITION
attacker      20493
defender      55405
goalkeeper    19827
midfielder    64147
Name: PLAYER_SUCCESSFUL_DRIBBLES_season_sum, dtype: int64

PLAYER_DRIBBLED_ATTEMPTS_season_average
POSITION
attacker      20493
defender      55405
goalkeeper    19827
midfielder    64147
Name: PLAYER_DRIBBLED_ATTEMPTS_season_average, dtype: int64

PLAYER_DRIBBLED_PAST_season_average
POSITION
attacker      20493
defender      55405
goalkeeper    19827
midfielder    64147
Name: PLAYER_DRIBBLED_PAST_season_average, dtype: int64

PLAYER_SUCCESSFUL_DRIBBLES_season_average
POSITION
attacker      20493
defender      55405
goalkeeper    19827
midfielder    64147
Name: PLAYER_SUCCESSFUL_DRIBBLES_season_average, dtype: int64

PLAYER_DRIBBLED_ATTEMPTS_season_std
POSITION
attacker      20141
defender      54614
goalkeeper    19561
midfielder    63205
Name: PLAYER_DRIBBLED_ATTEMPTS_season_std, dtype: int64

PLAYER_DRIBBLED_PAST_season_std
POSITION
attacker      20141
defender      54614
goalkeeper    19561
midfielder    63205
Name: PLAYER_DRIBBLED_PAST_season_std, dtype: int64

PLAYER_SUCCESSFUL_DRIBBLES_season_std
POSITION
attacker      20141
defender      54614
goalkeeper    19561
midfielder    63205
Name: PLAYER_SUCCESSFUL_DRIBBLES_season_std, dtype: int64

PLAYER_DRIBBLED_ATTEMPTS_5_last_match_sum
POSITION
attacker      20493
defender      55405
goalkeeper    19827
midfielder    64147
Name: PLAYER_DRIBBLED_ATTEMPTS_5_last_match_sum, dtype: int64

PLAYER_DRIBBLED_PAST_5_last_match_sum
POSITION
attacker      20493
defender      55405
goalkeeper    19827
midfielder    64147
Name: PLAYER_DRIBBLED_PAST_5_last_match_sum, dtype: int64

PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_sum
POSITION
attacker      20493
defender      55405
goalkeeper    19827
midfielder    64147
Name: PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_sum, dtype: int64

PLAYER_DRIBBLED_ATTEMPTS_5_last_match_average
POSITION
attacker      20493
defender      55405
goalkeeper    19827
midfielder    64147
Name: PLAYER_DRIBBLED_ATTEMPTS_5_last_match_average, dtype: int64

PLAYER_DRIBBLED_PAST_5_last_match_average
POSITION
attacker      20493
defender      55405
goalkeeper    19827
midfielder    64147
Name: PLAYER_DRIBBLED_PAST_5_last_match_average, dtype: int64

PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_average
POSITION
attacker      20493
defender      55405
goalkeeper    19827
midfielder    64147
Name: PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_average, dtype: int64

PLAYER_DRIBBLED_ATTEMPTS_5_last_match_std
POSITION
attacker      20141
defender      54614
goalkeeper    19561
midfielder    63205
Name: PLAYER_DRIBBLED_ATTEMPTS_5_last_match_std, dtype: int64

PLAYER_DRIBBLED_PAST_5_last_match_std
POSITION
attacker      20141
defender      54614
goalkeeper    19561
midfielder    63205
Name: PLAYER_DRIBBLED_PAST_5_last_match_std, dtype: int64

PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_std
POSITION
attacker      20141
defender      54614
goalkeeper    19561
midfielder    63205
Name: PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_std, dtype: int64

In [123]:
home_player_processed.groupby("POSITION")[dribble_cols].median()

,PLAYER_DRIBBLED_ATTEMPTS_season_sum,PLAYER_DRIBBLED_PAST_season_sum,PLAYER_SUCCESSFUL_DRIBBLES_season_sum,PLAYER_DRIBBLED_ATTEMPTS_season_average,PLAYER_DRIBBLED_PAST_season_average,PLAYER_SUCCESSFUL_DRIBBLES_season_average,PLAYER_DRIBBLED_ATTEMPTS_season_std,PLAYER_DRIBBLED_PAST_season_std,PLAYER_SUCCESSFUL_DRIBBLES_season_std,PLAYER_DRIBBLED_ATTEMPTS_5_last_match_sum,PLAYER_DRIBBLED_PAST_5_last_match_sum,PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_sum,PLAYER_DRIBBLED_ATTEMPTS_5_last_match_average,PLAYER_DRIBBLED_PAST_5_last_match_average,PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_average,PLAYER_DRIBBLED_ATTEMPTS_5_last_match_std,PLAYER_DRIBBLED_PAST_5_last_match_std,PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_std
POSITION,,,,,,,,,,,,,,,,,,
attacker,12.00,11.00,10.00,13.00,11.00,10.00,25.00,23.00,24.00,11.00,8.00,9.00,11.00,8.00,9.00,19.00,17.00,17.00
defender,3.00,12.00,4.00,3.00,11.00,4.00,11.00,23.00,13.00,3.00,8.00,3.00,3.00,8.00,3.00,9.00,17.00,10.00
goalkeeper,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
midfielder,11.00,21.00,10.00,10.00,19.00,10.00,22.00,32.00,22.00,9.00,16.00,9.00,9.00,16.00,8.00,17.00,23.00,16.00

In [124]:
for col in dribble_cols:

    # Position-wise median
    home_player_processed[col] = (
        home_player_processed
        .groupby("POSITION")[col]
        .transform(lambda x: x.fillna(x.median()))
    )

    # Remaining NaNs (missing POSITION)
    home_player_processed[col] = (
        home_player_processed[col]
        .fillna(home_player_processed[col].median())
    )

In [125]:
home_player_processed[dribble_cols].isnull().sum()

PLAYER_DRIBBLED_ATTEMPTS_season_sum                0
PLAYER_DRIBBLED_PAST_season_sum                    0
PLAYER_SUCCESSFUL_DRIBBLES_season_sum              0
PLAYER_DRIBBLED_ATTEMPTS_season_average            0
PLAYER_DRIBBLED_PAST_season_average                0
PLAYER_SUCCESSFUL_DRIBBLES_season_average          0
PLAYER_DRIBBLED_ATTEMPTS_season_std                0
PLAYER_DRIBBLED_PAST_season_std                    0
PLAYER_SUCCESSFUL_DRIBBLES_season_std              0
PLAYER_DRIBBLED_ATTEMPTS_5_last_match_sum          0
PLAYER_DRIBBLED_PAST_5_last_match_sum              0
PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_sum        0
PLAYER_DRIBBLED_ATTEMPTS_5_last_match_average      0
PLAYER_DRIBBLED_PAST_5_last_match_average          0
PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_average    0
PLAYER_DRIBBLED_ATTEMPTS_5_last_match_std          0
PLAYER_DRIBBLED_PAST_5_last_match_std              0
PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_std        0
dtype: int64

Missing values in player dribbling features were imputed using position-specific median imputation. Since dribbling performance differs substantially across attackers, midfielders, defenders and goalkeepers, calculating the median within each playing position preserves realistic positional behaviour while remaining robust to skewed distributions and extreme values. For observations with missing playing position information, the overall feature median was used.

In [126]:
home_player_processed.columns

Index(['ID', 'LEAGUE', 'TEAM_NAME', 'POSITION', 'PLAYER_NAME',
       'PLAYER_ACCURATE_CROSSES_season_sum',
       'PLAYER_ACCURATE_PASSES_season_sum', 'PLAYER_AERIALS_WON_season_sum',
       'PLAYER_ASSISTS_season_sum', 'PLAYER_BIG_CHANCES_CREATED_season_sum',
       ...
       'PLAYER_SAVES_INSIDE_BOX_5_last_match_std',
       'PLAYER_SHOTS_BLOCKED_5_last_match_std',
       'PLAYER_SHOTS_ON_TARGET_5_last_match_std',
       'PLAYER_SHOTS_TOTAL_5_last_match_std',
       'PLAYER_STARTING_LINEUP_5_last_match_std',
       'PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_std',
       'PLAYER_TACKLES_5_last_match_std',
       'PLAYER_TOTAL_CROSSES_5_last_match_std',
       'PLAYER_TOTAL_DUELS_5_last_match_std',
       'PLAYER_YELLOWCARDS_5_last_match_std'],
      dtype='object', length=277)

In [127]:
# Crossing

In [128]:
cross_cols = [col for col in home_player_processed.columns if "CROSS" in col.upper()]
cross_cols

['PLAYER_ACCURATE_CROSSES_season_sum',
 'PLAYER_TOTAL_CROSSES_season_sum',
 'PLAYER_ACCURATE_CROSSES_season_average',
 'PLAYER_TOTAL_CROSSES_season_average',
 'PLAYER_ACCURATE_CROSSES_season_std',
 'PLAYER_TOTAL_CROSSES_season_std',
 'PLAYER_ACCURATE_CROSSES_5_last_match_sum',
 'PLAYER_TOTAL_CROSSES_5_last_match_sum',
 'PLAYER_ACCURATE_CROSSES_5_last_match_average',
 'PLAYER_TOTAL_CROSSES_5_last_match_average',
 'PLAYER_ACCURATE_CROSSES_5_last_match_std',
 'PLAYER_TOTAL_CROSSES_5_last_match_std']

In [129]:
missing_numeric[cross_cols]

PLAYER_ACCURATE_CROSSES_season_sum             11.93
PLAYER_TOTAL_CROSSES_season_sum                11.93
PLAYER_ACCURATE_CROSSES_season_average         11.93
PLAYER_TOTAL_CROSSES_season_average            11.93
PLAYER_ACCURATE_CROSSES_season_std             13.37
PLAYER_TOTAL_CROSSES_season_std                13.37
PLAYER_ACCURATE_CROSSES_5_last_match_sum       11.93
PLAYER_TOTAL_CROSSES_5_last_match_sum          11.93
PLAYER_ACCURATE_CROSSES_5_last_match_average   11.93
PLAYER_TOTAL_CROSSES_5_last_match_average      11.93
PLAYER_ACCURATE_CROSSES_5_last_match_std       13.37
PLAYER_TOTAL_CROSSES_5_last_match_std          13.37
dtype: float64

In [130]:
home_player_processed[cross_cols].describe()

,PLAYER_ACCURATE_CROSSES_season_sum,PLAYER_TOTAL_CROSSES_season_sum,PLAYER_ACCURATE_CROSSES_season_average,PLAYER_TOTAL_CROSSES_season_average,PLAYER_ACCURATE_CROSSES_season_std,PLAYER_TOTAL_CROSSES_season_std,PLAYER_ACCURATE_CROSSES_5_last_match_sum,PLAYER_TOTAL_CROSSES_5_last_match_sum,PLAYER_ACCURATE_CROSSES_5_last_match_average,PLAYER_TOTAL_CROSSES_5_last_match_average,PLAYER_ACCURATE_CROSSES_5_last_match_std,PLAYER_TOTAL_CROSSES_5_last_match_std
count,208790.00,208790.00,208790.00,208790.00,205393.00,205393.00,208790.00,208790.00,208790.00,208790.00,205393.00,205393.00
mean,7.93,9.66,7.98,10.12,14.24,16.10,7.04,9.23,6.93,9.10,10.04,12.41
std,15.10,16.18,14.54,15.98,18.63,18.60,14.39,15.73,14.13,15.44,16.51,16.67
min,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
50%,1.00,2.00,1.00,3.00,9.00,9.00,0.00,2.00,0.00,2.00,0.00,7.00
75%,9.00,12.00,10.00,14.00,23.00,25.00,7.00,12.00,7.00,12.00,17.00,19.00
max,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00

In [131]:
for col in cross_cols:
    print(f"\n{col}")
    print(
        home_player_processed
        .groupby("POSITION")[col]
        .apply(lambda x: x.notna().sum())
    )

PLAYER_ACCURATE_CROSSES_season_sum
POSITION
attacker      22658
defender      59297
goalkeeper    21290
midfielder    69008
Name: PLAYER_ACCURATE_CROSSES_season_sum, dtype: int64

PLAYER_TOTAL_CROSSES_season_sum
POSITION
attacker      22658
defender      59297
goalkeeper    21290
midfielder    69008
Name: PLAYER_TOTAL_CROSSES_season_sum, dtype: int64

PLAYER_ACCURATE_CROSSES_season_average
POSITION
attacker      22658
defender      59297
goalkeeper    21290
midfielder    69008
Name: PLAYER_ACCURATE_CROSSES_season_average, dtype: int64

PLAYER_TOTAL_CROSSES_season_average
POSITION
attacker      22658
defender      59297
goalkeeper    21290
midfielder    69008
Name: PLAYER_TOTAL_CROSSES_season_average, dtype: int64

PLAYER_ACCURATE_CROSSES_season_std
POSITION
attacker      22263
defender      58409
goalkeeper    21000
midfielder    67969
Name: PLAYER_ACCURATE_CROSSES_season_std, dtype: int64

PLAYER_TOTAL_CROSSES_season_std
POSITION
attacker      22263
defender      58409
goalkeeper    21000
midfielder    67969
Name: PLAYER_TOTAL_CROSSES_season_std, dtype: int64

PLAYER_ACCURATE_CROSSES_5_last_match_sum
POSITION
attacker      22658
defender      59297
goalkeeper    21290
midfielder    69008
Name: PLAYER_ACCURATE_CROSSES_5_last_match_sum, dtype: int64

PLAYER_TOTAL_CROSSES_5_last_match_sum
POSITION
attacker      22658
defender      59297
goalkeeper    21290
midfielder    69008
Name: PLAYER_TOTAL_CROSSES_5_last_match_sum, dtype: int64

PLAYER_ACCURATE_CROSSES_5_last_match_average
POSITION
attacker      22658
defender      59297
goalkeeper    21290
midfielder    69008
Name: PLAYER_ACCURATE_CROSSES_5_last_match_average, dtype: int64

PLAYER_TOTAL_CROSSES_5_last_match_average
POSITION
attacker      22658
defender      59297
goalkeeper    21290
midfielder    69008
Name: PLAYER_TOTAL_CROSSES_5_last_match_average, dtype: int64

PLAYER_ACCURATE_CROSSES_5_last_match_std
POSITION
attacker      22263
defender      58409
goalkeeper    21000
midfielder    67969
Name: PLAYER_ACCURATE_CROSSES_5_last_match_std, dtype: int64

PLAYER_TOTAL_CROSSES_5_last_match_std
POSITION
attacker      22263
defender      58409
goalkeeper    21000
midfielder    67969
Name: PLAYER_TOTAL_CROSSES_5_last_match_std, dtype: int64

In [132]:
home_player_processed.groupby("POSITION")[cross_cols].median()

,PLAYER_ACCURATE_CROSSES_season_sum,PLAYER_TOTAL_CROSSES_season_sum,PLAYER_ACCURATE_CROSSES_season_average,PLAYER_TOTAL_CROSSES_season_average,PLAYER_ACCURATE_CROSSES_season_std,PLAYER_TOTAL_CROSSES_season_std,PLAYER_ACCURATE_CROSSES_5_last_match_sum,PLAYER_TOTAL_CROSSES_5_last_match_sum,PLAYER_ACCURATE_CROSSES_5_last_match_average,PLAYER_TOTAL_CROSSES_5_last_match_average,PLAYER_ACCURATE_CROSSES_5_last_match_std,PLAYER_TOTAL_CROSSES_5_last_match_std
POSITION,,,,,,,,,,,,
attacker,2.00,3.00,2.00,4.00,11.00,11.00,0.00,3.00,0.00,3.00,0.00,8.00
defender,1.00,2.00,1.00,2.00,8.00,8.00,0.00,1.00,0.00,1.00,0.00,6.00
goalkeeper,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
midfielder,4.00,6.00,4.00,6.00,15.00,16.00,0.00,5.00,0.00,5.00,0.00,11.00

In [133]:
for col in cross_cols:

    # Step 1: Fill using position-specific median
    home_player_processed[col] = (
        home_player_processed
        .groupby("POSITION")[col]
        .transform(lambda x: x.fillna(x.median()))
    )

    # Step 2: Fill remaining NaNs (missing POSITION)
    home_player_processed[col] = (
        home_player_processed[col]
        .fillna(home_player_processed[col].median())
    )

In [134]:
home_player_processed[cross_cols].isnull().sum()

PLAYER_ACCURATE_CROSSES_season_sum              0
PLAYER_TOTAL_CROSSES_season_sum                 0
PLAYER_ACCURATE_CROSSES_season_average          0
PLAYER_TOTAL_CROSSES_season_average             0
PLAYER_ACCURATE_CROSSES_season_std              0
PLAYER_TOTAL_CROSSES_season_std                 0
PLAYER_ACCURATE_CROSSES_5_last_match_sum        0
PLAYER_TOTAL_CROSSES_5_last_match_sum           0
PLAYER_ACCURATE_CROSSES_5_last_match_average    0
PLAYER_TOTAL_CROSSES_5_last_match_average       0
PLAYER_ACCURATE_CROSSES_5_last_match_std        0
PLAYER_TOTAL_CROSSES_5_last_match_std           0
dtype: int64

In [135]:
# Shooting

In [136]:
shoot_cols = [col for col in home_player_processed.columns if "SHOT" in col.upper()]
shoot_cols

['PLAYER_BLOCKED_SHOTS_season_sum',
 'PLAYER_SHOTS_BLOCKED_season_sum',
 'PLAYER_SHOTS_ON_TARGET_season_sum',
 'PLAYER_SHOTS_TOTAL_season_sum',
 'PLAYER_BLOCKED_SHOTS_season_average',
 'PLAYER_SHOTS_BLOCKED_season_average',
 'PLAYER_SHOTS_ON_TARGET_season_average',
 'PLAYER_SHOTS_TOTAL_season_average',
 'PLAYER_BLOCKED_SHOTS_season_std',
 'PLAYER_SHOTS_BLOCKED_season_std',
 'PLAYER_SHOTS_ON_TARGET_season_std',
 'PLAYER_SHOTS_TOTAL_season_std',
 'PLAYER_BLOCKED_SHOTS_5_last_match_sum',
 'PLAYER_SHOTS_BLOCKED_5_last_match_sum',
 'PLAYER_SHOTS_ON_TARGET_5_last_match_sum',
 'PLAYER_SHOTS_TOTAL_5_last_match_sum',
 'PLAYER_BLOCKED_SHOTS_5_last_match_average',
 'PLAYER_SHOTS_BLOCKED_5_last_match_average',
 'PLAYER_SHOTS_ON_TARGET_5_last_match_average',
 'PLAYER_SHOTS_TOTAL_5_last_match_average',
 'PLAYER_BLOCKED_SHOTS_5_last_match_std',
 'PLAYER_SHOTS_BLOCKED_5_last_match_std',
 'PLAYER_SHOTS_ON_TARGET_5_last_match_std',
 'PLAYER_SHOTS_TOTAL_5_last_match_std']

In [137]:
missing_numeric[shoot_cols]

PLAYER_BLOCKED_SHOTS_season_sum               12.61
PLAYER_SHOTS_BLOCKED_season_sum               11.93
PLAYER_SHOTS_ON_TARGET_season_sum             11.93
PLAYER_SHOTS_TOTAL_season_sum                 11.93
PLAYER_BLOCKED_SHOTS_season_average           12.61
PLAYER_SHOTS_BLOCKED_season_average           11.93
PLAYER_SHOTS_ON_TARGET_season_average         11.93
PLAYER_SHOTS_TOTAL_season_average             11.93
PLAYER_BLOCKED_SHOTS_season_std               14.02
PLAYER_SHOTS_BLOCKED_season_std               13.37
PLAYER_SHOTS_ON_TARGET_season_std             13.37
PLAYER_SHOTS_TOTAL_season_std                 13.37
PLAYER_BLOCKED_SHOTS_5_last_match_sum         12.61
PLAYER_SHOTS_BLOCKED_5_last_match_sum         11.93
PLAYER_SHOTS_ON_TARGET_5_last_match_sum       11.93
PLAYER_SHOTS_TOTAL_5_last_match_sum           11.93
PLAYER_BLOCKED_SHOTS_5_last_match_average     12.61
PLAYER_SHOTS_BLOCKED_5_last_match_average     11.93
PLAYER_SHOTS_ON_TARGET_5_last_match_average   11.93
PLAYER_SHOTS_TOTAL_5_last_match_average       11.93
PLAYER_BLOCKED_SHOTS_5_last_match_std         14.02
PLAYER_SHOTS_BLOCKED_5_last_match_std         13.37
PLAYER_SHOTS_ON_TARGET_5_last_match_std       13.37
PLAYER_SHOTS_TOTAL_5_last_match_std           13.37
dtype: float64

In [138]:
home_player_processed[shoot_cols].describe()

,PLAYER_BLOCKED_SHOTS_season_sum,PLAYER_SHOTS_BLOCKED_season_sum,PLAYER_SHOTS_ON_TARGET_season_sum,PLAYER_SHOTS_TOTAL_season_sum,PLAYER_BLOCKED_SHOTS_season_average,PLAYER_SHOTS_BLOCKED_season_average,PLAYER_SHOTS_ON_TARGET_season_average,PLAYER_SHOTS_TOTAL_season_average,PLAYER_BLOCKED_SHOTS_season_std,PLAYER_SHOTS_BLOCKED_season_std,PLAYER_SHOTS_ON_TARGET_season_std,PLAYER_SHOTS_TOTAL_season_std,PLAYER_BLOCKED_SHOTS_5_last_match_sum,PLAYER_SHOTS_BLOCKED_5_last_match_sum,PLAYER_SHOTS_ON_TARGET_5_last_match_sum,PLAYER_SHOTS_TOTAL_5_last_match_sum,PLAYER_BLOCKED_SHOTS_5_last_match_average,PLAYER_SHOTS_BLOCKED_5_last_match_average,PLAYER_SHOTS_ON_TARGET_5_last_match_average,PLAYER_SHOTS_TOTAL_5_last_match_average,PLAYER_BLOCKED_SHOTS_5_last_match_std,PLAYER_SHOTS_BLOCKED_5_last_match_std,PLAYER_SHOTS_ON_TARGET_5_last_match_std,PLAYER_SHOTS_TOTAL_5_last_match_std
count,207184.00,208790.00,208790.00,208790.00,207184.00,208790.00,208790.00,208790.00,203832.00,205393.00,205393.00,205393.00,207184.00,208790.00,208790.00,208790.00,207184.00,208790.00,208790.00,208790.00,203832.00,205393.00,205393.00,205393.00
mean,10.45,17.13,10.79,14.03,9.89,15.00,10.65,14.16,16.84,24.57,20.40,24.58,8.38,13.51,9.51,13.25,8.07,12.69,9.40,13.02,11.49,17.17,14.37,18.96
std,16.98,19.38,16.35,17.69,15.80,17.00,15.52,16.86,19.84,20.85,20.66,20.36,15.72,18.03,15.79,17.32,15.17,17.13,15.57,16.97,18.20,19.40,19.14,19.00
min,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,0.00,0.00,0.00,1.00,0.00,0.00,0.00,1.00,0.00,0.00,0.00,9.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
50%,3.00,11.00,4.00,8.00,3.00,10.00,5.00,8.00,14.00,25.00,18.00,22.00,0.00,9.00,0.00,7.00,0.00,8.00,0.00,7.00,0.00,18.00,0.00,15.00
75%,14.00,27.00,15.00,20.00,13.00,23.00,15.00,21.00,28.00,38.00,32.00,37.00,12.00,22.00,12.00,20.00,11.00,20.00,12.00,20.00,24.00,28.00,25.00,30.00
max,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00

In [139]:
for col in shoot_cols:
    print(f"\n{col}")
    print(
        home_player_processed
        .groupby("POSITION")[col]
        .apply(lambda x: x.notna().sum())
    )

PLAYER_BLOCKED_SHOTS_season_sum
POSITION
attacker      22633
defender      59096
goalkeeper    21227
midfielder    68726
Name: PLAYER_BLOCKED_SHOTS_season_sum, dtype: int64

PLAYER_SHOTS_BLOCKED_season_sum
POSITION
attacker      22658
defender      59297
goalkeeper    21290
midfielder    69008
Name: PLAYER_SHOTS_BLOCKED_season_sum, dtype: int64

PLAYER_SHOTS_ON_TARGET_season_sum
POSITION
attacker      22658
defender      59297
goalkeeper    21290
midfielder    69008
Name: PLAYER_SHOTS_ON_TARGET_season_sum, dtype: int64

PLAYER_SHOTS_TOTAL_season_sum
POSITION
attacker      22658
defender      59297
goalkeeper    21290
midfielder    69008
Name: PLAYER_SHOTS_TOTAL_season_sum, dtype: int64

PLAYER_BLOCKED_SHOTS_season_average
POSITION
attacker      22633
defender      59096
goalkeeper    21227
midfielder    68726
Name: PLAYER_BLOCKED_SHOTS_season_average, dtype: int64

PLAYER_SHOTS_BLOCKED_season_average
POSITION
attacker      22658
defender      59297
goalkeeper    21290
midfielder    69008
Name: PLAYER_SHOTS_BLOCKED_season_average, dtype: int64

PLAYER_SHOTS_ON_TARGET_season_average
POSITION
attacker      22658
defender      59297
goalkeeper    21290
midfielder    69008
Name: PLAYER_SHOTS_ON_TARGET_season_average, dtype: int64

PLAYER_SHOTS_TOTAL_season_average
POSITION
attacker      22658
defender      59297
goalkeeper    21290
midfielder    69008
Name: PLAYER_SHOTS_TOTAL_season_average, dtype: int64

PLAYER_BLOCKED_SHOTS_season_std
POSITION
attacker      22238
defender      58215
goalkeeper    20939
midfielder    67697
Name: PLAYER_BLOCKED_SHOTS_season_std, dtype: int64

PLAYER_SHOTS_BLOCKED_season_std
POSITION
attacker      22263
defender      58409
goalkeeper    21000
midfielder    67969
Name: PLAYER_SHOTS_BLOCKED_season_std, dtype: int64

PLAYER_SHOTS_ON_TARGET_season_std
POSITION
attacker      22263
defender      58409
goalkeeper    21000
midfielder    67969
Name: PLAYER_SHOTS_ON_TARGET_season_std, dtype: int64

PLAYER_SHOTS_TOTAL_season_std
POSITION
attacker      22263
defender      58409
goalkeeper    21000
midfielder    67969
Name: PLAYER_SHOTS_TOTAL_season_std, dtype: int64

PLAYER_BLOCKED_SHOTS_5_last_match_sum
POSITION
attacker      22633
defender      59096
goalkeeper    21227
midfielder    68726
Name: PLAYER_BLOCKED_SHOTS_5_last_match_sum, dtype: int64

PLAYER_SHOTS_BLOCKED_5_last_match_sum
POSITION
attacker      22658
defender      59297
goalkeeper    21290
midfielder    69008
Name: PLAYER_SHOTS_BLOCKED_5_last_match_sum, dtype: int64

PLAYER_SHOTS_ON_TARGET_5_last_match_sum
POSITION
attacker      22658
defender      59297
goalkeeper    21290
midfielder    69008
Name: PLAYER_SHOTS_ON_TARGET_5_last_match_sum, dtype: int64

PLAYER_SHOTS_TOTAL_5_last_match_sum
POSITION
attacker      22658
defender      59297
goalkeeper    21290
midfielder    69008
Name: PLAYER_SHOTS_TOTAL_5_last_match_sum, dtype: int64

PLAYER_BLOCKED_SHOTS_5_last_match_average
POSITION
attacker      22633
defender      59096
goalkeeper    21227
midfielder    68726
Name: PLAYER_BLOCKED_SHOTS_5_last_match_average, dtype: int64

PLAYER_SHOTS_BLOCKED_5_last_match_average
POSITION
attacker      22658
defender      59297
goalkeeper    21290
midfielder    69008
Name: PLAYER_SHOTS_BLOCKED_5_last_match_average, dtype: int64

PLAYER_SHOTS_ON_TARGET_5_last_match_average
POSITION
attacker      22658
defender      59297
goalkeeper    21290
midfielder    69008
Name: PLAYER_SHOTS_ON_TARGET_5_last_match_average, dtype: int64

PLAYER_SHOTS_TOTAL_5_last_match_average
POSITION
attacker      22658
defender      59297
goalkeeper    21290
midfielder    69008
Name: PLAYER_SHOTS_TOTAL_5_last_match_average, dtype: int64

PLAYER_BLOCKED_SHOTS_5_last_match_std
POSITION
attacker      22238
defender      58215
goalkeeper    20939
midfielder    67697
Name: PLAYER_BLOCKED_SHOTS_5_last_match_std, dtype: int64

PLAYER_SHOTS_BLOCKED_5_last_match_std
POSITION
attacker      22263
defender      58409
goalkeeper    21000
midfielder    67969
Name: PLAYER_SHOTS_BLOCKED_5_last_match_std, dtype: int64

PLAYER_SHOTS_ON_TARGET_5_last_match_std
POSITION
attacker      22263
defender      58409
goalkeeper    21000
midfielder    67969
Name: PLAYER_SHOTS_ON_TARGET_5_last_match_std, dtype: int64

PLAYER_SHOTS_TOTAL_5_last_match_std
POSITION
attacker      22263
defender      58409
goalkeeper    21000
midfielder    67969
Name: PLAYER_SHOTS_TOTAL_5_last_match_std, dtype: int64

In [140]:
home_player_processed.groupby("POSITION")[shoot_cols].median()

,PLAYER_BLOCKED_SHOTS_season_sum,PLAYER_SHOTS_BLOCKED_season_sum,PLAYER_SHOTS_ON_TARGET_season_sum,PLAYER_SHOTS_TOTAL_season_sum,PLAYER_BLOCKED_SHOTS_season_average,PLAYER_SHOTS_BLOCKED_season_average,PLAYER_SHOTS_ON_TARGET_season_average,PLAYER_SHOTS_TOTAL_season_average,PLAYER_BLOCKED_SHOTS_season_std,PLAYER_SHOTS_BLOCKED_season_std,PLAYER_SHOTS_ON_TARGET_season_std,PLAYER_SHOTS_TOTAL_season_std,PLAYER_BLOCKED_SHOTS_5_last_match_sum,PLAYER_SHOTS_BLOCKED_5_last_match_sum,PLAYER_SHOTS_ON_TARGET_5_last_match_sum,PLAYER_SHOTS_TOTAL_5_last_match_sum,PLAYER_BLOCKED_SHOTS_5_last_match_average,PLAYER_SHOTS_BLOCKED_5_last_match_average,PLAYER_SHOTS_ON_TARGET_5_last_match_average,PLAYER_SHOTS_TOTAL_5_last_match_average,PLAYER_BLOCKED_SHOTS_5_last_match_std,PLAYER_SHOTS_BLOCKED_5_last_match_std,PLAYER_SHOTS_ON_TARGET_5_last_match_std,PLAYER_SHOTS_TOTAL_5_last_match_std
POSITION,,,,,,,,,,,,,,,,,,,,,,,,
attacker,0.00,16.00,17.00,21.00,0.00,15.00,19.00,23.00,0.00,30.00,37.00,40.00,0.00,12.00,14.00,20.00,0.00,10.00,14.00,20.00,0.00,21.00,25.00,29.00
defender,15.00,13.00,2.00,5.00,15.00,12.00,2.00,5.00,29.00,27.00,14.00,17.00,11.00,11.00,0.00,4.00,11.00,10.00,0.00,4.00,21.00,20.00,0.00,13.00
goalkeeper,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
midfielder,4.00,15.00,7.00,12.00,4.00,13.00,7.00,13.00,15.00,28.00,23.00,28.00,0.00,11.00,7.00,11.00,0.00,10.00,6.00,11.00,0.00,21.00,19.00,20.00

In [141]:
for col in shoot_cols:
    home_player_processed[col] = (
        home_player_processed
        .groupby("POSITION")[col]
        .transform(lambda x: x.fillna(x.median()))
    )

In [142]:
for col in shoot_cols:
    home_player_processed[col].fillna(
        home_player_processed[col].median(),
        inplace=True
    )

In [143]:
home_player_processed[shoot_cols].isnull().sum()

PLAYER_BLOCKED_SHOTS_season_sum                0
PLAYER_SHOTS_BLOCKED_season_sum                0
PLAYER_SHOTS_ON_TARGET_season_sum              0
PLAYER_SHOTS_TOTAL_season_sum                  0
PLAYER_BLOCKED_SHOTS_season_average            0
PLAYER_SHOTS_BLOCKED_season_average            0
PLAYER_SHOTS_ON_TARGET_season_average          0
PLAYER_SHOTS_TOTAL_season_average              0
PLAYER_BLOCKED_SHOTS_season_std                0
PLAYER_SHOTS_BLOCKED_season_std                0
PLAYER_SHOTS_ON_TARGET_season_std              0
PLAYER_SHOTS_TOTAL_season_std                  0
PLAYER_BLOCKED_SHOTS_5_last_match_sum          0
PLAYER_SHOTS_BLOCKED_5_last_match_sum          0
PLAYER_SHOTS_ON_TARGET_5_last_match_sum        0
PLAYER_SHOTS_TOTAL_5_last_match_sum            0
PLAYER_BLOCKED_SHOTS_5_last_match_average      0
PLAYER_SHOTS_BLOCKED_5_last_match_average      0
PLAYER_SHOTS_ON_TARGET_5_last_match_average    0
PLAYER_SHOTS_TOTAL_5_last_match_average        0
PLAYER_BLOCKED_SHOTS_5_last_match_std          0
PLAYER_SHOTS_BLOCKED_5_last_match_std          0
PLAYER_SHOTS_ON_TARGET_5_last_match_std        0
PLAYER_SHOTS_TOTAL_5_last_match_std            0
dtype: int64

In [144]:
missing_numeric = (
    home_player_processed
    .select_dtypes(include='number')
    .isnull()
    .mean() * 100
).sort_values(ascending=False)

missing_numeric.head(20)

PLAYER_PENALTIES_SAVED_5_last_match_std       22.05
PLAYER_PENALTIES_SAVED_5_last_match_sum       20.79
PLAYER_PENALTIES_SAVED_5_last_match_average   20.79
PLAYER_PENALTIES_SAVED_season_std             16.57
PLAYER_PENALTIES_SAVED_season_sum             15.23
PLAYER_PENALTIES_SAVED_season_average         15.23
PLAYER_CLEARANCE_OFFLINE_5_last_match_std     15.04
PLAYER_RATING_season_std                      14.55
PLAYER_RATING_5_last_match_std                14.55
PLAYER_ERROR_LEAD_TO_GOAL_5_last_match_std    14.41
PLAYER_PENALTIES_WON_5_last_match_std         14.29
PLAYER_PENALTIES_COMMITTED_5_last_match_std   14.17
PLAYER_ERROR_LEAD_TO_GOAL_season_std          14.06
PLAYER_CLEARANCE_OFFLINE_season_std           14.05
PLAYER_BIG_CHANCES_MISSED_5_last_match_std    14.02
PLAYER_BIG_CHANCES_MISSED_season_std          14.02
PLAYER_DUELS_LOST_season_std                  14.02
PLAYER_DUELS_LOST_5_last_match_std            14.02
PLAYER_BIG_CHANCES_CREATED_season_std         14.02
PLAYER_BIG_CHANCES_CREATED_5_last_match_std   14.02
dtype: float64

In [145]:
for col in shoot_cols:
    print(f"\n{col}")
    print(home_player_processed.groupby("POSITION")[col].apply(lambda x: x.isna().sum()))

PLAYER_BLOCKED_SHOTS_season_sum
POSITION
attacker      0
defender      0
goalkeeper    0
midfielder    0
Name: PLAYER_BLOCKED_SHOTS_season_sum, dtype: int64

PLAYER_SHOTS_BLOCKED_season_sum
POSITION
attacker      0
defender      0
goalkeeper    0
midfielder    0
Name: PLAYER_SHOTS_BLOCKED_season_sum, dtype: int64

PLAYER_SHOTS_ON_TARGET_season_sum
POSITION
attacker      0
defender      0
goalkeeper    0
midfielder    0
Name: PLAYER_SHOTS_ON_TARGET_season_sum, dtype: int64

PLAYER_SHOTS_TOTAL_season_sum
POSITION
attacker      0
defender      0
goalkeeper    0
midfielder    0
Name: PLAYER_SHOTS_TOTAL_season_sum, dtype: int64

PLAYER_BLOCKED_SHOTS_season_average
POSITION
attacker      0
defender      0
goalkeeper    0
midfielder    0
Name: PLAYER_BLOCKED_SHOTS_season_average, dtype: int64

PLAYER_SHOTS_BLOCKED_season_average
POSITION
attacker      0
defender      0
goalkeeper    0
midfielder    0
Name: PLAYER_SHOTS_BLOCKED_season_average, dtype: int64

PLAYER_SHOTS_ON_TARGET_season_average
POSITION
attacker      0
defender      0
goalkeeper    0
midfielder    0
Name: PLAYER_SHOTS_ON_TARGET_season_average, dtype: int64

PLAYER_SHOTS_TOTAL_season_average
POSITION
attacker      0
defender      0
goalkeeper    0
midfielder    0
Name: PLAYER_SHOTS_TOTAL_season_average, dtype: int64

PLAYER_BLOCKED_SHOTS_season_std
POSITION
attacker      0
defender      0
goalkeeper    0
midfielder    0
Name: PLAYER_BLOCKED_SHOTS_season_std, dtype: int64

PLAYER_SHOTS_BLOCKED_season_std
POSITION
attacker      0
defender      0
goalkeeper    0
midfielder    0
Name: PLAYER_SHOTS_BLOCKED_season_std, dtype: int64

PLAYER_SHOTS_ON_TARGET_season_std
POSITION
attacker      0
defender      0
goalkeeper    0
midfielder    0
Name: PLAYER_SHOTS_ON_TARGET_season_std, dtype: int64

PLAYER_SHOTS_TOTAL_season_std
POSITION
attacker      0
defender      0
goalkeeper    0
midfielder    0
Name: PLAYER_SHOTS_TOTAL_season_std, dtype: int64

PLAYER_BLOCKED_SHOTS_5_last_match_sum
POSITION
attacker      0
defender      0
goalkeeper    0
midfielder    0
Name: PLAYER_BLOCKED_SHOTS_5_last_match_sum, dtype: int64

PLAYER_SHOTS_BLOCKED_5_last_match_sum
POSITION
attacker      0
defender      0
goalkeeper    0
midfielder    0
Name: PLAYER_SHOTS_BLOCKED_5_last_match_sum, dtype: int64

PLAYER_SHOTS_ON_TARGET_5_last_match_sum
POSITION
attacker      0
defender      0
goalkeeper    0
midfielder    0
Name: PLAYER_SHOTS_ON_TARGET_5_last_match_sum, dtype: int64

PLAYER_SHOTS_TOTAL_5_last_match_sum
POSITION
attacker      0
defender      0
goalkeeper    0
midfielder    0
Name: PLAYER_SHOTS_TOTAL_5_last_match_sum, dtype: int64

PLAYER_BLOCKED_SHOTS_5_last_match_average
POSITION
attacker      0
defender      0
goalkeeper    0
midfielder    0
Name: PLAYER_BLOCKED_SHOTS_5_last_match_average, dtype: int64

PLAYER_SHOTS_BLOCKED_5_last_match_average
POSITION
attacker      0
defender      0
goalkeeper    0
midfielder    0
Name: PLAYER_SHOTS_BLOCKED_5_last_match_average, dtype: int64

PLAYER_SHOTS_ON_TARGET_5_last_match_average
POSITION
attacker      0
defender      0
goalkeeper    0
midfielder    0
Name: PLAYER_SHOTS_ON_TARGET_5_last_match_average, dtype: int64

PLAYER_SHOTS_TOTAL_5_last_match_average
POSITION
attacker      0
defender      0
goalkeeper    0
midfielder    0
Name: PLAYER_SHOTS_TOTAL_5_last_match_average, dtype: int64

PLAYER_BLOCKED_SHOTS_5_last_match_std
POSITION
attacker      0
defender      0
goalkeeper    0
midfielder    0
Name: PLAYER_BLOCKED_SHOTS_5_last_match_std, dtype: int64

PLAYER_SHOTS_BLOCKED_5_last_match_std
POSITION
attacker      0
defender      0
goalkeeper    0
midfielder    0
Name: PLAYER_SHOTS_BLOCKED_5_last_match_std, dtype: int64

PLAYER_SHOTS_ON_TARGET_5_last_match_std
POSITION
attacker      0
defender      0
goalkeeper    0
midfielder    0
Name: PLAYER_SHOTS_ON_TARGET_5_last_match_std, dtype: int64

PLAYER_SHOTS_TOTAL_5_last_match_std
POSITION
attacker      0
defender      0
goalkeeper    0
midfielder    0
Name: PLAYER_SHOTS_TOTAL_5_last_match_std, dtype: int64

In [146]:
home_player_processed[col] = home_player_processed[col].fillna(
    home_player_processed[col].median()
)

In [147]:
home_player_processed[shoot_cols].isnull().sum()

PLAYER_BLOCKED_SHOTS_season_sum                0
PLAYER_SHOTS_BLOCKED_season_sum                0
PLAYER_SHOTS_ON_TARGET_season_sum              0
PLAYER_SHOTS_TOTAL_season_sum                  0
PLAYER_BLOCKED_SHOTS_season_average            0
PLAYER_SHOTS_BLOCKED_season_average            0
PLAYER_SHOTS_ON_TARGET_season_average          0
PLAYER_SHOTS_TOTAL_season_average              0
PLAYER_BLOCKED_SHOTS_season_std                0
PLAYER_SHOTS_BLOCKED_season_std                0
PLAYER_SHOTS_ON_TARGET_season_std              0
PLAYER_SHOTS_TOTAL_season_std                  0
PLAYER_BLOCKED_SHOTS_5_last_match_sum          0
PLAYER_SHOTS_BLOCKED_5_last_match_sum          0
PLAYER_SHOTS_ON_TARGET_5_last_match_sum        0
PLAYER_SHOTS_TOTAL_5_last_match_sum            0
PLAYER_BLOCKED_SHOTS_5_last_match_average      0
PLAYER_SHOTS_BLOCKED_5_last_match_average      0
PLAYER_SHOTS_ON_TARGET_5_last_match_average    0
PLAYER_SHOTS_TOTAL_5_last_match_average        0
PLAYER_BLOCKED_SHOTS_5_last_match_std          0
PLAYER_SHOTS_BLOCKED_5_last_match_std          0
PLAYER_SHOTS_ON_TARGET_5_last_match_std        0
PLAYER_SHOTS_TOTAL_5_last_match_std            0
dtype: int64

In [148]:
# Passing

In [149]:
pass_cols = [col for col in home_player_processed.columns if "PASS" in col.upper()]
pass_cols

['PLAYER_ACCURATE_PASSES_season_sum',
 'PLAYER_KEY_PASSES_season_sum',
 'PLAYER_PASSES_season_sum',
 'PLAYER_ACCURATE_PASSES_season_average',
 'PLAYER_ACCURATE_PASSES_PERCENTAGE_season_average',
 'PLAYER_KEY_PASSES_season_average',
 'PLAYER_PASSES_season_average',
 'PLAYER_ACCURATE_PASSES_season_std',
 'PLAYER_ACCURATE_PASSES_PERCENTAGE_season_std',
 'PLAYER_KEY_PASSES_season_std',
 'PLAYER_PASSES_season_std',
 'PLAYER_ACCURATE_PASSES_5_last_match_sum',
 'PLAYER_KEY_PASSES_5_last_match_sum',
 'PLAYER_PASSES_5_last_match_sum',
 'PLAYER_ACCURATE_PASSES_5_last_match_average',
 'PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_average',
 'PLAYER_KEY_PASSES_5_last_match_average',
 'PLAYER_PASSES_5_last_match_average',
 'PLAYER_ACCURATE_PASSES_5_last_match_std',
 'PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_std',
 'PLAYER_KEY_PASSES_5_last_match_std',
 'PLAYER_PASSES_5_last_match_std']

In [150]:
missing_numeric[pass_cols]

PLAYER_ACCURATE_PASSES_season_sum                        11.93
PLAYER_KEY_PASSES_season_sum                             11.93
PLAYER_PASSES_season_sum                                 11.93
PLAYER_ACCURATE_PASSES_season_average                    11.93
PLAYER_ACCURATE_PASSES_PERCENTAGE_season_average          0.00
PLAYER_KEY_PASSES_season_average                         11.93
PLAYER_PASSES_season_average                             11.93
PLAYER_ACCURATE_PASSES_season_std                        13.37
PLAYER_ACCURATE_PASSES_PERCENTAGE_season_std              0.00
PLAYER_KEY_PASSES_season_std                             13.37
PLAYER_PASSES_season_std                                 13.37
PLAYER_ACCURATE_PASSES_5_last_match_sum                  11.93
PLAYER_KEY_PASSES_5_last_match_sum                       11.93
PLAYER_PASSES_5_last_match_sum                           11.93
PLAYER_ACCURATE_PASSES_5_last_match_average              11.93
PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_average    0.00
PLAYER_KEY_PASSES_5_last_match_average                   11.93
PLAYER_PASSES_5_last_match_average                       11.93
PLAYER_ACCURATE_PASSES_5_last_match_std                  13.37
PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_std        0.00
PLAYER_KEY_PASSES_5_last_match_std                       13.37
PLAYER_PASSES_5_last_match_std                           13.37
dtype: float64

In [151]:
home_player_processed[pass_cols].describe()

,PLAYER_ACCURATE_PASSES_season_sum,PLAYER_KEY_PASSES_season_sum,PLAYER_PASSES_season_sum,PLAYER_ACCURATE_PASSES_season_average,PLAYER_ACCURATE_PASSES_PERCENTAGE_season_average,PLAYER_KEY_PASSES_season_average,PLAYER_PASSES_season_average,PLAYER_ACCURATE_PASSES_season_std,PLAYER_ACCURATE_PASSES_PERCENTAGE_season_std,PLAYER_KEY_PASSES_season_std,PLAYER_PASSES_season_std,PLAYER_ACCURATE_PASSES_5_last_match_sum,PLAYER_KEY_PASSES_5_last_match_sum,PLAYER_PASSES_5_last_match_sum,PLAYER_ACCURATE_PASSES_5_last_match_average,PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_average,PLAYER_KEY_PASSES_5_last_match_average,PLAYER_PASSES_5_last_match_average,PLAYER_ACCURATE_PASSES_5_last_match_std,PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_std,PLAYER_KEY_PASSES_5_last_match_std,PLAYER_PASSES_5_last_match_std
count,208790.00,208790.00,208790.00,208790.00,237079.00,208790.00,208790.00,205393.00,237079.00,205393.00,205393.00,208790.00,208790.00,208790.00,208790.00,237079.00,208790.00,208790.00,205393.00,237079.00,205393.00,205393.00
mean,22.72,13.79,25.65,23.23,65.52,14.25,26.44,27.45,25.92,23.81,29.60,21.94,12.54,25.09,21.76,67.16,12.51,24.99,21.83,21.35,17.48,23.62
std,20.85,17.21,22.06,19.59,12.86,16.65,20.69,19.14,10.97,20.09,19.19,20.10,16.73,21.34,19.69,13.41,16.59,20.97,18.28,11.05,18.54,18.66
min,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,6.00,1.00,7.00,8.00,61.00,1.00,9.00,13.00,22.00,8.00,16.00,5.00,0.00,6.00,5.00,62.00,0.00,7.00,8.00,17.00,0.00,10.00
50%,18.00,7.00,21.00,19.00,69.00,9.00,23.00,24.00,23.00,21.00,27.00,18.00,6.00,22.00,18.00,71.00,6.00,22.00,18.00,19.00,15.00,20.00
75%,34.00,20.00,40.00,35.00,70.00,22.00,40.00,39.00,32.00,36.00,42.00,33.00,19.00,39.00,33.00,72.00,20.00,38.00,32.00,25.00,28.00,34.00
max,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00

In [152]:
for col in pass_cols:
    print(f"\n{col}")
    print(
        home_player_processed
        .groupby("POSITION")[col]
        .apply(lambda x: x.notna().sum())
    )

PLAYER_ACCURATE_PASSES_season_sum
POSITION
attacker      22658
defender      59297
goalkeeper    21290
midfielder    69008
Name: PLAYER_ACCURATE_PASSES_season_sum, dtype: int64

PLAYER_KEY_PASSES_season_sum
POSITION
attacker      22658
defender      59297
goalkeeper    21290
midfielder    69008
Name: PLAYER_KEY_PASSES_season_sum, dtype: int64

PLAYER_PASSES_season_sum
POSITION
attacker      22658
defender      59297
goalkeeper    21290
midfielder    69008
Name: PLAYER_PASSES_season_sum, dtype: int64

PLAYER_ACCURATE_PASSES_season_average
POSITION
attacker      22658
defender      59297
goalkeeper    21290
midfielder    69008
Name: PLAYER_ACCURATE_PASSES_season_average, dtype: int64

PLAYER_ACCURATE_PASSES_PERCENTAGE_season_average
POSITION
attacker      23691
defender      67746
goalkeeper    24298
midfielder    78524
Name: PLAYER_ACCURATE_PASSES_PERCENTAGE_season_average, dtype: int64

PLAYER_KEY_PASSES_season_average
POSITION
attacker      22658
defender      59297
goalkeeper    21290
midfielder    69008
Name: PLAYER_KEY_PASSES_season_average, dtype: int64

PLAYER_PASSES_season_average
POSITION
attacker      22658
defender      59297
goalkeeper    21290
midfielder    69008
Name: PLAYER_PASSES_season_average, dtype: int64

PLAYER_ACCURATE_PASSES_season_std
POSITION
attacker      22263
defender      58409
goalkeeper    21000
midfielder    67969
Name: PLAYER_ACCURATE_PASSES_season_std, dtype: int64

PLAYER_ACCURATE_PASSES_PERCENTAGE_season_std
POSITION
attacker      23691
defender      67746
goalkeeper    24298
midfielder    78524
Name: PLAYER_ACCURATE_PASSES_PERCENTAGE_season_std, dtype: int64

PLAYER_KEY_PASSES_season_std
POSITION
attacker      22263
defender      58409
goalkeeper    21000
midfielder    67969
Name: PLAYER_KEY_PASSES_season_std, dtype: int64

PLAYER_PASSES_season_std
POSITION
attacker      22263
defender      58409
goalkeeper    21000
midfielder    67969
Name: PLAYER_PASSES_season_std, dtype: int64

PLAYER_ACCURATE_PASSES_5_last_match_sum
POSITION
attacker      22658
defender      59297
goalkeeper    21290
midfielder    69008
Name: PLAYER_ACCURATE_PASSES_5_last_match_sum, dtype: int64

PLAYER_KEY_PASSES_5_last_match_sum
POSITION
attacker      22658
defender      59297
goalkeeper    21290
midfielder    69008
Name: PLAYER_KEY_PASSES_5_last_match_sum, dtype: int64

PLAYER_PASSES_5_last_match_sum
POSITION
attacker      22658
defender      59297
goalkeeper    21290
midfielder    69008
Name: PLAYER_PASSES_5_last_match_sum, dtype: int64

PLAYER_ACCURATE_PASSES_5_last_match_average
POSITION
attacker      22658
defender      59297
goalkeeper    21290
midfielder    69008
Name: PLAYER_ACCURATE_PASSES_5_last_match_average, dtype: int64

PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_average
POSITION
attacker      23691
defender      67746
goalkeeper    24298
midfielder    78524
Name: PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_average, dtype: int64

PLAYER_KEY_PASSES_5_last_match_average
POSITION
attacker      22658
defender      59297
goalkeeper    21290
midfielder    69008
Name: PLAYER_KEY_PASSES_5_last_match_average, dtype: int64

PLAYER_PASSES_5_last_match_average
POSITION
attacker      22658
defender      59297
goalkeeper    21290
midfielder    69008
Name: PLAYER_PASSES_5_last_match_average, dtype: int64

PLAYER_ACCURATE_PASSES_5_last_match_std
POSITION
attacker      22263
defender      58409
goalkeeper    21000
midfielder    67969
Name: PLAYER_ACCURATE_PASSES_5_last_match_std, dtype: int64

PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_std
POSITION
attacker      23691
defender      67746
goalkeeper    24298
midfielder    78524
Name: PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_std, dtype: int64

PLAYER_KEY_PASSES_5_last_match_std
POSITION
attacker      22263
defender      58409
goalkeeper    21000
midfielder    67969
Name: PLAYER_KEY_PASSES_5_last_match_std, dtype: int64

PLAYER_PASSES_5_last_match_std
POSITION
attacker      22263
defender      58409
goalkeeper    21000
midfielder    67969
Name: PLAYER_PASSES_5_last_match_std, dtype: int64

In [153]:
home_player_processed.groupby("POSITION")[pass_cols].median()

,PLAYER_ACCURATE_PASSES_season_sum,PLAYER_KEY_PASSES_season_sum,PLAYER_PASSES_season_sum,PLAYER_ACCURATE_PASSES_season_average,PLAYER_ACCURATE_PASSES_PERCENTAGE_season_average,PLAYER_KEY_PASSES_season_average,PLAYER_PASSES_season_average,PLAYER_ACCURATE_PASSES_season_std,PLAYER_ACCURATE_PASSES_PERCENTAGE_season_std,PLAYER_KEY_PASSES_season_std,PLAYER_PASSES_season_std,PLAYER_ACCURATE_PASSES_5_last_match_sum,PLAYER_KEY_PASSES_5_last_match_sum,PLAYER_PASSES_5_last_match_sum,PLAYER_ACCURATE_PASSES_5_last_match_average,PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_average,PLAYER_KEY_PASSES_5_last_match_average,PLAYER_PASSES_5_last_match_average,PLAYER_ACCURATE_PASSES_5_last_match_std,PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_std,PLAYER_KEY_PASSES_5_last_match_std,PLAYER_PASSES_5_last_match_std
POSITION,,,,,,,,,,,,,,,,,,,,,,
attacker,10.00,13.00,12.00,11.00,62.00,15.00,14.00,14.00,33.00,29.00,17.00,10.00,11.00,13.00,10.00,64.00,11.00,13.00,11.00,25.00,19.00,13.00
defender,28.00,5.00,32.00,30.00,69.00,5.00,35.00,38.00,22.00,17.00,40.00,28.00,5.00,33.00,28.00,71.00,5.00,34.00,29.00,17.00,13.00,31.00
goalkeeper,6.00,0.00,10.00,7.00,46.00,0.00,10.00,11.00,33.00,0.00,15.00,5.00,0.00,8.00,5.00,48.00,0.00,8.00,6.00,27.00,0.00,8.00
midfielder,21.00,14.00,24.00,23.00,70.00,16.00,26.00,28.00,23.00,29.00,30.00,21.00,12.00,24.00,21.00,71.00,12.00,25.00,21.00,19.00,19.00,23.00

In [154]:
for col in pass_cols:
    home_player_processed[col] = (
        home_player_processed
        .groupby("POSITION")[col]
        .transform(lambda x: x.fillna(x.median()))
    )

In [155]:
home_player_processed[pass_cols].isnull().sum()

PLAYER_ACCURATE_PASSES_season_sum                         42820
PLAYER_KEY_PASSES_season_sum                              42820
PLAYER_PASSES_season_sum                                  42820
PLAYER_ACCURATE_PASSES_season_average                     42820
PLAYER_ACCURATE_PASSES_PERCENTAGE_season_average          42820
PLAYER_KEY_PASSES_season_average                          42820
PLAYER_PASSES_season_average                              42820
PLAYER_ACCURATE_PASSES_season_std                         42820
PLAYER_ACCURATE_PASSES_PERCENTAGE_season_std              42820
PLAYER_KEY_PASSES_season_std                              42820
PLAYER_PASSES_season_std                                  42820
PLAYER_ACCURATE_PASSES_5_last_match_sum                   42820
PLAYER_KEY_PASSES_5_last_match_sum                        42820
PLAYER_PASSES_5_last_match_sum                            42820
PLAYER_ACCURATE_PASSES_5_last_match_average               42820
PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_average    42820
PLAYER_KEY_PASSES_5_last_match_average                    42820
PLAYER_PASSES_5_last_match_average                        42820
PLAYER_ACCURATE_PASSES_5_last_match_std                   42820
PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_std        42820
PLAYER_KEY_PASSES_5_last_match_std                        42820
PLAYER_PASSES_5_last_match_std                            42820
dtype: int64

In [156]:
for col in pass_cols:
    home_player_processed[col] = home_player_processed[col].fillna(
        home_player_processed[col].median()
    )

In [157]:
home_player_processed[pass_cols].isnull().sum()

PLAYER_ACCURATE_PASSES_season_sum                         0
PLAYER_KEY_PASSES_season_sum                              0
PLAYER_PASSES_season_sum                                  0
PLAYER_ACCURATE_PASSES_season_average                     0
PLAYER_ACCURATE_PASSES_PERCENTAGE_season_average          0
PLAYER_KEY_PASSES_season_average                          0
PLAYER_PASSES_season_average                              0
PLAYER_ACCURATE_PASSES_season_std                         0
PLAYER_ACCURATE_PASSES_PERCENTAGE_season_std              0
PLAYER_KEY_PASSES_season_std                              0
PLAYER_PASSES_season_std                                  0
PLAYER_ACCURATE_PASSES_5_last_match_sum                   0
PLAYER_KEY_PASSES_5_last_match_sum                        0
PLAYER_PASSES_5_last_match_sum                            0
PLAYER_ACCURATE_PASSES_5_last_match_average               0
PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_average    0
PLAYER_KEY_PASSES_5_last_match_average                    0
PLAYER_PASSES_5_last_match_average                        0
PLAYER_ACCURATE_PASSES_5_last_match_std                   0
PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_std        0
PLAYER_KEY_PASSES_5_last_match_std                        0
PLAYER_PASSES_5_last_match_std                            0
dtype: int64

In [158]:
# Tackle

In [159]:
tackle_cols = [col for col in home_player_processed.columns if "TACKLE" in col.upper()]
tackle_cols

['PLAYER_TACKLES_season_sum',
 'PLAYER_TACKLES_season_average',
 'PLAYER_TACKLES_season_std',
 'PLAYER_TACKLES_5_last_match_sum',
 'PLAYER_TACKLES_5_last_match_average',
 'PLAYER_TACKLES_5_last_match_std']

In [160]:
missing_numeric[tackle_cols]

PLAYER_TACKLES_season_sum             11.93
PLAYER_TACKLES_season_average         11.93
PLAYER_TACKLES_season_std             13.37
PLAYER_TACKLES_5_last_match_sum       11.93
PLAYER_TACKLES_5_last_match_average   11.93
PLAYER_TACKLES_5_last_match_std       13.37
dtype: float64

In [161]:
home_player_processed[tackle_cols].describe()

,PLAYER_TACKLES_season_sum,PLAYER_TACKLES_season_average,PLAYER_TACKLES_season_std,PLAYER_TACKLES_5_last_match_sum,PLAYER_TACKLES_5_last_match_average,PLAYER_TACKLES_5_last_match_std
count,208790.00,208790.00,205393.00,208790.00,208790.00,205393.00
mean,19.81,19.55,28.11,17.46,17.14,21.67
std,20.13,18.66,20.18,18.92,18.46,19.34
min,0.00,0.00,0.00,0.00,0.00,0.00
25%,3.00,4.00,13.00,0.00,0.00,0.00
50%,14.00,15.00,28.00,12.00,12.00,19.00
75%,31.00,30.00,42.00,27.00,27.00,33.00
max,100.00,100.00,100.00,100.00,100.00,100.00

In [162]:
for col in tackle_cols:
    print(f"\n{col}")
    print(
        home_player_processed
        .groupby("POSITION")[col]
        .apply(lambda x: x.notna().sum())
    )

PLAYER_TACKLES_season_sum
POSITION
attacker      22658
defender      59297
goalkeeper    21290
midfielder    69008
Name: PLAYER_TACKLES_season_sum, dtype: int64

PLAYER_TACKLES_season_average
POSITION
attacker      22658
defender      59297
goalkeeper    21290
midfielder    69008
Name: PLAYER_TACKLES_season_average, dtype: int64

PLAYER_TACKLES_season_std
POSITION
attacker      22263
defender      58409
goalkeeper    21000
midfielder    67969
Name: PLAYER_TACKLES_season_std, dtype: int64

PLAYER_TACKLES_5_last_match_sum
POSITION
attacker      22658
defender      59297
goalkeeper    21290
midfielder    69008
Name: PLAYER_TACKLES_5_last_match_sum, dtype: int64

PLAYER_TACKLES_5_last_match_average
POSITION
attacker      22658
defender      59297
goalkeeper    21290
midfielder    69008
Name: PLAYER_TACKLES_5_last_match_average, dtype: int64

PLAYER_TACKLES_5_last_match_std
POSITION
attacker      22263
defender      58409
goalkeeper    21000
midfielder    67969
Name: PLAYER_TACKLES_5_last_match_std, dtype: int64

In [163]:
home_player_processed.groupby("POSITION")[tackle_cols].median()

,PLAYER_TACKLES_season_sum,PLAYER_TACKLES_season_average,PLAYER_TACKLES_season_std,PLAYER_TACKLES_5_last_match_sum,PLAYER_TACKLES_5_last_match_average,PLAYER_TACKLES_5_last_match_std
POSITION,,,,,,
attacker,9.00,10.00,21.00,7.00,7.00,14.00
defender,22.00,23.00,35.00,19.00,19.00,25.00
goalkeeper,0.00,0.00,0.00,0.00,0.00,0.00
midfielder,21.00,22.00,34.00,18.00,18.00,25.00

In [164]:
for col in pass_cols:
    home_player_processed[col] = (
        home_player_processed
        .groupby("POSITION")[col]
        .transform(lambda x: x.fillna(x.median()))
    )

In [165]:
home_player_processed[pass_cols].isnull().sum()

PLAYER_ACCURATE_PASSES_season_sum                         42820
PLAYER_KEY_PASSES_season_sum                              42820
PLAYER_PASSES_season_sum                                  42820
PLAYER_ACCURATE_PASSES_season_average                     42820
PLAYER_ACCURATE_PASSES_PERCENTAGE_season_average          42820
PLAYER_KEY_PASSES_season_average                          42820
PLAYER_PASSES_season_average                              42820
PLAYER_ACCURATE_PASSES_season_std                         42820
PLAYER_ACCURATE_PASSES_PERCENTAGE_season_std              42820
PLAYER_KEY_PASSES_season_std                              42820
PLAYER_PASSES_season_std                                  42820
PLAYER_ACCURATE_PASSES_5_last_match_sum                   42820
PLAYER_KEY_PASSES_5_last_match_sum                        42820
PLAYER_PASSES_5_last_match_sum                            42820
PLAYER_ACCURATE_PASSES_5_last_match_average               42820
PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_average    42820
PLAYER_KEY_PASSES_5_last_match_average                    42820
PLAYER_PASSES_5_last_match_average                        42820
PLAYER_ACCURATE_PASSES_5_last_match_std                   42820
PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_std        42820
PLAYER_KEY_PASSES_5_last_match_std                        42820
PLAYER_PASSES_5_last_match_std                            42820
dtype: int64

In [166]:
for col in pass_cols:
    home_player_processed[col].fillna(
        home_player_processed[col].median(),
        inplace=True
    )

In [167]:
home_player_processed[pass_cols].isnull().sum()

PLAYER_ACCURATE_PASSES_season_sum                         0
PLAYER_KEY_PASSES_season_sum                              0
PLAYER_PASSES_season_sum                                  0
PLAYER_ACCURATE_PASSES_season_average                     0
PLAYER_ACCURATE_PASSES_PERCENTAGE_season_average          0
PLAYER_KEY_PASSES_season_average                          0
PLAYER_PASSES_season_average                              0
PLAYER_ACCURATE_PASSES_season_std                         0
PLAYER_ACCURATE_PASSES_PERCENTAGE_season_std              0
PLAYER_KEY_PASSES_season_std                              0
PLAYER_PASSES_season_std                                  0
PLAYER_ACCURATE_PASSES_5_last_match_sum                   0
PLAYER_KEY_PASSES_5_last_match_sum                        0
PLAYER_PASSES_5_last_match_sum                            0
PLAYER_ACCURATE_PASSES_5_last_match_average               0
PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_average    0
PLAYER_KEY_PASSES_5_last_match_average                    0
PLAYER_PASSES_5_last_match_average                        0
PLAYER_ACCURATE_PASSES_5_last_match_std                   0
PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_std        0
PLAYER_KEY_PASSES_5_last_match_std                        0
PLAYER_PASSES_5_last_match_std                            0
dtype: int64

In [168]:
# Tackles

In [169]:
for col in tackle_cols:
    home_player_processed[col] = (
        home_player_processed
        .groupby("POSITION")[col]
        .transform(lambda x: x.fillna(x.median()))
    )

In [170]:
for col in tackle_cols:
    home_player_processed[col].fillna(
        home_player_processed[col].median(),
        inplace=True
    )

In [171]:
home_player_processed[tackle_cols].isnull().sum()

PLAYER_TACKLES_season_sum              0
PLAYER_TACKLES_season_average          0
PLAYER_TACKLES_season_std              0
PLAYER_TACKLES_5_last_match_sum        0
PLAYER_TACKLES_5_last_match_average    0
PLAYER_TACKLES_5_last_match_std        0
dtype: int64

In [172]:
feature_groups = {
    "aerial": "AERIAL",
    "assist": "ASSIST",
    "big_created": "BIG_CHANCES_CREATED",
    "big_missed": "BIG_CHANCES_MISSED",
    "clearance": "CLEARANCE",
    "clearances": "CLEARANCES",
    "dispossessed": "DISPOSSESSED",
    "duels": "DUELS",
    "interceptions": "INTERCEPTION",
    "fouls": "FOUL",
    "goals": "GOAL",
    "saves": "SAVE",
    "penalties": "PENALT",
    "own_goals": "OWN_GOAL",
    "woodwork": "WOODWORK",
    "offsides": "OFFSIDE",
    "yellow_cards": "YELLOWCARD",
    "red_cards": "REDCARD",
    "errors": "ERROR",
    "minutes": "MINUTES_PLAYED",
    "starting": "STARTING_LINEUP",
    "rating": "RATING"
}

In [173]:
for keyword in feature_groups.values():

    cols = [
        col for col in home_player_processed.columns
        if keyword in col.upper()
    ]

    if len(cols) == 0:
        continue

    # Position-wise median
    for col in cols:
        home_player_processed[col] = (
            home_player_processed
            .groupby("POSITION")[col]
            .transform(lambda x: x.fillna(x.median()))
        )

    # Overall median fallback
    for col in cols:
        home_player_processed[col].fillna(
            home_player_processed[col].median(),
            inplace=True
        )

In [174]:
remaining_missing = (
    home_player_processed
    .select_dtypes(include="number")
    .isnull()
    .sum()
)

remaining_missing = remaining_missing[remaining_missing > 0]

print("Columns with missing values:", len(remaining_missing))
print("Total missing values:", remaining_missing.sum())

remaining_missing

Columns with missing values: 0
Total missing values: 0

Series([], dtype: int64)

In [175]:
missing_cols = home_player_processed.columns[
    home_player_processed.isnull().any()
]

print("Number of columns with missing values:", len(missing_cols))
print(missing_cols.tolist())

Number of columns with missing values: 1
['POSITION']

In [176]:
home_player_processed["POSITION"].isnull().sum()

np.int64(42820)

In [177]:
print(home_player_processed.shape)

home_player_processed["POSITION"].value_counts(dropna=False)

(237079, 277)

POSITION
midfielder    78524
defender      67746
NaN           42820
goalkeeper    24298
attacker      23691
Name: count, dtype: int64

In [178]:
home_player_processed[
    home_player_processed["POSITION"].isnull()
].head()

,ID,LEAGUE,TEAM_NAME,POSITION,PLAYER_NAME,PLAYER_ACCURATE_CROSSES_season_sum,PLAYER_ACCURATE_PASSES_season_sum,PLAYER_AERIALS_WON_season_sum,PLAYER_ASSISTS_season_sum,PLAYER_BIG_CHANCES_CREATED_season_sum,PLAYER_BIG_CHANCES_MISSED_season_sum,PLAYER_BLOCKED_SHOTS_season_sum,PLAYER_CLEARANCES_season_sum,PLAYER_CLEARANCE_OFFLINE_season_sum,PLAYER_DISPOSSESSED_season_sum,PLAYER_DRIBBLED_ATTEMPTS_season_sum,PLAYER_DRIBBLED_PAST_season_sum,PLAYER_DUELS_LOST_season_sum,PLAYER_DUELS_WON_season_sum,PLAYER_ERROR_LEAD_TO_GOAL_season_sum,PLAYER_FOULS_season_sum,PLAYER_FOULS_DRAWN_season_sum,PLAYER_GOALKEEPER_GOALS_CONCEDED_season_sum,PLAYER_GOALS_season_sum,PLAYER_GOALS_CONCEDED_season_sum,PLAYER_HIT_WOODWORK_season_sum,PLAYER_INTERCEPTIONS_season_sum,PLAYER_KEY_PASSES_season_sum,PLAYER_MINUTES_PLAYED_season_sum,PLAYER_OFFSIDES_season_sum,PLAYER_OWN_GOALS_season_sum,PLAYER_PASSES_season_sum,PLAYER_PENALTIES_COMMITTED_season_sum,PLAYER_PENALTIES_MISSES_season_sum,PLAYER_PENALTIES_SAVED_season_sum,PLAYER_PENALTIES_SCORED_season_sum,PLAYER_PENALTIES_WON_season_sum,PLAYER_REDCARDS_season_sum,PLAYER_SAVES_season_sum,PLAYER_SAVES_INSIDE_BOX_season_sum,PLAYER_SHOTS_BLOCKED_season_sum,PLAYER_SHOTS_ON_TARGET_season_sum,PLAYER_SHOTS_TOTAL_season_sum,PLAYER_STARTING_LINEUP_season_sum,PLAYER_SUCCESSFUL_DRIBBLES_season_sum,PLAYER_TACKLES_season_sum,PLAYER_TOTAL_CROSSES_season_sum,PLAYER_TOTAL_DUELS_season_sum,PLAYER_YELLOWCARDS_season_sum,PLAYER_ACCURATE_CROSSES_season_average,PLAYER_ACCURATE_PASSES_season_average,PLAYER_ACCURATE_PASSES_PERCENTAGE_season_average,PLAYER_AERIALS_WON_season_average,PLAYER_ASSISTS_season_average,PLAYER_BIG_CHANCES_CREATED_season_average,PLAYER_BIG_CHANCES_MISSED_season_average,PLAYER_BLOCKED_SHOTS_season_average,PLAYER_CLEARANCES_season_average,PLAYER_CLEARANCE_OFFLINE_season_average,PLAYER_DISPOSSESSED_season_average,PLAYER_DRIBBLED_ATTEMPTS_season_average,PLAYER_DRIBBLED_PAST_season_average,PLAYER_DUELS_LOST_season_average,PLAYER_DUELS_WON_season_average,PLAYER_ERROR_LEAD_TO_GOAL_season_average,PLAYER_FOULS_season_average,PLAYER_FOULS_DRAWN_season_average,PLAYER_GOALKEEPER_GOALS_CONCEDED_season_average,PLAYER_GOALS_season_average,PLAYER_GOALS_CONCEDED_season_average,PLAYER_HIT_WOODWORK_season_average,PLAYER_INTERCEPTIONS_season_average,PLAYER_KEY_PASSES_season_average,PLAYER_MINUTES_PLAYED_season_average,PLAYER_OFFSIDES_season_average,PLAYER_OWN_GOALS_season_average,PLAYER_PASSES_season_average,PLAYER_PENALTIES_COMMITTED_season_average,PLAYER_PENALTIES_MISSES_season_average,PLAYER_PENALTIES_SAVED_season_average,PLAYER_PENALTIES_SCORED_season_average,PLAYER_PENALTIES_WON_season_average,PLAYER_RATING_season_average,PLAYER_REDCARDS_season_average,PLAYER_SAVES_season_average,PLAYER_SAVES_INSIDE_BOX_season_average,PLAYER_SHOTS_BLOCKED_season_average,PLAYER_SHOTS_ON_TARGET_season_average,PLAYER_SHOTS_TOTAL_season_average,PLAYER_STARTING_LINEUP_season_average,PLAYER_SUCCESSFUL_DRIBBLES_season_average,PLAYER_TACKLES_season_average,PLAYER_TOTAL_CROSSES_season_average,PLAYER_TOTAL_DUELS_season_average,PLAYER_YELLOWCARDS_season_average,PLAYER_ACCURATE_CROSSES_season_std,PLAYER_ACCURATE_PASSES_season_std,PLAYER_ACCURATE_PASSES_PERCENTAGE_season_std,PLAYER_AERIALS_WON_season_std,PLAYER_ASSISTS_season_std,PLAYER_BIG_CHANCES_CREATED_season_std,PLAYER_BIG_CHANCES_MISSED_season_std,PLAYER_BLOCKED_SHOTS_season_std,PLAYER_CLEARANCES_season_std,PLAYER_CLEARANCE_OFFLINE_season_std,PLAYER_DISPOSSESSED_season_std,PLAYER_DRIBBLED_ATTEMPTS_season_std,PLAYER_DRIBBLED_PAST_season_std,PLAYER_DUELS_LOST_season_std,PLAYER_DUELS_WON_season_std,PLAYER_ERROR_LEAD_TO_GOAL_season_std,PLAYER_FOULS_season_std,PLAYER_FOULS_DRAWN_season_std,PLAYER_GOALKEEPER_GOALS_CONCEDED_season_std,PLAYER_GOALS_season_std,PLAYER_GOALS_CONCEDED_season_std,PLAYER_HIT_WOODWORK_season_std,PLAYER_INTERCEPTIONS_season_std,PLAYER_KEY_PASSES_season_std,PLAYER_MINUTES_PLAYED_season_std,PLAYER_OFFSIDES_season_std,PLAYER_OWN_GOALS_season_std,PLAYER_PASSES_season_std,PLAYER_PENALTIES_COMMITTED_season_std,PLAYER_PENALTIES_MISSES_season_std,PLAYER_PENALTIES_SAVED_season_std,PLAYER_PENALTIES_SCORED_season_std,PLAYER_PENALTIES_WON_season_std,PLAYER_RATING_season_std,PLAYER_REDCARDS_season_std,PLAYER_SAVES_season_std,PLAYER_SAVES_INSIDE_BOX_season_std,PLAYER_SHOTS_BLOCKED_season_std,PLAYER_SHOTS_ON_TARGET_season_std,PLAYER_SHOTS_TOTAL_season_std,PLAYER_STARTING_LINEUP_season_std,PLAYER_SUCCESSFUL_DRIBBLES_season_std,PLAYER_TACKLES_season_std,PLAYER_TOTAL_CROSSES_season_std,PLAYER_TOTAL_DUELS_season_std,PLAYER_YELLOWCARDS_season_std,PLAYER_ACCURATE_CROSSES_5_last_match_sum,PLAYER_ACCURATE_PASSES_5_last_match_sum,PLAYER_AERIALS_WON_5_last_match_sum,PLAYER_ASSISTS_5_last_match_sum,PLAYER_BIG_CHANCES_CREATED_5_last_match_sum,PLAYER_BIG_CHANCES_MISSED_5_last_match_sum,PLAYER_BLOCKED_SHOTS_5_last_match_sum,PLAYER_CLEARANCES_5_last_match_sum,PLAYER_CLEARANCE_OFFLINE_5_last_match_sum,PLAYER_DISPOSSESSED_5_last_match_sum,PLAYER_DRIBBLED_ATTEMPTS_5_last_match_sum,PLAYER_DRIBBLED_PAST_5_last_match_sum,PLAYER_DUELS_LOST_5_last_match_sum,PLAYER_DUELS_WON_5_last_match_sum,PLAYER_ERROR_LEAD_TO_GOAL_5_last_match_sum,PLAYER_FOULS_5_last_match_sum,PLAYER_FOULS_DRAWN_5_last_match_sum,PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_sum,PLAYER_GOALS_5_last_match_sum,PLAYER_GOALS_CONCEDED_5_last_match_sum,PLAYER_HIT_WOODWORK_5_last_match_sum,PLAYER_INTERCEPTIONS_5_last_match_sum,PLAYER_KEY_PASSES_5_last_match_sum,PLAYER_MINUTES_PLAYED_5_last_match_sum,PLAYER_OFFSIDES_5_last_match_sum,PLAYER_OWN_GOALS_5_last_match_sum,PLAYER_PASSES_5_last_match_sum,PLAYER_PENALTIES_COMMITTED_5_last_match_sum,PLAYER_PENALTIES_MISSES_5_last_match_sum,PLAYER_PENALTIES_SAVED_5_last_match_sum,PLAYER_PENALTIES_SCORED_5_last_match_sum,PLAYER_PENALTIES_WON_5_last_match_sum,PLAYER_REDCARDS_5_last_match_sum,PLAYER_SAVES_5_last_match_sum,PLAYER_SAVES_INSIDE_BOX_5_last_match_sum,PLAYER_SHOTS_BLOCKED_5_last_match_sum,PLAYER_SHOTS_ON_TARGET_5_last_match_sum,PLAYER_SHOTS_TOTAL_5_last_match_sum,PLAYER_STARTING_LINEUP_5_last_match_sum,PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_sum,PLAYER_TACKLES_5_last_match_sum,PLAYER_TOTAL_CROSSES_5_last_match_sum,PLAYER_TOTAL_DUELS_5_last_match_sum,PLAYER_YELLOWCARDS_5_last_match_sum,PLAYER_ACCURATE_CROSSES_5_last_match_average,PLAYER_ACCURATE_PASSES_5_last_match_average,PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_average,PLAYER_AERIALS_WON_5_last_match_average,PLAYER_ASSISTS_5_last_match_average,PLAYER_BIG_CHANCES_CREATED_5_last_match_average,PLAYER_BIG_CHANCES_MISSED_5_last_match_average,PLAYER_BLOCKED_SHOTS_5_last_match_average,PLAYER_CLEARANCES_5_last_match_average,PLAYER_CLEARANCE_OFFLINE_5_last_match_average,PLAYER_DISPOSSESSED_5_last_match_average,PLAYER_DRIBBLED_ATTEMPTS_5_last_match_average,PLAYER_DRIBBLED_PAST_5_last_match_average,PLAYER_DUELS_LOST_5_last_match_average,PLAYER_DUELS_WON_5_last_match_average,PLAYER_ERROR_LEAD_TO_GOAL_5_last_match_average,PLAYER_FOULS_5_last_match_average,PLAYER_FOULS_DRAWN_5_last_match_average,PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_average,PLAYER_GOALS_5_last_match_average,PLAYER_GOALS_CONCEDED_5_last_match_average,PLAYER_HIT_WOODWORK_5_last_match_average,PLAYER_INTERCEPTIONS_5_last_match_average,PLAYER_KEY_PASSES_5_last_match_average,PLAYER_MINUTES_PLAYED_5_last_match_average,PLAYER_OFFSIDES_5_last_match_average,PLAYER_OWN_GOALS_5_last_match_average,PLAYER_PASSES_5_last_match_average,PLAYER_PENALTIES_COMMITTED_5_last_match_average,PLAYER_PENALTIES_MISSES_5_last_match_average,PLAYER_PENALTIES_SAVED_5_last_match_average,PLAYER_PENALTIES_SCORED_5_last_match_average,PLAYER_PENALTIES_WON_5_last_match_average,PLAYER_RATING_5_last_match_average,PLAYER_REDCARDS_5_last_match_average,PLAYER_SAVES_5_last_match_average,PLAYER_SAVES_INSIDE_BOX_5_last_match_average,PLAYER_SHOTS_BLOCKED_5_last_match_average,PLAYER_SHOTS_ON_TARGET_5_last_match_average,PLAYER_SHOTS_TOTAL_5_last_match_average,PLAYER_STARTING_LINEUP_5_last_match_average,PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_average,PLAYER_TACKLES_5_last_match_average,PLAYER_TOTAL_CROSSES_5_last_match_average,PLAYER_TOTAL_DUELS_5_last_match_average,PLAYER_YELLOWCARDS_5_last_match_average,PLAYER_ACCURATE_CROSSES_5_last_match_std,PLAYER_ACCURATE_PASSES_5_last_match_std,PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_std,PLAYER_AERIALS_WON_5_last_match_std,PLAYER_ASSISTS_5_last_match_std,PLAYER_BIG_CHANCES_CREATED_5_last_match_std,PLAYER_BIG_CHANCES_MISSED_5_last_match_std,PLAYER_BLOCKED_SHOTS_5_last_match_std,PLAYER_CLEARANCES_5_last_match_std,PLAYER_CLEARANCE_OFFLINE_5_last_match_std,PLAYER_DISPOSSESSED_5_last_match_std,PLAYER_DRIBBLED_ATTEMPTS_5_last_match_std,PLAYER_DRIBBLED_PAST_5_last_match_std,PLAYER_DUELS_LOST_5_last_match_std,PLAYER_DUELS_WON_5_last_match_std,PLAYER_ERROR_LEAD_TO_GOAL_5_last_match_std,PLAYER_FOULS_5_last_match_std,PLAYER_FOULS_DRAWN_5_last_match_std,PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_std,PLAYER_GOALS_5_last_match_std,PLAYER_GOALS_CONCEDED_5_last_match_std,PLAYER_HIT_WOODWORK_5_last_match_std,PLAYER_INTERCEPTIONS_5_last_match_std,PLAYER_KEY_PASSES_5_last_match_std,PLAYER_MINUTES_PLAYED_5_last_match_std,PLAYER_OFFSIDES_5_last_match_std,PLAYER_OWN_GOALS_5_last_match_std,PLAYER_PASSES_5_last_match_std,PLAYER_PENALTIES_COMMITTED_5_last_match_std,PLAYER_PENALTIES_MISSES_5_last_match_std,PLAYER_PENALTIES_SAVED_5_last_match_std,PLAYER_PENALTIES_SCORED_5_last_match_std,PLAYER_PENALTIES_WON_5_last_match_std,PLAYER_RATING_5_last_match_std,PLAYER_REDCARDS_5_last_match_std,PLAYER_SAVES_5_last_match_std,PLAYER_SAVES_INSIDE_BOX_5_last_match_std,PLAYER_SHOTS_BLOCKED_5_last_match_std,PLAYER_SHOTS_ON_TARGET_5_last_match_std,PLAYER_SHOTS_TOTAL_5_last_match_std,PLAYER_STARTING_LINEUP_5_last_match_std,PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_std,PLAYER_TACKLES_5_last_match_std,PLAYER_TOTAL_CROSSES_5_last_match_std,PLAYER_TOTAL_DUELS_5_last_match_std,PLAYER_YELLOWCARDS_5_last_match_std
4,0,Ligue 1,Toulouse,NaN,Efthymios Koulouris,1.00,21.00,7.00,0.00,0.00,0.00,4.00,7.00,0.00,7.00,5.00,12.00,19.00,24.00,0.00,20.00,11.00,0.00,0.00,47.00,0.00,14.00,7.00,46.00,0.00,0.00,24.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,13.00,4.00,7.00,47.00,5.00,18.00,2.00,25.00,15.00,1.00,23.00,69.00,7.00,0.00,0.00,0.00,4.00,7.00,0.00,7.00,6.00,11.00,21.00,26.00,0.00,20.00,12.00,0.00,0.00,28.00,0.00,15.00,8.00,62.00,0.00,0.00,26.00,0.00,0.00,0.00,0.00,0.00,72.00,0.00,0.00,0.00,12.00,4.00,8.00,63.00,5.00,19.00,3.00,28.00,10.00,8.00,28.00,23.00,18.00,0.00,0.00,0.00,15.00,17.00,0.00,18.00,15.00,23.00,30.00,37.00,0.00,34.00,27.00,0.00,0.00,36.00,0.00,27.00,20.00,46.00,0.00,0.00,30.00,0.00,0.00,0.00,0.00,0.00,43.00,0.00,0.00,0.00,27.00,17.00,21.00,54.00,15.00,31.00,9.00,35.00,41.00,0.00,21.00,6.00,0.00,0.00,0.00,0.00,6.00,0.00,5.00,4.00,8.00,18.00,24.00,0.00,17.00,10.00,0.00,0.00,38.00,0.00,12.00,5.00,62.00,0.00,0.00,24.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,11.00,0.00,5.00,60.00,4.00,15.00,2.00,25.00,0.00,0.00,21.00,71.00,6.00,0.00,0.00,0.00,0.00,6.00,0.00,5.00,4.00,8.00,18.00,23.00,0.00,16.00,10.00,0.00,0.00,28.00,0.00,11.00,5.00,64.00,0.00,0.00,25.00,0.00,0.00,0.00,0.00,0.00,73.00,0.00,0.00,0.00,10.00,0.00,5.00,60.00,4.00,15.00,2.00,25.00,0.00,0.00,21.00,19.00,12.00,0.00,0.00,0.00,0.00,11.00,0.00,13.00,11.00,17.00,23.00,28.00,0.00,25.00,19.00,0.00,0.00,32.00,0.00,18.00,15.00,26.00,0.00,0.00,23.00,0.00,0.00,0.00,0.00,0.00,12.00,0.00,0.00,0.00,20.00,0.00,15.00,0.00,12.00,22.00,7.00,28.00,0.00
9,0,Ligue 1,Toulouse,NaN,Aaron Leya Iseka,1.00,21.00,7.00,0.00,0.00,0.00,4.00,7.00,0.00,7.00,5.00,12.00,19.00,24.00,0.00,20.00,11.00,0.00,0.00,47.00,0.00,14.00,7.00,46.00,0.00,0.00,24.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,13.00,4.00,7.00,47.00,5.00,18.00,2.00,25.00,15.00,1.00,23.00,69.00,7.00,0.00,0.00,0.00,4.00,7.00,0.00,7.00,6.00,11.00,21.00,26.00,0.00,20.00,12.00,0.00,0.00,28.00,0.00,15.00,8.00,62.00,0.00,0.00,26.00,0.00,0.00,0.00,0.00,0.00,72.00,0.00,0.00,0.00,12.00,4.00,8.00,63.00,5.00,19.00,3.00,28.00,10.00,8.00,28.00,23.00,18.00,0.00,0.00,0.00,15.00,17.00,0.00,18.00,15.00,23.00,30.00,37.00,0.00,34.00,27.00,0.00,0.00,36.00,0.00,27.00,20.00,46.00,0.00,0.00,30.00,0.00,0.00,0.00,0.00,0.00,43.00,0.00,0.00,0.00,27.00,17.00,21.00,54.00,15.00,31.00,9.00,35.00,41.00,0.00,21.00,6.00,0.00,0.00,0.00,0.00,6.00,0.00,5.00,4.00,8.00,18.00,24.00,0.00,17.00,10.00,0.00,0.00,38.00,0.00,12.00,5.00,62.00,0.00,0.00,24.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,11.00,0.00,5.00,60.00,4.00,15.00,2.00,25.00,0.00,0.00,21.00,71.00,6.00,0.00,0.00,0.00,0.00,6.00,0.00,5.00,4.00,8.00,18.00,23.00,0.00,16.00,10.00,0.00,0.00,28.00,0.00,11.00,5.00,64.00,0.00,0.00,25.00,0.00,0.00,0.00,0.00,0.00,73.00,0.00,0.00,0.00,10.00,0.00,5.00,60.00,4.00,15.00,2.00,25.00,0.00,0.00,21.00,19.00,12.00,0.00,0.00,0.00,0.00,11.00,0.00,13.00,11.00,17.00,23.00,28.00,0.00,25.00,19.00,0.00,0.00,32.00,0.00,18.00,15.00,26.00,0.00,0.00,23.00,0.00,0.00,0.00,0.00,0.00,12.00,0.00,0.00,0.00,20.00,0.00,15.00,0.00,12.00,22.00,7.00,28.00,0.00
10,0,Ligue 1,Toulouse,NaN,Yaya Sanogo,1.00,21.00,7.00,0.00,0.00,0.00,4.00,7.00,0.00,7.00,5.00,12.00,19.00,24.00,0.00,20.00,11.00,0.00,0.00,47.00,0.00,14.00,7.00,46.00,0.00,0.00,24.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,13.00,4.00,7.00,47.00,5.00,18.00,2.00,25.00,15.00,1.00,23.00,69.00,7.00,0.00,0.00,0.00,4.00,7.00,0.00,7.00,6.00,11.00,21.00,26.00,0.00,20.00,12.00,0.00,0.00,28.00,0.00,15.00,8.00,62.00,0.00,0.00,26.00,0.00,0.00,0.00,0.00,0.00,72.00,0.00,0.00,0.00,12.00,4.00,8.00,63.00,5.00,19.00,3.00,28.00,10.00,8.00,28.00,23.00,18.00,0.00,0.00,0.00,15.00,17.00,0.00,18.00,15.00,23.00,30.00,37.00,0.00,34.00,27.00,0.00,0.00,36.00,0.00,27.00,20.00,46.00,0.00,0.00,30.00,0.00,0.00,0.00,0.00,0.00,43.00,0.00,0.00,0.00,27.00,17.00,21.00,54.00,15.00,31.00,9.00,35.00,41.00,0.00,21.00,6.00,0.00,0.00,0.00,0.00,6.00,0.00,5.00,4.00,8.00,18.00,24.00,0.00,17.00,10.00,0.00,0.00,38.00,0.00,12.00,5.00,62.00,0.00,0.00,24.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,11.00,0.00,5.00,60.00,4.00,15.00,2.00,25.00,0.00,0.00,21.00,71.00,6.00,0.00,0.00,0.00,0.00,6.00,0.00,5.00,4.00,8.00,18.00,23.00,0.00,16.00,10.00,0.00,0.00,28.00,0.00,11.00,5.00,64.00,0.00,0.00,25.00,0.00,0.00,0.00,0.00,0.00,73.00,0.00,0.00,0.00,10.00,0.00,5.00,60.00,4.00,15.00,2.00,25.00,0.00,0.00,21.00,19.00,12.00,0.00,0.00,0.00,0.00,11.00,0.00,13.00,11.00,17.00,23.00,28.00,0.00,25.00,19.00,0.00,0.00,32.00,0.00,18.00,15.00,26.00,0.00,0.00,23.00,0.00,0.00,0.00,0.00,0.00,12.00,0.00,0.00,0.00,20.00,0.00,15.00,0.00,12.00,22.00,7.00,28.00,0.00
17,0,Ligue 1,Toulouse,NaN,Wesley Saïd,1.00,21.00,7.00,0.00,0.00,0.00,4.00,7.00,0.00,7.00,5.00,12.00,19.00,24.00,0.00,20.00,11.00,0.00,0.00,47.00,0.00,14.00,7.00,46.00,0.00,0.00,24.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,13.00,4.00,7.00,47.00,5.00,18.00,2.00,25.00,15.00,1.00,23.00,69.00,7.00,0.00,0.00,0.00,4.00,7.00,0.00,7.00,6.00,11.00,21.00,26.00,0.00,20.00,12.00,0.00,0.00,28.00,0.00,15.00,8.00,62.00,0.00,0.00,26.00,0.00,0.00,0.00,0.00,0.00,72.00,0.00,0.00,0.00,12.00,4.00,8.00,63.00,5.00,19.00,3.00,28.00,10.00,8.00,28.00,23.00,18.00,0.00,0.00,0.00,15.00,17.00,0.00,18.00,15.00,23.00,30.00,37.00,0.00,34.00,27.00,0.00,0.00,36.00,0.00,27.00,20.00,46.00,0.00,0.00,30.00,0.00,0.00,0.00,0.00,0.00,43.00,0.00,0.00,0.00,27.00,17.00,21.00,54.00,15.00,31.00,9.00,35.00,41.00,0.00,21.00,6.00,0.00,0.00,0.00,0.00,6.00,0.00,5.00,4.00,8.00,18.00,24.00,0.00,17.00,10.00,0.00,0.00,38.00,0.00,12.00,5.00,62.00,0.00,0.00,24.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,11.00,0.00,5.00,60.00,4.00,15.00,2.00,25.00,0.00,0.00,21.00,71.00,6.00,0.00,0.00,0.00,0.00,6.00,0.00,5.00,4.00,8.00,18.00,23.00,0.00,16.00,10.00,0.00,0.00,28.00,0.00,11.00,5.00,64.00,0.00,0.00,25.00,0.00,0.00,0.00,0.00,0.00,73.00,0.00,0.00,0.00,10.00,0.00,5.00,60.00,4.00,15.00,2.00,25.00,0.00,0.00,21.00,19.00,12.00,0.00,0.00,0.00,0.00,11.00,0.00,13.00,11.00,17.00,23.00,28.00,0.00,25.00,19.00,0.00,0.00,32.00,0.00,18.00,15.00,26.00,0.00,0.00,23.00,0.00,0.00,0.00,0.00,0.00,12.00,0.00,0.00,0.00,20.00,0.00,15.00,0.00,12.00,22.00,7.00,28.00,0.00
21,1,Ligue 2,Brest,NaN,Édouard Butin,1.00,21.00,7.00,0.00,0.00,0.00,4.00,7.00,0.00,7.00,5.00,12.00,19.00,24.00,0.00,20.00,11.00,0.00,0.00,47.00,0.00,14.00,7.00,46.00,0.00,0.00,24.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,13.00,4.00,7.00,47.00,5.00,18.00,2.00,25.00,15.00,1.00,23.00,69.00,7.00,0.00,0.00,0.00,4.00,7.00,0.00,7.00,6.00,11.00,21.00,26.00,0.00,20.00,12.00,0.00,0.00,28.00,0.00,15.00,8.00,62.00,0.00,0.00,26.00,0.00,0.00,0.00,0.00,0.00,72.00,0.00,0.00,0.00,12.00,4.00,8.00,63.00,5.00,19.00,3.00,28.00,10.00,8.00,28.00,23.00,18.00,0.00,0.00,0.00,15.00,17.00,0.00,18.00,15.00,23.00,30.00,37.00,0.00,34.00,27.00,0.00,0.00,36.00,0.00,27.00,20.00,46.00,0.00,0.00,30.00,0.00,0.00,0.00,0.00,0.00,43.00,0.00,0.00,0.00,27.00,17.00,21.00,54.00,15.00,31.00,9.00,35.00,41.00,0.00,21.00,6.00,0.00,0.00,0.00,0.00,6.00,0.00,5.00,4.00,8.00,18.00,24.00,0.00,17.00,10.00,0.00,0.00,38.00,0.00,12.00,5.00,62.00,0.00,0.00,24.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,11.00,0.00,5.00,60.00,4.00,15.00,2.00,25.00,0.00,0.00,21.00,71.00,6.00,0.00,0.00,0.00,0.00,6.00,0.00,5.00,4.00,8.00,18.00,23.00,0.00,16.00,10.00,0.00,0.00,28.00,0.00,11.00,5.00,64.00,0.00,0.00,25.00,0.00,0.00,0.00,0.00,0.00,73.00,0.00,0.00,0.00,10.00,0.00,5.00,60.00,4.00,15.00,2.00,25.00,0.00,0.00,21.00,19.00,12.00,0.00,0.00,0.00,0.00,11.00,0.00,13.00,11.00,17.00,23.00,28.00,0.00,25.00,19.00,0.00,0.00,32.00,0.00,18.00,15.00,26.00,0.00,0.00,23.00,0.00,0.00,0.00,0.00,0.00,12.00,0.00,0.00,0.00,20.00,0.00,15.00,0.00,12.00,22.00,7.00,28.00,0.00

In [179]:
home_player_processed.loc[
    home_player_processed["POSITION"].isna()
].iloc[0]

ID                                                               0
LEAGUE                                                     Ligue 1
TEAM_NAME                                                 Toulouse
POSITION                                                       NaN
PLAYER_NAME                                    Efthymios Koulouris
                                                      ...
PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_std                  12.00
PLAYER_TACKLES_5_last_match_std                              22.00
PLAYER_TOTAL_CROSSES_5_last_match_std                         7.00
PLAYER_TOTAL_DUELS_5_last_match_std                          28.00
PLAYER_YELLOWCARDS_5_last_match_std                           0.00
Name: 4, Length: 277, dtype: object

In [180]:
# Remove POSITION column
home_player_processed = home_player_processed.drop(columns=["POSITION"])

In [181]:
print("POSITION" in home_player_processed.columns)

False

In [182]:
home_player_processed.columns

Index(['ID', 'LEAGUE', 'TEAM_NAME', 'PLAYER_NAME',
       'PLAYER_ACCURATE_CROSSES_season_sum',
       'PLAYER_ACCURATE_PASSES_season_sum', 'PLAYER_AERIALS_WON_season_sum',
       'PLAYER_ASSISTS_season_sum', 'PLAYER_BIG_CHANCES_CREATED_season_sum',
       'PLAYER_BIG_CHANCES_MISSED_season_sum',
       ...
       'PLAYER_SAVES_INSIDE_BOX_5_last_match_std',
       'PLAYER_SHOTS_BLOCKED_5_last_match_std',
       'PLAYER_SHOTS_ON_TARGET_5_last_match_std',
       'PLAYER_SHOTS_TOTAL_5_last_match_std',
       'PLAYER_STARTING_LINEUP_5_last_match_std',
       'PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_std',
       'PLAYER_TACKLES_5_last_match_std',
       'PLAYER_TOTAL_CROSSES_5_last_match_std',
       'PLAYER_TOTAL_DUELS_5_last_match_std',
       'PLAYER_YELLOWCARDS_5_last_match_std'],
      dtype='object', length=276)

In [183]:
print("Shape:", home_player_processed.shape)
print("Total missing values:", home_player_processed.isnull().sum().sum())

Shape: (237079, 276)
Total missing values: 0

### 6.1.4 Away Player Dataset

In [184]:
missing_numeric = (
    away_player
    .select_dtypes(include="number")
    .isnull()
    .mean()
    .mul(100)
    .sort_values(ascending=False)
)

missing_numeric[missing_numeric > 0]

PLAYER_CAPTAIN_5_last_match_sum                92.43
PLAYER_CAPTAIN_season_sum                      89.42
PLAYER_PUNCHES_season_std                      72.03
PLAYER_PUNCHES_5_last_match_std                72.03
PLAYER_PUNCHES_5_last_match_sum                71.60
                                                ...
PLAYER_ASSISTS_5_last_match_average             1.62
PLAYER_GOALS_5_last_match_average               1.62
PLAYER_GOALS_CONCEDED_5_last_match_average      1.62
PLAYER_MINUTES_PLAYED_5_last_match_average      1.62
PLAYER_PENALTIES_SCORED_5_last_match_average    1.62
Length: 280, dtype: float64

In [185]:
away_player.shape

(236132, 285)

In [186]:
cols_to_drop = [
    "PLAYER_CAPTAIN_season_sum",
    "PLAYER_CAPTAIN_5_last_match_sum",
    "PLAYER_PUNCHES_season_sum",
    "PLAYER_PUNCHES_season_average",
    "PLAYER_PUNCHES_season_std",
    "PLAYER_PUNCHES_5_last_match_sum",
    "PLAYER_PUNCHES_5_last_match_average",
    "PLAYER_PUNCHES_5_last_match_std"
]

In [187]:
[col for col in cols_to_drop if col in away_player.columns]

['PLAYER_CAPTAIN_season_sum',
 'PLAYER_CAPTAIN_5_last_match_sum',
 'PLAYER_PUNCHES_season_sum',
 'PLAYER_PUNCHES_season_average',
 'PLAYER_PUNCHES_season_std',
 'PLAYER_PUNCHES_5_last_match_sum',
 'PLAYER_PUNCHES_5_last_match_average',
 'PLAYER_PUNCHES_5_last_match_std']

In [188]:
away_player_processed = away_player.drop(columns=cols_to_drop)

In [189]:
away_player_processed.shape

(236132, 277)

In [190]:
away_player_processed.columns[away_player_processed.columns == "POSITION"]

Index(['POSITION'], dtype='object')

In [191]:
feature_groups = {
    "accurate_passes": "ACCURATE_PASS",
    "passing": "PASS",
    "crossing": "CROSS",
    "dribbling": "DRIBBLE",
    "shooting": "SHOT",
    "tackles": "TACKLE"
}

In [192]:
for keyword in feature_groups.values():

    cols = [
        col for col in away_player_processed.columns
        if keyword in col.upper()
    ]

    if len(cols) == 0:
        continue

    # Position-wise median
    for col in cols:
        away_player_processed[col] = (
            away_player_processed
            .groupby("POSITION")[col]
            .transform(lambda x: x.fillna(x.median()))
        )

    # Overall median fallback
    for col in cols:
        away_player_processed[col] = (
            away_player_processed[col]
            .fillna(away_player_processed[col].median())
        )

In [193]:
remaining_missing = (
    away_player_processed
    .select_dtypes(include="number")
    .isnull()
    .sum()
)

remaining_missing = remaining_missing[remaining_missing > 0]

print("Columns with missing values:", len(remaining_missing))
print("Total missing values:", remaining_missing.sum())

Columns with missing values: 190
Total missing values: 4332071

In [194]:
feature_groups = {
    "aerials": "AERIAL",
    "assists": "ASSIST",
    "big_chances_created": "BIG_CHANCES_CREATED",
    "big_chances_missed": "BIG_CHANCES_MISSED",
    "clearances": "CLEARANCE",
    "dispossessed": "DISPOSSESSED",
    "duels_lost": "DUELS_LOST",
    "duels_won": "DUELS_WON",
    "errors": "ERROR",
    "fouls": "FOUL",
    "goals": "GOAL",
    "hit_woodwork": "WOODWORK",
    "interceptions": "INTERCEPTION",
    "minutes": "MINUTES_PLAYED",
    "offsides": "OFFSIDE",
    "own_goals": "OWN_GOAL",
    "penalties": "PENALT",
    "rating": "RATING",
    "red_cards": "REDCARD",
    "saves": "SAVE",
    "starting_lineup": "STARTING_LINEUP",
    "total_duels": "TOTAL_DUELS",
    "yellow_cards": "YELLOWCARD"
}

for keyword in feature_groups.values():

    cols = [
        col for col in away_player_processed.columns
        if keyword in col.upper()
    ]

    if len(cols) == 0:
        continue

    # Position-wise median
    for col in cols:
        away_player_processed[col] = (
            away_player_processed
            .groupby("POSITION")[col]
            .transform(lambda x: x.fillna(x.median()))
        )

    # Overall median fallback
    for col in cols:
        away_player_processed[col] = (
            away_player_processed[col]
            .fillna(away_player_processed[col].median())
        )

In [195]:
remaining_missing = (
    away_player_processed
    .select_dtypes(include="number")
    .isnull()
    .sum()
)

remaining_missing = remaining_missing[remaining_missing > 0]

print("Columns with missing values:", len(remaining_missing))
print("Total missing values:", remaining_missing.sum())

Columns with missing values: 0
Total missing values: 0

In [196]:
away_player_processed = away_player_processed.drop(columns=["POSITION"])

In [197]:
print(away_player_processed.shape)

missing_cols = away_player_processed.columns[
    away_player_processed.isnull().any()
]

print("Columns with missing values:", len(missing_cols))
print(missing_cols.tolist())

(236132, 276)
Columns with missing values: 0
[]

## Merging Dataset

In [198]:
print(home_team_processed.columns.tolist())

['ID', 'LEAGUE', 'TEAM_NAME', 'TEAM_SHOTS_TOTAL_season_sum', 'TEAM_SHOTS_INSIDEBOX_season_sum', 'TEAM_SHOTS_OFF_TARGET_season_sum', 'TEAM_SHOTS_ON_TARGET_season_sum', 'TEAM_SHOTS_OUTSIDEBOX_season_sum', 'TEAM_PASSES_season_sum', 'TEAM_SUCCESSFUL_PASSES_season_sum', 'TEAM_SAVES_season_sum', 'TEAM_CORNERS_season_sum', 'TEAM_FOULS_season_sum', 'TEAM_YELLOWCARDS_season_sum', 'TEAM_REDCARDS_season_sum', 'TEAM_OFFSIDES_season_sum', 'TEAM_ATTACKS_season_sum', 'TEAM_PENALTIES_season_sum', 'TEAM_SUBSTITUTIONS_season_sum', 'TEAM_BALL_SAFE_season_sum', 'TEAM_DANGEROUS_ATTACKS_season_sum', 'TEAM_INJURIES_season_sum', 'TEAM_GOALS_season_sum', 'TEAM_GAME_WON_season_sum', 'TEAM_GAME_DRAW_season_sum', 'TEAM_GAME_LOST_season_sum', 'TEAM_SHOTS_TOTAL_season_average', 'TEAM_SHOTS_INSIDEBOX_season_average', 'TEAM_SHOTS_OFF_TARGET_season_average', 'TEAM_SHOTS_ON_TARGET_season_average', 'TEAM_SHOTS_OUTSIDEBOX_season_average', 'TEAM_PASSES_season_average', 'TEAM_SUCCESSFUL_PASSES_season_average', 'TEAM_SUCCESSFUL_PASSES_PERCENTAGE_season_average', 'TEAM_SAVES_season_average', 'TEAM_CORNERS_season_average', 'TEAM_BALL_POSSESSION_season_average', 'TEAM_FOULS_season_average', 'TEAM_YELLOWCARDS_season_average', 'TEAM_REDCARDS_season_average', 'TEAM_OFFSIDES_season_average', 'TEAM_ATTACKS_season_average', 'TEAM_PENALTIES_season_average', 'TEAM_SUBSTITUTIONS_season_average', 'TEAM_BALL_SAFE_season_average', 'TEAM_DANGEROUS_ATTACKS_season_average', 'TEAM_INJURIES_season_average', 'TEAM_GOALS_season_average', 'TEAM_GAME_WON_season_average', 'TEAM_GAME_DRAW_season_average', 'TEAM_GAME_LOST_season_average', 'TEAM_SHOTS_TOTAL_season_std', 'TEAM_SHOTS_INSIDEBOX_season_std', 'TEAM_SHOTS_OFF_TARGET_season_std', 'TEAM_SHOTS_ON_TARGET_season_std', 'TEAM_SHOTS_OUTSIDEBOX_season_std', 'TEAM_PASSES_season_std', 'TEAM_SUCCESSFUL_PASSES_season_std', 'TEAM_SUCCESSFUL_PASSES_PERCENTAGE_season_std', 'TEAM_SAVES_season_std', 'TEAM_CORNERS_season_std', 'TEAM_BALL_POSSESSION_season_std', 'TEAM_FOULS_season_std', 'TEAM_YELLOWCARDS_season_std', 'TEAM_REDCARDS_season_std', 'TEAM_OFFSIDES_season_std', 'TEAM_ATTACKS_season_std', 'TEAM_PENALTIES_season_std', 'TEAM_SUBSTITUTIONS_season_std', 'TEAM_BALL_SAFE_season_std', 'TEAM_DANGEROUS_ATTACKS_season_std', 'TEAM_INJURIES_season_std', 'TEAM_GOALS_season_std', 'TEAM_SHOTS_TOTAL_5_last_match_sum', 'TEAM_SHOTS_INSIDEBOX_5_last_match_sum', 'TEAM_SHOTS_OFF_TARGET_5_last_match_sum', 'TEAM_SHOTS_ON_TARGET_5_last_match_sum', 'TEAM_SHOTS_OUTSIDEBOX_5_last_match_sum', 'TEAM_PASSES_5_last_match_sum', 'TEAM_SUCCESSFUL_PASSES_5_last_match_sum', 'TEAM_SAVES_5_last_match_sum', 'TEAM_CORNERS_5_last_match_sum', 'TEAM_FOULS_5_last_match_sum', 'TEAM_YELLOWCARDS_5_last_match_sum', 'TEAM_REDCARDS_5_last_match_sum', 'TEAM_OFFSIDES_5_last_match_sum', 'TEAM_ATTACKS_5_last_match_sum', 'TEAM_PENALTIES_5_last_match_sum', 'TEAM_SUBSTITUTIONS_5_last_match_sum', 'TEAM_BALL_SAFE_5_last_match_sum', 'TEAM_DANGEROUS_ATTACKS_5_last_match_sum', 'TEAM_INJURIES_5_last_match_sum', 'TEAM_GOALS_5_last_match_sum', 'TEAM_GAME_WON_5_last_match_sum', 'TEAM_GAME_DRAW_5_last_match_sum', 'TEAM_GAME_LOST_5_last_match_sum', 'TEAM_SHOTS_TOTAL_5_last_match_average', 'TEAM_SHOTS_INSIDEBOX_5_last_match_average', 'TEAM_SHOTS_OFF_TARGET_5_last_match_average', 'TEAM_SHOTS_ON_TARGET_5_last_match_average', 'TEAM_SHOTS_OUTSIDEBOX_5_last_match_average', 'TEAM_PASSES_5_last_match_average', 'TEAM_SUCCESSFUL_PASSES_5_last_match_average', 'TEAM_SUCCESSFUL_PASSES_PERCENTAGE_5_last_match_average', 'TEAM_SAVES_5_last_match_average', 'TEAM_CORNERS_5_last_match_average', 'TEAM_BALL_POSSESSION_5_last_match_average', 'TEAM_FOULS_5_last_match_average', 'TEAM_YELLOWCARDS_5_last_match_average', 'TEAM_REDCARDS_5_last_match_average', 'TEAM_OFFSIDES_5_last_match_average', 'TEAM_ATTACKS_5_last_match_average', 'TEAM_PENALTIES_5_last_match_average', 'TEAM_SUBSTITUTIONS_5_last_match_average', 'TEAM_BALL_SAFE_5_last_match_average', 'TEAM_DANGEROUS_ATTACKS_5_last_match_average', 'TEAM_INJURIES_5_last_match_average', 'TEAM_GOALS_5_last_match_average', 'TEAM_GAME_WON_5_last_match_average', 'TEAM_GAME_DRAW_5_last_match_average', 'TEAM_GAME_LOST_5_last_match_average', 'TEAM_SHOTS_TOTAL_5_last_match_std', 'TEAM_SHOTS_INSIDEBOX_5_last_match_std', 'TEAM_SHOTS_OFF_TARGET_5_last_match_std', 'TEAM_SHOTS_ON_TARGET_5_last_match_std', 'TEAM_SHOTS_OUTSIDEBOX_5_last_match_std', 'TEAM_PASSES_5_last_match_std', 'TEAM_SUCCESSFUL_PASSES_5_last_match_std', 'TEAM_SUCCESSFUL_PASSES_PERCENTAGE_5_last_match_std', 'TEAM_SAVES_5_last_match_std', 'TEAM_CORNERS_5_last_match_std', 'TEAM_BALL_POSSESSION_5_last_match_std', 'TEAM_FOULS_5_last_match_std', 'TEAM_YELLOWCARDS_5_last_match_std', 'TEAM_REDCARDS_5_last_match_std', 'TEAM_OFFSIDES_5_last_match_std', 'TEAM_ATTACKS_5_last_match_std', 'TEAM_PENALTIES_5_last_match_std', 'TEAM_SUBSTITUTIONS_5_last_match_std', 'TEAM_BALL_SAFE_5_last_match_std', 'TEAM_DANGEROUS_ATTACKS_5_last_match_std', 'TEAM_INJURIES_5_last_match_std', 'TEAM_GOALS_5_last_match_std']

In [199]:
print(away_team_processed.columns.tolist())

['ID', 'LEAGUE', 'TEAM_NAME', 'TEAM_SHOTS_TOTAL_season_sum', 'TEAM_SHOTS_INSIDEBOX_season_sum', 'TEAM_SHOTS_OFF_TARGET_season_sum', 'TEAM_SHOTS_ON_TARGET_season_sum', 'TEAM_SHOTS_OUTSIDEBOX_season_sum', 'TEAM_PASSES_season_sum', 'TEAM_SUCCESSFUL_PASSES_season_sum', 'TEAM_SAVES_season_sum', 'TEAM_CORNERS_season_sum', 'TEAM_FOULS_season_sum', 'TEAM_YELLOWCARDS_season_sum', 'TEAM_REDCARDS_season_sum', 'TEAM_OFFSIDES_season_sum', 'TEAM_ATTACKS_season_sum', 'TEAM_PENALTIES_season_sum', 'TEAM_SUBSTITUTIONS_season_sum', 'TEAM_BALL_SAFE_season_sum', 'TEAM_DANGEROUS_ATTACKS_season_sum', 'TEAM_INJURIES_season_sum', 'TEAM_GOALS_season_sum', 'TEAM_GAME_WON_season_sum', 'TEAM_GAME_DRAW_season_sum', 'TEAM_GAME_LOST_season_sum', 'TEAM_SHOTS_TOTAL_season_average', 'TEAM_SHOTS_INSIDEBOX_season_average', 'TEAM_SHOTS_OFF_TARGET_season_average', 'TEAM_SHOTS_ON_TARGET_season_average', 'TEAM_SHOTS_OUTSIDEBOX_season_average', 'TEAM_PASSES_season_average', 'TEAM_SUCCESSFUL_PASSES_season_average', 'TEAM_SUCCESSFUL_PASSES_PERCENTAGE_season_average', 'TEAM_SAVES_season_average', 'TEAM_CORNERS_season_average', 'TEAM_BALL_POSSESSION_season_average', 'TEAM_FOULS_season_average', 'TEAM_YELLOWCARDS_season_average', 'TEAM_REDCARDS_season_average', 'TEAM_OFFSIDES_season_average', 'TEAM_ATTACKS_season_average', 'TEAM_PENALTIES_season_average', 'TEAM_SUBSTITUTIONS_season_average', 'TEAM_BALL_SAFE_season_average', 'TEAM_DANGEROUS_ATTACKS_season_average', 'TEAM_INJURIES_season_average', 'TEAM_GOALS_season_average', 'TEAM_GAME_WON_season_average', 'TEAM_GAME_DRAW_season_average', 'TEAM_GAME_LOST_season_average', 'TEAM_SHOTS_TOTAL_season_std', 'TEAM_SHOTS_INSIDEBOX_season_std', 'TEAM_SHOTS_OFF_TARGET_season_std', 'TEAM_SHOTS_ON_TARGET_season_std', 'TEAM_SHOTS_OUTSIDEBOX_season_std', 'TEAM_PASSES_season_std', 'TEAM_SUCCESSFUL_PASSES_season_std', 'TEAM_SUCCESSFUL_PASSES_PERCENTAGE_season_std', 'TEAM_SAVES_season_std', 'TEAM_CORNERS_season_std', 'TEAM_BALL_POSSESSION_season_std', 'TEAM_FOULS_season_std', 'TEAM_YELLOWCARDS_season_std', 'TEAM_REDCARDS_season_std', 'TEAM_OFFSIDES_season_std', 'TEAM_ATTACKS_season_std', 'TEAM_PENALTIES_season_std', 'TEAM_SUBSTITUTIONS_season_std', 'TEAM_BALL_SAFE_season_std', 'TEAM_DANGEROUS_ATTACKS_season_std', 'TEAM_INJURIES_season_std', 'TEAM_GOALS_season_std', 'TEAM_SHOTS_TOTAL_5_last_match_sum', 'TEAM_SHOTS_INSIDEBOX_5_last_match_sum', 'TEAM_SHOTS_OFF_TARGET_5_last_match_sum', 'TEAM_SHOTS_ON_TARGET_5_last_match_sum', 'TEAM_SHOTS_OUTSIDEBOX_5_last_match_sum', 'TEAM_PASSES_5_last_match_sum', 'TEAM_SUCCESSFUL_PASSES_5_last_match_sum', 'TEAM_SAVES_5_last_match_sum', 'TEAM_CORNERS_5_last_match_sum', 'TEAM_FOULS_5_last_match_sum', 'TEAM_YELLOWCARDS_5_last_match_sum', 'TEAM_REDCARDS_5_last_match_sum', 'TEAM_OFFSIDES_5_last_match_sum', 'TEAM_ATTACKS_5_last_match_sum', 'TEAM_PENALTIES_5_last_match_sum', 'TEAM_SUBSTITUTIONS_5_last_match_sum', 'TEAM_BALL_SAFE_5_last_match_sum', 'TEAM_DANGEROUS_ATTACKS_5_last_match_sum', 'TEAM_INJURIES_5_last_match_sum', 'TEAM_GOALS_5_last_match_sum', 'TEAM_GAME_WON_5_last_match_sum', 'TEAM_GAME_DRAW_5_last_match_sum', 'TEAM_GAME_LOST_5_last_match_sum', 'TEAM_SHOTS_TOTAL_5_last_match_average', 'TEAM_SHOTS_INSIDEBOX_5_last_match_average', 'TEAM_SHOTS_OFF_TARGET_5_last_match_average', 'TEAM_SHOTS_ON_TARGET_5_last_match_average', 'TEAM_SHOTS_OUTSIDEBOX_5_last_match_average', 'TEAM_PASSES_5_last_match_average', 'TEAM_SUCCESSFUL_PASSES_5_last_match_average', 'TEAM_SUCCESSFUL_PASSES_PERCENTAGE_5_last_match_average', 'TEAM_SAVES_5_last_match_average', 'TEAM_CORNERS_5_last_match_average', 'TEAM_BALL_POSSESSION_5_last_match_average', 'TEAM_FOULS_5_last_match_average', 'TEAM_YELLOWCARDS_5_last_match_average', 'TEAM_REDCARDS_5_last_match_average', 'TEAM_OFFSIDES_5_last_match_average', 'TEAM_ATTACKS_5_last_match_average', 'TEAM_PENALTIES_5_last_match_average', 'TEAM_SUBSTITUTIONS_5_last_match_average', 'TEAM_BALL_SAFE_5_last_match_average', 'TEAM_DANGEROUS_ATTACKS_5_last_match_average', 'TEAM_INJURIES_5_last_match_average', 'TEAM_GOALS_5_last_match_average', 'TEAM_GAME_WON_5_last_match_average', 'TEAM_GAME_DRAW_5_last_match_average', 'TEAM_GAME_LOST_5_last_match_average', 'TEAM_SHOTS_TOTAL_5_last_match_std', 'TEAM_SHOTS_INSIDEBOX_5_last_match_std', 'TEAM_SHOTS_OFF_TARGET_5_last_match_std', 'TEAM_SHOTS_ON_TARGET_5_last_match_std', 'TEAM_SHOTS_OUTSIDEBOX_5_last_match_std', 'TEAM_PASSES_5_last_match_std', 'TEAM_SUCCESSFUL_PASSES_5_last_match_std', 'TEAM_SUCCESSFUL_PASSES_PERCENTAGE_5_last_match_std', 'TEAM_SAVES_5_last_match_std', 'TEAM_CORNERS_5_last_match_std', 'TEAM_BALL_POSSESSION_5_last_match_std', 'TEAM_FOULS_5_last_match_std', 'TEAM_YELLOWCARDS_5_last_match_std', 'TEAM_REDCARDS_5_last_match_std', 'TEAM_OFFSIDES_5_last_match_std', 'TEAM_ATTACKS_5_last_match_std', 'TEAM_PENALTIES_5_last_match_std', 'TEAM_SUBSTITUTIONS_5_last_match_std', 'TEAM_BALL_SAFE_5_last_match_std', 'TEAM_DANGEROUS_ATTACKS_5_last_match_std', 'TEAM_INJURIES_5_last_match_std', 'TEAM_GOALS_5_last_match_std']

In [200]:
print(home_player_processed.columns.tolist())

['ID', 'LEAGUE', 'TEAM_NAME', 'PLAYER_NAME', 'PLAYER_ACCURATE_CROSSES_season_sum', 'PLAYER_ACCURATE_PASSES_season_sum', 'PLAYER_AERIALS_WON_season_sum', 'PLAYER_ASSISTS_season_sum', 'PLAYER_BIG_CHANCES_CREATED_season_sum', 'PLAYER_BIG_CHANCES_MISSED_season_sum', 'PLAYER_BLOCKED_SHOTS_season_sum', 'PLAYER_CLEARANCES_season_sum', 'PLAYER_CLEARANCE_OFFLINE_season_sum', 'PLAYER_DISPOSSESSED_season_sum', 'PLAYER_DRIBBLED_ATTEMPTS_season_sum', 'PLAYER_DRIBBLED_PAST_season_sum', 'PLAYER_DUELS_LOST_season_sum', 'PLAYER_DUELS_WON_season_sum', 'PLAYER_ERROR_LEAD_TO_GOAL_season_sum', 'PLAYER_FOULS_season_sum', 'PLAYER_FOULS_DRAWN_season_sum', 'PLAYER_GOALKEEPER_GOALS_CONCEDED_season_sum', 'PLAYER_GOALS_season_sum', 'PLAYER_GOALS_CONCEDED_season_sum', 'PLAYER_HIT_WOODWORK_season_sum', 'PLAYER_INTERCEPTIONS_season_sum', 'PLAYER_KEY_PASSES_season_sum', 'PLAYER_MINUTES_PLAYED_season_sum', 'PLAYER_OFFSIDES_season_sum', 'PLAYER_OWN_GOALS_season_sum', 'PLAYER_PASSES_season_sum', 'PLAYER_PENALTIES_COMMITTED_season_sum', 'PLAYER_PENALTIES_MISSES_season_sum', 'PLAYER_PENALTIES_SAVED_season_sum', 'PLAYER_PENALTIES_SCORED_season_sum', 'PLAYER_PENALTIES_WON_season_sum', 'PLAYER_REDCARDS_season_sum', 'PLAYER_SAVES_season_sum', 'PLAYER_SAVES_INSIDE_BOX_season_sum', 'PLAYER_SHOTS_BLOCKED_season_sum', 'PLAYER_SHOTS_ON_TARGET_season_sum', 'PLAYER_SHOTS_TOTAL_season_sum', 'PLAYER_STARTING_LINEUP_season_sum', 'PLAYER_SUCCESSFUL_DRIBBLES_season_sum', 'PLAYER_TACKLES_season_sum', 'PLAYER_TOTAL_CROSSES_season_sum', 'PLAYER_TOTAL_DUELS_season_sum', 'PLAYER_YELLOWCARDS_season_sum', 'PLAYER_ACCURATE_CROSSES_season_average', 'PLAYER_ACCURATE_PASSES_season_average', 'PLAYER_ACCURATE_PASSES_PERCENTAGE_season_average', 'PLAYER_AERIALS_WON_season_average', 'PLAYER_ASSISTS_season_average', 'PLAYER_BIG_CHANCES_CREATED_season_average', 'PLAYER_BIG_CHANCES_MISSED_season_average', 'PLAYER_BLOCKED_SHOTS_season_average', 'PLAYER_CLEARANCES_season_average', 'PLAYER_CLEARANCE_OFFLINE_season_average', 'PLAYER_DISPOSSESSED_season_average', 'PLAYER_DRIBBLED_ATTEMPTS_season_average', 'PLAYER_DRIBBLED_PAST_season_average', 'PLAYER_DUELS_LOST_season_average', 'PLAYER_DUELS_WON_season_average', 'PLAYER_ERROR_LEAD_TO_GOAL_season_average', 'PLAYER_FOULS_season_average', 'PLAYER_FOULS_DRAWN_season_average', 'PLAYER_GOALKEEPER_GOALS_CONCEDED_season_average', 'PLAYER_GOALS_season_average', 'PLAYER_GOALS_CONCEDED_season_average', 'PLAYER_HIT_WOODWORK_season_average', 'PLAYER_INTERCEPTIONS_season_average', 'PLAYER_KEY_PASSES_season_average', 'PLAYER_MINUTES_PLAYED_season_average', 'PLAYER_OFFSIDES_season_average', 'PLAYER_OWN_GOALS_season_average', 'PLAYER_PASSES_season_average', 'PLAYER_PENALTIES_COMMITTED_season_average', 'PLAYER_PENALTIES_MISSES_season_average', 'PLAYER_PENALTIES_SAVED_season_average', 'PLAYER_PENALTIES_SCORED_season_average', 'PLAYER_PENALTIES_WON_season_average', 'PLAYER_RATING_season_average', 'PLAYER_REDCARDS_season_average', 'PLAYER_SAVES_season_average', 'PLAYER_SAVES_INSIDE_BOX_season_average', 'PLAYER_SHOTS_BLOCKED_season_average', 'PLAYER_SHOTS_ON_TARGET_season_average', 'PLAYER_SHOTS_TOTAL_season_average', 'PLAYER_STARTING_LINEUP_season_average', 'PLAYER_SUCCESSFUL_DRIBBLES_season_average', 'PLAYER_TACKLES_season_average', 'PLAYER_TOTAL_CROSSES_season_average', 'PLAYER_TOTAL_DUELS_season_average', 'PLAYER_YELLOWCARDS_season_average', 'PLAYER_ACCURATE_CROSSES_season_std', 'PLAYER_ACCURATE_PASSES_season_std', 'PLAYER_ACCURATE_PASSES_PERCENTAGE_season_std', 'PLAYER_AERIALS_WON_season_std', 'PLAYER_ASSISTS_season_std', 'PLAYER_BIG_CHANCES_CREATED_season_std', 'PLAYER_BIG_CHANCES_MISSED_season_std', 'PLAYER_BLOCKED_SHOTS_season_std', 'PLAYER_CLEARANCES_season_std', 'PLAYER_CLEARANCE_OFFLINE_season_std', 'PLAYER_DISPOSSESSED_season_std', 'PLAYER_DRIBBLED_ATTEMPTS_season_std', 'PLAYER_DRIBBLED_PAST_season_std', 'PLAYER_DUELS_LOST_season_std', 'PLAYER_DUELS_WON_season_std', 'PLAYER_ERROR_LEAD_TO_GOAL_season_std', 'PLAYER_FOULS_season_std', 'PLAYER_FOULS_DRAWN_season_std', 'PLAYER_GOALKEEPER_GOALS_CONCEDED_season_std', 'PLAYER_GOALS_season_std', 'PLAYER_GOALS_CONCEDED_season_std', 'PLAYER_HIT_WOODWORK_season_std', 'PLAYER_INTERCEPTIONS_season_std', 'PLAYER_KEY_PASSES_season_std', 'PLAYER_MINUTES_PLAYED_season_std', 'PLAYER_OFFSIDES_season_std', 'PLAYER_OWN_GOALS_season_std', 'PLAYER_PASSES_season_std', 'PLAYER_PENALTIES_COMMITTED_season_std', 'PLAYER_PENALTIES_MISSES_season_std', 'PLAYER_PENALTIES_SAVED_season_std', 'PLAYER_PENALTIES_SCORED_season_std', 'PLAYER_PENALTIES_WON_season_std', 'PLAYER_RATING_season_std', 'PLAYER_REDCARDS_season_std', 'PLAYER_SAVES_season_std', 'PLAYER_SAVES_INSIDE_BOX_season_std', 'PLAYER_SHOTS_BLOCKED_season_std', 'PLAYER_SHOTS_ON_TARGET_season_std', 'PLAYER_SHOTS_TOTAL_season_std', 'PLAYER_STARTING_LINEUP_season_std', 'PLAYER_SUCCESSFUL_DRIBBLES_season_std', 'PLAYER_TACKLES_season_std', 'PLAYER_TOTAL_CROSSES_season_std', 'PLAYER_TOTAL_DUELS_season_std', 'PLAYER_YELLOWCARDS_season_std', 'PLAYER_ACCURATE_CROSSES_5_last_match_sum', 'PLAYER_ACCURATE_PASSES_5_last_match_sum', 'PLAYER_AERIALS_WON_5_last_match_sum', 'PLAYER_ASSISTS_5_last_match_sum', 'PLAYER_BIG_CHANCES_CREATED_5_last_match_sum', 'PLAYER_BIG_CHANCES_MISSED_5_last_match_sum', 'PLAYER_BLOCKED_SHOTS_5_last_match_sum', 'PLAYER_CLEARANCES_5_last_match_sum', 'PLAYER_CLEARANCE_OFFLINE_5_last_match_sum', 'PLAYER_DISPOSSESSED_5_last_match_sum', 'PLAYER_DRIBBLED_ATTEMPTS_5_last_match_sum', 'PLAYER_DRIBBLED_PAST_5_last_match_sum', 'PLAYER_DUELS_LOST_5_last_match_sum', 'PLAYER_DUELS_WON_5_last_match_sum', 'PLAYER_ERROR_LEAD_TO_GOAL_5_last_match_sum', 'PLAYER_FOULS_5_last_match_sum', 'PLAYER_FOULS_DRAWN_5_last_match_sum', 'PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_sum', 'PLAYER_GOALS_5_last_match_sum', 'PLAYER_GOALS_CONCEDED_5_last_match_sum', 'PLAYER_HIT_WOODWORK_5_last_match_sum', 'PLAYER_INTERCEPTIONS_5_last_match_sum', 'PLAYER_KEY_PASSES_5_last_match_sum', 'PLAYER_MINUTES_PLAYED_5_last_match_sum', 'PLAYER_OFFSIDES_5_last_match_sum', 'PLAYER_OWN_GOALS_5_last_match_sum', 'PLAYER_PASSES_5_last_match_sum', 'PLAYER_PENALTIES_COMMITTED_5_last_match_sum', 'PLAYER_PENALTIES_MISSES_5_last_match_sum', 'PLAYER_PENALTIES_SAVED_5_last_match_sum', 'PLAYER_PENALTIES_SCORED_5_last_match_sum', 'PLAYER_PENALTIES_WON_5_last_match_sum', 'PLAYER_REDCARDS_5_last_match_sum', 'PLAYER_SAVES_5_last_match_sum', 'PLAYER_SAVES_INSIDE_BOX_5_last_match_sum', 'PLAYER_SHOTS_BLOCKED_5_last_match_sum', 'PLAYER_SHOTS_ON_TARGET_5_last_match_sum', 'PLAYER_SHOTS_TOTAL_5_last_match_sum', 'PLAYER_STARTING_LINEUP_5_last_match_sum', 'PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_sum', 'PLAYER_TACKLES_5_last_match_sum', 'PLAYER_TOTAL_CROSSES_5_last_match_sum', 'PLAYER_TOTAL_DUELS_5_last_match_sum', 'PLAYER_YELLOWCARDS_5_last_match_sum', 'PLAYER_ACCURATE_CROSSES_5_last_match_average', 'PLAYER_ACCURATE_PASSES_5_last_match_average', 'PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_average', 'PLAYER_AERIALS_WON_5_last_match_average', 'PLAYER_ASSISTS_5_last_match_average', 'PLAYER_BIG_CHANCES_CREATED_5_last_match_average', 'PLAYER_BIG_CHANCES_MISSED_5_last_match_average', 'PLAYER_BLOCKED_SHOTS_5_last_match_average', 'PLAYER_CLEARANCES_5_last_match_average', 'PLAYER_CLEARANCE_OFFLINE_5_last_match_average', 'PLAYER_DISPOSSESSED_5_last_match_average', 'PLAYER_DRIBBLED_ATTEMPTS_5_last_match_average', 'PLAYER_DRIBBLED_PAST_5_last_match_average', 'PLAYER_DUELS_LOST_5_last_match_average', 'PLAYER_DUELS_WON_5_last_match_average', 'PLAYER_ERROR_LEAD_TO_GOAL_5_last_match_average', 'PLAYER_FOULS_5_last_match_average', 'PLAYER_FOULS_DRAWN_5_last_match_average', 'PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_average', 'PLAYER_GOALS_5_last_match_average', 'PLAYER_GOALS_CONCEDED_5_last_match_average', 'PLAYER_HIT_WOODWORK_5_last_match_average', 'PLAYER_INTERCEPTIONS_5_last_match_average', 'PLAYER_KEY_PASSES_5_last_match_average', 'PLAYER_MINUTES_PLAYED_5_last_match_average', 'PLAYER_OFFSIDES_5_last_match_average', 'PLAYER_OWN_GOALS_5_last_match_average', 'PLAYER_PASSES_5_last_match_average', 'PLAYER_PENALTIES_COMMITTED_5_last_match_average', 'PLAYER_PENALTIES_MISSES_5_last_match_average', 'PLAYER_PENALTIES_SAVED_5_last_match_average', 'PLAYER_PENALTIES_SCORED_5_last_match_average', 'PLAYER_PENALTIES_WON_5_last_match_average', 'PLAYER_RATING_5_last_match_average', 'PLAYER_REDCARDS_5_last_match_average', 'PLAYER_SAVES_5_last_match_average', 'PLAYER_SAVES_INSIDE_BOX_5_last_match_average', 'PLAYER_SHOTS_BLOCKED_5_last_match_average', 'PLAYER_SHOTS_ON_TARGET_5_last_match_average', 'PLAYER_SHOTS_TOTAL_5_last_match_average', 'PLAYER_STARTING_LINEUP_5_last_match_average', 'PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_average', 'PLAYER_TACKLES_5_last_match_average', 'PLAYER_TOTAL_CROSSES_5_last_match_average', 'PLAYER_TOTAL_DUELS_5_last_match_average', 'PLAYER_YELLOWCARDS_5_last_match_average', 'PLAYER_ACCURATE_CROSSES_5_last_match_std', 'PLAYER_ACCURATE_PASSES_5_last_match_std', 'PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_std', 'PLAYER_AERIALS_WON_5_last_match_std', 'PLAYER_ASSISTS_5_last_match_std', 'PLAYER_BIG_CHANCES_CREATED_5_last_match_std', 'PLAYER_BIG_CHANCES_MISSED_5_last_match_std', 'PLAYER_BLOCKED_SHOTS_5_last_match_std', 'PLAYER_CLEARANCES_5_last_match_std', 'PLAYER_CLEARANCE_OFFLINE_5_last_match_std', 'PLAYER_DISPOSSESSED_5_last_match_std', 'PLAYER_DRIBBLED_ATTEMPTS_5_last_match_std', 'PLAYER_DRIBBLED_PAST_5_last_match_std', 'PLAYER_DUELS_LOST_5_last_match_std', 'PLAYER_DUELS_WON_5_last_match_std', 'PLAYER_ERROR_LEAD_TO_GOAL_5_last_match_std', 'PLAYER_FOULS_5_last_match_std', 'PLAYER_FOULS_DRAWN_5_last_match_std', 'PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_std', 'PLAYER_GOALS_5_last_match_std', 'PLAYER_GOALS_CONCEDED_5_last_match_std', 'PLAYER_HIT_WOODWORK_5_last_match_std', 'PLAYER_INTERCEPTIONS_5_last_match_std', 'PLAYER_KEY_PASSES_5_last_match_std', 'PLAYER_MINUTES_PLAYED_5_last_match_std', 'PLAYER_OFFSIDES_5_last_match_std', 'PLAYER_OWN_GOALS_5_last_match_std', 'PLAYER_PASSES_5_last_match_std', 'PLAYER_PENALTIES_COMMITTED_5_last_match_std', 'PLAYER_PENALTIES_MISSES_5_last_match_std', 'PLAYER_PENALTIES_SAVED_5_last_match_std', 'PLAYER_PENALTIES_SCORED_5_last_match_std', 'PLAYER_PENALTIES_WON_5_last_match_std', 'PLAYER_RATING_5_last_match_std', 'PLAYER_REDCARDS_5_last_match_std', 'PLAYER_SAVES_5_last_match_std', 'PLAYER_SAVES_INSIDE_BOX_5_last_match_std', 'PLAYER_SHOTS_BLOCKED_5_last_match_std', 'PLAYER_SHOTS_ON_TARGET_5_last_match_std', 'PLAYER_SHOTS_TOTAL_5_last_match_std', 'PLAYER_STARTING_LINEUP_5_last_match_std', 'PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_std', 'PLAYER_TACKLES_5_last_match_std', 'PLAYER_TOTAL_CROSSES_5_last_match_std', 'PLAYER_TOTAL_DUELS_5_last_match_std', 'PLAYER_YELLOWCARDS_5_last_match_std']

In [201]:
print(away_player_processed.columns.tolist())

['ID', 'LEAGUE', 'TEAM_NAME', 'PLAYER_NAME', 'PLAYER_ACCURATE_CROSSES_season_sum', 'PLAYER_ACCURATE_PASSES_season_sum', 'PLAYER_AERIALS_WON_season_sum', 'PLAYER_ASSISTS_season_sum', 'PLAYER_BIG_CHANCES_CREATED_season_sum', 'PLAYER_BIG_CHANCES_MISSED_season_sum', 'PLAYER_BLOCKED_SHOTS_season_sum', 'PLAYER_CLEARANCES_season_sum', 'PLAYER_CLEARANCE_OFFLINE_season_sum', 'PLAYER_DISPOSSESSED_season_sum', 'PLAYER_DRIBBLED_ATTEMPTS_season_sum', 'PLAYER_DRIBBLED_PAST_season_sum', 'PLAYER_DUELS_LOST_season_sum', 'PLAYER_DUELS_WON_season_sum', 'PLAYER_ERROR_LEAD_TO_GOAL_season_sum', 'PLAYER_FOULS_season_sum', 'PLAYER_FOULS_DRAWN_season_sum', 'PLAYER_GOALKEEPER_GOALS_CONCEDED_season_sum', 'PLAYER_GOALS_season_sum', 'PLAYER_GOALS_CONCEDED_season_sum', 'PLAYER_HIT_WOODWORK_season_sum', 'PLAYER_INTERCEPTIONS_season_sum', 'PLAYER_KEY_PASSES_season_sum', 'PLAYER_MINUTES_PLAYED_season_sum', 'PLAYER_OFFSIDES_season_sum', 'PLAYER_OWN_GOALS_season_sum', 'PLAYER_PASSES_season_sum', 'PLAYER_PENALTIES_COMMITTED_season_sum', 'PLAYER_PENALTIES_MISSES_season_sum', 'PLAYER_PENALTIES_SAVED_season_sum', 'PLAYER_PENALTIES_SCORED_season_sum', 'PLAYER_PENALTIES_WON_season_sum', 'PLAYER_REDCARDS_season_sum', 'PLAYER_SAVES_season_sum', 'PLAYER_SAVES_INSIDE_BOX_season_sum', 'PLAYER_SHOTS_BLOCKED_season_sum', 'PLAYER_SHOTS_ON_TARGET_season_sum', 'PLAYER_SHOTS_TOTAL_season_sum', 'PLAYER_STARTING_LINEUP_season_sum', 'PLAYER_SUCCESSFUL_DRIBBLES_season_sum', 'PLAYER_TACKLES_season_sum', 'PLAYER_TOTAL_CROSSES_season_sum', 'PLAYER_TOTAL_DUELS_season_sum', 'PLAYER_YELLOWCARDS_season_sum', 'PLAYER_ACCURATE_CROSSES_season_average', 'PLAYER_ACCURATE_PASSES_season_average', 'PLAYER_ACCURATE_PASSES_PERCENTAGE_season_average', 'PLAYER_AERIALS_WON_season_average', 'PLAYER_ASSISTS_season_average', 'PLAYER_BIG_CHANCES_CREATED_season_average', 'PLAYER_BIG_CHANCES_MISSED_season_average', 'PLAYER_BLOCKED_SHOTS_season_average', 'PLAYER_CLEARANCES_season_average', 'PLAYER_CLEARANCE_OFFLINE_season_average', 'PLAYER_DISPOSSESSED_season_average', 'PLAYER_DRIBBLED_ATTEMPTS_season_average', 'PLAYER_DRIBBLED_PAST_season_average', 'PLAYER_DUELS_LOST_season_average', 'PLAYER_DUELS_WON_season_average', 'PLAYER_ERROR_LEAD_TO_GOAL_season_average', 'PLAYER_FOULS_season_average', 'PLAYER_FOULS_DRAWN_season_average', 'PLAYER_GOALKEEPER_GOALS_CONCEDED_season_average', 'PLAYER_GOALS_season_average', 'PLAYER_GOALS_CONCEDED_season_average', 'PLAYER_HIT_WOODWORK_season_average', 'PLAYER_INTERCEPTIONS_season_average', 'PLAYER_KEY_PASSES_season_average', 'PLAYER_MINUTES_PLAYED_season_average', 'PLAYER_OFFSIDES_season_average', 'PLAYER_OWN_GOALS_season_average', 'PLAYER_PASSES_season_average', 'PLAYER_PENALTIES_COMMITTED_season_average', 'PLAYER_PENALTIES_MISSES_season_average', 'PLAYER_PENALTIES_SAVED_season_average', 'PLAYER_PENALTIES_SCORED_season_average', 'PLAYER_PENALTIES_WON_season_average', 'PLAYER_RATING_season_average', 'PLAYER_REDCARDS_season_average', 'PLAYER_SAVES_season_average', 'PLAYER_SAVES_INSIDE_BOX_season_average', 'PLAYER_SHOTS_BLOCKED_season_average', 'PLAYER_SHOTS_ON_TARGET_season_average', 'PLAYER_SHOTS_TOTAL_season_average', 'PLAYER_STARTING_LINEUP_season_average', 'PLAYER_SUCCESSFUL_DRIBBLES_season_average', 'PLAYER_TACKLES_season_average', 'PLAYER_TOTAL_CROSSES_season_average', 'PLAYER_TOTAL_DUELS_season_average', 'PLAYER_YELLOWCARDS_season_average', 'PLAYER_ACCURATE_CROSSES_season_std', 'PLAYER_ACCURATE_PASSES_season_std', 'PLAYER_ACCURATE_PASSES_PERCENTAGE_season_std', 'PLAYER_AERIALS_WON_season_std', 'PLAYER_ASSISTS_season_std', 'PLAYER_BIG_CHANCES_CREATED_season_std', 'PLAYER_BIG_CHANCES_MISSED_season_std', 'PLAYER_BLOCKED_SHOTS_season_std', 'PLAYER_CLEARANCES_season_std', 'PLAYER_CLEARANCE_OFFLINE_season_std', 'PLAYER_DISPOSSESSED_season_std', 'PLAYER_DRIBBLED_ATTEMPTS_season_std', 'PLAYER_DRIBBLED_PAST_season_std', 'PLAYER_DUELS_LOST_season_std', 'PLAYER_DUELS_WON_season_std', 'PLAYER_ERROR_LEAD_TO_GOAL_season_std', 'PLAYER_FOULS_season_std', 'PLAYER_FOULS_DRAWN_season_std', 'PLAYER_GOALKEEPER_GOALS_CONCEDED_season_std', 'PLAYER_GOALS_season_std', 'PLAYER_GOALS_CONCEDED_season_std', 'PLAYER_HIT_WOODWORK_season_std', 'PLAYER_INTERCEPTIONS_season_std', 'PLAYER_KEY_PASSES_season_std', 'PLAYER_MINUTES_PLAYED_season_std', 'PLAYER_OFFSIDES_season_std', 'PLAYER_OWN_GOALS_season_std', 'PLAYER_PASSES_season_std', 'PLAYER_PENALTIES_COMMITTED_season_std', 'PLAYER_PENALTIES_MISSES_season_std', 'PLAYER_PENALTIES_SAVED_season_std', 'PLAYER_PENALTIES_SCORED_season_std', 'PLAYER_PENALTIES_WON_season_std', 'PLAYER_RATING_season_std', 'PLAYER_REDCARDS_season_std', 'PLAYER_SAVES_season_std', 'PLAYER_SAVES_INSIDE_BOX_season_std', 'PLAYER_SHOTS_BLOCKED_season_std', 'PLAYER_SHOTS_ON_TARGET_season_std', 'PLAYER_SHOTS_TOTAL_season_std', 'PLAYER_STARTING_LINEUP_season_std', 'PLAYER_SUCCESSFUL_DRIBBLES_season_std', 'PLAYER_TACKLES_season_std', 'PLAYER_TOTAL_CROSSES_season_std', 'PLAYER_TOTAL_DUELS_season_std', 'PLAYER_YELLOWCARDS_season_std', 'PLAYER_ACCURATE_CROSSES_5_last_match_sum', 'PLAYER_ACCURATE_PASSES_5_last_match_sum', 'PLAYER_AERIALS_WON_5_last_match_sum', 'PLAYER_ASSISTS_5_last_match_sum', 'PLAYER_BIG_CHANCES_CREATED_5_last_match_sum', 'PLAYER_BIG_CHANCES_MISSED_5_last_match_sum', 'PLAYER_BLOCKED_SHOTS_5_last_match_sum', 'PLAYER_CLEARANCES_5_last_match_sum', 'PLAYER_CLEARANCE_OFFLINE_5_last_match_sum', 'PLAYER_DISPOSSESSED_5_last_match_sum', 'PLAYER_DRIBBLED_ATTEMPTS_5_last_match_sum', 'PLAYER_DRIBBLED_PAST_5_last_match_sum', 'PLAYER_DUELS_LOST_5_last_match_sum', 'PLAYER_DUELS_WON_5_last_match_sum', 'PLAYER_ERROR_LEAD_TO_GOAL_5_last_match_sum', 'PLAYER_FOULS_5_last_match_sum', 'PLAYER_FOULS_DRAWN_5_last_match_sum', 'PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_sum', 'PLAYER_GOALS_5_last_match_sum', 'PLAYER_GOALS_CONCEDED_5_last_match_sum', 'PLAYER_HIT_WOODWORK_5_last_match_sum', 'PLAYER_INTERCEPTIONS_5_last_match_sum', 'PLAYER_KEY_PASSES_5_last_match_sum', 'PLAYER_MINUTES_PLAYED_5_last_match_sum', 'PLAYER_OFFSIDES_5_last_match_sum', 'PLAYER_OWN_GOALS_5_last_match_sum', 'PLAYER_PASSES_5_last_match_sum', 'PLAYER_PENALTIES_COMMITTED_5_last_match_sum', 'PLAYER_PENALTIES_MISSES_5_last_match_sum', 'PLAYER_PENALTIES_SAVED_5_last_match_sum', 'PLAYER_PENALTIES_SCORED_5_last_match_sum', 'PLAYER_PENALTIES_WON_5_last_match_sum', 'PLAYER_REDCARDS_5_last_match_sum', 'PLAYER_SAVES_5_last_match_sum', 'PLAYER_SAVES_INSIDE_BOX_5_last_match_sum', 'PLAYER_SHOTS_BLOCKED_5_last_match_sum', 'PLAYER_SHOTS_ON_TARGET_5_last_match_sum', 'PLAYER_SHOTS_TOTAL_5_last_match_sum', 'PLAYER_STARTING_LINEUP_5_last_match_sum', 'PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_sum', 'PLAYER_TACKLES_5_last_match_sum', 'PLAYER_TOTAL_CROSSES_5_last_match_sum', 'PLAYER_TOTAL_DUELS_5_last_match_sum', 'PLAYER_YELLOWCARDS_5_last_match_sum', 'PLAYER_ACCURATE_CROSSES_5_last_match_average', 'PLAYER_ACCURATE_PASSES_5_last_match_average', 'PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_average', 'PLAYER_AERIALS_WON_5_last_match_average', 'PLAYER_ASSISTS_5_last_match_average', 'PLAYER_BIG_CHANCES_CREATED_5_last_match_average', 'PLAYER_BIG_CHANCES_MISSED_5_last_match_average', 'PLAYER_BLOCKED_SHOTS_5_last_match_average', 'PLAYER_CLEARANCES_5_last_match_average', 'PLAYER_CLEARANCE_OFFLINE_5_last_match_average', 'PLAYER_DISPOSSESSED_5_last_match_average', 'PLAYER_DRIBBLED_ATTEMPTS_5_last_match_average', 'PLAYER_DRIBBLED_PAST_5_last_match_average', 'PLAYER_DUELS_LOST_5_last_match_average', 'PLAYER_DUELS_WON_5_last_match_average', 'PLAYER_ERROR_LEAD_TO_GOAL_5_last_match_average', 'PLAYER_FOULS_5_last_match_average', 'PLAYER_FOULS_DRAWN_5_last_match_average', 'PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_average', 'PLAYER_GOALS_5_last_match_average', 'PLAYER_GOALS_CONCEDED_5_last_match_average', 'PLAYER_HIT_WOODWORK_5_last_match_average', 'PLAYER_INTERCEPTIONS_5_last_match_average', 'PLAYER_KEY_PASSES_5_last_match_average', 'PLAYER_MINUTES_PLAYED_5_last_match_average', 'PLAYER_OFFSIDES_5_last_match_average', 'PLAYER_OWN_GOALS_5_last_match_average', 'PLAYER_PASSES_5_last_match_average', 'PLAYER_PENALTIES_COMMITTED_5_last_match_average', 'PLAYER_PENALTIES_MISSES_5_last_match_average', 'PLAYER_PENALTIES_SAVED_5_last_match_average', 'PLAYER_PENALTIES_SCORED_5_last_match_average', 'PLAYER_PENALTIES_WON_5_last_match_average', 'PLAYER_RATING_5_last_match_average', 'PLAYER_REDCARDS_5_last_match_average', 'PLAYER_SAVES_5_last_match_average', 'PLAYER_SAVES_INSIDE_BOX_5_last_match_average', 'PLAYER_SHOTS_BLOCKED_5_last_match_average', 'PLAYER_SHOTS_ON_TARGET_5_last_match_average', 'PLAYER_SHOTS_TOTAL_5_last_match_average', 'PLAYER_STARTING_LINEUP_5_last_match_average', 'PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_average', 'PLAYER_TACKLES_5_last_match_average', 'PLAYER_TOTAL_CROSSES_5_last_match_average', 'PLAYER_TOTAL_DUELS_5_last_match_average', 'PLAYER_YELLOWCARDS_5_last_match_average', 'PLAYER_ACCURATE_CROSSES_5_last_match_std', 'PLAYER_ACCURATE_PASSES_5_last_match_std', 'PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_std', 'PLAYER_AERIALS_WON_5_last_match_std', 'PLAYER_ASSISTS_5_last_match_std', 'PLAYER_BIG_CHANCES_CREATED_5_last_match_std', 'PLAYER_BIG_CHANCES_MISSED_5_last_match_std', 'PLAYER_BLOCKED_SHOTS_5_last_match_std', 'PLAYER_CLEARANCES_5_last_match_std', 'PLAYER_CLEARANCE_OFFLINE_5_last_match_std', 'PLAYER_DISPOSSESSED_5_last_match_std', 'PLAYER_DRIBBLED_ATTEMPTS_5_last_match_std', 'PLAYER_DRIBBLED_PAST_5_last_match_std', 'PLAYER_DUELS_LOST_5_last_match_std', 'PLAYER_DUELS_WON_5_last_match_std', 'PLAYER_ERROR_LEAD_TO_GOAL_5_last_match_std', 'PLAYER_FOULS_5_last_match_std', 'PLAYER_FOULS_DRAWN_5_last_match_std', 'PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_std', 'PLAYER_GOALS_5_last_match_std', 'PLAYER_GOALS_CONCEDED_5_last_match_std', 'PLAYER_HIT_WOODWORK_5_last_match_std', 'PLAYER_INTERCEPTIONS_5_last_match_std', 'PLAYER_KEY_PASSES_5_last_match_std', 'PLAYER_MINUTES_PLAYED_5_last_match_std', 'PLAYER_OFFSIDES_5_last_match_std', 'PLAYER_OWN_GOALS_5_last_match_std', 'PLAYER_PASSES_5_last_match_std', 'PLAYER_PENALTIES_COMMITTED_5_last_match_std', 'PLAYER_PENALTIES_MISSES_5_last_match_std', 'PLAYER_PENALTIES_SAVED_5_last_match_std', 'PLAYER_PENALTIES_SCORED_5_last_match_std', 'PLAYER_PENALTIES_WON_5_last_match_std', 'PLAYER_RATING_5_last_match_std', 'PLAYER_REDCARDS_5_last_match_std', 'PLAYER_SAVES_5_last_match_std', 'PLAYER_SAVES_INSIDE_BOX_5_last_match_std', 'PLAYER_SHOTS_BLOCKED_5_last_match_std', 'PLAYER_SHOTS_ON_TARGET_5_last_match_std', 'PLAYER_SHOTS_TOTAL_5_last_match_std', 'PLAYER_STARTING_LINEUP_5_last_match_std', 'PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_std', 'PLAYER_TACKLES_5_last_match_std', 'PLAYER_TOTAL_CROSSES_5_last_match_std', 'PLAYER_TOTAL_DUELS_5_last_match_std', 'PLAYER_YELLOWCARDS_5_last_match_std']

In [202]:
home_team_processed.head(2)

,ID,LEAGUE,TEAM_NAME,TEAM_SHOTS_TOTAL_season_sum,TEAM_SHOTS_INSIDEBOX_season_sum,TEAM_SHOTS_OFF_TARGET_season_sum,TEAM_SHOTS_ON_TARGET_season_sum,TEAM_SHOTS_OUTSIDEBOX_season_sum,TEAM_PASSES_season_sum,TEAM_SUCCESSFUL_PASSES_season_sum,TEAM_SAVES_season_sum,TEAM_CORNERS_season_sum,TEAM_FOULS_season_sum,TEAM_YELLOWCARDS_season_sum,TEAM_REDCARDS_season_sum,TEAM_OFFSIDES_season_sum,TEAM_ATTACKS_season_sum,TEAM_PENALTIES_season_sum,TEAM_SUBSTITUTIONS_season_sum,TEAM_BALL_SAFE_season_sum,TEAM_DANGEROUS_ATTACKS_season_sum,TEAM_INJURIES_season_sum,TEAM_GOALS_season_sum,TEAM_GAME_WON_season_sum,TEAM_GAME_DRAW_season_sum,TEAM_GAME_LOST_season_sum,TEAM_SHOTS_TOTAL_season_average,TEAM_SHOTS_INSIDEBOX_season_average,TEAM_SHOTS_OFF_TARGET_season_average,TEAM_SHOTS_ON_TARGET_season_average,TEAM_SHOTS_OUTSIDEBOX_season_average,TEAM_PASSES_season_average,TEAM_SUCCESSFUL_PASSES_season_average,TEAM_SUCCESSFUL_PASSES_PERCENTAGE_season_average,TEAM_SAVES_season_average,TEAM_CORNERS_season_average,TEAM_BALL_POSSESSION_season_average,TEAM_FOULS_season_average,TEAM_YELLOWCARDS_season_average,TEAM_REDCARDS_season_average,TEAM_OFFSIDES_season_average,TEAM_ATTACKS_season_average,TEAM_PENALTIES_season_average,TEAM_SUBSTITUTIONS_season_average,TEAM_BALL_SAFE_season_average,TEAM_DANGEROUS_ATTACKS_season_average,TEAM_INJURIES_season_average,TEAM_GOALS_season_average,TEAM_GAME_WON_season_average,TEAM_GAME_DRAW_season_average,TEAM_GAME_LOST_season_average,TEAM_SHOTS_TOTAL_season_std,TEAM_SHOTS_INSIDEBOX_season_std,TEAM_SHOTS_OFF_TARGET_season_std,TEAM_SHOTS_ON_TARGET_season_std,TEAM_SHOTS_OUTSIDEBOX_season_std,TEAM_PASSES_season_std,TEAM_SUCCESSFUL_PASSES_season_std,TEAM_SUCCESSFUL_PASSES_PERCENTAGE_season_std,TEAM_SAVES_season_std,TEAM_CORNERS_season_std,TEAM_BALL_POSSESSION_season_std,TEAM_FOULS_season_std,TEAM_YELLOWCARDS_season_std,TEAM_REDCARDS_season_std,TEAM_OFFSIDES_season_std,TEAM_ATTACKS_season_std,TEAM_PENALTIES_season_std,TEAM_SUBSTITUTIONS_season_std,TEAM_BALL_SAFE_season_std,TEAM_DANGEROUS_ATTACKS_season_std,TEAM_INJURIES_season_std,TEAM_GOALS_season_std,TEAM_SHOTS_TOTAL_5_last_match_sum,TEAM_SHOTS_INSIDEBOX_5_last_match_sum,TEAM_SHOTS_OFF_TARGET_5_last_match_sum,TEAM_SHOTS_ON_TARGET_5_last_match_sum,TEAM_SHOTS_OUTSIDEBOX_5_last_match_sum,TEAM_PASSES_5_last_match_sum,TEAM_SUCCESSFUL_PASSES_5_last_match_sum,TEAM_SAVES_5_last_match_sum,TEAM_CORNERS_5_last_match_sum,TEAM_FOULS_5_last_match_sum,TEAM_YELLOWCARDS_5_last_match_sum,TEAM_REDCARDS_5_last_match_sum,TEAM_OFFSIDES_5_last_match_sum,TEAM_ATTACKS_5_last_match_sum,TEAM_PENALTIES_5_last_match_sum,TEAM_SUBSTITUTIONS_5_last_match_sum,TEAM_BALL_SAFE_5_last_match_sum,TEAM_DANGEROUS_ATTACKS_5_last_match_sum,TEAM_INJURIES_5_last_match_sum,TEAM_GOALS_5_last_match_sum,TEAM_GAME_WON_5_last_match_sum,TEAM_GAME_DRAW_5_last_match_sum,TEAM_GAME_LOST_5_last_match_sum,TEAM_SHOTS_TOTAL_5_last_match_average,TEAM_SHOTS_INSIDEBOX_5_last_match_average,TEAM_SHOTS_OFF_TARGET_5_last_match_average,TEAM_SHOTS_ON_TARGET_5_last_match_average,TEAM_SHOTS_OUTSIDEBOX_5_last_match_average,TEAM_PASSES_5_last_match_average,TEAM_SUCCESSFUL_PASSES_5_last_match_average,TEAM_SUCCESSFUL_PASSES_PERCENTAGE_5_last_match_average,TEAM_SAVES_5_last_match_average,TEAM_CORNERS_5_last_match_average,TEAM_BALL_POSSESSION_5_last_match_average,TEAM_FOULS_5_last_match_average,TEAM_YELLOWCARDS_5_last_match_average,TEAM_REDCARDS_5_last_match_average,TEAM_OFFSIDES_5_last_match_average,TEAM_ATTACKS_5_last_match_average,TEAM_PENALTIES_5_last_match_average,TEAM_SUBSTITUTIONS_5_last_match_average,TEAM_BALL_SAFE_5_last_match_average,TEAM_DANGEROUS_ATTACKS_5_last_match_average,TEAM_INJURIES_5_last_match_average,TEAM_GOALS_5_last_match_average,TEAM_GAME_WON_5_last_match_average,TEAM_GAME_DRAW_5_last_match_average,TEAM_GAME_LOST_5_last_match_average,TEAM_SHOTS_TOTAL_5_last_match_std,TEAM_SHOTS_INSIDEBOX_5_last_match_std,TEAM_SHOTS_OFF_TARGET_5_last_match_std,TEAM_SHOTS_ON_TARGET_5_last_match_std,TEAM_SHOTS_OUTSIDEBOX_5_last_match_std,TEAM_PASSES_5_last_match_std,TEAM_SUCCESSFUL_PASSES_5_last_match_std,TEAM_SUCCESSFUL_PASSES_PERCENTAGE_5_last_match_std,TEAM_SAVES_5_last_match_std,TEAM_CORNERS_5_last_match_std,TEAM_BALL_POSSESSION_5_last_match_std,TEAM_FOULS_5_last_match_std,TEAM_YELLOWCARDS_5_last_match_std,TEAM_REDCARDS_5_last_match_std,TEAM_OFFSIDES_5_last_match_std,TEAM_ATTACKS_5_last_match_std,TEAM_PENALTIES_5_last_match_std,TEAM_SUBSTITUTIONS_5_last_match_std,TEAM_BALL_SAFE_5_last_match_std,TEAM_DANGEROUS_ATTACKS_5_last_match_std,TEAM_INJURIES_5_last_match_std,TEAM_GOALS_5_last_match_std
0,0.00,Ligue 1,Toulouse,3.00,2.00,5.00,2.00,1.00,2.00,2.00,5.00,3.00,6.00,2.00,2.00,1.00,2.00,6.00,8.00,4.00,4.00,0.00,3.00,1.00,6.00,10.00,3.00,2.00,4.00,2.00,1.00,2.00,1.00,2.00,5.00,3.00,1.00,6.00,2.00,2.00,1.00,1.00,6.00,8.00,2.00,4.00,0.00,3.00,1.00,5.00,10.00,5.00,4.00,3.00,5.00,3.00,10.00,9.00,7.00,8.00,1.00,10.00,3.00,7.00,4.00,4.00,2.00,10.00,4.00,4.00,4.00,0.00,1.00,4.00,3.00,6.00,3.00,6.00,0.00,0.00,0.00,2.00,8.00,8.00,0.00,2.00,2.00,10.00,5.00,5.00,6.00,1.00,4.00,2.00,0.00,10.00,4.00,3.00,6.00,3.00,6.00,0.00,0.00,1.00,0.00,2.00,0.00,8.00,8.00,0.00,2.00,2.00,10.00,4.00,5.00,6.00,2.00,4.00,2.00,0.00,10.00,4.00,4.00,7.00,1.00,5.00,4.00,2.00,2.00,4.00,0.00,6.00,6.00,3.00,0.00,6.00,0.00,10.00,8.00,7.00,2.00,4.00,3.00
1,1.00,Ligue 2,Brest,6.00,8.00,3.00,6.00,5.00,8.00,7.00,10.00,6.00,8.00,3.00,0.00,7.00,7.00,6.00,10.00,9.00,6.00,2.00,10.00,8.00,4.00,1.00,5.00,7.00,2.00,5.00,2.00,5.00,5.00,6.00,9.00,5.00,6.00,5.00,3.00,0.00,5.00,4.00,6.00,7.00,5.00,4.00,2.00,9.00,7.00,3.00,1.00,4.00,3.00,1.00,5.00,6.00,1.00,1.00,0.00,10.00,6.00,3.00,4.00,4.00,0.00,3.00,6.00,8.00,4.00,2.00,4.00,3.00,10.00,5.00,6.00,1.00,7.00,3.00,4.00,4.00,5.00,1.00,2.00,4.00,0.00,7.00,8.00,10.00,10.00,5.00,3.00,3.00,10.00,8.00,3.00,0.00,5.00,6.00,1.00,7.00,3.00,4.00,4.00,5.00,5.00,1.00,5.00,1.00,4.00,0.00,7.00,8.00,10.00,10.00,5.00,3.00,3.00,10.00,8.00,3.00,0.00,5.00,2.00,1.00,3.00,7.00,5.00,5.00,3.00,7.00,2.00,6.00,3.00,4.00,0.00,4.00,3.00,10.00,0.00,1.00,2.00,8.00,4.00

In [203]:
away_team_processed.head(2)

,ID,LEAGUE,TEAM_NAME,TEAM_SHOTS_TOTAL_season_sum,TEAM_SHOTS_INSIDEBOX_season_sum,TEAM_SHOTS_OFF_TARGET_season_sum,TEAM_SHOTS_ON_TARGET_season_sum,TEAM_SHOTS_OUTSIDEBOX_season_sum,TEAM_PASSES_season_sum,TEAM_SUCCESSFUL_PASSES_season_sum,TEAM_SAVES_season_sum,TEAM_CORNERS_season_sum,TEAM_FOULS_season_sum,TEAM_YELLOWCARDS_season_sum,TEAM_REDCARDS_season_sum,TEAM_OFFSIDES_season_sum,TEAM_ATTACKS_season_sum,TEAM_PENALTIES_season_sum,TEAM_SUBSTITUTIONS_season_sum,TEAM_BALL_SAFE_season_sum,TEAM_DANGEROUS_ATTACKS_season_sum,TEAM_INJURIES_season_sum,TEAM_GOALS_season_sum,TEAM_GAME_WON_season_sum,TEAM_GAME_DRAW_season_sum,TEAM_GAME_LOST_season_sum,TEAM_SHOTS_TOTAL_season_average,TEAM_SHOTS_INSIDEBOX_season_average,TEAM_SHOTS_OFF_TARGET_season_average,TEAM_SHOTS_ON_TARGET_season_average,TEAM_SHOTS_OUTSIDEBOX_season_average,TEAM_PASSES_season_average,TEAM_SUCCESSFUL_PASSES_season_average,TEAM_SUCCESSFUL_PASSES_PERCENTAGE_season_average,TEAM_SAVES_season_average,TEAM_CORNERS_season_average,TEAM_BALL_POSSESSION_season_average,TEAM_FOULS_season_average,TEAM_YELLOWCARDS_season_average,TEAM_REDCARDS_season_average,TEAM_OFFSIDES_season_average,TEAM_ATTACKS_season_average,TEAM_PENALTIES_season_average,TEAM_SUBSTITUTIONS_season_average,TEAM_BALL_SAFE_season_average,TEAM_DANGEROUS_ATTACKS_season_average,TEAM_INJURIES_season_average,TEAM_GOALS_season_average,TEAM_GAME_WON_season_average,TEAM_GAME_DRAW_season_average,TEAM_GAME_LOST_season_average,TEAM_SHOTS_TOTAL_season_std,TEAM_SHOTS_INSIDEBOX_season_std,TEAM_SHOTS_OFF_TARGET_season_std,TEAM_SHOTS_ON_TARGET_season_std,TEAM_SHOTS_OUTSIDEBOX_season_std,TEAM_PASSES_season_std,TEAM_SUCCESSFUL_PASSES_season_std,TEAM_SUCCESSFUL_PASSES_PERCENTAGE_season_std,TEAM_SAVES_season_std,TEAM_CORNERS_season_std,TEAM_BALL_POSSESSION_season_std,TEAM_FOULS_season_std,TEAM_YELLOWCARDS_season_std,TEAM_REDCARDS_season_std,TEAM_OFFSIDES_season_std,TEAM_ATTACKS_season_std,TEAM_PENALTIES_season_std,TEAM_SUBSTITUTIONS_season_std,TEAM_BALL_SAFE_season_std,TEAM_DANGEROUS_ATTACKS_season_std,TEAM_INJURIES_season_std,TEAM_GOALS_season_std,TEAM_SHOTS_TOTAL_5_last_match_sum,TEAM_SHOTS_INSIDEBOX_5_last_match_sum,TEAM_SHOTS_OFF_TARGET_5_last_match_sum,TEAM_SHOTS_ON_TARGET_5_last_match_sum,TEAM_SHOTS_OUTSIDEBOX_5_last_match_sum,TEAM_PASSES_5_last_match_sum,TEAM_SUCCESSFUL_PASSES_5_last_match_sum,TEAM_SAVES_5_last_match_sum,TEAM_CORNERS_5_last_match_sum,TEAM_FOULS_5_last_match_sum,TEAM_YELLOWCARDS_5_last_match_sum,TEAM_REDCARDS_5_last_match_sum,TEAM_OFFSIDES_5_last_match_sum,TEAM_ATTACKS_5_last_match_sum,TEAM_PENALTIES_5_last_match_sum,TEAM_SUBSTITUTIONS_5_last_match_sum,TEAM_BALL_SAFE_5_last_match_sum,TEAM_DANGEROUS_ATTACKS_5_last_match_sum,TEAM_INJURIES_5_last_match_sum,TEAM_GOALS_5_last_match_sum,TEAM_GAME_WON_5_last_match_sum,TEAM_GAME_DRAW_5_last_match_sum,TEAM_GAME_LOST_5_last_match_sum,TEAM_SHOTS_TOTAL_5_last_match_average,TEAM_SHOTS_INSIDEBOX_5_last_match_average,TEAM_SHOTS_OFF_TARGET_5_last_match_average,TEAM_SHOTS_ON_TARGET_5_last_match_average,TEAM_SHOTS_OUTSIDEBOX_5_last_match_average,TEAM_PASSES_5_last_match_average,TEAM_SUCCESSFUL_PASSES_5_last_match_average,TEAM_SUCCESSFUL_PASSES_PERCENTAGE_5_last_match_average,TEAM_SAVES_5_last_match_average,TEAM_CORNERS_5_last_match_average,TEAM_BALL_POSSESSION_5_last_match_average,TEAM_FOULS_5_last_match_average,TEAM_YELLOWCARDS_5_last_match_average,TEAM_REDCARDS_5_last_match_average,TEAM_OFFSIDES_5_last_match_average,TEAM_ATTACKS_5_last_match_average,TEAM_PENALTIES_5_last_match_average,TEAM_SUBSTITUTIONS_5_last_match_average,TEAM_BALL_SAFE_5_last_match_average,TEAM_DANGEROUS_ATTACKS_5_last_match_average,TEAM_INJURIES_5_last_match_average,TEAM_GOALS_5_last_match_average,TEAM_GAME_WON_5_last_match_average,TEAM_GAME_DRAW_5_last_match_average,TEAM_GAME_LOST_5_last_match_average,TEAM_SHOTS_TOTAL_5_last_match_std,TEAM_SHOTS_INSIDEBOX_5_last_match_std,TEAM_SHOTS_OFF_TARGET_5_last_match_std,TEAM_SHOTS_ON_TARGET_5_last_match_std,TEAM_SHOTS_OUTSIDEBOX_5_last_match_std,TEAM_PASSES_5_last_match_std,TEAM_SUCCESSFUL_PASSES_5_last_match_std,TEAM_SUCCESSFUL_PASSES_PERCENTAGE_5_last_match_std,TEAM_SAVES_5_last_match_std,TEAM_CORNERS_5_last_match_std,TEAM_BALL_POSSESSION_5_last_match_std,TEAM_FOULS_5_last_match_std,TEAM_YELLOWCARDS_5_last_match_std,TEAM_REDCARDS_5_last_match_std,TEAM_OFFSIDES_5_last_match_std,TEAM_ATTACKS_5_last_match_std,TEAM_PENALTIES_5_last_match_std,TEAM_SUBSTITUTIONS_5_last_match_std,TEAM_BALL_SAFE_5_last_match_std,TEAM_DANGEROUS_ATTACKS_5_last_match_std,TEAM_INJURIES_5_last_match_std,TEAM_GOALS_5_last_match_std
0,0.00,Ligue 1,Olympique Marseille,4.00,1.00,4.00,1.00,5.00,4.00,3.00,6.00,4.00,6.00,10.00,6.00,1.00,4.00,10.00,8.00,2.00,4.00,1.00,4.00,5.00,8.00,0.00,4.00,1.00,4.00,1.00,5.00,3.00,3.00,5.00,6.00,4.00,3.00,6.00,10.00,6.00,1.00,4.00,10.00,8.00,0.00,4.00,0.00,4.00,4.00,7.00,0.00,4.00,1.00,0.00,3.00,10.00,7.00,7.00,5.00,4.00,6.00,7.00,2.00,7.00,9.00,1.00,1.00,6.00,4.00,3.00,10.00,1.00,4.00,2.00,2.00,2.00,1.00,4.00,2.00,3.00,2.00,4.00,4.00,6.00,3.00,5.00,4.00,10.00,5.00,0.00,6.00,0.00,4.00,7.00,0.00,5.00,2.00,2.00,2.00,1.00,4.00,2.00,3.00,5.00,2.00,4.00,3.00,4.00,6.00,3.00,4.00,4.00,10.00,4.00,0.00,6.00,0.00,4.00,7.00,0.00,5.00,0.00,3.00,2.00,3.00,7.00,6.00,6.00,6.00,0.00,1.00,8.00,2.00,5.00,5.00,4.00,0.00,6.00,8.00,4.00,3.00,2.00,3.00
1,1.00,Ligue 2,Red Star,4.00,3.00,4.00,3.00,8.00,8.00,7.00,8.00,5.00,8.00,3.00,2.00,5.00,5.00,3.00,10.00,4.00,7.00,5.00,2.00,1.00,4.00,8.00,3.00,2.00,2.00,2.00,6.00,4.00,4.00,5.00,8.00,4.00,4.00,5.00,3.00,1.00,3.00,2.00,3.00,7.00,0.00,5.00,6.00,2.00,1.00,3.00,7.00,5.00,0.00,4.00,2.00,8.00,6.00,5.00,3.00,7.00,1.00,5.00,9.00,2.00,4.00,3.00,7.00,6.00,4.00,10.00,6.00,4.00,2.00,3.00,2.00,0.00,3.00,5.00,5.00,5.00,7.00,3.00,5.00,3.00,0.00,5.00,3.00,5.00,5.00,0.00,4.00,3.00,2.00,2.00,3.00,7.00,3.00,2.00,0.00,3.00,5.00,5.00,5.00,6.00,7.00,3.00,5.00,5.00,3.00,0.00,4.00,3.00,5.00,4.00,0.00,4.00,3.00,2.00,2.00,3.00,7.00,4.00,0.00,3.00,3.00,4.00,9.00,8.00,5.00,5.00,1.00,6.00,10.00,0.00,0.00,3.00,1.00,8.00,4.00,10.00,0.00,5.00,3.00

In [204]:
home_player_processed.head(2)

,ID,LEAGUE,TEAM_NAME,PLAYER_NAME,PLAYER_ACCURATE_CROSSES_season_sum,PLAYER_ACCURATE_PASSES_season_sum,PLAYER_AERIALS_WON_season_sum,PLAYER_ASSISTS_season_sum,PLAYER_BIG_CHANCES_CREATED_season_sum,PLAYER_BIG_CHANCES_MISSED_season_sum,PLAYER_BLOCKED_SHOTS_season_sum,PLAYER_CLEARANCES_season_sum,PLAYER_CLEARANCE_OFFLINE_season_sum,PLAYER_DISPOSSESSED_season_sum,PLAYER_DRIBBLED_ATTEMPTS_season_sum,PLAYER_DRIBBLED_PAST_season_sum,PLAYER_DUELS_LOST_season_sum,PLAYER_DUELS_WON_season_sum,PLAYER_ERROR_LEAD_TO_GOAL_season_sum,PLAYER_FOULS_season_sum,PLAYER_FOULS_DRAWN_season_sum,PLAYER_GOALKEEPER_GOALS_CONCEDED_season_sum,PLAYER_GOALS_season_sum,PLAYER_GOALS_CONCEDED_season_sum,PLAYER_HIT_WOODWORK_season_sum,PLAYER_INTERCEPTIONS_season_sum,PLAYER_KEY_PASSES_season_sum,PLAYER_MINUTES_PLAYED_season_sum,PLAYER_OFFSIDES_season_sum,PLAYER_OWN_GOALS_season_sum,PLAYER_PASSES_season_sum,PLAYER_PENALTIES_COMMITTED_season_sum,PLAYER_PENALTIES_MISSES_season_sum,PLAYER_PENALTIES_SAVED_season_sum,PLAYER_PENALTIES_SCORED_season_sum,PLAYER_PENALTIES_WON_season_sum,PLAYER_REDCARDS_season_sum,PLAYER_SAVES_season_sum,PLAYER_SAVES_INSIDE_BOX_season_sum,PLAYER_SHOTS_BLOCKED_season_sum,PLAYER_SHOTS_ON_TARGET_season_sum,PLAYER_SHOTS_TOTAL_season_sum,PLAYER_STARTING_LINEUP_season_sum,PLAYER_SUCCESSFUL_DRIBBLES_season_sum,PLAYER_TACKLES_season_sum,PLAYER_TOTAL_CROSSES_season_sum,PLAYER_TOTAL_DUELS_season_sum,PLAYER_YELLOWCARDS_season_sum,PLAYER_ACCURATE_CROSSES_season_average,PLAYER_ACCURATE_PASSES_season_average,PLAYER_ACCURATE_PASSES_PERCENTAGE_season_average,PLAYER_AERIALS_WON_season_average,PLAYER_ASSISTS_season_average,PLAYER_BIG_CHANCES_CREATED_season_average,PLAYER_BIG_CHANCES_MISSED_season_average,PLAYER_BLOCKED_SHOTS_season_average,PLAYER_CLEARANCES_season_average,PLAYER_CLEARANCE_OFFLINE_season_average,PLAYER_DISPOSSESSED_season_average,PLAYER_DRIBBLED_ATTEMPTS_season_average,PLAYER_DRIBBLED_PAST_season_average,PLAYER_DUELS_LOST_season_average,PLAYER_DUELS_WON_season_average,PLAYER_ERROR_LEAD_TO_GOAL_season_average,PLAYER_FOULS_season_average,PLAYER_FOULS_DRAWN_season_average,PLAYER_GOALKEEPER_GOALS_CONCEDED_season_average,PLAYER_GOALS_season_average,PLAYER_GOALS_CONCEDED_season_average,PLAYER_HIT_WOODWORK_season_average,PLAYER_INTERCEPTIONS_season_average,PLAYER_KEY_PASSES_season_average,PLAYER_MINUTES_PLAYED_season_average,PLAYER_OFFSIDES_season_average,PLAYER_OWN_GOALS_season_average,PLAYER_PASSES_season_average,PLAYER_PENALTIES_COMMITTED_season_average,PLAYER_PENALTIES_MISSES_season_average,PLAYER_PENALTIES_SAVED_season_average,PLAYER_PENALTIES_SCORED_season_average,PLAYER_PENALTIES_WON_season_average,PLAYER_RATING_season_average,PLAYER_REDCARDS_season_average,PLAYER_SAVES_season_average,PLAYER_SAVES_INSIDE_BOX_season_average,PLAYER_SHOTS_BLOCKED_season_average,PLAYER_SHOTS_ON_TARGET_season_average,PLAYER_SHOTS_TOTAL_season_average,PLAYER_STARTING_LINEUP_season_average,PLAYER_SUCCESSFUL_DRIBBLES_season_average,PLAYER_TACKLES_season_average,PLAYER_TOTAL_CROSSES_season_average,PLAYER_TOTAL_DUELS_season_average,PLAYER_YELLOWCARDS_season_average,PLAYER_ACCURATE_CROSSES_season_std,PLAYER_ACCURATE_PASSES_season_std,PLAYER_ACCURATE_PASSES_PERCENTAGE_season_std,PLAYER_AERIALS_WON_season_std,PLAYER_ASSISTS_season_std,PLAYER_BIG_CHANCES_CREATED_season_std,PLAYER_BIG_CHANCES_MISSED_season_std,PLAYER_BLOCKED_SHOTS_season_std,PLAYER_CLEARANCES_season_std,PLAYER_CLEARANCE_OFFLINE_season_std,PLAYER_DISPOSSESSED_season_std,PLAYER_DRIBBLED_ATTEMPTS_season_std,PLAYER_DRIBBLED_PAST_season_std,PLAYER_DUELS_LOST_season_std,PLAYER_DUELS_WON_season_std,PLAYER_ERROR_LEAD_TO_GOAL_season_std,PLAYER_FOULS_season_std,PLAYER_FOULS_DRAWN_season_std,PLAYER_GOALKEEPER_GOALS_CONCEDED_season_std,PLAYER_GOALS_season_std,PLAYER_GOALS_CONCEDED_season_std,PLAYER_HIT_WOODWORK_season_std,PLAYER_INTERCEPTIONS_season_std,PLAYER_KEY_PASSES_season_std,PLAYER_MINUTES_PLAYED_season_std,PLAYER_OFFSIDES_season_std,PLAYER_OWN_GOALS_season_std,PLAYER_PASSES_season_std,PLAYER_PENALTIES_COMMITTED_season_std,PLAYER_PENALTIES_MISSES_season_std,PLAYER_PENALTIES_SAVED_season_std,PLAYER_PENALTIES_SCORED_season_std,PLAYER_PENALTIES_WON_season_std,PLAYER_RATING_season_std,PLAYER_REDCARDS_season_std,PLAYER_SAVES_season_std,PLAYER_SAVES_INSIDE_BOX_season_std,PLAYER_SHOTS_BLOCKED_season_std,PLAYER_SHOTS_ON_TARGET_season_std,PLAYER_SHOTS_TOTAL_season_std,PLAYER_STARTING_LINEUP_season_std,PLAYER_SUCCESSFUL_DRIBBLES_season_std,PLAYER_TACKLES_season_std,PLAYER_TOTAL_CROSSES_season_std,PLAYER_TOTAL_DUELS_season_std,PLAYER_YELLOWCARDS_season_std,PLAYER_ACCURATE_CROSSES_5_last_match_sum,PLAYER_ACCURATE_PASSES_5_last_match_sum,PLAYER_AERIALS_WON_5_last_match_sum,PLAYER_ASSISTS_5_last_match_sum,PLAYER_BIG_CHANCES_CREATED_5_last_match_sum,PLAYER_BIG_CHANCES_MISSED_5_last_match_sum,PLAYER_BLOCKED_SHOTS_5_last_match_sum,PLAYER_CLEARANCES_5_last_match_sum,PLAYER_CLEARANCE_OFFLINE_5_last_match_sum,PLAYER_DISPOSSESSED_5_last_match_sum,PLAYER_DRIBBLED_ATTEMPTS_5_last_match_sum,PLAYER_DRIBBLED_PAST_5_last_match_sum,PLAYER_DUELS_LOST_5_last_match_sum,PLAYER_DUELS_WON_5_last_match_sum,PLAYER_ERROR_LEAD_TO_GOAL_5_last_match_sum,PLAYER_FOULS_5_last_match_sum,PLAYER_FOULS_DRAWN_5_last_match_sum,PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_sum,PLAYER_GOALS_5_last_match_sum,PLAYER_GOALS_CONCEDED_5_last_match_sum,PLAYER_HIT_WOODWORK_5_last_match_sum,PLAYER_INTERCEPTIONS_5_last_match_sum,PLAYER_KEY_PASSES_5_last_match_sum,PLAYER_MINUTES_PLAYED_5_last_match_sum,PLAYER_OFFSIDES_5_last_match_sum,PLAYER_OWN_GOALS_5_last_match_sum,PLAYER_PASSES_5_last_match_sum,PLAYER_PENALTIES_COMMITTED_5_last_match_sum,PLAYER_PENALTIES_MISSES_5_last_match_sum,PLAYER_PENALTIES_SAVED_5_last_match_sum,PLAYER_PENALTIES_SCORED_5_last_match_sum,PLAYER_PENALTIES_WON_5_last_match_sum,PLAYER_REDCARDS_5_last_match_sum,PLAYER_SAVES_5_last_match_sum,PLAYER_SAVES_INSIDE_BOX_5_last_match_sum,PLAYER_SHOTS_BLOCKED_5_last_match_sum,PLAYER_SHOTS_ON_TARGET_5_last_match_sum,PLAYER_SHOTS_TOTAL_5_last_match_sum,PLAYER_STARTING_LINEUP_5_last_match_sum,PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_sum,PLAYER_TACKLES_5_last_match_sum,PLAYER_TOTAL_CROSSES_5_last_match_sum,PLAYER_TOTAL_DUELS_5_last_match_sum,PLAYER_YELLOWCARDS_5_last_match_sum,PLAYER_ACCURATE_CROSSES_5_last_match_average,PLAYER_ACCURATE_PASSES_5_last_match_average,PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_average,PLAYER_AERIALS_WON_5_last_match_average,PLAYER_ASSISTS_5_last_match_average,PLAYER_BIG_CHANCES_CREATED_5_last_match_average,PLAYER_BIG_CHANCES_MISSED_5_last_match_average,PLAYER_BLOCKED_SHOTS_5_last_match_average,PLAYER_CLEARANCES_5_last_match_average,PLAYER_CLEARANCE_OFFLINE_5_last_match_average,PLAYER_DISPOSSESSED_5_last_match_average,PLAYER_DRIBBLED_ATTEMPTS_5_last_match_average,PLAYER_DRIBBLED_PAST_5_last_match_average,PLAYER_DUELS_LOST_5_last_match_average,PLAYER_DUELS_WON_5_last_match_average,PLAYER_ERROR_LEAD_TO_GOAL_5_last_match_average,PLAYER_FOULS_5_last_match_average,PLAYER_FOULS_DRAWN_5_last_match_average,PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_average,PLAYER_GOALS_5_last_match_average,PLAYER_GOALS_CONCEDED_5_last_match_average,PLAYER_HIT_WOODWORK_5_last_match_average,PLAYER_INTERCEPTIONS_5_last_match_average,PLAYER_KEY_PASSES_5_last_match_average,PLAYER_MINUTES_PLAYED_5_last_match_average,PLAYER_OFFSIDES_5_last_match_average,PLAYER_OWN_GOALS_5_last_match_average,PLAYER_PASSES_5_last_match_average,PLAYER_PENALTIES_COMMITTED_5_last_match_average,PLAYER_PENALTIES_MISSES_5_last_match_average,PLAYER_PENALTIES_SAVED_5_last_match_average,PLAYER_PENALTIES_SCORED_5_last_match_average,PLAYER_PENALTIES_WON_5_last_match_average,PLAYER_RATING_5_last_match_average,PLAYER_REDCARDS_5_last_match_average,PLAYER_SAVES_5_last_match_average,PLAYER_SAVES_INSIDE_BOX_5_last_match_average,PLAYER_SHOTS_BLOCKED_5_last_match_average,PLAYER_SHOTS_ON_TARGET_5_last_match_average,PLAYER_SHOTS_TOTAL_5_last_match_average,PLAYER_STARTING_LINEUP_5_last_match_average,PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_average,PLAYER_TACKLES_5_last_match_average,PLAYER_TOTAL_CROSSES_5_last_match_average,PLAYER_TOTAL_DUELS_5_last_match_average,PLAYER_YELLOWCARDS_5_last_match_average,PLAYER_ACCURATE_CROSSES_5_last_match_std,PLAYER_ACCURATE_PASSES_5_last_match_std,PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_std,PLAYER_AERIALS_WON_5_last_match_std,PLAYER_ASSISTS_5_last_match_std,PLAYER_BIG_CHANCES_CREATED_5_last_match_std,PLAYER_BIG_CHANCES_MISSED_5_last_match_std,PLAYER_BLOCKED_SHOTS_5_last_match_std,PLAYER_CLEARANCES_5_last_match_std,PLAYER_CLEARANCE_OFFLINE_5_last_match_std,PLAYER_DISPOSSESSED_5_last_match_std,PLAYER_DRIBBLED_ATTEMPTS_5_last_match_std,PLAYER_DRIBBLED_PAST_5_last_match_std,PLAYER_DUELS_LOST_5_last_match_std,PLAYER_DUELS_WON_5_last_match_std,PLAYER_ERROR_LEAD_TO_GOAL_5_last_match_std,PLAYER_FOULS_5_last_match_std,PLAYER_FOULS_DRAWN_5_last_match_std,PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_std,PLAYER_GOALS_5_last_match_std,PLAYER_GOALS_CONCEDED_5_last_match_std,PLAYER_HIT_WOODWORK_5_last_match_std,PLAYER_INTERCEPTIONS_5_last_match_std,PLAYER_KEY_PASSES_5_last_match_std,PLAYER_MINUTES_PLAYED_5_last_match_std,PLAYER_OFFSIDES_5_last_match_std,PLAYER_OWN_GOALS_5_last_match_std,PLAYER_PASSES_5_last_match_std,PLAYER_PENALTIES_COMMITTED_5_last_match_std,PLAYER_PENALTIES_MISSES_5_last_match_std,PLAYER_PENALTIES_SAVED_5_last_match_std,PLAYER_PENALTIES_SCORED_5_last_match_std,PLAYER_PENALTIES_WON_5_last_match_std,PLAYER_RATING_5_last_match_std,PLAYER_REDCARDS_5_last_match_std,PLAYER_SAVES_5_last_match_std,PLAYER_SAVES_INSIDE_BOX_5_last_match_std,PLAYER_SHOTS_BLOCKED_5_last_match_std,PLAYER_SHOTS_ON_TARGET_5_last_match_std,PLAYER_SHOTS_TOTAL_5_last_match_std,PLAYER_STARTING_LINEUP_5_last_match_std,PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_std,PLAYER_TACKLES_5_last_match_std,PLAYER_TOTAL_CROSSES_5_last_match_std,PLAYER_TOTAL_DUELS_5_last_match_std,PLAYER_YELLOWCARDS_5_last_match_std
0,0,Ligue 1,Toulouse,Agustín Rogel,0.00,8.00,5.00,0.00,0.00,0.00,0.00,4.00,0.00,0.00,0.00,0.00,0.00,3.00,0.00,0.00,0.00,0.00,0.00,4.00,0.00,0.00,0.00,6.00,0.00,0.00,7.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2.00,7.00,0.00,0.00,0.00,1.00,0.00,0.00,89.00,69.00,61.00,0.00,0.00,0.00,0.00,44.00,0.00,0.00,0.00,0.00,0.00,35.00,0.00,0.00,0.00,0.00,0.00,25.00,0.00,0.00,0.00,86.00,0.00,0.00,88.00,0.00,0.00,0.00,0.00,0.00,86.00,0.00,0.00,0.00,0.00,0.00,18.00,100.00,0.00,0.00,0.00,20.00,0.00,8.00,38.00,22.00,28.00,0.00,0.00,0.00,29.00,37.00,0.00,14.00,11.00,23.00,29.00,39.00,0.00,34.00,26.00,0.00,0.00,38.00,0.00,38.00,17.00,52.00,0.00,0.00,40.00,0.00,0.00,0.00,0.00,0.00,49.00,0.00,0.00,0.00,27.00,14.00,17.00,53.00,13.00,35.00,8.00,35.00,46.00,0.00,16.00,10.00,0.00,0.00,0.00,0.00,8.00,0.00,0.00,0.00,0.00,0.00,6.00,0.00,0.00,0.00,0.00,0.00,7.00,0.00,0.00,0.00,17.00,0.00,0.00,16.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,3.00,20.00,0.00,0.00,0.00,3.00,0.00,0.00,81.00,71.00,54.00,0.00,0.00,0.00,0.00,44.00,0.00,0.00,0.00,0.00,0.00,31.00,0.00,0.00,0.00,0.00,0.00,25.00,0.00,0.00,0.00,86.00,0.00,0.00,82.00,0.00,0.00,0.00,0.00,0.00,82.00,0.00,0.00,0.00,0.00,0.00,18.00,100.00,0.00,0.00,0.00,19.00,0.00,0.00,29.00,17.00,20.00,0.00,0.00,0.00,21.00,27.00,0.00,7.00,9.00,17.00,23.00,30.00,0.00,25.00,18.00,0.00,0.00,33.00,0.00,28.00,13.00,26.00,0.00,0.00,31.00,0.00,0.00,0.00,0.00,0.00,13.00,0.00,0.00,0.00,20.00,0.00,13.00,0.00,10.00,25.00,6.00,28.00,0.00
1,0,Ligue 1,Toulouse,Mathieu Goncalves,0.00,7.00,4.00,0.00,0.00,0.00,6.00,12.00,0.00,4.00,1.00,19.00,8.00,7.00,0.00,9.00,2.00,0.00,0.00,64.00,0.00,3.00,0.00,20.00,0.00,100.00,8.00,50.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,6.00,0.00,0.00,15.00,4.00,5.00,0.00,8.00,20.00,0.00,11.00,75.00,6.00,0.00,0.00,0.00,9.00,17.00,0.00,8.00,1.00,25.00,14.00,11.00,0.00,10.00,3.00,0.00,0.00,57.00,0.00,3.00,0.00,38.00,0.00,42.00,14.00,71.00,0.00,0.00,0.00,0.00,32.00,0.00,0.00,0.00,11.00,0.00,0.00,28.00,3.00,10.00,0.00,14.00,14.00,0.00,26.00,31.00,16.00,0.00,0.00,0.00,23.00,33.00,0.00,32.00,7.00,45.00,30.00,21.00,0.00,17.00,13.00,0.00,0.00,48.00,0.00,10.00,0.00,69.00,0.00,65.00,35.00,59.00,0.00,0.00,0.00,0.00,59.00,0.00,0.00,0.00,23.00,0.00,0.00,69.00,13.00,14.00,0.00,32.00,65.00,0.00,10.00,8.00,0.00,0.00,0.00,12.00,14.00,0.00,0.00,2.00,28.00,14.00,9.00,0.00,11.00,0.00,0.00,0.00,92.00,0.00,0.00,0.00,34.00,0.00,0.00,12.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,12.00,0.00,0.00,20.00,4.00,8.00,0.00,14.00,25.00,0.00,10.00,75.00,8.00,0.00,0.00,0.00,12.00,14.00,0.00,0.00,2.00,28.00,14.00,9.00,0.00,10.00,0.00,0.00,0.00,60.00,0.00,0.00,0.00,34.00,0.00,0.00,12.00,0.00,0.00,0.00,0.00,0.00,29.00,0.00,0.00,0.00,12.00,0.00,0.00,20.00,4.00,8.00,0.00,14.00,20.00,0.00,26.00,25.00,16.00,0.00,0.00,0.00,25.00,24.00,0.00,0.00,9.00,48.00,47.00,22.00,0.00,17.00,0.00,0.00,0.00,31.00,0.00,0.00,0.00,67.00,0.00,0.00,31.00,0.00,0.00,0.00,0.00,0.00,62.00,0.00,0.00,0.00,21.00,0.00,0.00,63.00,14.00,13.00,0.00,36.00,77.00

In [205]:
away_player_processed.head(2)

,ID,LEAGUE,TEAM_NAME,PLAYER_NAME,PLAYER_ACCURATE_CROSSES_season_sum,PLAYER_ACCURATE_PASSES_season_sum,PLAYER_AERIALS_WON_season_sum,PLAYER_ASSISTS_season_sum,PLAYER_BIG_CHANCES_CREATED_season_sum,PLAYER_BIG_CHANCES_MISSED_season_sum,PLAYER_BLOCKED_SHOTS_season_sum,PLAYER_CLEARANCES_season_sum,PLAYER_CLEARANCE_OFFLINE_season_sum,PLAYER_DISPOSSESSED_season_sum,PLAYER_DRIBBLED_ATTEMPTS_season_sum,PLAYER_DRIBBLED_PAST_season_sum,PLAYER_DUELS_LOST_season_sum,PLAYER_DUELS_WON_season_sum,PLAYER_ERROR_LEAD_TO_GOAL_season_sum,PLAYER_FOULS_season_sum,PLAYER_FOULS_DRAWN_season_sum,PLAYER_GOALKEEPER_GOALS_CONCEDED_season_sum,PLAYER_GOALS_season_sum,PLAYER_GOALS_CONCEDED_season_sum,PLAYER_HIT_WOODWORK_season_sum,PLAYER_INTERCEPTIONS_season_sum,PLAYER_KEY_PASSES_season_sum,PLAYER_MINUTES_PLAYED_season_sum,PLAYER_OFFSIDES_season_sum,PLAYER_OWN_GOALS_season_sum,PLAYER_PASSES_season_sum,PLAYER_PENALTIES_COMMITTED_season_sum,PLAYER_PENALTIES_MISSES_season_sum,PLAYER_PENALTIES_SAVED_season_sum,PLAYER_PENALTIES_SCORED_season_sum,PLAYER_PENALTIES_WON_season_sum,PLAYER_REDCARDS_season_sum,PLAYER_SAVES_season_sum,PLAYER_SAVES_INSIDE_BOX_season_sum,PLAYER_SHOTS_BLOCKED_season_sum,PLAYER_SHOTS_ON_TARGET_season_sum,PLAYER_SHOTS_TOTAL_season_sum,PLAYER_STARTING_LINEUP_season_sum,PLAYER_SUCCESSFUL_DRIBBLES_season_sum,PLAYER_TACKLES_season_sum,PLAYER_TOTAL_CROSSES_season_sum,PLAYER_TOTAL_DUELS_season_sum,PLAYER_YELLOWCARDS_season_sum,PLAYER_ACCURATE_CROSSES_season_average,PLAYER_ACCURATE_PASSES_season_average,PLAYER_ACCURATE_PASSES_PERCENTAGE_season_average,PLAYER_AERIALS_WON_season_average,PLAYER_ASSISTS_season_average,PLAYER_BIG_CHANCES_CREATED_season_average,PLAYER_BIG_CHANCES_MISSED_season_average,PLAYER_BLOCKED_SHOTS_season_average,PLAYER_CLEARANCES_season_average,PLAYER_CLEARANCE_OFFLINE_season_average,PLAYER_DISPOSSESSED_season_average,PLAYER_DRIBBLED_ATTEMPTS_season_average,PLAYER_DRIBBLED_PAST_season_average,PLAYER_DUELS_LOST_season_average,PLAYER_DUELS_WON_season_average,PLAYER_ERROR_LEAD_TO_GOAL_season_average,PLAYER_FOULS_season_average,PLAYER_FOULS_DRAWN_season_average,PLAYER_GOALKEEPER_GOALS_CONCEDED_season_average,PLAYER_GOALS_season_average,PLAYER_GOALS_CONCEDED_season_average,PLAYER_HIT_WOODWORK_season_average,PLAYER_INTERCEPTIONS_season_average,PLAYER_KEY_PASSES_season_average,PLAYER_MINUTES_PLAYED_season_average,PLAYER_OFFSIDES_season_average,PLAYER_OWN_GOALS_season_average,PLAYER_PASSES_season_average,PLAYER_PENALTIES_COMMITTED_season_average,PLAYER_PENALTIES_MISSES_season_average,PLAYER_PENALTIES_SAVED_season_average,PLAYER_PENALTIES_SCORED_season_average,PLAYER_PENALTIES_WON_season_average,PLAYER_RATING_season_average,PLAYER_REDCARDS_season_average,PLAYER_SAVES_season_average,PLAYER_SAVES_INSIDE_BOX_season_average,PLAYER_SHOTS_BLOCKED_season_average,PLAYER_SHOTS_ON_TARGET_season_average,PLAYER_SHOTS_TOTAL_season_average,PLAYER_STARTING_LINEUP_season_average,PLAYER_SUCCESSFUL_DRIBBLES_season_average,PLAYER_TACKLES_season_average,PLAYER_TOTAL_CROSSES_season_average,PLAYER_TOTAL_DUELS_season_average,PLAYER_YELLOWCARDS_season_average,PLAYER_ACCURATE_CROSSES_season_std,PLAYER_ACCURATE_PASSES_season_std,PLAYER_ACCURATE_PASSES_PERCENTAGE_season_std,PLAYER_AERIALS_WON_season_std,PLAYER_ASSISTS_season_std,PLAYER_BIG_CHANCES_CREATED_season_std,PLAYER_BIG_CHANCES_MISSED_season_std,PLAYER_BLOCKED_SHOTS_season_std,PLAYER_CLEARANCES_season_std,PLAYER_CLEARANCE_OFFLINE_season_std,PLAYER_DISPOSSESSED_season_std,PLAYER_DRIBBLED_ATTEMPTS_season_std,PLAYER_DRIBBLED_PAST_season_std,PLAYER_DUELS_LOST_season_std,PLAYER_DUELS_WON_season_std,PLAYER_ERROR_LEAD_TO_GOAL_season_std,PLAYER_FOULS_season_std,PLAYER_FOULS_DRAWN_season_std,PLAYER_GOALKEEPER_GOALS_CONCEDED_season_std,PLAYER_GOALS_season_std,PLAYER_GOALS_CONCEDED_season_std,PLAYER_HIT_WOODWORK_season_std,PLAYER_INTERCEPTIONS_season_std,PLAYER_KEY_PASSES_season_std,PLAYER_MINUTES_PLAYED_season_std,PLAYER_OFFSIDES_season_std,PLAYER_OWN_GOALS_season_std,PLAYER_PASSES_season_std,PLAYER_PENALTIES_COMMITTED_season_std,PLAYER_PENALTIES_MISSES_season_std,PLAYER_PENALTIES_SAVED_season_std,PLAYER_PENALTIES_SCORED_season_std,PLAYER_PENALTIES_WON_season_std,PLAYER_RATING_season_std,PLAYER_REDCARDS_season_std,PLAYER_SAVES_season_std,PLAYER_SAVES_INSIDE_BOX_season_std,PLAYER_SHOTS_BLOCKED_season_std,PLAYER_SHOTS_ON_TARGET_season_std,PLAYER_SHOTS_TOTAL_season_std,PLAYER_STARTING_LINEUP_season_std,PLAYER_SUCCESSFUL_DRIBBLES_season_std,PLAYER_TACKLES_season_std,PLAYER_TOTAL_CROSSES_season_std,PLAYER_TOTAL_DUELS_season_std,PLAYER_YELLOWCARDS_season_std,PLAYER_ACCURATE_CROSSES_5_last_match_sum,PLAYER_ACCURATE_PASSES_5_last_match_sum,PLAYER_AERIALS_WON_5_last_match_sum,PLAYER_ASSISTS_5_last_match_sum,PLAYER_BIG_CHANCES_CREATED_5_last_match_sum,PLAYER_BIG_CHANCES_MISSED_5_last_match_sum,PLAYER_BLOCKED_SHOTS_5_last_match_sum,PLAYER_CLEARANCES_5_last_match_sum,PLAYER_CLEARANCE_OFFLINE_5_last_match_sum,PLAYER_DISPOSSESSED_5_last_match_sum,PLAYER_DRIBBLED_ATTEMPTS_5_last_match_sum,PLAYER_DRIBBLED_PAST_5_last_match_sum,PLAYER_DUELS_LOST_5_last_match_sum,PLAYER_DUELS_WON_5_last_match_sum,PLAYER_ERROR_LEAD_TO_GOAL_5_last_match_sum,PLAYER_FOULS_5_last_match_sum,PLAYER_FOULS_DRAWN_5_last_match_sum,PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_sum,PLAYER_GOALS_5_last_match_sum,PLAYER_GOALS_CONCEDED_5_last_match_sum,PLAYER_HIT_WOODWORK_5_last_match_sum,PLAYER_INTERCEPTIONS_5_last_match_sum,PLAYER_KEY_PASSES_5_last_match_sum,PLAYER_MINUTES_PLAYED_5_last_match_sum,PLAYER_OFFSIDES_5_last_match_sum,PLAYER_OWN_GOALS_5_last_match_sum,PLAYER_PASSES_5_last_match_sum,PLAYER_PENALTIES_COMMITTED_5_last_match_sum,PLAYER_PENALTIES_MISSES_5_last_match_sum,PLAYER_PENALTIES_SAVED_5_last_match_sum,PLAYER_PENALTIES_SCORED_5_last_match_sum,PLAYER_PENALTIES_WON_5_last_match_sum,PLAYER_REDCARDS_5_last_match_sum,PLAYER_SAVES_5_last_match_sum,PLAYER_SAVES_INSIDE_BOX_5_last_match_sum,PLAYER_SHOTS_BLOCKED_5_last_match_sum,PLAYER_SHOTS_ON_TARGET_5_last_match_sum,PLAYER_SHOTS_TOTAL_5_last_match_sum,PLAYER_STARTING_LINEUP_5_last_match_sum,PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_sum,PLAYER_TACKLES_5_last_match_sum,PLAYER_TOTAL_CROSSES_5_last_match_sum,PLAYER_TOTAL_DUELS_5_last_match_sum,PLAYER_YELLOWCARDS_5_last_match_sum,PLAYER_ACCURATE_CROSSES_5_last_match_average,PLAYER_ACCURATE_PASSES_5_last_match_average,PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_average,PLAYER_AERIALS_WON_5_last_match_average,PLAYER_ASSISTS_5_last_match_average,PLAYER_BIG_CHANCES_CREATED_5_last_match_average,PLAYER_BIG_CHANCES_MISSED_5_last_match_average,PLAYER_BLOCKED_SHOTS_5_last_match_average,PLAYER_CLEARANCES_5_last_match_average,PLAYER_CLEARANCE_OFFLINE_5_last_match_average,PLAYER_DISPOSSESSED_5_last_match_average,PLAYER_DRIBBLED_ATTEMPTS_5_last_match_average,PLAYER_DRIBBLED_PAST_5_last_match_average,PLAYER_DUELS_LOST_5_last_match_average,PLAYER_DUELS_WON_5_last_match_average,PLAYER_ERROR_LEAD_TO_GOAL_5_last_match_average,PLAYER_FOULS_5_last_match_average,PLAYER_FOULS_DRAWN_5_last_match_average,PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_average,PLAYER_GOALS_5_last_match_average,PLAYER_GOALS_CONCEDED_5_last_match_average,PLAYER_HIT_WOODWORK_5_last_match_average,PLAYER_INTERCEPTIONS_5_last_match_average,PLAYER_KEY_PASSES_5_last_match_average,PLAYER_MINUTES_PLAYED_5_last_match_average,PLAYER_OFFSIDES_5_last_match_average,PLAYER_OWN_GOALS_5_last_match_average,PLAYER_PASSES_5_last_match_average,PLAYER_PENALTIES_COMMITTED_5_last_match_average,PLAYER_PENALTIES_MISSES_5_last_match_average,PLAYER_PENALTIES_SAVED_5_last_match_average,PLAYER_PENALTIES_SCORED_5_last_match_average,PLAYER_PENALTIES_WON_5_last_match_average,PLAYER_RATING_5_last_match_average,PLAYER_REDCARDS_5_last_match_average,PLAYER_SAVES_5_last_match_average,PLAYER_SAVES_INSIDE_BOX_5_last_match_average,PLAYER_SHOTS_BLOCKED_5_last_match_average,PLAYER_SHOTS_ON_TARGET_5_last_match_average,PLAYER_SHOTS_TOTAL_5_last_match_average,PLAYER_STARTING_LINEUP_5_last_match_average,PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_average,PLAYER_TACKLES_5_last_match_average,PLAYER_TOTAL_CROSSES_5_last_match_average,PLAYER_TOTAL_DUELS_5_last_match_average,PLAYER_YELLOWCARDS_5_last_match_average,PLAYER_ACCURATE_CROSSES_5_last_match_std,PLAYER_ACCURATE_PASSES_5_last_match_std,PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_std,PLAYER_AERIALS_WON_5_last_match_std,PLAYER_ASSISTS_5_last_match_std,PLAYER_BIG_CHANCES_CREATED_5_last_match_std,PLAYER_BIG_CHANCES_MISSED_5_last_match_std,PLAYER_BLOCKED_SHOTS_5_last_match_std,PLAYER_CLEARANCES_5_last_match_std,PLAYER_CLEARANCE_OFFLINE_5_last_match_std,PLAYER_DISPOSSESSED_5_last_match_std,PLAYER_DRIBBLED_ATTEMPTS_5_last_match_std,PLAYER_DRIBBLED_PAST_5_last_match_std,PLAYER_DUELS_LOST_5_last_match_std,PLAYER_DUELS_WON_5_last_match_std,PLAYER_ERROR_LEAD_TO_GOAL_5_last_match_std,PLAYER_FOULS_5_last_match_std,PLAYER_FOULS_DRAWN_5_last_match_std,PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_std,PLAYER_GOALS_5_last_match_std,PLAYER_GOALS_CONCEDED_5_last_match_std,PLAYER_HIT_WOODWORK_5_last_match_std,PLAYER_INTERCEPTIONS_5_last_match_std,PLAYER_KEY_PASSES_5_last_match_std,PLAYER_MINUTES_PLAYED_5_last_match_std,PLAYER_OFFSIDES_5_last_match_std,PLAYER_OWN_GOALS_5_last_match_std,PLAYER_PASSES_5_last_match_std,PLAYER_PENALTIES_COMMITTED_5_last_match_std,PLAYER_PENALTIES_MISSES_5_last_match_std,PLAYER_PENALTIES_SAVED_5_last_match_std,PLAYER_PENALTIES_SCORED_5_last_match_std,PLAYER_PENALTIES_WON_5_last_match_std,PLAYER_RATING_5_last_match_std,PLAYER_REDCARDS_5_last_match_std,PLAYER_SAVES_5_last_match_std,PLAYER_SAVES_INSIDE_BOX_5_last_match_std,PLAYER_SHOTS_BLOCKED_5_last_match_std,PLAYER_SHOTS_ON_TARGET_5_last_match_std,PLAYER_SHOTS_TOTAL_5_last_match_std,PLAYER_STARTING_LINEUP_5_last_match_std,PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_std,PLAYER_TACKLES_5_last_match_std,PLAYER_TOTAL_CROSSES_5_last_match_std,PLAYER_TOTAL_DUELS_5_last_match_std,PLAYER_YELLOWCARDS_5_last_match_std
0,0,Ligue 1,Olympique Marseille,Lucas Perrin,0.00,19.00,20.00,0.00,0.00,12.00,6.00,18.00,0.00,0.00,5.00,23.00,20.00,23.00,0.00,28.00,13.00,0.00,0.00,16.00,0.00,34.00,0.00,23.00,0.00,0.00,20.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,6.00,0.00,4.00,23.00,12.00,9.00,0.00,23.00,40.00,0.00,53.00,85.00,57.00,0.00,0.00,25.00,17.00,44.00,0.00,0.00,9.00,55.00,61.00,59.00,0.00,56.00,30.00,0.00,0.00,25.00,0.00,62.00,0.00,75.00,0.00,0.00,56.00,0.00,0.00,0.00,0.00,0.00,65.00,0.00,0.00,0.00,20.00,0.00,9.00,75.00,16.00,31.00,0.00,70.00,50.00,0.00,67.00,12.00,71.00,0.00,0.00,32.00,30.00,59.00,0.00,0.00,19.00,50.00,62.00,63.00,0.00,55.00,33.00,0.00,0.00,49.00,0.00,67.00,0.00,70.00,0.00,0.00,71.00,0.00,0.00,0.00,0.00,0.00,64.00,0.00,0.00,0.00,30.00,0.00,41.00,70.00,33.00,51.00,0.00,79.00,99.00,0.00,39.00,40.00,0.00,0.00,14.00,12.00,35.00,0.00,0.00,7.00,35.00,42.00,42.00,0.00,52.00,25.00,0.00,0.00,30.00,0.00,66.00,0.00,60.00,0.00,0.00,41.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,12.00,0.00,7.00,60.00,13.00,20.00,0.00,52.00,50.00,0.00,49.00,85.00,50.00,0.00,0.00,17.00,15.00,44.00,0.00,0.00,9.00,44.00,53.00,53.00,0.00,56.00,31.00,0.00,0.00,25.00,0.00,62.00,0.00,75.00,0.00,0.00,52.00,0.00,0.00,0.00,0.00,0.00,61.00,0.00,0.00,0.00,15.00,0.00,9.00,75.00,16.00,26.00,0.00,66.00,50.00,0.00,60.00,9.00,60.00,0.00,0.00,29.00,27.00,42.00,0.00,0.00,19.00,46.00,83.00,63.00,0.00,55.00,33.00,0.00,0.00,49.00,0.00,67.00,0.00,70.00,0.00,0.00,60.00,0.00,0.00,0.00,0.00,0.00,64.00,0.00,0.00,0.00,24.00,0.00,32.00,70.00,30.00,46.00,0.00,79.00,99.00
1,0,Ligue 1,Olympique Marseille,Kevin Strootman,2.00,48.00,19.00,28.00,8.00,12.00,6.00,21.00,0.00,4.00,3.00,47.00,39.00,37.00,0.00,56.00,18.00,0.00,11.00,52.00,25.00,24.00,24.00,72.00,6.00,0.00,51.00,0.00,0.00,0.00,33.00,0.00,0.00,0.00,0.00,20.00,5.00,16.00,69.00,4.00,40.00,3.00,41.00,80.00,2.00,44.00,79.00,17.00,16.00,8.00,8.00,5.00,17.00,0.00,4.00,2.00,37.00,39.00,31.00,0.00,37.00,14.00,0.00,10.00,27.00,20.00,14.00,21.00,78.00,7.00,0.00,47.00,0.00,0.00,0.00,33.00,0.00,79.00,0.00,0.00,0.00,20.00,3.00,10.00,75.00,1.00,43.00,2.00,41.00,33.00,12.00,48.00,41.00,37.00,40.00,25.00,18.00,17.00,36.00,0.00,24.00,8.00,44.00,32.00,41.00,0.00,40.00,34.00,0.00,31.00,45.00,45.00,25.00,34.00,53.00,23.00,0.00,50.00,0.00,0.00,0.00,63.00,0.00,37.00,0.00,0.00,0.00,27.00,14.00,33.00,63.00,10.00,43.00,12.00,41.00,85.00,0.00,32.00,0.00,16.00,0.00,0.00,0.00,20.00,0.00,9.00,2.00,35.00,34.00,14.00,0.00,47.00,10.00,0.00,20.00,46.00,0.00,6.00,13.00,65.00,12.00,0.00,35.00,0.00,0.00,0.00,100.00,0.00,0.00,0.00,0.00,12.00,7.00,7.00,60.00,0.00,29.00,2.00,30.00,25.00,0.00,32.00,75.00,0.00,16.00,0.00,0.00,0.00,20.00,0.00,9.00,2.00,35.00,34.00,14.00,0.00,40.00,10.00,0.00,20.00,30.00,0.00,5.00,13.00,65.00,12.00,0.00,35.00,0.00,0.00,0.00,100.00,0.00,65.00,0.00,0.00,0.00,12.00,7.00,7.00,60.00,0.00,29.00,1.00,30.00,20.00,0.00,46.00,41.00,0.00,40.00,0.00,0.00,0.00,37.00,0.00,32.00,9.00,52.00,58.00,29.00,0.00,43.00,18.00,0.00,50.00,57.00,0.00,12.00,18.00,67.00,34.00,0.00,47.00,0.00,0.00,0.00,99.00,0.00,57.00,0.00,0.00,0.00,21.00,20.00,17.00,77.00,0.00,40.00,6.00,46.00,77.00

In [206]:
home_team_processed["ID"].value_counts().head()

ID
0.00       1
8458.00    1
8196.00    1
8197.00    1
8198.00    1
Name: count, dtype: int64

In [207]:
away_team_processed["ID"].value_counts().head()

ID
0.00       1
8458.00    1
8196.00    1
8197.00    1
8198.00    1
Name: count, dtype: int64

In [208]:
home_player_processed["ID"].value_counts().head()

ID
5515     25
6569     24
7220     24
11697    24
1983     24
Name: count, dtype: int64

In [209]:
away_player_processed["ID"].value_counts().head()

ID
1642     23
5824     23
11489    23
4665     23
11491    23
Name: count, dtype: int64

In [210]:
home_player_agg = (
    home_player_processed
    .groupby(["ID", "LEAGUE", "TEAM_NAME"], as_index=False)
    .mean(numeric_only=True)
)

home_player_agg.shape

(12303, 275)

In [211]:
away_player_agg = (
    away_player_processed
    .groupby(["ID", "LEAGUE", "TEAM_NAME"], as_index=False)
    .mean(numeric_only=True)
)

away_player_agg.shape

(12303, 275)

In [212]:
home_player_agg.shape
away_player_agg.shape

(12303, 275)

In [213]:
home_team_merge = home_team_processed.copy()

home_team_merge = home_team_merge.rename(
    columns=lambda x: "HOME_" + x
    if x not in ["ID", "LEAGUE"]
    else x
)

In [214]:
away_team_merge = away_team_processed.copy()

away_team_merge = away_team_merge.rename(
    columns=lambda x: "AWAY_" + x
    if x not in ["ID", "LEAGUE"]
    else x
)

In [215]:
home_player_merge = home_player_agg.copy()

home_player_merge = home_player_merge.rename(
    columns=lambda x: "HOME_" + x
    if x not in ["ID", "LEAGUE"]
    else x
)

In [216]:
away_player_merge = away_player_agg.copy()

away_player_merge = away_player_merge.rename(
    columns=lambda x: "AWAY_" + x
    if x not in ["ID", "LEAGUE"]
    else x
)

In [217]:
print(home_team_merge.columns[:10])

print(away_team_merge.columns[:10])

print(home_player_merge.columns[:10])

print(away_player_merge.columns[:10])

Index(['ID', 'LEAGUE', 'HOME_TEAM_NAME', 'HOME_TEAM_SHOTS_TOTAL_season_sum',
       'HOME_TEAM_SHOTS_INSIDEBOX_season_sum',
       'HOME_TEAM_SHOTS_OFF_TARGET_season_sum',
       'HOME_TEAM_SHOTS_ON_TARGET_season_sum',
       'HOME_TEAM_SHOTS_OUTSIDEBOX_season_sum', 'HOME_TEAM_PASSES_season_sum',
       'HOME_TEAM_SUCCESSFUL_PASSES_season_sum'],
      dtype='object')
Index(['ID', 'LEAGUE', 'AWAY_TEAM_NAME', 'AWAY_TEAM_SHOTS_TOTAL_season_sum',
       'AWAY_TEAM_SHOTS_INSIDEBOX_season_sum',
       'AWAY_TEAM_SHOTS_OFF_TARGET_season_sum',
       'AWAY_TEAM_SHOTS_ON_TARGET_season_sum',
       'AWAY_TEAM_SHOTS_OUTSIDEBOX_season_sum', 'AWAY_TEAM_PASSES_season_sum',
       'AWAY_TEAM_SUCCESSFUL_PASSES_season_sum'],
      dtype='object')
Index(['ID', 'LEAGUE', 'HOME_TEAM_NAME',
       'HOME_PLAYER_ACCURATE_CROSSES_season_sum',
       'HOME_PLAYER_ACCURATE_PASSES_season_sum',
       'HOME_PLAYER_AERIALS_WON_season_sum', 'HOME_PLAYER_ASSISTS_season_sum',
       'HOME_PLAYER_BIG_CHANCES_CREATED_season_sum',
       'HOME_PLAYER_BIG_CHANCES_MISSED_season_sum',
       'HOME_PLAYER_BLOCKED_SHOTS_season_sum'],
      dtype='object')
Index(['ID', 'LEAGUE', 'AWAY_TEAM_NAME',
       'AWAY_PLAYER_ACCURATE_CROSSES_season_sum',
       'AWAY_PLAYER_ACCURATE_PASSES_season_sum',
       'AWAY_PLAYER_AERIALS_WON_season_sum', 'AWAY_PLAYER_ASSISTS_season_sum',
       'AWAY_PLAYER_BIG_CHANCES_CREATED_season_sum',
       'AWAY_PLAYER_BIG_CHANCES_MISSED_season_sum',
       'AWAY_PLAYER_BLOCKED_SHOTS_season_sum'],
      dtype='object')

### Merging Home team and Away Team

In [218]:
match_data = home_team_merge.merge(
    away_team_merge,
    on=["ID", "LEAGUE"],
    how="inner"
)

print(match_data.shape)

(12303, 284)

### Merging Home Player

In [219]:
match_data = match_data.merge(
    home_player_merge,
    on=["ID", "LEAGUE"],
    how="inner"
)

print(match_data.shape)

(12303, 557)

### Merging Away Player

In [220]:
match_data = match_data.merge(
    away_player_merge,
    on=["ID", "LEAGUE"],
    how="inner"
)

print(match_data.shape)

(12303, 830)

In [221]:
print(match_data.shape)

match_data.head(2)

(12303, 830)

,ID,LEAGUE,HOME_TEAM_NAME_x,HOME_TEAM_SHOTS_TOTAL_season_sum,HOME_TEAM_SHOTS_INSIDEBOX_season_sum,HOME_TEAM_SHOTS_OFF_TARGET_season_sum,HOME_TEAM_SHOTS_ON_TARGET_season_sum,HOME_TEAM_SHOTS_OUTSIDEBOX_season_sum,HOME_TEAM_PASSES_season_sum,HOME_TEAM_SUCCESSFUL_PASSES_season_sum,HOME_TEAM_SAVES_season_sum,HOME_TEAM_CORNERS_season_sum,HOME_TEAM_FOULS_season_sum,HOME_TEAM_YELLOWCARDS_season_sum,HOME_TEAM_REDCARDS_season_sum,HOME_TEAM_OFFSIDES_season_sum,HOME_TEAM_ATTACKS_season_sum,HOME_TEAM_PENALTIES_season_sum,HOME_TEAM_SUBSTITUTIONS_season_sum,HOME_TEAM_BALL_SAFE_season_sum,HOME_TEAM_DANGEROUS_ATTACKS_season_sum,HOME_TEAM_INJURIES_season_sum,HOME_TEAM_GOALS_season_sum,HOME_TEAM_GAME_WON_season_sum,HOME_TEAM_GAME_DRAW_season_sum,HOME_TEAM_GAME_LOST_season_sum,HOME_TEAM_SHOTS_TOTAL_season_average,HOME_TEAM_SHOTS_INSIDEBOX_season_average,HOME_TEAM_SHOTS_OFF_TARGET_season_average,HOME_TEAM_SHOTS_ON_TARGET_season_average,HOME_TEAM_SHOTS_OUTSIDEBOX_season_average,HOME_TEAM_PASSES_season_average,HOME_TEAM_SUCCESSFUL_PASSES_season_average,HOME_TEAM_SUCCESSFUL_PASSES_PERCENTAGE_season_average,HOME_TEAM_SAVES_season_average,HOME_TEAM_CORNERS_season_average,HOME_TEAM_BALL_POSSESSION_season_average,HOME_TEAM_FOULS_season_average,HOME_TEAM_YELLOWCARDS_season_average,HOME_TEAM_REDCARDS_season_average,HOME_TEAM_OFFSIDES_season_average,HOME_TEAM_ATTACKS_season_average,HOME_TEAM_PENALTIES_season_average,HOME_TEAM_SUBSTITUTIONS_season_average,HOME_TEAM_BALL_SAFE_season_average,HOME_TEAM_DANGEROUS_ATTACKS_season_average,HOME_TEAM_INJURIES_season_average,HOME_TEAM_GOALS_season_average,HOME_TEAM_GAME_WON_season_average,HOME_TEAM_GAME_DRAW_season_average,HOME_TEAM_GAME_LOST_season_average,HOME_TEAM_SHOTS_TOTAL_season_std,HOME_TEAM_SHOTS_INSIDEBOX_season_std,HOME_TEAM_SHOTS_OFF_TARGET_season_std,HOME_TEAM_SHOTS_ON_TARGET_season_std,HOME_TEAM_SHOTS_OUTSIDEBOX_season_std,HOME_TEAM_PASSES_season_std,HOME_TEAM_SUCCESSFUL_PASSES_season_std,HOME_TEAM_SUCCESSFUL_PASSES_PERCENTAGE_season_std,HOME_TEAM_SAVES_season_std,HOME_TEAM_CORNERS_season_std,HOME_TEAM_BALL_POSSESSION_season_std,HOME_TEAM_FOULS_season_std,HOME_TEAM_YELLOWCARDS_season_std,HOME_TEAM_REDCARDS_season_std,HOME_TEAM_OFFSIDES_season_std,HOME_TEAM_ATTACKS_season_std,HOME_TEAM_PENALTIES_season_std,HOME_TEAM_SUBSTITUTIONS_season_std,HOME_TEAM_BALL_SAFE_season_std,HOME_TEAM_DANGEROUS_ATTACKS_season_std,HOME_TEAM_INJURIES_season_std,HOME_TEAM_GOALS_season_std,HOME_TEAM_SHOTS_TOTAL_5_last_match_sum,HOME_TEAM_SHOTS_INSIDEBOX_5_last_match_sum,HOME_TEAM_SHOTS_OFF_TARGET_5_last_match_sum,HOME_TEAM_SHOTS_ON_TARGET_5_last_match_sum,HOME_TEAM_SHOTS_OUTSIDEBOX_5_last_match_sum,HOME_TEAM_PASSES_5_last_match_sum,HOME_TEAM_SUCCESSFUL_PASSES_5_last_match_sum,HOME_TEAM_SAVES_5_last_match_sum,HOME_TEAM_CORNERS_5_last_match_sum,HOME_TEAM_FOULS_5_last_match_sum,HOME_TEAM_YELLOWCARDS_5_last_match_sum,HOME_TEAM_REDCARDS_5_last_match_sum,HOME_TEAM_OFFSIDES_5_last_match_sum,HOME_TEAM_ATTACKS_5_last_match_sum,HOME_TEAM_PENALTIES_5_last_match_sum,HOME_TEAM_SUBSTITUTIONS_5_last_match_sum,HOME_TEAM_BALL_SAFE_5_last_match_sum,HOME_TEAM_DANGEROUS_ATTACKS_5_last_match_sum,HOME_TEAM_INJURIES_5_last_match_sum,HOME_TEAM_GOALS_5_last_match_sum,HOME_TEAM_GAME_WON_5_last_match_sum,HOME_TEAM_GAME_DRAW_5_last_match_sum,HOME_TEAM_GAME_LOST_5_last_match_sum,HOME_TEAM_SHOTS_TOTAL_5_last_match_average,HOME_TEAM_SHOTS_INSIDEBOX_5_last_match_average,HOME_TEAM_SHOTS_OFF_TARGET_5_last_match_average,HOME_TEAM_SHOTS_ON_TARGET_5_last_match_average,HOME_TEAM_SHOTS_OUTSIDEBOX_5_last_match_average,HOME_TEAM_PASSES_5_last_match_average,HOME_TEAM_SUCCESSFUL_PASSES_5_last_match_average,HOME_TEAM_SUCCESSFUL_PASSES_PERCENTAGE_5_last_match_average,HOME_TEAM_SAVES_5_last_match_average,HOME_TEAM_CORNERS_5_last_match_average,HOME_TEAM_BALL_POSSESSION_5_last_match_average,HOME_TEAM_FOULS_5_last_match_average,HOME_TEAM_YELLOWCARDS_5_last_match_average,HOME_TEAM_REDCARDS_5_last_match_average,HOME_TEAM_OFFSIDES_5_last_match_average,HOME_TEAM_ATTACKS_5_last_match_average,HOME_TEAM_PENALTIES_5_last_match_average,HOME_TEAM_SUBSTITUTIONS_5_last_match_average,HOME_TEAM_BALL_SAFE_5_last_match_average,HOME_TEAM_DANGEROUS_ATTACKS_5_last_match_average,HOME_TEAM_INJURIES_5_last_match_average,HOME_TEAM_GOALS_5_last_match_average,HOME_TEAM_GAME_WON_5_last_match_average,HOME_TEAM_GAME_DRAW_5_last_match_average,HOME_TEAM_GAME_LOST_5_last_match_average,HOME_TEAM_SHOTS_TOTAL_5_last_match_std,HOME_TEAM_SHOTS_INSIDEBOX_5_last_match_std,HOME_TEAM_SHOTS_OFF_TARGET_5_last_match_std,HOME_TEAM_SHOTS_ON_TARGET_5_last_match_std,HOME_TEAM_SHOTS_OUTSIDEBOX_5_last_match_std,HOME_TEAM_PASSES_5_last_match_std,HOME_TEAM_SUCCESSFUL_PASSES_5_last_match_std,HOME_TEAM_SUCCESSFUL_PASSES_PERCENTAGE_5_last_match_std,HOME_TEAM_SAVES_5_last_match_std,HOME_TEAM_CORNERS_5_last_match_std,HOME_TEAM_BALL_POSSESSION_5_last_match_std,HOME_TEAM_FOULS_5_last_match_std,HOME_TEAM_YELLOWCARDS_5_last_match_std,HOME_TEAM_REDCARDS_5_last_match_std,HOME_TEAM_OFFSIDES_5_last_match_std,HOME_TEAM_ATTACKS_5_last_match_std,HOME_TEAM_PENALTIES_5_last_match_std,HOME_TEAM_SUBSTITUTIONS_5_last_match_std,HOME_TEAM_BALL_SAFE_5_last_match_std,HOME_TEAM_DANGEROUS_ATTACKS_5_last_match_std,HOME_TEAM_INJURIES_5_last_match_std,HOME_TEAM_GOALS_5_last_match_std,AWAY_TEAM_NAME_x,AWAY_TEAM_SHOTS_TOTAL_season_sum,AWAY_TEAM_SHOTS_INSIDEBOX_season_sum,AWAY_TEAM_SHOTS_OFF_TARGET_season_sum,AWAY_TEAM_SHOTS_ON_TARGET_season_sum,AWAY_TEAM_SHOTS_OUTSIDEBOX_season_sum,AWAY_TEAM_PASSES_season_sum,AWAY_TEAM_SUCCESSFUL_PASSES_season_sum,AWAY_TEAM_SAVES_season_sum,AWAY_TEAM_CORNERS_season_sum,AWAY_TEAM_FOULS_season_sum,AWAY_TEAM_YELLOWCARDS_season_sum,AWAY_TEAM_REDCARDS_season_sum,AWAY_TEAM_OFFSIDES_season_sum,AWAY_TEAM_ATTACKS_season_sum,AWAY_TEAM_PENALTIES_season_sum,AWAY_TEAM_SUBSTITUTIONS_season_sum,AWAY_TEAM_BALL_SAFE_season_sum,AWAY_TEAM_DANGEROUS_ATTACKS_season_sum,AWAY_TEAM_INJURIES_season_sum,AWAY_TEAM_GOALS_season_sum,AWAY_TEAM_GAME_WON_season_sum,AWAY_TEAM_GAME_DRAW_season_sum,AWAY_TEAM_GAME_LOST_season_sum,AWAY_TEAM_SHOTS_TOTAL_season_average,AWAY_TEAM_SHOTS_INSIDEBOX_season_average,AWAY_TEAM_SHOTS_OFF_TARGET_season_average,AWAY_TEAM_SHOTS_ON_TARGET_season_average,AWAY_TEAM_SHOTS_OUTSIDEBOX_season_average,AWAY_TEAM_PASSES_season_average,AWAY_TEAM_SUCCESSFUL_PASSES_season_average,AWAY_TEAM_SUCCESSFUL_PASSES_PERCENTAGE_season_average,AWAY_TEAM_SAVES_season_average,AWAY_TEAM_CORNERS_season_average,AWAY_TEAM_BALL_POSSESSION_season_average,AWAY_TEAM_FOULS_season_average,AWAY_TEAM_YELLOWCARDS_season_average,AWAY_TEAM_REDCARDS_season_average,AWAY_TEAM_OFFSIDES_season_average,AWAY_TEAM_ATTACKS_season_average,AWAY_TEAM_PENALTIES_season_average,AWAY_TEAM_SUBSTITUTIONS_season_average,AWAY_TEAM_BALL_SAFE_season_average,AWAY_TEAM_DANGEROUS_ATTACKS_season_average,AWAY_TEAM_INJURIES_season_average,AWAY_TEAM_GOALS_season_average,AWAY_TEAM_GAME_WON_season_average,AWAY_TEAM_GAME_DRAW_season_average,AWAY_TEAM_GAME_LOST_season_average,AWAY_TEAM_SHOTS_TOTAL_season_std,AWAY_TEAM_SHOTS_INSIDEBOX_season_std,AWAY_TEAM_SHOTS_OFF_TARGET_season_std,AWAY_TEAM_SHOTS_ON_TARGET_season_std,AWAY_TEAM_SHOTS_OUTSIDEBOX_season_std,AWAY_TEAM_PASSES_season_std,AWAY_TEAM_SUCCESSFUL_PASSES_season_std,AWAY_TEAM_SUCCESSFUL_PASSES_PERCENTAGE_season_std,AWAY_TEAM_SAVES_season_std,AWAY_TEAM_CORNERS_season_std,AWAY_TEAM_BALL_POSSESSION_season_std,AWAY_TEAM_FOULS_season_std,AWAY_TEAM_YELLOWCARDS_season_std,AWAY_TEAM_REDCARDS_season_std,AWAY_TEAM_OFFSIDES_season_std,AWAY_TEAM_ATTACKS_season_std,AWAY_TEAM_PENALTIES_season_std,AWAY_TEAM_SUBSTITUTIONS_season_std,AWAY_TEAM_BALL_SAFE_season_std,AWAY_TEAM_DANGEROUS_ATTACKS_season_std,AWAY_TEAM_INJURIES_season_std,AWAY_TEAM_GOALS_season_std,AWAY_TEAM_SHOTS_TOTAL_5_last_match_sum,AWAY_TEAM_SHOTS_INSIDEBOX_5_last_match_sum,AWAY_TEAM_SHOTS_OFF_TARGET_5_last_match_sum,AWAY_TEAM_SHOTS_ON_TARGET_5_last_match_sum,AWAY_TEAM_SHOTS_OUTSIDEBOX_5_last_match_sum,AWAY_TEAM_PASSES_5_last_match_sum,AWAY_TEAM_SUCCESSFUL_PASSES_5_last_match_sum,AWAY_TEAM_SAVES_5_last_match_sum,AWAY_TEAM_CORNERS_5_last_match_sum,AWAY_TEAM_FOULS_5_last_match_sum,AWAY_TEAM_YELLOWCARDS_5_last_match_sum,AWAY_TEAM_REDCARDS_5_last_match_sum,AWAY_TEAM_OFFSIDES_5_last_match_sum,AWAY_TEAM_ATTACKS_5_last_match_sum,AWAY_TEAM_PENALTIES_5_last_match_sum,AWAY_TEAM_SUBSTITUTIONS_5_last_match_sum,AWAY_TEAM_BALL_SAFE_5_last_match_sum,AWAY_TEAM_DANGEROUS_ATTACKS_5_last_match_sum,AWAY_TEAM_INJURIES_5_last_match_sum,AWAY_TEAM_GOALS_5_last_match_sum,AWAY_TEAM_GAME_WON_5_last_match_sum,AWAY_TEAM_GAME_DRAW_5_last_match_sum,AWAY_TEAM_GAME_LOST_5_last_match_sum,AWAY_TEAM_SHOTS_TOTAL_5_last_match_average,AWAY_TEAM_SHOTS_INSIDEBOX_5_last_match_average,AWAY_TEAM_SHOTS_OFF_TARGET_5_last_match_average,AWAY_TEAM_SHOTS_ON_TARGET_5_last_match_average,AWAY_TEAM_SHOTS_OUTSIDEBOX_5_last_match_average,AWAY_TEAM_PASSES_5_last_match_average,AWAY_TEAM_SUCCESSFUL_PASSES_5_last_match_average,AWAY_TEAM_SUCCESSFUL_PASSES_PERCENTAGE_5_last_match_average,AWAY_TEAM_SAVES_5_last_match_average,AWAY_TEAM_CORNERS_5_last_match_average,AWAY_TEAM_BALL_POSSESSION_5_last_match_average,AWAY_TEAM_FOULS_5_last_match_average,AWAY_TEAM_YELLOWCARDS_5_last_match_average,AWAY_TEAM_REDCARDS_5_last_match_average,AWAY_TEAM_OFFSIDES_5_last_match_average,AWAY_TEAM_ATTACKS_5_last_match_average,AWAY_TEAM_PENALTIES_5_last_match_average,AWAY_TEAM_SUBSTITUTIONS_5_last_match_average,AWAY_TEAM_BALL_SAFE_5_last_match_average,AWAY_TEAM_DANGEROUS_ATTACKS_5_last_match_average,AWAY_TEAM_INJURIES_5_last_match_average,AWAY_TEAM_GOALS_5_last_match_average,AWAY_TEAM_GAME_WON_5_last_match_average,AWAY_TEAM_GAME_DRAW_5_last_match_average,AWAY_TEAM_GAME_LOST_5_last_match_average,AWAY_TEAM_SHOTS_TOTAL_5_last_match_std,AWAY_TEAM_SHOTS_INSIDEBOX_5_last_match_std,AWAY_TEAM_SHOTS_OFF_TARGET_5_last_match_std,AWAY_TEAM_SHOTS_ON_TARGET_5_last_match_std,AWAY_TEAM_SHOTS_OUTSIDEBOX_5_last_match_std,AWAY_TEAM_PASSES_5_last_match_std,AWAY_TEAM_SUCCESSFUL_PASSES_5_last_match_std,AWAY_TEAM_SUCCESSFUL_PASSES_PERCENTAGE_5_last_match_std,AWAY_TEAM_SAVES_5_last_match_std,AWAY_TEAM_CORNERS_5_last_match_std,AWAY_TEAM_BALL_POSSESSION_5_last_match_std,AWAY_TEAM_FOULS_5_last_match_std,AWAY_TEAM_YELLOWCARDS_5_last_match_std,AWAY_TEAM_REDCARDS_5_last_match_std,AWAY_TEAM_OFFSIDES_5_last_match_std,AWAY_TEAM_ATTACKS_5_last_match_std,AWAY_TEAM_PENALTIES_5_last_match_std,AWAY_TEAM_SUBSTITUTIONS_5_last_match_std,AWAY_TEAM_BALL_SAFE_5_last_match_std,AWAY_TEAM_DANGEROUS_ATTACKS_5_last_match_std,AWAY_TEAM_INJURIES_5_last_match_std,AWAY_TEAM_GOALS_5_last_match_std,HOME_TEAM_NAME_y,HOME_PLAYER_ACCURATE_CROSSES_season_sum,HOME_PLAYER_ACCURATE_PASSES_season_sum,HOME_PLAYER_AERIALS_WON_season_sum,HOME_PLAYER_ASSISTS_season_sum,HOME_PLAYER_BIG_CHANCES_CREATED_season_sum,HOME_PLAYER_BIG_CHANCES_MISSED_season_sum,HOME_PLAYER_BLOCKED_SHOTS_season_sum,HOME_PLAYER_CLEARANCES_season_sum,HOME_PLAYER_CLEARANCE_OFFLINE_season_sum,HOME_PLAYER_DISPOSSESSED_season_sum,HOME_PLAYER_DRIBBLED_ATTEMPTS_season_sum,HOME_PLAYER_DRIBBLED_PAST_season_sum,HOME_PLAYER_DUELS_LOST_season_sum,HOME_PLAYER_DUELS_WON_season_sum,HOME_PLAYER_ERROR_LEAD_TO_GOAL_season_sum,HOME_PLAYER_FOULS_season_sum,HOME_PLAYER_FOULS_DRAWN_season_sum,HOME_PLAYER_GOALKEEPER_GOALS_CONCEDED_season_sum,HOME_PLAYER_GOALS_season_sum,HOME_PLAYER_GOALS_CONCEDED_season_sum,HOME_PLAYER_HIT_WOODWORK_season_sum,HOME_PLAYER_INTERCEPTIONS_season_sum,HOME_PLAYER_KEY_PASSES_season_sum,HOME_PLAYER_MINUTES_PLAYED_season_sum,HOME_PLAYER_OFFSIDES_season_sum,HOME_PLAYER_OWN_GOALS_season_sum,HOME_PLAYER_PASSES_season_sum,HOME_PLAYER_PENALTIES_COMMITTED_season_sum,HOME_PLAYER_PENALTIES_MISSES_season_sum,HOME_PLAYER_PENALTIES_SAVED_season_sum,HOME_PLAYER_PENALTIES_SCORED_season_sum,HOME_PLAYER_PENALTIES_WON_season_sum,HOME_PLAYER_REDCARDS_season_sum,HOME_PLAYER_SAVES_season_sum,HOME_PLAYER_SAVES_INSIDE_BOX_season_sum,HOME_PLAYER_SHOTS_BLOCKED_season_sum,HOME_PLAYER_SHOTS_ON_TARGET_season_sum,HOME_PLAYER_SHOTS_TOTAL_season_sum,HOME_PLAYER_STARTING_LINEUP_season_sum,HOME_PLAYER_SUCCESSFUL_DRIBBLES_season_sum,HOME_PLAYER_TACKLES_season_sum,HOME_PLAYER_TOTAL_CROSSES_season_sum,HOME_PLAYER_TOTAL_DUELS_season_sum,HOME_PLAYER_YELLOWCARDS_season_sum,HOME_PLAYER_ACCURATE_CROSSES_season_average,HOME_PLAYER_ACCURATE_PASSES_season_average,HOME_PLAYER_ACCURATE_PASSES_PERCENTAGE_season_average,HOME_PLAYER_AERIALS_WON_season_average,HOME_PLAYER_ASSISTS_season_average,HOME_PLAYER_BIG_CHANCES_CREATED_season_average,HOME_PLAYER_BIG_CHANCES_MISSED_season_average,HOME_PLAYER_BLOCKED_SHOTS_season_average,HOME_PLAYER_CLEARANCES_season_average,HOME_PLAYER_CLEARANCE_OFFLINE_season_average,HOME_PLAYER_DISPOSSESSED_season_average,HOME_PLAYER_DRIBBLED_ATTEMPTS_season_average,HOME_PLAYER_DRIBBLED_PAST_season_average,HOME_PLAYER_DUELS_LOST_season_average,HOME_PLAYER_DUELS_WON_season_average,HOME_PLAYER_ERROR_LEAD_TO_GOAL_season_average,HOME_PLAYER_FOULS_season_average,HOME_PLAYER_FOULS_DRAWN_season_average,HOME_PLAYER_GOALKEEPER_GOALS_CONCEDED_season_average,HOME_PLAYER_GOALS_season_average,HOME_PLAYER_GOALS_CONCEDED_season_average,HOME_PLAYER_HIT_WOODWORK_season_average,HOME_PLAYER_INTERCEPTIONS_season_average,HOME_PLAYER_KEY_PASSES_season_average,HOME_PLAYER_MINUTES_PLAYED_season_average,HOME_PLAYER_OFFSIDES_season_average,HOME_PLAYER_OWN_GOALS_season_average,HOME_PLAYER_PASSES_season_average,HOME_PLAYER_PENALTIES_COMMITTED_season_average,HOME_PLAYER_PENALTIES_MISSES_season_average,HOME_PLAYER_PENALTIES_SAVED_season_average,HOME_PLAYER_PENALTIES_SCORED_season_average,HOME_PLAYER_PENALTIES_WON_season_average,HOME_PLAYER_RATING_season_average,HOME_PLAYER_REDCARDS_season_average,HOME_PLAYER_SAVES_season_average,HOME_PLAYER_SAVES_INSIDE_BOX_season_average,HOME_PLAYER_SHOTS_BLOCKED_season_average,HOME_PLAYER_SHOTS_ON_TARGET_season_average,HOME_PLAYER_SHOTS_TOTAL_season_average,HOME_PLAYER_STARTING_LINEUP_season_average,HOME_PLAYER_SUCCESSFUL_DRIBBLES_season_average,HOME_PLAYER_TACKLES_season_average,HOME_PLAYER_TOTAL_CROSSES_season_average,HOME_PLAYER_TOTAL_DUELS_season_average,HOME_PLAYER_YELLOWCARDS_season_average,HOME_PLAYER_ACCURATE_CROSSES_season_std,HOME_PLAYER_ACCURATE_PASSES_season_std,HOME_PLAYER_ACCURATE_PASSES_PERCENTAGE_season_std,HOME_PLAYER_AERIALS_WON_season_std,HOME_PLAYER_ASSISTS_season_std,HOME_PLAYER_BIG_CHANCES_CREATED_season_std,HOME_PLAYER_BIG_CHANCES_MISSED_season_std,HOME_PLAYER_BLOCKED_SHOTS_season_std,HOME_PLAYER_CLEARANCES_season_std,HOME_PLAYER_CLEARANCE_OFFLINE_season_std,HOME_PLAYER_DISPOSSESSED_season_std,HOME_PLAYER_DRIBBLED_ATTEMPTS_season_std,HOME_PLAYER_DRIBBLED_PAST_season_std,HOME_PLAYER_DUELS_LOST_season_std,HOME_PLAYER_DUELS_WON_season_std,HOME_PLAYER_ERROR_LEAD_TO_GOAL_season_std,HOME_PLAYER_FOULS_season_std,HOME_PLAYER_FOULS_DRAWN_season_std,HOME_PLAYER_GOALKEEPER_GOALS_CONCEDED_season_std,HOME_PLAYER_GOALS_season_std,HOME_PLAYER_GOALS_CONCEDED_season_std,HOME_PLAYER_HIT_WOODWORK_season_std,HOME_PLAYER_INTERCEPTIONS_season_std,HOME_PLAYER_KEY_PASSES_season_std,HOME_PLAYER_MINUTES_PLAYED_season_std,HOME_PLAYER_OFFSIDES_season_std,HOME_PLAYER_OWN_GOALS_season_std,HOME_PLAYER_PASSES_season_std,HOME_PLAYER_PENALTIES_COMMITTED_season_std,HOME_PLAYER_PENALTIES_MISSES_season_std,HOME_PLAYER_PENALTIES_SAVED_season_std,HOME_PLAYER_PENALTIES_SCORED_season_std,HOME_PLAYER_PENALTIES_WON_season_std,HOME_PLAYER_RATING_season_std,HOME_PLAYER_REDCARDS_season_std,HOME_PLAYER_SAVES_season_std,HOME_PLAYER_SAVES_INSIDE_BOX_season_std,HOME_PLAYER_SHOTS_BLOCKED_season_std,HOME_PLAYER_SHOTS_ON_TARGET_season_std,HOME_PLAYER_SHOTS_TOTAL_season_std,HOME_PLAYER_STARTING_LINEUP_season_std,HOME_PLAYER_SUCCESSFUL_DRIBBLES_season_std,HOME_PLAYER_TACKLES_season_std,HOME_PLAYER_TOTAL_CROSSES_season_std,HOME_PLAYER_TOTAL_DUELS_season_std,HOME_PLAYER_YELLOWCARDS_season_std,HOME_PLAYER_ACCURATE_CROSSES_5_last_match_sum,HOME_PLAYER_ACCURATE_PASSES_5_last_match_sum,HOME_PLAYER_AERIALS_WON_5_last_match_sum,HOME_PLAYER_ASSISTS_5_last_match_sum,HOME_PLAYER_BIG_CHANCES_CREATED_5_last_match_sum,HOME_PLAYER_BIG_CHANCES_MISSED_5_last_match_sum,HOME_PLAYER_BLOCKED_SHOTS_5_last_match_sum,HOME_PLAYER_CLEARANCES_5_last_match_sum,HOME_PLAYER_CLEARANCE_OFFLINE_5_last_match_sum,HOME_PLAYER_DISPOSSESSED_5_last_match_sum,HOME_PLAYER_DRIBBLED_ATTEMPTS_5_last_match_sum,HOME_PLAYER_DRIBBLED_PAST_5_last_match_sum,HOME_PLAYER_DUELS_LOST_5_last_match_sum,HOME_PLAYER_DUELS_WON_5_last_match_sum,HOME_PLAYER_ERROR_LEAD_TO_GOAL_5_last_match_sum,HOME_PLAYER_FOULS_5_last_match_sum,HOME_PLAYER_FOULS_DRAWN_5_last_match_sum,HOME_PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_sum,HOME_PLAYER_GOALS_5_last_match_sum,HOME_PLAYER_GOALS_CONCEDED_5_last_match_sum,HOME_PLAYER_HIT_WOODWORK_5_last_match_sum,HOME_PLAYER_INTERCEPTIONS_5_last_match_sum,HOME_PLAYER_KEY_PASSES_5_last_match_sum,HOME_PLAYER_MINUTES_PLAYED_5_last_match_sum,HOME_PLAYER_OFFSIDES_5_last_match_sum,HOME_PLAYER_OWN_GOALS_5_last_match_sum,HOME_PLAYER_PASSES_5_last_match_sum,HOME_PLAYER_PENALTIES_COMMITTED_5_last_match_sum,HOME_PLAYER_PENALTIES_MISSES_5_last_match_sum,HOME_PLAYER_PENALTIES_SAVED_5_last_match_sum,HOME_PLAYER_PENALTIES_SCORED_5_last_match_sum,HOME_PLAYER_PENALTIES_WON_5_last_match_sum,HOME_PLAYER_REDCARDS_5_last_match_sum,HOME_PLAYER_SAVES_5_last_match_sum,HOME_PLAYER_SAVES_INSIDE_BOX_5_last_match_sum,HOME_PLAYER_SHOTS_BLOCKED_5_last_match_sum,HOME_PLAYER_SHOTS_ON_TARGET_5_last_match_sum,HOME_PLAYER_SHOTS_TOTAL_5_last_match_sum,HOME_PLAYER_STARTING_LINEUP_5_last_match_sum,HOME_PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_sum,HOME_PLAYER_TACKLES_5_last_match_sum,HOME_PLAYER_TOTAL_CROSSES_5_last_match_sum,HOME_PLAYER_TOTAL_DUELS_5_last_match_sum,HOME_PLAYER_YELLOWCARDS_5_last_match_sum,HOME_PLAYER_ACCURATE_CROSSES_5_last_match_average,HOME_PLAYER_ACCURATE_PASSES_5_last_match_average,HOME_PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_average,HOME_PLAYER_AERIALS_WON_5_last_match_average,HOME_PLAYER_ASSISTS_5_last_match_average,HOME_PLAYER_BIG_CHANCES_CREATED_5_last_match_average,HOME_PLAYER_BIG_CHANCES_MISSED_5_last_match_average,HOME_PLAYER_BLOCKED_SHOTS_5_last_match_average,HOME_PLAYER_CLEARANCES_5_last_match_average,HOME_PLAYER_CLEARANCE_OFFLINE_5_last_match_average,HOME_PLAYER_DISPOSSESSED_5_last_match_average,HOME_PLAYER_DRIBBLED_ATTEMPTS_5_last_match_average,HOME_PLAYER_DRIBBLED_PAST_5_last_match_average,HOME_PLAYER_DUELS_LOST_5_last_match_average,HOME_PLAYER_DUELS_WON_5_last_match_average,HOME_PLAYER_ERROR_LEAD_TO_GOAL_5_last_match_average,HOME_PLAYER_FOULS_5_last_match_average,HOME_PLAYER_FOULS_DRAWN_5_last_match_average,HOME_PLAYER_GOALKEEPER_GOALS_CONCEDED_5_last_match_average,HOME_PLAYER_GOALS_5_last_match_average,HOME_PLAYER_GOALS_CONCEDED_5_last_match_average,HOME_PLAYER_HIT_WOODWORK_5_last_match_average,HOME_PLAYER_INTERCEPTIONS_5_last_match_average,HOME_PLAYER_KEY_PASSES_5_last_match_average,HOME_PLAYER_MINUTES_PLAYED_5_last_match_average,HOME_PLAYER_OFFSIDES_5_last_match_average,HOME_PLAYER_OWN_GOALS_5_last_match_average,HOME_PLAYER_PASSES_5_last_match_average,HOME_PLAYER_PENALTIES_COMMITTED_5_last_match_average,HOME_PLAYER_PENALTIES_MISSES_5_last_match_average,HOME_PLAYER_PENALTIES_SAVED_5_last_match_average,HOME_PLAYER_PENALTIES_SCORED_5_last_match_average,HOME_PLAYER_PENALTIES_WON_5_last_match_average,HOME_PLAYER_RATING_5_last_match_average,HOME_PLAYER_REDCARDS_5_last_match_average,HOME_PLAYER_SAVES_5_last_match_average,HOME_PLAYER_SAVES_INSIDE_BOX_5_last_match_average,HOME_PLAYER_SHOTS_BLOCKED_5_last_match_average,HOME_PLAYER_SHOTS_ON_TARGET_5_last_match_average,HOME_PLAYER_SHOTS_TOTAL_5_last_match_average,HOME_PLAYER_STARTING_LINEUP_5_last_match_average,HOME_PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_average,HOME_PLAYER_TACKLES_5_last_match_average,HOME_PLAYER_TOTAL_CROSSES_5_last_match_average,HOME_PLAYER_TOTAL_DUELS_5_last_match_average,HOME_PLAYER_YELLOWCARDS_5_last_match_average,HOME_PLAYER_ACCURATE_CROSSES_5_last_match_std,HOME_PLAYER_ACCURATE_PASSES_5_last_match_std,HOME_PLAYER_ACCURATE_PASSES_PERCENTAGE_5_last_match_std,HOME_PLAYER_AERIALS_WON_5_last_match_std,HOME_PLAYER_ASSISTS_5_last_match_std,HOME_PLAYER_BIG_CHANCES_CREATED_5_las

In [222]:
match_data.shape

(12303, 830)

In [223]:
match_data.columns[-10:]

Index(['AWAY_PLAYER_SAVES_INSIDE_BOX_5_last_match_std',
       'AWAY_PLAYER_SHOTS_BLOCKED_5_last_match_std',
       'AWAY_PLAYER_SHOTS_ON_TARGET_5_last_match_std',
       'AWAY_PLAYER_SHOTS_TOTAL_5_last_match_std',
       'AWAY_PLAYER_STARTING_LINEUP_5_last_match_std',
       'AWAY_PLAYER_SUCCESSFUL_DRIBBLES_5_last_match_std',
       'AWAY_PLAYER_TACKLES_5_last_match_std',
       'AWAY_PLAYER_TOTAL_CROSSES_5_last_match_std',
       'AWAY_PLAYER_TOTAL_DUELS_5_last_match_std',
       'AWAY_PLAYER_YELLOWCARDS_5_last_match_std'],
      dtype='object')

In [224]:
[c for c in match_data.columns if c.endswith("_x") or c.endswith("_y")]

['HOME_TEAM_NAME_x',
 'AWAY_TEAM_NAME_x',
 'HOME_TEAM_NAME_y',
 'AWAY_TEAM_NAME_y']

In [225]:
match_data = match_data.rename(columns={
    "HOME_TEAM_NAME_x": "HOME_TEAM_NAME",
    "AWAY_TEAM_NAME_x": "AWAY_TEAM_NAME"
})

match_data = match_data.drop(columns=[
    "HOME_TEAM_NAME_y",
    "AWAY_TEAM_NAME_y"
])

print(match_data.shape)

(12303, 828)

In [226]:
missing = match_data.isnull().sum()

missing = missing[missing > 0]

print("Columns with missing values:", len(missing))
print("Total missing values:", missing.sum())

missing.head(20)

Columns with missing values: 0
Total missing values: 0

Series([], dtype: int64)

In [227]:
print("Duplicate rows:", match_data.duplicated().sum())

Duplicate rows: 0

In [228]:
match_data.dtypes.value_counts()

float64    825
object       3
Name: count, dtype: int64

In [229]:
numeric = match_data.select_dtypes(include=np.number)

print(np.isinf(numeric).sum().sum())

0

In [230]:
print(y_train.shape)
print(y_train.columns.tolist())
print(y_train.head())

(12303, 4)
['ID', 'HOME_WINS', 'DRAW', 'AWAY_WINS']
   ID  HOME_WINS  DRAW  AWAY_WINS
0   0          0     0          1
1   1          0     1          0
2   2          0     0          1
3   3          1     0          0
4   4          0     1          0

In [231]:
print(y_train.dtypes)

ID           int64
HOME_WINS    int64
DRAW         int64
AWAY_WINS    int64
dtype: object

In [232]:
# Merging the target into Match data
match_data = match_data.merge(
    y_train,
    on="ID",
    how="inner"
)

print("Shape after merging target:", match_data.shape)

Shape after merging target: (12303, 831)

In [233]:
print(match_data[["ID", "HOME_WINS", "DRAW", "AWAY_WINS"]].head(10))

    ID  HOME_WINS  DRAW  AWAY_WINS
0 0.00          0     0          1
1 1.00          0     1          0
2 2.00          0     0          1
3 3.00          1     0          0
4 4.00          0     1          0
5 5.00          1     0          0
6 6.00          1     0          0
7 7.00          0     1          0
8 8.00          0     0          1
9 9.00          1     0          0

In [234]:
outcome_sum = (
    match_data[["HOME_WINS", "DRAW", "AWAY_WINS"]]
    .sum(axis=1)
)

print("Rows with exactly one outcome:", (outcome_sum == 1).sum())
print("Rows with invalid outcome:", (outcome_sum != 1).sum())

Rows with exactly one outcome: 12303
Rows with invalid outcome: 0

In [235]:
print("Home wins:", match_data["HOME_WINS"].sum())
print("Draws:", match_data["DRAW"].sum())
print("Away wins:", match_data["AWAY_WINS"].sum())

Home wins: 5356
Draws: 3186
Away wins: 3761

In [236]:
# Creating one single target variable
# Create a single multiclass target

match_data["TARGET"] = np.select(
    [
        match_data["HOME_WINS"] == 1,
        match_data["DRAW"] == 1,
        match_data["AWAY_WINS"] == 1
    ],
    [
        0,
        1,
        2
    ]
)

print(match_data["TARGET"].value_counts().sort_index())

TARGET
0    5356
1    3186
2    3761
Name: count, dtype: int64

In [237]:
print(match_data[["ID", "HOME_WINS", "DRAW", "AWAY_WINS", "TARGET"]].head(10))

    ID  HOME_WINS  DRAW  AWAY_WINS  TARGET
0 0.00          0     0          1       2
1 1.00          0     1          0       1
2 2.00          0     0          1       2
3 3.00          1     0          0       0
4 4.00          0     1          0       1
5 5.00          1     0          0       0
6 6.00          1     0          0       0
7 7.00          0     1          0       1
8 8.00          0     0          1       2
9 9.00          1     0          0       0

In [238]:
match_data = match_data.drop(
    columns=["HOME_WINS", "DRAW", "AWAY_WINS"]
)

print(match_data.shape)

(12303, 829)

In [239]:
# Check all non-numeric columns

object_columns = match_data.select_dtypes(include=["object"]).columns.tolist()

print("Number of object columns:", len(object_columns))
print("\nObject columns:")
print(object_columns)

Number of object columns: 3

Object columns:
['LEAGUE', 'HOME_TEAM_NAME', 'AWAY_TEAM_NAME']

In [240]:
print("ID unique values:", match_data["ID"].nunique())
print("Total rows:", len(match_data))

print("\nID range:")
print(match_data["ID"].min(), match_data["ID"].max())

ID unique values: 12303
Total rows: 12303

ID range:
0.0 12302.0

In [241]:
# Count features by their statistical aggregation type

feature_types = {
    "season_sum": [],
    "season_average": [],
    "season_std": [],
    "last_5_sum": [],
    "last_5_average": [],
    "last_5_std": []
}

for col in match_data.columns:

    if col in ["ID", "LEAGUE", "HOME_TEAM_NAME", "AWAY_TEAM_NAME", "TARGET"]:
        continue

    if "season_sum" in col:
        feature_types["season_sum"].append(col)

    elif "season_average" in col:
        feature_types["season_average"].append(col)

    elif "season_std" in col:
        feature_types["season_std"].append(col)

    elif "5_last_match_sum" in col:
        feature_types["last_5_sum"].append(col)

    elif "5_last_match_average" in col:
        feature_types["last_5_average"].append(col)

    elif "5_last_match_std" in col:
        feature_types["last_5_std"].append(col)


for name, columns in feature_types.items():
    print(name, ":", len(columns))

season_sum : 134
season_average : 142
season_std : 136
last_5_sum : 134
last_5_average : 142
last_5_std : 136

In [242]:
# Look for columns that could directly reveal the match result

keywords = [
    "WIN",
    "DRAW",
    "RESULT",
    "OUTCOME"
]

suspicious_columns = [
    col for col in match_data.columns
    if any(keyword in col.upper() for keyword in keywords)
]

print("Potentially suspicious columns:")
print(suspicious_columns)

Potentially suspicious columns:
['HOME_TEAM_GAME_DRAW_season_sum', 'HOME_TEAM_GAME_DRAW_season_average', 'HOME_TEAM_GAME_DRAW_5_last_match_sum', 'HOME_TEAM_GAME_DRAW_5_last_match_average', 'AWAY_TEAM_GAME_DRAW_season_sum', 'AWAY_TEAM_GAME_DRAW_season_average', 'AWAY_TEAM_GAME_DRAW_5_last_match_sum', 'AWAY_TEAM_GAME_DRAW_5_last_match_average', 'HOME_PLAYER_FOULS_DRAWN_season_sum', 'HOME_PLAYER_FOULS_DRAWN_season_average', 'HOME_PLAYER_FOULS_DRAWN_season_std', 'HOME_PLAYER_FOULS_DRAWN_5_last_match_sum', 'HOME_PLAYER_FOULS_DRAWN_5_last_match_average', 'HOME_PLAYER_FOULS_DRAWN_5_last_match_std', 'AWAY_PLAYER_FOULS_DRAWN_season_sum', 'AWAY_PLAYER_FOULS_DRAWN_season_average', 'AWAY_PLAYER_FOULS_DRAWN_season_std', 'AWAY_PLAYER_FOULS_DRAWN_5_last_match_sum', 'AWAY_PLAYER_FOULS_DRAWN_5_last_match_average', 'AWAY_PLAYER_FOULS_DRAWN_5_last_match_std']

In [243]:
X = match_data.drop(columns=["TARGET"])
y = match_data["TARGET"]

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (12303, 828)
y shape: (12303,)

In [244]:
print(
    match_data[["ID", "TARGET"]]
    .sort_values("ID")
    .head(20)
)

      ID  TARGET
0   0.00       2
1   1.00       1
2   2.00       2
3   3.00       0
4   4.00       1
5   5.00       0
6   6.00       0
7   7.00       1
8   8.00       2
9   9.00       0
10 10.00       1
11 11.00       0
12 12.00       2
13 13.00       2
14 14.00       0
15 15.00       1
16 16.00       0
17 17.00       0
18 18.00       0
19 19.00       0

In [245]:
print(
    match_data[["ID", "TARGET"]]
    .sort_values("ID")
    .tail(20)
)

            ID  TARGET
12283 12283.00       0
12284 12284.00       0
12285 12285.00       1
12286 12286.00       1
12287 12287.00       0
12288 12288.00       2
12289 12289.00       1
12290 12290.00       0
12291 12291.00       1
12292 12292.00       0
12293 12293.00       1
12294 12294.00       0
12295 12295.00       1
12296 12296.00       0
12297 12297.00       0
12298 12298.00       2
12299 12299.00       2
12300 12300.00       2
12301 12301.00       0
12302 12302.00       0

In [246]:
id_sorted = match_data["ID"].sort_values().reset_index(drop=True)

print("IDs are sequential:",
      np.array_equal(id_sorted.values, np.arange(len(match_data))))

IDs are sequential: True

In [247]:
match_data["ID_GROUP"] = pd.qcut(
    match_data["ID"],
    q=5,
    labels=["Q1", "Q2", "Q3", "Q4", "Q5"]
)

print(
    pd.crosstab(
        match_data["ID_GROUP"],
        match_data["TARGET"],
        normalize="index"
    ).round(3)
)

TARGET      0    1    2
ID_GROUP
Q1       0.45 0.26 0.29
Q2       0.42 0.25 0.34
Q3       0.43 0.27 0.30
Q4       0.44 0.25 0.30
Q5       0.44 0.26 0.30

In [248]:
print("Number of leagues:",
      match_data["LEAGUE"].nunique())

print("\nLeague distribution:")
print(match_data["LEAGUE"].value_counts())

Number of leagues: 13

League distribution:
LEAGUE
Serie A           1966
League Two        1376
Superliga         1124
La Liga            973
Ligue 2            884
Ligue 1            851
League One         844
J-League           783
Bundesliga         777
Liga Portugal      772
Eredivisie         674
Pro League         649
Premier League     630
Name: count, dtype: int64

In [249]:
print(
    pd.crosstab(
        match_data["LEAGUE"],
        match_data["TARGET"],
        normalize="index"
    ).round(3)
)

TARGET            0    1    2
LEAGUE
Bundesliga     0.42 0.24 0.34
Eredivisie     0.50 0.21 0.29
J-League       0.42 0.22 0.36
La Liga        0.45 0.28 0.27
League One     0.44 0.27 0.29
League Two     0.43 0.27 0.30
Liga Portugal  0.44 0.23 0.33
Ligue 1        0.42 0.27 0.32
Ligue 2        0.40 0.31 0.28
Premier League 0.43 0.23 0.34
Pro League     0.44 0.23 0.33
Serie A        0.45 0.27 0.28
Superliga      0.42 0.27 0.31

In [250]:
print("Unique home teams:",
      match_data["HOME_TEAM_NAME"].nunique())

print("Unique away teams:",
      match_data["AWAY_TEAM_NAME"].nunique())

print("Unique teams overall:",
      pd.concat([
          match_data["HOME_TEAM_NAME"],
          match_data["AWAY_TEAM_NAME"]
      ]).nunique())

Unique home teams: 350
Unique away teams: 350
Unique teams overall: 350

In [251]:
match_data = match_data.drop(columns=["ID_GROUP"])

print(match_data.shape)

(12303, 829)

In [252]:
# Final modelling-readiness check

print("Dataset shape:", match_data.shape)

print("\nTarget distribution:")
print(match_data["TARGET"].value_counts().sort_index())

print("\nTarget percentages:")
print((match_data["TARGET"].value_counts(normalize=True).sort_index() * 100).round(2))

print("\nObject/categorical columns:")
print(match_data.select_dtypes(include=["object"]).columns.tolist())

print("\nID column:")
print(match_data["ID"].head())

Dataset shape: (12303, 829)

Target distribution:
TARGET
0    5356
1    3186
2    3761
Name: count, dtype: int64

Target percentages:
TARGET
0   43.53
1   25.90
2   30.57
Name: proportion, dtype: float64

Object/categorical columns:
['LEAGUE', 'HOME_TEAM_NAME', 'AWAY_TEAM_NAME']

ID column:
0   0.00
1   1.00
2   2.00
3   3.00
4   4.00
Name: ID, dtype: float64

In [253]:
# Prepare data for modelling

# Remove identifier and raw team-name columns
X = match_data.drop(
    columns=["TARGET", "ID", "HOME_TEAM_NAME", "AWAY_TEAM_NAME"]
)

y = match_data["TARGET"]

print("X shape:", X.shape)
print("y shape:", y.shape)

print("\nRemaining non-numeric columns:")
print(X.select_dtypes(include=["object"]).columns.tolist())

print("\nMissing values in X:", X.isna().sum().sum())
print("Infinite values in X:", np.isinf(X.select_dtypes(include=np.number)).sum().sum())

X shape: (12303, 825)
y shape: (12303,)

Remaining non-numeric columns:
['LEAGUE']

Missing values in X: 0
Infinite values in X: 0

In [254]:
from sklearn.model_selection import train_test_split

# Stratified 80/20 train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    stratify=y,
    random_state=42
)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

print("\nTraining target distribution:")
print(y_train.value_counts(normalize=True).sort_index().round(3))

print("\nTest target distribution:")
print(y_test.value_counts(normalize=True).sort_index().round(3))

X_train shape: (9842, 825)
X_test shape: (2461, 825)
y_train shape: (9842,)
y_test shape: (2461,)

Training target distribution:
TARGET
0   0.43
1   0.26
2   0.31
Name: proportion, dtype: float64

Test target distribution:
TARGET
0   0.44
1   0.26
2   0.31
Name: proportion, dtype: float64

In [255]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# Identify categorical and numerical columns
categorical_features = ["LEAGUE"]

numerical_features = [
    col for col in X_train.columns
    if col not in categorical_features
]

# Preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features
        ),
        (
            "num",
            "passthrough",
            numerical_features
        )
    ]
)

print("Categorical features:", categorical_features)
print("Number of numerical features:", len(numerical_features))

Categorical features: ['LEAGUE']
Number of numerical features: 824

## Logistic Regression

In [256]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression

# Preprocessing
preprocessor_lr = ColumnTransformer(
    transformers=[
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features
        ),
        (
            "num",
            StandardScaler(),
            numerical_features
        )
    ]
)

# Multinomial Logistic Regression
logistic_model = Pipeline(
    steps=[
        ("preprocessor", preprocessor_lr),
        (
            "classifier",
            LogisticRegression(
                max_iter=2000,
                solver="lbfgs",
                multi_class="multinomial",
                random_state=42
            )
        )
    ]
)

# Fit only on the training data
logistic_model.fit(X_train, y_train)

print("Multinomial Logistic Regression fitted successfully.")

Multinomial Logistic Regression fitted successfully.

In [257]:
y_pred_lr = logistic_model.predict(X_test)
y_prob_lr = logistic_model.predict_proba(X_test)

print("Predictions generated successfully.")
print("Probability shape:", y_prob_lr.shape)

Predictions generated successfully.
Probability shape: (2461, 3)

In [258]:
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    log_loss,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

# Classification metrics
accuracy_lr = accuracy_score(y_test, y_pred_lr)
balanced_accuracy_lr = balanced_accuracy_score(y_test, y_pred_lr)

precision_lr = precision_score(
    y_test, y_pred_lr,
    average="macro",
    zero_division=0
)

recall_lr = recall_score(
    y_test, y_pred_lr,
    average="macro",
    zero_division=0
)

f1_lr = f1_score(
    y_test, y_pred_lr,
    average="macro",
    zero_division=0
)

# Probability-based metrics
log_loss_lr = log_loss(y_test, y_prob_lr)

roc_auc_lr = roc_auc_score(
    y_test,
    y_prob_lr,
    multi_class="ovr",
    average="macro"
)

# Print results
print("LOGISTIC REGRESSION - TEST SET RESULTS")
print("-" * 50)

print(f"Accuracy:           {accuracy_lr:.4f}")
print(f"Balanced Accuracy:  {balanced_accuracy_lr:.4f}")
print(f"Macro Precision:    {precision_lr:.4f}")
print(f"Macro Recall:       {recall_lr:.4f}")
print(f"Macro F1-score:     {f1_lr:.4f}")
print(f"ROC-AUC (Macro):    {roc_auc_lr:.4f}")
print(f"Log Loss:           {log_loss_lr:.4f}")

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred_lr,
        target_names=["Home Win (0)", "Draw (1)", "Away Win (2)"],
        digits=4,
        zero_division=0
    )
)

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_lr))

LOGISTIC REGRESSION - TEST SET RESULTS
--------------------------------------------------
Accuracy:           0.4486
Balanced Accuracy:  0.4061
Macro Precision:    0.4009
Macro Recall:       0.4061
Macro F1-score:     0.3975
ROC-AUC (Macro):    0.5871
Log Loss:           1.1228

Classification Report:
              precision    recall  f1-score   support

Home Win (0)     0.5130    0.6437    0.5710      1072
    Draw (1)     0.2500    0.1586    0.1940       637
Away Win (2)     0.4396    0.4162    0.4276       752

    accuracy                         0.4486      2461
   macro avg     0.4009    0.4061    0.3975      2461
weighted avg     0.4225    0.4486    0.4296      2461


Confusion Matrix:
[[690 170 212]
 [349 101 187]
 [306 133 313]]

## Decision Trees

In [259]:
# Decision Tree

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.tree import DecisionTreeClassifier

# Preprocessing
preprocessor_dt = ColumnTransformer(
    transformers=[
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features
        ),
        (
            "num",
            "passthrough",
            numerical_features
        )
    ]
)

# Decision Tree model
decision_tree_model = Pipeline(
    steps=[
        ("preprocessor", preprocessor_dt),
        (
            "classifier",
            DecisionTreeClassifier(
                random_state=42
            )
        )
    ]
)

# Fit ONLY on training data
decision_tree_model.fit(X_train, y_train)

print("Decision Tree fitted successfully.")

Decision Tree fitted successfully.

In [260]:
# Generate predictions on the unseen test set

y_pred_dt = decision_tree_model.predict(X_test)
y_prob_dt = decision_tree_model.predict_proba(X_test)

print("Decision Tree predictions generated successfully.")
print("Probability shape:", y_prob_dt.shape)

Decision Tree predictions generated successfully.
Probability shape: (2461, 3)

In [261]:
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    log_loss,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

# Classification metrics
accuracy_dt = accuracy_score(y_test, y_pred_dt)

balanced_accuracy_dt = balanced_accuracy_score(
    y_test,
    y_pred_dt
)

precision_dt = precision_score(
    y_test,
    y_pred_dt,
    average="macro",
    zero_division=0
)

recall_dt = recall_score(
    y_test,
    y_pred_dt,
    average="macro",
    zero_division=0
)

f1_dt = f1_score(
    y_test,
    y_pred_dt,
    average="macro",
    zero_division=0
)

# Probability-based metrics
log_loss_dt = log_loss(
    y_test,
    y_prob_dt
)

roc_auc_dt = roc_auc_score(
    y_test,
    y_prob_dt,
    multi_class="ovr",
    average="macro"
)

# Print results
print("DECISION TREE – TEST SET RESULTS")
print("-" * 50)

print(f"Accuracy:             {accuracy_dt:.4f}")
print(f"Balanced Accuracy:    {balanced_accuracy_dt:.4f}")
print(f"Macro Precision:      {precision_dt:.4f}")
print(f"Macro Recall:         {recall_dt:.4f}")
print(f"Macro F1-score:       {f1_dt:.4f}")
print(f"ROC-AUC (Macro):      {roc_auc_dt:.4f}")
print(f"Log Loss:             {log_loss_dt:.4f}")

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred_dt,
        target_names=[
            "Home Win (0)",
            "Draw (1)",
            "Away Win (2)"
        ],
        digits=4,
        zero_division=0
    )
)

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_dt))

DECISION TREE – TEST SET RESULTS
--------------------------------------------------
Accuracy:             0.3807
Balanced Accuracy:    0.3650
Macro Precision:      0.3649
Macro Recall:         0.3650
Macro F1-score:       0.3649
ROC-AUC (Macro):      0.5246
Log Loss:             22.3204

Classification Report:
              precision    recall  f1-score   support

Home Win (0)     0.4743    0.4571    0.4656      1072
    Draw (1)     0.2772    0.2841    0.2806       637
Away Win (2)     0.3432    0.3537    0.3484       752

    accuracy                         0.3807      2461
   macro avg     0.3649    0.3650    0.3649      2461
weighted avg     0.3832    0.3807    0.3819      2461


Confusion Matrix:
[[490 268 314]
 [261 181 195]
 [282 204 266]]

## Random Forest

In [262]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# Preprocessing for Random Forest
preprocessor_rf = ColumnTransformer(
    transformers=[
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features
        ),
        (
            "num",
            "passthrough",
            numerical_features
        )
    ]
)

# Random Forest model
random_forest_model = Pipeline(
    steps=[
        ("preprocessor", preprocessor_rf),
        (
            "classifier",
            RandomForestClassifier(
                n_estimators=300,
                random_state=42,
                n_jobs=-1
            )
        )
    ]
)

# Fit ONLY on training data
random_forest_model.fit(X_train, y_train)

print("Random Forest fitted successfully.")

Random Forest fitted successfully.

In [263]:
# Generate predictions on the unseen test set
y_pred_rf = random_forest_model.predict(X_test)
y_prob_rf = random_forest_model.predict_proba(X_test)

print("Random Forest predictions generated successfully.")
print("Probability shape:", y_prob_rf.shape)

Random Forest predictions generated successfully.
Probability shape: (2461, 3)

In [264]:
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    log_loss,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

# Classification metrics
accuracy_rf = accuracy_score(y_test, y_pred_rf)

balanced_accuracy_rf = balanced_accuracy_score(
    y_test,
    y_pred_rf
)

precision_rf = precision_score(
    y_test,
    y_pred_rf,
    average="macro",
    zero_division=0
)

recall_rf = recall_score(
    y_test,
    y_pred_rf,
    average="macro",
    zero_division=0
)

f1_rf = f1_score(
    y_test,
    y_pred_rf,
    average="macro",
    zero_division=0
)

# Probability-based metrics
log_loss_rf = log_loss(
    y_test,
    y_prob_rf
)

roc_auc_rf = roc_auc_score(
    y_test,
    y_prob_rf,
    multi_class="ovr",
    average="macro"
)

# Print results
print("RANDOM FOREST – TEST SET RESULTS")
print("-" * 50)

print(f"Accuracy:              {accuracy_rf:.4f}")
print(f"Balanced Accuracy:     {balanced_accuracy_rf:.4f}")
print(f"Macro Precision:       {precision_rf:.4f}")
print(f"Macro Recall:          {recall_rf:.4f}")
print(f"Macro F1-score:        {f1_rf:.4f}")
print(f"ROC-AUC (Macro):       {roc_auc_rf:.4f}")
print(f"Log Loss:              {log_loss_rf:.4f}")

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred_rf,
        target_names=[
            "Home Win (0)",
            "Draw (1)",
            "Away Win (2)"
        ],
        digits=4,
        zero_division=0
    )
)

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_rf))

RANDOM FOREST – TEST SET RESULTS
--------------------------------------------------
Accuracy:              0.4892
Balanced Accuracy:     0.4195
Macro Precision:       0.4429
Macro Recall:          0.4195
Macro F1-score:        0.3732
ROC-AUC (Macro):       0.6219
Log Loss:              1.0269

Classification Report:
              precision    recall  f1-score   support

Home Win (0)     0.5029    0.8172    0.6226      1072
    Draw (1)     0.3607    0.0345    0.0630       637
Away Win (2)     0.4650    0.4069    0.4340       752

    accuracy                         0.4892      2461
   macro avg     0.4429    0.4195    0.3732      2461
weighted avg     0.4545    0.4892    0.4201      2461


Confusion Matrix:
[[876  16 180]
 [443  22 172]
 [423  23 306]]

## Gradient Boosting with XGBoost

In [265]:
%pip install xgboost

Requirement already satisfied: xgboost in /opt/anaconda3/lib/python3.13/site-packages (3.4.0)
Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.13/site-packages (from xgboost) (2.1.3)
Requirement already satisfied: scipy in /opt/anaconda3/lib/python3.13/site-packages (from xgboost) (1.15.3)
Note: you may need to restart the kernel to use updated packages.

In [266]:
from xgboost import XGBClassifier

print("XGBoost imported successfully.")

XGBoost imported successfully.

In [267]:
# Gradient Boosting with XGBoost

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# Preprocessing
preprocessor_xgb = ColumnTransformer(
    transformers=[
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features
        ),
        (
            "num",
            "passthrough",
            numerical_features
        )
    ]
)

# XGBoost model
xgb_model = Pipeline(
    steps=[
        ("preprocessor", preprocessor_xgb),
        (
            "classifier",
            XGBClassifier(
                n_estimators=300,
                max_depth=6,
                learning_rate=0.05,
                subsample=0.8,
                colsample_bytree=0.8,
                objective="multi:softprob",
                num_class=3,
                eval_metric="mlogloss",
                random_state=42,
                n_jobs=-1
            )
        )
    ]
)

# Fit ONLY on training data
xgb_model.fit(X_train, y_train)

print("XGBoost fitted successfully.")

XGBoost fitted successfully.

In [268]:
# Generate predictions on the unseen test set

y_pred_xgb = xgb_model.predict(X_test)
y_prob_xgb = xgb_model.predict_proba(X_test)

print("XGBoost predictions generated successfully.")
print("Probability shape:", y_prob_xgb.shape)

XGBoost predictions generated successfully.
Probability shape: (2461, 3)

In [269]:
# XGBoost evaluation

accuracy_xgb = accuracy_score(y_test, y_pred_xgb)

balanced_accuracy_xgb = balanced_accuracy_score(
    y_test,
    y_pred_xgb
)

precision_xgb = precision_score(
    y_test,
    y_pred_xgb,
    average="macro",
    zero_division=0
)

recall_xgb = recall_score(
    y_test,
    y_pred_xgb,
    average="macro",
    zero_division=0
)

f1_xgb = f1_score(
    y_test,
    y_pred_xgb,
    average="macro",
    zero_division=0
)

log_loss_xgb = log_loss(
    y_test,
    y_prob_xgb
)

roc_auc_xgb = roc_auc_score(
    y_test,
    y_prob_xgb,
    multi_class="ovr",
    average="macro"
)

print("XGBOOST – TEST SET RESULTS")
print("-" * 50)

print(f"Accuracy:              {accuracy_xgb:.4f}")
print(f"Balanced Accuracy:     {balanced_accuracy_xgb:.4f}")
print(f"Macro Precision:       {precision_xgb:.4f}")
print(f"Macro Recall:          {recall_xgb:.4f}")
print(f"Macro F1-score:        {f1_xgb:.4f}")
print(f"ROC-AUC (Macro):       {roc_auc_xgb:.4f}")
print(f"Log Loss:              {log_loss_xgb:.4f}")

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred_xgb,
        target_names=[
            "Home Win (0)",
            "Draw (1)",
            "Away Win (2)"
        ],
        digits=4,
        zero_division=0
    )
)

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_xgb))

XGBOOST – TEST SET RESULTS
--------------------------------------------------
Accuracy:              0.4835
Balanced Accuracy:     0.4254
Macro Precision:       0.4269
Macro Recall:          0.4254
Macro F1-score:        0.3973
ROC-AUC (Macro):       0.6221
Log Loss:              1.0421

Classification Report:
              precision    recall  f1-score   support

Home Win (0)     0.5201    0.7500    0.6142      1072
    Draw (1)     0.3140    0.0848    0.1335       637
Away Win (2)     0.4468    0.4415    0.4441       752

    accuracy                         0.4835      2461
   macro avg     0.4269    0.4254    0.3973      2461
weighted avg     0.4443    0.4835    0.4378      2461


Confusion Matrix:
[[804  61 207]
 [379  54 204]
 [363  57 332]]

## Neural Netowrk

In [270]:
# Multilayer Perceptron (MLP)

from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

# Preprocessing
preprocessor_mlp = ColumnTransformer(
    transformers=[
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features
        ),
        (
            "num",
            StandardScaler(),
            numerical_features
        )
    ]
)

# MLP model
mlp_model = Pipeline(
    steps=[
        ("preprocessor", preprocessor_mlp),
        (
            "classifier",
            MLPClassifier(
                hidden_layer_sizes=(128, 64),
                activation="relu",
                solver="adam",
                alpha=0.0001,
                learning_rate_init=0.001,
                max_iter=100,
                early_stopping=True,
                validation_fraction=0.1,
                random_state=42
            )
        )
    ]
)

# Fit ONLY on training data
mlp_model.fit(X_train, y_train)

print("MLP fitted successfully.")

MLP fitted successfully.

In [271]:
# Generate predictions on the unseen test set

y_pred_mlp = mlp_model.predict(X_test)
y_prob_mlp = mlp_model.predict_proba(X_test)

print("MLP predictions generated successfully.")
print("Probability shape:", y_prob_mlp.shape)

MLP predictions generated successfully.
Probability shape: (2461, 3)

In [272]:
# MLP evaluation

accuracy_mlp = accuracy_score(y_test, y_pred_mlp)

balanced_accuracy_mlp = balanced_accuracy_score(
    y_test,
    y_pred_mlp
)

precision_mlp = precision_score(
    y_test,
    y_pred_mlp,
    average="macro",
    zero_division=0
)

recall_mlp = recall_score(
    y_test,
    y_pred_mlp,
    average="macro",
    zero_division=0
)

f1_mlp = f1_score(
    y_test,
    y_pred_mlp,
    average="macro",
    zero_division=0
)

log_loss_mlp = log_loss(
    y_test,
    y_prob_mlp
)

roc_auc_mlp = roc_auc_score(
    y_test,
    y_prob_mlp,
    multi_class="ovr",
    average="macro"
)

print("MLP - TEST SET RESULTS")
print("-" * 50)

print(f"Accuracy:             {accuracy_mlp:.4f}")
print(f"Balanced Accuracy:    {balanced_accuracy_mlp:.4f}")
print(f"Macro Precision:      {precision_mlp:.4f}")
print(f"Macro Recall:         {recall_mlp:.4f}")
print(f"Macro F1-score:       {f1_mlp:.4f}")
print(f"ROC-AUC (Macro):      {roc_auc_mlp:.4f}")
print(f"Log Loss:             {log_loss_mlp:.4f}")

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred_mlp,
        target_names=[
            "Home Win (0)",
            "Draw (1)",
            "Away Win (2)"
        ],
        digits=4,
        zero_division=0
    )
)

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_mlp))

MLP - TEST SET RESULTS
--------------------------------------------------
Accuracy:             0.4681
Balanced Accuracy:    0.4149
Macro Precision:      0.4227
Macro Recall:         0.4149
Macro F1-score:       0.4028
ROC-AUC (Macro):      0.6054
Log Loss:             1.0613

Classification Report:
              precision    recall  f1-score   support

Home Win (0)     0.5104    0.7351    0.6024      1072
    Draw (1)     0.3020    0.1664    0.2146       637
Away Win (2)     0.4558    0.3431    0.3915       752

    accuracy                         0.4681      2461
   macro avg     0.4227    0.4149    0.4028      2461
weighted avg     0.4398    0.4681    0.4376      2461


Confusion Matrix:
[[788 134 150]
 [373 106 158]
 [383 111 258]]